### ISSUE TITLE
Deployment of saved model in Triton inference server with support of gRPC

### ISSUE THREAD

**Issue by nashra2637** [kserve/kserve#1217]
/kind bug

We have deployed a ml model using triton inference server with tensorflow savedmodel in KFServing. But we can't access/hit the deployed ml model in cluster, it is running on port 9000 gRPC and 8080 RestAPI

**Environment:**

- Istio Version: 1.7.4
- Knative Version: 
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@nashra2637 Can you share more details about the issue and which version of KFS you are running

**Comment by nashra2637** [comment]
Istio Version: 1.7.4
Knative Version: v0.14.3+
KFServing Version: KFServing 0.4
Kubernetes version: (use kubectl version): 1.18

**Comment by nashra2637** [comment]
Istio Version: 1.7.4
Knative Version: v0.14.3+
KFServing Version: KFServing 0.4
Kubernetes version: (use kubectl version): 1.18

**Comment by AkashDharani** [comment]
Here is our sample.yaml file to deploy model in our cluster, we have seen the logs of deployed model, it is successfully deployed and running on port 9000 gRPC and 8080 RestAPI. But what we dont know is how exactly we have to hit that deployed model in cluster using kfserving. How we can find the port on which these ports are mapped, or how can we map these ports to ingress ports which we can use to hit these models. I tried to do docker port <container-name> to see the mapped ports but there was not any port mapped in container as well.

```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "model-name"
spec:
  default:
    predictor:
      serviceAccountName: sa
      triton:
        resources:
          limits:
          cpu: "3"
          memory: 6Gi
          nvidia.com/gpu:
        storageUri: "<s3-path>"

```

**Comment by yuzisun** [comment]
@AkashDharani The build-in triton model server currently only exposes REST port as only one of REST/gRPC port can be exposed on ingress. If you try the 0.5.0-rc0 release with v1beta1 API the gRPC can be exposed with this.

```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "model-name"
spec:
    predictor:
      serviceAccountName: sa
      triton:
        ports:
        - containerPort: 9000
          name: h2c
          protocol: TCP
        resources:
          limits:
          cpu: "3"
          memory: 6Gi
          nvidia.com/gpu:
        storageUri: "<s3-path>"
```

If you have to use earlier release, then the only possibility is to use custom container to expose gRPC port.
