### ISSUE TITLE
Authentication in Kfserving API services on public cluster. 

### ISSUE THREAD

**Issue by iavinas** [kserve/kserve#1297]
Our team has deployed a few Pytorch GPU models with scale down to zero. I don't want others to access the model. 
I am searching for a solution to stop the access of API before the upscaling of our Pytorch GPU starts. Please help me find a solution.

**Comment by KanwarpartapSingh** [comment]
### **_In order to impose limitations on the accessibility of PyTorch GPU models distributed using KFServing, it is possible to include access control and permission procedures prior to their scaling up._** 

**_The following is a systematic approach to solving the problem at hand:_**

_**1. Use Kubernetes Namespace Isolation:**_

One may effectively use a distinct Kubernetes namespace to deploy PyTorch models that are optimised for GPU processing. This action effectively severs their connection to additional resources inside the cluster, so establishing a heightened degree of security.

**_2. Kubernetes ServiceAccount:_**

It is essential to guarantee the use of a designated Kubernetes ServiceAccount with restricted privileges for PyTorch GPU model pods. The service account's access should be restricted to the specific resources necessary for model serving in order to minimise potential vulnerabilities.

**_3. Ingress Controller:_**

When exposing your model through an Ingress controller, it is advisable to setup it in a manner that restricts access depending on source IP or other pertinent criteria. IP whitelists may be defined or other access control rules can be implemented inside the Ingress setup.

**_4. Use Network Policies:_**

Incorporate Kubernetes Network Policies to regulate network communication to and from PyTorch GPU model pods. Policies should be implemented to regulate and limit access to the pods only to authorised sources, hence ensuring security and preventing unauthorised entry.

**_Here's an example for Network Policy:_**

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-access
spec:
  podSelector:
    matchLabels:
      app: pytorch-gpu-model
  ingress:
  - from:
    - ipBlock:
        cidr: 192.168.1.0/24  # Replace with your trusted IP range
```

In the above example, only traffic from the specified IP range is allowed.

**_5. Horizontal Pod Autoscaling (HPA):_**

It is essential to establish explicit guidelines for Horizontal Pod Autoscaling (HPA) regulations pertaining to the deployment of PyTorch GPU models. Establishing suitable metrics and thresholds is crucial in order to start the process of scaling up, taking into consideration factors such as resource utilisation or other relevant criteria.

**_6. Prevent Access During Scale-Up:_**

To mitigate unauthorised access to your models throughout the scaling process, it is advisable to use readiness probes. It is recommended to configure the readiness probes in order to verify the complete loading of the model and its readiness to handle incoming requests. The pods will not accept traffic, regardless of their operating status, until the readiness probe yields a favourable result.

_**Below is the example for `readinessProbe` configuration in your deployment YAML:**_

```
readinessProbe:
  httpGet:
    path: /healthz  # Replace with the actual health check endpoint
    port: 8080       # Replace with the port your model is listening on
  initialDelaySeconds: 60
  periodSeconds: 10
```

To ensure the readiness of the model for serving requests, it is recommended to include the /healthz endpoint into the model code. This endpoint will act as an indicator, signalling when the model has been completely loaded and is prepared to handle incoming requests.

**_7. Monitoring and Alerts:_**

Establishing monitoring and alarm systems for PyTorch GPU models and the scaling procedure is crucial. In this manner, users may be notified when the scaling procedure takes place, so assuring their awareness of any changes in traffic patterns.

By using these procedures, one may effectively manage access to PyTorch GPU models, impose restrictions throughout the scaling process, and guarantee that just authorised traffic is permitted to reach the models.
