### ISSUE TITLE
Enable true mesh-only, remove hard dependency on the knative-local-gateway

### ISSUE THREAD

**Issue by adamkgray** [kserve/kserve#1371]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Remove hard dependency on the knative local gateway and let kfserving have the option to run 100% mesh-only with istio.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Kfserving should be able to run in true mesh-only mode on istio with sidecars enabled. In doing so, we ought to be able to remove the hard dependency on the knative local gateway which currently is used to route top level requests (name.ns.svc.cluster.local) to the other knative services that kfserving creates (name-predictor-default.ns.svc.cluster.local). Vanilla knative services support this feature, so kfserving ought to as well.

Im not sure how the routing should be done in this case... Perhaps we can start by making the predictor ksvc the top level service so that name.ns.svc.cluster.local can resolve to its clusterIP instead of just being a CNAME for the knative local gateway.

**Comment by yuzisun** [comment]
@adamkgray I think I have figured out that the top level virtual service should use the `mesh` gateway instead for the mesh-only setup.

**Comment by yuzisun** [comment]
This is the current setup, with the mesh mode we had to use knative local gateway to route from top level virtual service `sklearn-iris` to the knative service virtual service `sklearn-iris-transformer-default`.
<img width="1037" alt="Screen Shot 2021-06-12 at 11 58 23 AM" src="https://user-images.githubusercontent.com/7662095/121782038-a254a300-cb75-11eb-90b1-d240973ba8c7.png">

**Comment by yuzisun** [comment]
istio virtual service delegate helps forwarding the traffic to transformer when using the top level host `sklearn-iris` however this does not seem to work and get 404 instead
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sklearn-iris
  namespace: default
spec:
  gateways:
  - knative-serving/knative-ingress-gateway
  hosts:
  - sklearn-iris.default.example.com
  http:
  - delegate:
      name: sklearn-iris-predictor-default-ingress
      namespace: default
```

```
curl -v -H "Host: sklearn-iris.default.example.com" http://localhost:8080/v1/models/sklearn-iris:predict -d @./docs/samples/v1beta1/sklearn/v1/iris-input.json
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> POST /v1/models/sklearn-iris:predict HTTP/1.1
> Host: sklearn-iris.default.example.com
> User-Agent: curl/7.73.0
> Accept: */*
> Content-Length: 76
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 76 out of 76 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Sun, 13 Jun 2021 12:07:23 GMT
< server: istio-envoy
< connection: close
< content-length: 0
< 
* Closing connection 0
```
