### ISSUE TITLE
When using batcher in a custom inference service the the containerPort isn't respected

### ISSUE THREAD

**Issue by timothyjlaurent** [kserve/kserve#1536]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: InferenceService
metadata:
  name: bran-relation-bento-batched
  namespace: kfserving
spec:
  predictor:
    minReplicas: 1
    batcher:
      maxBatchSize: 32
      maxLatency: 5000
      timeout: 60
    containers:
    - image: foo.dkr.ecr.us-east-1.amazonaws.com/bran-relation-bento:20210327T151131-0700
      name: bento
      ports:
        - containerPort: 5000
          protocol: TCP
```

With that inference service deployed the queue proxy still tries to use port 8080

**What did you expect to happen:**
It should use port 500 as it's specified in the containerPort argument

**Anything else you would like to add:**
Making the server listen on port 8080 rescues the service.

**Environment:**

- Istio Version:
- Knative Version: 0.22.0
- KFServing Version: 0,5,1
- Kubeflow version: ??
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
