### ISSUE TITLE
[kubeflow 1.3] unable to route requests to the kfserving pod due to auth policy

### ISSUE THREAD

**Issue by raffaelespazzoli** [kserve/kserve#1558]
/kind bug

**What steps did you take and what happened:**
deploy and inferenceserving example

I am installing in a preexisting knative deployment and perhaps I'm missing some steps. 
When I make a request, either using the external route/ingress or the internal service, the requests hangs for a long time and then times out.
retracing the steps of the request, I ended up in the activator pod, and found this error message:
```
{"level":"error","ts":"2021-04-24T19:10:16.241Z","logger":"activator","caller":"net/revision_backends.go:322","msg":"Failed to probe clusterIP 172.30.171.229:80","knative.dev/controller":"activator","knative.dev/pod":"activator-886cd96fb-4gqq5","knative.dev/key":"raffa/flowers-sample-predictor-default-00002","error":"unexpected body: want \"queue\", got \"RBAC: access denied\"","stacktrace":"knative.dev/serving/pkg/activator/net.(*revisionWatcher).checkDests\n\t/opt/app-root/src/go/src/knative.dev/serving/pkg/activator/net/revision_backends.go:322\nknative.dev/serving/pkg/activator/net.(*revisionWatcher).run\n\t/opt/app-root/src/go/src/knative.dev/serving/pkg/activator/net/revision_backends.go:366"}
{"level":"warn","ts":"2021-04-24T19:10:16.440Z","logger":"activator","caller":"net/revision_backends.go:286","msg":"Failed probing pods","knative.dev/controller":"activator","knative.dev/pod":"activator-886cd96fb-4gqq5","knative.dev/key":"raffa/flowers-sample-predictor-default-00002","curDests":{"ready":"10.128.2.38:8012","notReady":""},"error":"unexpected body: want \"queue\", got \"RBAC: access denied\""}
```
so it looks like the activator pod is probing the kfserving pod for the length of the queue but it's getting an RBAC error, due to, presumably, this istio RBAC rule:
```
spec:
  rules:
    - when:
        - key: 'request.headers[kubeflow-userid]'
          values:
            - raffa
    - when:
        - key: source.namespace
          values:
            - raffa
```
this is a standard RBAC rule created by the kubeflow profile when using a multitenant deployment.
I am not 100% sure that this is what is holding up the requests but it seems likely, because when I forge a request to go direclty to the kfserving pod I get a response.

am I missing something? 
This problem should be affecting any standard multitenant kubeflow deployment, how is it normally fixed? 

**What did you expect to happen:**
being able to route requests to the kfserving pod.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.6.5
- Knative Version: 0.19.0
- KFServing Version: 1.3
- Kubeflow version: 1.3
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version: na
- Kubernetes version: (use `kubectl version`): 1.20
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@raffaelespazzoli I assume you have istio proxy injected in the kfserving pod, I think there are two options
1) modify the RBAC policy and add `knative-serving` to the source namespace list, I think the knative activator also need the istio proxy injected in this case.
2) disable istio-proxy on kfserving pod with annotation `sidecar.istio.io/inject: false`, if RBAC is not required for inference service

**Comment by raffaelespazzoli** [comment]
@yuzisun thanks for your answer.
1. how can I modify the RBAC policy? It is automatically created by kubeflow based on the profile. is there a way to customize it? Also my knative activator does not have the istio-proxy
2. If I add the `sidecar.istio.io/inject: false` annotation, what do I lose. I'm assuming I lose all the observability stack...

**Comment by yuzisun** [comment]
@yanniszark @pvaneck I think this is a bug for multitenant env potentially related to istio 1.9 changes?

**Comment by yuzisun** [comment]
> @raffaelespazzoli I assume you have istio proxy injected in the kfserving pod, I think there are two options
> 
> 1. modify the RBAC policy and add `knative-serving` to the source namespace list, I think the knative activator also need the istio proxy injected in this case.
You can create the authorization policy for your inference service to allow the traffic, e.g
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: test-service
spec:
 selector:
   matchLabels:
     serving.kubeflow.org/inferenceservice: test-service  
 rules:
   -  {}
 ``` 
   


> 2. disable istio-proxy on kfserving pod with annotation `sidecar.istio.io/inject: false`, if RBAC is not required for inference service

**Comment by yuzisun** [comment]
> @yuzisun thanks for your answer.
> 
> 1. how can I modify the RBAC policy? It is automatically created by kubeflow based on the profile. is there a way to customize it? Also my knative activator does not have the istio-proxy

@raffaelespazzoli You can create the authorization policy for your inference service to allow the traffic, e.g

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: default
spec:
 selector:
   matchLabels:
     serving.kubeflow.org/inferenceservice: income  
 rules:
   -  {}
```
> 2. If I add the `sidecar.istio.io/inject: false` annotation, what do I lose. I'm assuming I lose all the observability stack...

**Comment by pvaneck** [comment]
I believe namespaces with automatic sidecar injection need the following authorizationpolicy based on the [Knative docs](https://knative.dev/docs/serving/istio-authorization/#allowing-access-from-system-pods-by-paths):

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allowlist-by-paths
  namespace: <your_namespace>
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        paths:
        - /metrics   # The path to collect metrics by system pod.
        - /healthz   # The path to probe by system pod.
```
Probably need to figure out how to get Kubeflow to automatically create this resource in the user namespace upon creation.

**Comment by pvaneck** [comment]
Tested out KFServing in a multi-user Kubeflow install (on IKS). In the user namespace generated from the central dashboard, I can create an inferenceservice but can't curl it due to problems listed in the issue:

Knative activator pod:
```
error":"unexpected body: want \"queue\", got \"RBAC: access denied\""
```

Istio-proxy sidecar container:
```
"GET /metrics HTTP/1.1" 403 - rbac_access_denied_matched_policy[none]
```

I can confirm, adding the following AuthorizationPolicy does get rid of these issues for me, and I can curl the Isvc.

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allowlist-by-paths
  namespace: test-user
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        paths:
        - /metrics   # The path to collect metrics by system pod.
        - /healthz   # The path to probe by system pod.
```

@animeshsingh @yuzisun Do you think it would be worthwhile to have this authorizationpolicy be created upon user profile creation in the dashboard?

**Comment by markwinter** [comment]
@pvaneck 

I also had to add `/v1/models/*` path to allow Transformer->Predictor requests

**Comment by danishsamad** [comment]
Applying @pvaneck recommended authorization policy permits to access isvcs from external clients but internal clients (sending reqs through cluster local gateway) are still unable to access the service.
I see a rbac_access_denied_matched_policy[none] error in istio-proxy container within the inference service pod for internal requests coming in through the cluster local gateway
Do we need another authorization config to allow in cluster traffic as well?

**Comment by markwinter** [comment]
To add to my comment above

I separated the policy into two and limited them to the Predictor and Transformer with a selector.

```
selector:
    matchLabels:
      component: predictor
```

```
selector:
    matchLabels:
      component: transformer
```

**Comment by jiaozhentian** [comment]
@markwinter 
I still have the same problem when using the transformer, we got the same error when post the <IP> /v1/models/<model-name>:predict, did you resolve this problem with the yaml path, could you please paste you yaml content if convenient.

**Comment by markwinter** [comment]
@jiaozhentian 

It should look like this

```YAML
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allowlist-by-paths
  namespace: istio-system
spec:
  selector:
    matchLabels:
      component: predictor
  action: ALLOW
  rules:
  - to:
    - operation:
        paths:
        - /metrics
        - /healthz
        - /ready
        - /wait-for-drain
        - /v1/models/*
```

AuthorizationPolicy applied in istio-system will be applied to all namespaces (e.g. if you have kfserving in many namespaces)
