### ISSUE TITLE
torchserve can not read mounted pvc file due to permission denied error

### ISSUE THREAD

**Issue by haijohn** [kserve/kserve#1607]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I download the image_classifer example from gcs and put it in a pvc, pvc is create by NFS storage class, and apply following spec
```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: "torchserve"
spec:
  predictor:
    pytorch:
      # storageUri: gs://kfserving-examples/models/torchserve/image_classifier
      storageUri: "pvc://data-pvc/image_classifier"
```
the pod has following error
```
    State:      Terminated
      Reason:   Error
      Message:  --ts-config file not found: /mnt/models/config/config.properties
```

add command `command: ["sh", "-c", "sleep 1d"]` and exec into the container and `ls /mnt/models` shows the file exists
```
lrwxrwxrwx. 1 root root 64 May 12 02:09 config -> /mnt/pvc/image_classifier/config
lrwxrwxrwx. 1 root root 69 May 12 02:09 model-store -> /mnt/pvc/image_classifier/model-store
```
but `ls /mnt/models/config` got Permission denied
```
ls: cannot access '/mnt/models/config': Permission denied
```
this is because torchserve use `model-server` as user but the mounted file is owned by `root`

I tried to add securityContext to run the container as root and the server started successfully
```
      securityContext:
        runAsUser: 0
```
**My question is: is this a good practice , or are there better solutions, can we mount the pvc using non-root users**

**Environment:**

- Istio Version: 1.9.2
- Knative Version: 0.20.0
- KFServing Version: 0.6.0-rc0
- Kubeflow version: 1.13
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.18.2
- OS (e.g. from `/etc/os-release`): centos7
