### ISSUE TITLE
Inferenceservice Admission Webhook Denied env[3].valueFrom.fieldRef Environment Variable Type

### ISSUE THREAD

**Issue by amybachir** [kserve/kserve#1651]
Was `nferenceservice.kfserving-webhook-server.validator` specifically designed to reject environment variables of this type for a specific reason?
```
- name: DD_AGENT_HOST
   valueFrom:
     fieldRef:
       fieldPath: status.hostIP 
```
I'm trying to enable datadog APM on the inference services pods but  the admission webhook does not like that. I get the following error:

`for: "inferenceservice.yaml": admission webhook "inferenceservice.kfserving-webhook-server.validator" denied the request: Custom container validation error: must not set the field(s): env[3].valueFrom.fieldRef`
