### ISSUE TITLE
Cannot access KFServing InferenceService through Ingress IAP GCP (Error 503).

### ISSUE THREAD

**Issue by austynherman** [kserve/kserve#1660]
/kind bug

**What steps did you take and what happened:**
Cannot access KFServing InferenceService through Ingress (Error 503).

I deployed an instance of Kubeflow (v1.3.0) to GCP accompanied by an KFServing InferenceService. I am unable to access the InferenceService external to the cluster.

The InferenceService is a custom model that was deployed following the custom model tutorial: https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1alpha2/custom/kfserving-custom-model. The manifest:

```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: InferenceService
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
  name: { Model }
spec:
  predictor:
    containers:
      - name: { Model }
        image: { My Image }
```

I was able to verify the above deployment by exec-ing into the deployment and submitting a requests.

```
kubectl exec -it { Model }-predictor-default-00002-deployment-... -- /bin/bash

curl -X POST http://127.0.0.1:8080/v1/models/{ Model }:predict -d '{"instances": [...]}'
>>> {"predictions": "..."}
```

After verifying the deployment, I followed the GCP IAP guide for KFserving (https://github.com/kubeflow/kfserving/tree/master/docs/samples/gcp-iap). I applied an Istio VirtualService manifest to route external traffic from the ingress gateway to the deployment.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-iap
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /kfserving/default/{ Model }
    route:
    - destination:
        ## knative-local-gateway is in the `knative-serving` namespace.
        ## Attempted to make the request with both of the following.
        # host: knative-local-gateway.knative-serving.svc.cluster.local
        host: knative-local-gateway.istio-system.svc.cluster.local
      headers:
        request:
          set:
            Host: { Model }-predictor-default.default.{ Cluster Name }.endpoints.{ Project }.cloud.goog
      weight: 100
    rewrite:
        uri: /v1/models/{ Model }
    timeout: 300s
```

Using the following example, I submit a request to the cluster:
https://github.com/kubeflow/kubeflow/blob/master/docs/gke/iap_request.py

Request
```
python3 iap_request.py https://{ Cluster }.endpoints.{ Project }.cloud.goog/kfserving/default/{ Model }:predict xxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com --input=./input.json
```
Response
```
Bad response from application: 503 / {'date': 'Fri, 11 Jun 2021 04:03:34 GMT', 'server': 'istio-envoy', 'content-length': '0', 'Via': '1.1 google', 'Alt-Svc': 'clear'} / ''
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
During setup I followed the prerequisites (https://github.com/kubeflow/kfserving#prerequisites).

- Istio 1.9.0 required: Istio version is 1.9.3.
- Knative is 0.22.0: No `cluster-local-gateway` setup needed (`knative-local-gateway` has replaced `cluster-local-gateway`)
- Cert Manager: Applied script.
- Applied the inference service config ```kubectl apply -f https://raw.githubusercontent.com/kubeflow/kfserving/master/config/configmap/inferenceservice.yaml```

Related to:
- Issue on older deployments of kubeflow with `cluster-local-gateway` - https://github.com/kubeflow/kfserving/issues/1393
- Same issue on Kubeflow 1.1: https://github.com/kubeflow/kfserving/issues/1199

The solution in issue 1199 appears to be out of date due to the deprecation of the `cluster-local-gateway`.

Any help resolving this would be greatly appreciated.

**Environment:**

- Istio Version: 1.9.3
- Knative Version: v0.22.0
- KFServing Version: v0.5.1 (According to the kubeflow docs https://www.kubeflow.org/docs/components/kfserving/kfserving/)
- Kubeflow version: 1.3.0
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.18.17-gke.1901
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@austynherman check the installation guide [here](https://github.com/kubeflow/kfserving#prerequisites), for 0.5.1 you would need to modify `localGateway` to `knative-local-gateway` and `localGatewayService` to `knative-local-gateway.istio-system.svc.cluster.local` in the [inference service config](https://github.com/kubeflow/kfserving/blob/master/config/configmap/inferenceservice.yaml).

**Comment by yuzisun** [comment]
also the host header is wrong I believe, it should be `{ Model }-predictor-default.default.svc.cluster.local`

**Comment by austynherman** [comment]
@yuzisun I really appreciate the support. 

I have applied the inference service config as you have specified:

```
  ingress: |-
    {
        "ingressGateway" : "$(ingressGateway)",
        "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
        "localGateway" : "knative-local-gateway",
        "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local"
    }
```

I have also updated my virtual service manifest to the following:

**Comment by yuzisun** [comment]
> @yuzisun I really appreciate the support.
> 
> I have applied the inference service config as you have specified:
> 
> ```
>   ingress: |-
>     {
>         "ingressGateway" : "$(ingressGateway)",
>         "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
>         "localGateway" : "knative-local-gateway",
>         "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local"
>     }
> ```
> 
> One interesting thing here is that I had to create the `kfserving-system` namespace. Is this expected?

@austynherman `kfserving-system` is for standalone installation, I think you are using kfserving in kubeflow so kfserving is actually installed in the `kubeflow` namespace as well as the inference service configuration.

```
    ingress: |-
      {
          "ingressGateway" : "kubeflow/kubeflow-gateway",
          "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
          "localGateway" : "knative-serving/knative-local-gateway",
          "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local"
      }
```

**Comment by yuzisun** [comment]
@austynherman also which knative version you are running and is knative local gateway installed, just to make sure it is not same issue as https://github.com/kubeflow/kfserving/issues/1199

**Comment by austynherman** [comment]
@yuzisun I am on Knative version 0.22.0. The `knative-local-gateway` is installed and I am able to see it in "services".


One interesting thing to note, but not entirely sure if it would result in any configuration issues... I noticed that the `knative-local-gateway` is installed in the `knative-serving` namespace when deployed with kubeflow vs `istio-system` when deployed through the standalone process (standalone deployment works but does not use IAP). 

I am reviewing the above error #1199.

**Comment by austynherman** [comment]
@yuzisun I have looked at that issue quite a bit. I do not believe that #1199 is the same error as the issue is centered around the installation of the `cluster-local-gateway` which has been folded into `knative-local-gateway` in later versions of Knative I have (v0.22.0). Does this sound correct to you?

**Comment by yuzisun** [comment]
@austynherman Is this still an issue after applying the right configuration?

**Comment by austynherman** [comment]
@yuzisun Yes. Unfortunately I have not been able to get past this 503 Error.

**Comment by austynherman** [comment]
I also noticed that there are no pods attached to the `knative-local-gateway` with the standard kubeflow 1.3 deployment. In a "stand alone" KFServing deployment, I see the gateway is attached to the `istio-ingressgateway`. Do you think this could be an issue?

Stand alone deployment shows the following in the GCP UI:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/80695206/126164958-ad37c000-921c-44f5-b2b9-45e16e0f97ff.png">


Deploying with Kubeflow 1.3 shows these sections as empty.

**Comment by zijianjoy** [comment]
Exploring the difference between kubeflow/manifests and kubeflow/gcp-blueprints repositories for Knative serving installation. 

kubeflow/manifests repository: https://github.com/kubeflow/manifests/tree/master/common/knative#knative-serving

Google Cloud distribution kubeflow/gcp-blueprints repository: https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/common/knative/kustomization.yaml#L4-L5

Differences:
1. kubeflow/manifests is using knative `serving-core 0.17.4` and `net-istio 0.17.1`. Google Cloud uses version `0.22.0`. Because KFserving requires KFserving version to be 0.19.0+ https://github.com/kubeflow/kfserving#prerequisites
2. kubeflow/manifests installs `serving-post-install-jobs.yaml` with customization, when Google Cloud doesn't install this yaml.
3. kubeflow/manifests skips `knative-ingress-gateway` installation, when Google Cloud doesn't. The following is the Google Cloud gateway list:

```
$ k get gateway -A
NAMESPACE         NAME                      AGE
knative-serving   knative-ingress-gateway   2d18h
knative-serving   knative-local-gateway     2d18h
kubeflow          kubeflow-gateway          2d18h
```

Does these raise any flag for incorrect knative serving installation?

**Comment by zijianjoy** [comment]
I am able to get it working by removing the label selectors in `knative-local-gateway` service. @austynherman Would you like to validate if this fixes the issue on your side?

Run command: `kubectl edit svc knative-local-gateway -n istio-system`

Change the following:

```
spec: 
  selector:
    app.kubernetes.io/component: knative-serving-install
    app.kubernetes.io/name: knative-serving-install
    istio: ingressgateway
    kustomize.component: knative
```

to:

```
spec: 
  selector:
    istio: ingressgateway
```

After that, you should be able to see matching pods for knative-local-gateway service:

![knative-local-gateway-pod](https://user-images.githubusercontent.com/37026441/128949866-23f76e50-e520-450b-8d87-a4102afc72d3.png)


Reference: https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/common/knative/kustomization.yaml#L7-L10
