### ISSUE TITLE
HTTPError: 503 Server Error: Service Unavailable for url

### ISSUE THREAD

**Issue by karlschriek** [kserve/kserve#1700]
/kind bug

**What steps did you take and what happened:**

This is more of a request for help than a bug report at this point, since I have not yet managed to pinpoint exactly where the problem lies. We are currently trying to get KFServing to work on [argoflow-aws](https://github.com/argoflow/argoflow-aws/tree/feature/kfserving-testing), so the setup is not 100% comparable to what is in the KF 1.3 manifests.

We are currently working with a setup with Istio 1.10.1, KNative 0.24 and KFServing 0.6.0. 

I am deploying the following example model spec:

```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "flowers"
  namespace: karl-schriek
spec:
  default:
    predictor:
      tensorflow:
        storageUri: "gs://kfserving-samples/models/tensorflow/flowers"
```

To make a long story short, this produces a model at the Endpoint `flowers-karl-schriek.serving.dev-kfserving-test-4.build-mlops-2.com`. However, sending a REST request (with the required cookies) to this address (or from inside the cluster to the address `flowers.karl-schriek.svc.cluster.local`) results in `HTTPError: 503 Server Error: Service Unavailable for url`. Querying the KNative endpoints that sits behind the KFServing enpoint directly works (i.e. going directly to` flowers-predictor-default-karl-schriek.serving.dev-kfserving-test-4.build-mlops-2.com`).

My understanding of what is supposed to happen is as follows:

A REST request is sent to `flowers-karl-schriek.serving.dev-kfserving-test-4.build-mlops-2.com` which comes in via the `istio-ingressgateway` Service (LoadBalancer) and the `istio-ingressgateway` Pod routes it via the `kubeflow-gateway` where it is picked up by the `flowers` VirtualService, which rewrites the host as `flowers-predictor-default.karl-schriek.svc.cluster.local` and sends it off to the `knative-local-gateway` Service. From here it lands again at the `istio-ingressgateway` Pod which this time routes it via the `knative-local-gateway` Gateway where it should then hit one of `flower-predictor-default-ingress` or `flowers-predictor-default-mesh` VirtualServicies (I am not sure which one) from where it is finally routed to the model behind.

However this process seems to break down at the point where `knative-local-gateway` forwards to the `istio-ingressgateway` Pod. Or at least, it doesn't look like the  `flower-predictor-default-ingress`/`flowers-predictor-default-mesh` is receiving the request with the altered host. The break could however be happending anywhere and it could also be that the VS is simply not configured correctly in the end. 

Below is a small diagram representing what i defined above:

![image](https://user-images.githubusercontent.com/25316920/124279903-5085b400-db48-11eb-854f-8f79cd4080a2.png)

And here are the various resource Specs:

**flowers:**
```
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: flowers
  namespace: karl-schriek
spec:
  gateways:
    - knative-serving/knative-local-gateway
    - kubeflow/kubeflow-gateway
  hosts:
    - flowers.karl-schriek.svc.cluster.local
    - flowers-karl-schriek.serving.dev-kfserving-test-4.build-mlops-2.com
  http:
    - headers:
        request:
          set:
            Host: flowers-predictor-default.karl-schriek.svc.cluster.local
      match:
        - authority:
            regex: '^flowers\.karl-schriek(\.svc(\.cluster\.local)?)?(?::\d{1,5})?$'
          gateways:
            - knative-serving/knative-local-gateway
        - authority:
            regex: >-
              ^flowers-karl-schriek\.serving\.dev-kfserving-test-4\.build-mlops-2\.com(?::\d{1,5})?$
          gateways:
            - kubeflow/kubeflow-gateway
      route:
        - destination:
            host: knative-local-gateway.istio-system.svc.cluster.local
            port:
              number: 80
          weight: 100
```

**flowers-predictor-default-ingress**
```
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  labels:
    networking.internal.knative.dev/ingress: flowers-predictor-default
    serving.knative.dev/route: flowers-predictor-default
    serving.knative.dev/routeNamespace: karl-schriek
  name: flowers-predictor-default-ingress
  namespace: karl-schriek
spec:
  gateways:
    - knative-serving/knative-local-gateway
    - kubeflow/kubeflow-gateway
  hosts:
    - >-
      flowers-predictor-default-karl-schriek.serving.dev-kfserving-test-4.build-mlops-2.com
    - flowers-predictor-default.karl-schriek
    - flowers-predictor-default.karl-schriek.svc
    - flowers-predictor-default.karl-schriek.svc.cluster.local
  http:
    - headers:
        request:
          set:
            K-Network-Hash: ddfb1f2c402c7317d72483bbafe7dd50741b0eabac11da044be46ba0d56dc6e1
      match:
        - authority:
            prefix: flowers-predictor-default.karl-schriek
          gateways:
            - knative-serving/knative-local-gateway
          headers:
            K-Network-Hash:
              exact: override
      retries: {}
      route:
        - destination:
            host: flowers-predictor-default-00001.karl-schriek.svc.cluster.local
            port:
              number: 80
          headers:
            request:
              set:
                Knative-Serving-Namespace: karl-schriek
                Knative-Serving-Revision: flowers-predictor-default-00001
          weight: 100
    - match:
        - authority:
            prefix: flowers-predictor-default.karl-schriek
          gateways:
            - knative-serving/knative-local-gateway
      retries: {}
      route:
        - destination:
            host: flowers-predictor-default-00001.karl-schriek.svc.cluster.local
            port:
              number: 80
          headers:
            request:
              set:
                Knative-Serving-Namespace: karl-schriek
                Knative-Serving-Revision: flowers-predictor-default-00001
          weight: 100
    - headers:
        request:
          set:
            K-Network-Hash: ddfb1f2c402c7317d72483bbafe7dd50741b0eabac11da044be46ba0d56dc6e1
      match:
        - authority:
            prefix: >-
              flowers-predictor-default-karl-schriek.serving.dev-kfserving-test-4.build-mlops-2.com
          gateways:
            - kubeflow/kubeflow-gateway
          headers:
            K-Network-Hash:
              exact: override
      retries: {}
      route:
        - destination:
            host: flowers-predictor-default-00001.karl-schriek.svc.cluster.local
            port:
              number: 80
          headers:
            request:
              set:
                Knative-Serving-Namespace: karl-schriek
                Knative-Serving-Revision: flowers-predictor-default-00001
          weight: 100
    - match:
        - authority:
            prefix: >-
              flowers-predictor-default-karl-schriek.serving.dev-kfserving-test-4.build-mlops-2.com
          gateways:
            - kubeflow/kubeflow-gateway
      retries: {}
      route:
        - destination:
            host: flowers-predictor-default-00001.karl-schriek.svc.cluster.local
            port:
              number: 80
          headers:
            request:
              set:
                Knative-Serving-Namespace: karl-schriek
                Knative-Serving-Revision: flowers-predictor-default-00001
          weight: 100
```

**flowers-predictor-default-mesh**
```
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  labels:
    networking.internal.knative.dev/ingress: flowers-predictor-default
    serving.knative.dev/route: flowers-predictor-default
    serving.knative.dev/routeNamespace: karl-schriek  
  name: flowers-predictor-default-mesh
  namespace: karl-schriek
 spec:
  gateways:
    - mesh
  hosts:
    - flowers-predictor-default.karl-schriek
    - flowers-predictor-default.karl-schriek.svc
    - flowers-predictor-default.karl-schriek.svc.cluster.local
  http:
    - headers:
        request:
          set:
            K-Network-Hash: ddfb1f2c402c7317d72483bbafe7dd50741b0eabac11da044be46ba0d56dc6e1
      match:
        - authority:
            prefix: flowers-predictor-default.karl-schriek
          gateways:
            - mesh
          headers:
            K-Network-Hash:
              exact: override
      retries: {}
      route:
        - destination:
            host: flowers-predictor-default-00001.karl-schriek.svc.cluster.local
            port:
              number: 80
          headers:
            request:
              set:
                Knative-Serving-Namespace: karl-schriek
                Knative-Serving-Revision: flowers-predictor-default-00001
          weight: 100
    - match:
        - authority:
            prefix: flowers-predictor-default.karl-schriek
          gateways:
            - mesh
      retries: {}
      route:
        - destination:
            host: flowers-predictor-default-00001.karl-schriek.svc.cluster.local
            port:
              number: 80
          headers:
            request:
              set:
                Knative-Serving-Namespace: karl-schriek
                Knative-Serving-Revision: flowers-predictor-default-00001
          weight: 100
```

The Gateways are defined as follows:

**kubeflow-gateway**
```
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  labels:
    app.kubernetes.io/instance: istio-resources  
  name: kubeflow-gateway
  namespace: kubeflow
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - kubeflow.dev-kfserving-test-4.build-mlops-2.com
        - serving.dev-kfserving-test-4.build-mlops-2.com
        - '*.serving.dev-kfserving-test-4.build-mlops-2.com'
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - kubeflow.dev-kfserving-test-4.build-mlops-2.com
        - serving.dev-kfserving-test-4.build-mlops-2.com
        - '*.serving.dev-kfserving-test-4.build-mlops-2.com'
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: kubeflow-ingressgateway-certs
        mode: SIMPLE
```

**knative-local-gateway**
```
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  labels:
    app.kubernetes.io/instance: knative
    networking.knative.dev/ingress-provider: istio
    serving.knative.dev/release: v0.24.0 
  name: knative-local-gateway
  namespace: knative-serving
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: http
        number: 8081
        protocol: HTTP
```

The gateway Services are defined as follows:

**istio-ingressgateway**
```
kind: Service
apiVersion: v1
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  uid: 6140f53d-19dd-42db-a9d1-db6a4776268e
  resourceVersion: '2283420'
  creationTimestamp: '2021-06-23T13:19:01Z'
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: istio
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.10.2
    release: istio
  annotations:
    ....   
spec:
  ports:
    - name: status-port
      protocol: TCP
      port: 15021
      targetPort: 15021
      nodePort: 30941
    - name: http2
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32513
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
      nodePort: 31057
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  clusterIP: 172.20.7.206
  clusterIPs:
    - 172.20.7.206
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - hostname: >-
          nlb-dev-kfserving-test-4-4fb326bde7472038.elb.eu-central-1.amazonaws.com
```

**knative-local-gateway**
```
kind: Service
apiVersion: v1
metadata:
  name: knative-local-gateway
  namespace: istio-system  
  labels:
    app.kubernetes.io/instance: knative
    experimental.istio.io/disable-gateway-port-translation: 'true'
    networking.knative.dev/ingress-provider: istio
    serving.knative.dev/release: v0.24.0
  spec:
  ports:
    - name: http2
      protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    istio: ingressgateway
  clusterIP: 172.20.247.16
  clusterIPs:
    - 172.20.247.16
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
```

**What did you expect to happen:**

I would expect the REST request to `flowers-karl-schriek.serving.dev-kfserving-test-4.build-mlops-2.com` to get through the the KFServing model in the back.

My question is if there is anything that strikes you here on being obviously wrong or missing?

@yuzisun @theofpa ?

@DavidSpek  FYI.

**Environment:**

- Istio Version: 1.10.1
- Knative Version: 0.24
- KFServing Version: 0.6.0
- Kubeflow version: 1.3 (sort of)
- Kubernetes version: 1.20
