### ISSUE TITLE
The custom kfserving doesn't work with private image registry

### ISSUE THREAD

**Issue by SeibertronSS** [kserve/kserve#1719]
Hello everyone

I try to customize kfserving according to the [tutorial](https://github.com/kubeflow/kfserving/blob/master/docs/samples/v1beta1/custom/custom_model/README.md), but it doesn't work properly. The image I build by myself can work normally locally, but when I deploy an inferenceservice, k8s prompts me that the image can't be found. I have already pushed the image to the repository. At the same time, the pod corresponding to the inferenceservice doesn't appear. (The program I use comes from [here](https://github.com/kubeflow/kfserving/tree/master/python/custom_model)) Why is there a problem of not being able to find the image?

**Comment by SeibertronSS** [comment]
I also find that `kfserving==0.5.1` needs to be specified in`requirements.txt`. The latest version of kfserving will cause the image build to fail.

**Comment by SeibertronSS** [comment]
The error message is as follows, `Revision "custom-model-predictor-default-c9cb6" failed with message: Unable to fetch image "xxx.xxx.com/xxx/custom-model:v1": failed to resolve image to digest: failed to fetch image information: Get https://xxx.xxx.com/v2/: dial tcp xxx.xx.x.xx:443: connect: connection timed out.` This seems to be a knative certificate issue.(https://stackoverflow.com/questions/60416312/knative-service-unable-to-download-hello-world-image-from-docker-hub)(https://github.com/knative/serving/issues/8038)

**Comment by yuzisun** [comment]
@SeibertronSS which image registry you are using?  Also can you share what's causing the image build to fail using latest kfserving sdk?

**Comment by SeibertronSS** [comment]
> @SeibertronSS which image registry you are using? Also can you share what's causing the image build to fail using latest kfserving sdk?

Thank you very much for your reply.
The registry I use is built by our company, not dockerhub. Do I have to use dockerhub?
The problem I encountered when building images using the latest kfserving are as follows,
```
20: Pulling from heroku/buildpacks
c549ccf8d472: Already exists
8604388c59ec: Already exists
2ae213b746a8: Already exists
01e8ca5a279a: Pull complete
7eac610903ea: Pull complete
618d46b9d5ad: Pull complete
b3a5c46fea69: Pull complete
357fefdf9bc9: Pull complete
a697cc8a1d5c: Pull complete
5c54716644fd: Pull complete
93efa6a4be6e: Pull complete
2bb98bc75455: Pull complete
5035dafe4b03: Pull complete
c10fd1b9aa75: Pull complete
5232ada5c376: Pull complete
03fb7dba7baa: Pull complete
176339affd3c: Pull complete
d164f15ad646: Pull complete
491c1ce9c4f9: Pull complete
e4302ddcbc25: Pull complete
1dbb82a94c0c: Pull complete
a311ef07bf61: Pull complete
8f7ab136a2c9: Pull complete
6018af265953: Pull complete
f18d74887f79: Pull complete
d2a2659301d3: Pull complete
08d54b036422: Pull complete
79e543bfa977: Pull complete
5b4e401b4f57: Pull complete
389c78e055a8: Pull complete
7b1b24b7b79e: Pull complete
1a5fa6ac112c: Pull complete
4e062952eafd: Pull complete
c3dea1ee6789: Pull complete
9215aa0839f1: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:adb9e739d4699e1d1b0b802b7c47adb1c2cf9d3f7f0792ea2e8457fe63161975
Status: Downloaded newer image for heroku/buildpacks:20
20: Pulling from heroku/pack
c549ccf8d472: Already exists
8604388c59ec: Already exists
2ae213b746a8: Already exists
f419dc473af0: Pull complete
add6af8d5e72: Pull complete
Digest: sha256:85510cc68fd8bc25db4dadadd84c0f4fc003fd09a6122c538d5b99d98b1e485d
Status: Downloaded newer image for heroku/pack:20
===> DETECTING
======== Output: heroku/ruby@0.0.1 ========
no
err:  heroku/ruby@0.0.1 (1)
heroku/python   0.3.1
heroku/procfile 0.6.2
===> ANALYZING
Previous image with name "dockerhub.jd.com/ime/custom-model-test:v1" not found
===> RESTORING
===> BUILDING
-----> No Python version was specified. Using the buildpack default: python-3.9.6
       To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes
-----> Installing python-3.9.6
-----> Installing pip 20.2.4, setuptools 47.1.1 and wheel 0.36.2
-----> Installing SQLite3
-----> Installing requirements with pip
       Collecting kfserving
         Downloading kfserving-0.6.0-py3-none-any.whl (287 kB)
       Collecting torchvision
         Downloading torchvision-0.10.0-cp39-cp39-manylinux1_x86_64.whl (22.1 MB)
       Collecting tornado>=6.0.0
         Downloading tornado-6.1-cp39-cp39-manylinux2010_x86_64.whl (427 kB)
       Collecting botocore>=1.20.32
         Downloading botocore-1.20.110-py2.py3-none-any.whl (7.7 MB)
       Collecting psutil>=5.0
         Downloading psutil-5.8.0-cp39-cp39-manylinux2010_x86_64.whl (293 kB)
       Collecting adal>=1.2.2
         Downloading adal-1.2.7-py2.py3-none-any.whl (55 kB)
       Collecting numpy>=1.17.3
         Downloading numpy-1.21.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
       Collecting google-cloud-storage>=1.31.0
         Downloading google_cloud_storage-1.40.0-py2.py3-none-any.whl (104 kB)
       Collecting certifi>=14.05.14
         Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
       Collecting six>=1.15
         Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
       Collecting minio<7.0.0,>=4.0.9
         Downloading minio-6.0.2-py2.py3-none-any.whl (73 kB)
       Collecting boto3>=1.17.32
         Downloading boto3-1.17.110-py2.py3-none-any.whl (131 kB)
       Collecting table-logger>=0.3.5
         Downloading table_logger-0.3.6-py3-none-any.whl (14 kB)
       Collecting kubernetes>=12.0.0
         Downloading kubernetes-17.17.0-py3-none-any.whl (1.8 MB)
       Collecting python-dateutil>=2.5.3
         Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
       Collecting argparse>=1.4.0
         Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
       ERROR: Could not find a version that satisfies the requirement ray[serve]==1.3.0 (from kfserving->-r /workspace/requirements.txt (line 1)) (from versions: 1.4.1)
       ERROR: No matching distribution found for ray[serve]==1.3.0 (from kfserving->-r /workspace/requirements.txt (line 1))
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 145
```

**Comment by yuzisun** [comment]
@SeibertronSS check this [knative documention](https://knative.dev/development/developer/serving/tag-resolution), maybe your registry is behind your corporate proxy.

**Comment by SeibertronSS** [comment]
> @SeibertronSS check this [knative documention](https://knative.dev/development/developer/serving/tag-resolution), maybe your registry is behind your corporate proxy.
Thank you very much for your suggestion.
I check the documention you give, but I still don't understand the content. I am a newbie to Knative, and I install Knative through [kubeflow manifests](https://github.com/kubeflow/manifests). What file do I need to modify to proxy the tag resolution requests between the controller and my registry.

**Comment by SeibertronSS** [comment]
> @SeibertronSS check this [knative documention](https://knative.dev/development/developer/serving/tag-resolution), maybe your registry is behind your corporate proxy.

I try to use corporate proxy in the controller, but this caused the controller pod to Error.

|NAME|                                READY|   STATUS  |  RESTARTS |  AGE|
|----|----|----|----|----|
|activator-789bcb5644-gtrfm |         1/1|     Running|   0 |         60s|
|autoscaler-5888bf7697-495g2  |       1/1  |   Running |  0  |        60s|
|controller-85f5d9879d-tpnwh|         1/1|     Error|   2   |       60s|
|istio-webhook-7db84bf7bf-rtsmq   |   1/1  |  Running |  0  |        60s|
|networking-istio-55d86868c6-bbzgr |  1/1   |  Running |  0      |    60s|
|webhook-579f9448c4-klld7         |   1/1  |   Running  | 0    |      60s|

My yaml file is:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    serving.knative.dev/release: v0.14.3
  name: controller
  namespace: knative-serving
spec:
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
      labels:
        app: controller
        serving.knative.dev/release: v0.14.3
    spec:
      containers:
      - env:
        - name: HTTP_PROXY
          value: http://dockerhub.xxx.com
        - name: HTTPS_PROXY
          value: https://dockerhub.xxx.com
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: knative.dev/internal/serving
        image: 'gcr.io/knative-releases/knative.dev/serving/cmd/controller@sha256:b86ac8ecc6b2688a0e0b9cb68298220a752125d0a048b8edf2cf42403224393c'
        name: controller
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 8008
          name: profiling
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
      serviceAccountName: controller
```

The Pod log shows
```
2021/07/14 02:25:14 Registering 4 clients
2021/07/14 02:25:14 Registering 4 informer factories
2021/07/14 02:25:14 Registering 13 informers
2021/07/14 02:25:14 Registering 7 controllers
2021/07/14 02:25:29 Error reading/parsing logging configuration: timed out waiting for the condition
```
If I comment out `HTTP_PROXY` and `HTTPS_PROXY`, the controller can work normally.
Why this problem occurs？
