### ISSUE TITLE
Can't deploy a custom inference service by pythonSDK with PVC

### ISSUE THREAD

**Issue by SeibertronSS** [kserve/kserve#1733]
Hello everyone
I try to deploy a custom inference service by pythonSDK. I have built my docker image. My code is as follows.
```
import os
import time
import logging


import kubernetes.client as k8s_client
from kubernetes.client import V1Container
from kubernetes.client import V1ResourceRequirements

from kfserving import constants
from kfserving import KFServingClient
from kfserving import V1beta1PredictorSpec
from kfserving import V1beta1InferenceService
from kfserving import V1beta1InferenceServiceSpec


KFSERVING_TEST_NAMESPACE = 'kfserving'

logging.basicConfig(level=logging.INFO)


KFServing = KFServingClient(
    config_file=os.environ.get("KUBECONFIG", "~/.kube/config"))


def test_pytorch(model_name: str, model_dir: str, model_class_name: str):
    volume_name = 'cifar10-beta-cpu'
    pvc_name = 'kfserving-pytorch-kubeflow'
    pvc_mount_path = '/mnt/models'

    volumes = k8s_client.V1Volume(
        name=volume_name,
        persistent_volume_claim=k8s_client.V1PersistentVolumeClaimVolumeSource(
            claim_name=pvc_name))
    volume_mounts = k8s_client.V1VolumeMount(
        mount_path=pvc_mount_path,
        name=volume_name)

    predictor = V1beta1PredictorSpec(
        max_replicas=5,
        min_replicas=1,
        timeout=6,
        volumes=[volumes],
        containers=[V1Container(
            name='kfserving-container',
            image='SeibertronSS/custom-model:v2',
            image_pull_policy='IfNotPresent',
            volume_mounts=[volume_mounts],
            args=([f'--model_name {model_name}', f'--model_dir {model_dir}',
                  f'--model_class_name {model_class_name}']),
            resources=V1ResourceRequirements(
                requests={'cpu': '200m', 'memory': '2Gi'},
                limits={'cpu': '200m', 'memory': '2Gi'}
            )
        )]
    )

    isvc = V1beta1InferenceService(api_version=constants.KFSERVING_V1BETA1,
                                   kind=constants.KFSERVING_KIND,
                                   metadata=k8s_client.V1ObjectMeta(
                                       name=model_name, namespace=KFSERVING_TEST_NAMESPACE),
                                   spec=V1beta1InferenceServiceSpec(predictor=predictor))

    KFServing.create(isvc)

    try:
        KFServing.wait_isvc_ready(
            model_name, namespace=KFSERVING_TEST_NAMESPACE, watch=True)

    except RuntimeError as e:
        print(KFServing.api_instance.get_namespaced_custom_object("serving.knative.dev", "v1", KFSERVING_TEST_NAMESPACE,
                                                                  "services", model_name + "-predictor-default"))
        pods = KFServing.core_api.list_namespaced_pod(KFSERVING_TEST_NAMESPACE,
                                                      label_selector='serving.kubeflow.org/inferenceservice={}'.
                                                      format(model_name))
        for pod in pods.items:
            print(pod)
        raise e


if __name__ == "__main__":
    start_time = time.time()

    test_pytorch(model_name='custom-cifar10-beta-cpu',
                 model_dir='/mnt/models/cifar10_multi_parameters', model_class_name='Net')

    end_time = time.time()

    run_time = end_time - start_time

    logging.info("run_time: %f", run_time)
```
Running the program won't be able to successfully deploy isvc. I get a warring.
```
Events:
  Type     Reason         Age                   From                Message
  ----     ------         ----                  ----                -------
  Warning  InternalError  4m44s (x17 over 10m)  v1beta1Controllers  fails to reconcile predictor: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: expected exactly one, got neither: spec.template.spec.volumes[0].configMap, spec.template.spec.volumes[0].projected, spec.template.spec.volumes[0].secret
must not set the field(s): spec.template.spec.volumes[0].persistentVolumeClaim
```
Why can't I use pvc?

**Comment by yuzisun** [comment]
@SeibertronSS you should use the [PVC storage uri](https://github.com/kubeflow/kfserving/tree/master/docs/samples/storage/pvc) instead, under the hood it does the same thing as you did.

**Comment by SeibertronSS** [comment]
> @SeibertronSS you should use the [PVC storage uri](https://github.com/kubeflow/kfserving/tree/master/docs/samples/storage/pvc) instead, under the hood it does the same thing as you did.

Thank you very much for your suggestions. I will do some experiments.

**Comment by SeibertronSS** [comment]
> @SeibertronSS you should use the [PVC storage uri](https://github.com/kubeflow/kfserving/tree/master/docs/samples/storage/pvc) instead, under the hood it does the same thing as you did.

I modify the code to
```
def test_pytorch(model_name: str):
    predictor = V1beta1PredictorSpec(
        max_replicas=5,
        min_replicas=1,
        pytorch=V1beta1TorchServeSpec(
            storage_uri='pvc://kfserving-pytorch-kubeflow/cifar10',
            model_class_name="Net",
            image='SeibertronSS/custom-model:v3',
            resources=V1ResourceRequirements(
                requests={'cpu': '1', 'memory': '5Gi'},
                limits={'cpu': '1', 'memory': '5Gi'}
            )
        )
    )

    isvc = V1beta1InferenceService(api_version=constants.KFSERVING_V1BETA1,
                                   kind=constants.KFSERVING_KIND,
                                   metadata=k8s_client.V1ObjectMeta(
                                       name=model_name, namespace=KFSERVING_TEST_NAMESPACE),
                                   spec=V1beta1InferenceServiceSpec(predictor=predictor))

    KFServing.create(isvc)

    try:
        KFServing.wait_isvc_ready(
            model_name, namespace=KFSERVING_TEST_NAMESPACE, watch=True)

    except RuntimeError as e:
        print(KFServing.api_instance.get_namespaced_custom_object("serving.knative.dev", "v1", KFSERVING_TEST_NAMESPACE,
                                                                  "services", model_name + "-predictor-default"))
        pods = KFServing.core_api.list_namespaced_pod(KFSERVING_TEST_NAMESPACE,
                                                      label_selector='serving.kubeflow.org/inferenceservice={}'.
                                                      format(model_name))
        for pod in pods.items:
            print(pod)
        raise e
```
This seems to be able to use PVC. But I get another error,
```
Traceback (most recent call last):
  File "test_model.py", line 15, in <module>
    from pytorchserver import PyTorchModel
  File "/workspace/pytorchserver/pytorchserver/__init__.py", line 15, in <module>
    from .model import PyTorchModel  # noqa # pylint: disable=unused-import
  File "/workspace/pytorchserver/pytorchserver/model.py", line 15, in <module>
    import kfserving
  File "/workspace/kfserving/kfserving/__init__.py", line 18, in <module>
    from kfserving.storage import Storage
  File "/workspace/kfserving/kfserving/storage.py", line 32, in <module>
    from azure.storage.blob import BlockBlobService
  File "/opt/conda/envs/pytorch-py37/lib/python3.7/site-packages/azure/storage/blob/__init__.py", line 6, in <module>
    from .appendblobservice import AppendBlobService
  File "/opt/conda/envs/pytorch-py37/lib/python3.7/site-packages/azure/storage/blob/appendblobservice.py", line 30, in <module>
    from ._deserialization import (
  File "/opt/conda/envs/pytorch-py37/lib/python3.7/site-packages/azure/storage/blob/_deserialization.py", line 42, in <module>
    from ._encryption import _decrypt_blob
  File "/opt/conda/envs/pytorch-py37/lib/python3.7/site-packages/azure/storage/blob/_encryption.py", line 13, in <module>
    from cryptography.hazmat.primitives.padding import PKCS7
  File "/opt/conda/envs/pytorch-py37/lib/python3.7/site-packages/cryptography/hazmat/primitives/padding.py", line 11, in <module>
    from cryptography.hazmat.bindings._padding import lib
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```
how to solve this error? 
This is the error I get after running test_model.py in the container. When I publish an isvc, I will get the same error.
test_model.py is as follows.
```
from pytorchserver import PyTorchModel
import torch
import torchvision
import torchvision.transforms as transforms
import os

model_dir = model_dir = os.path.join(os.path.dirname(__file__), "example_model", "model")


def test_model():
    server = PyTorchModel("model", "Net", model_dir)
    server.load()

    transform = transforms.Compose([transforms.ToTensor(),
                                    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
    testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                           download=True, transform=transform)
    testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                             shuffle=False, num_workers=2)
    dataiter = iter(testloader)
    images, _ = dataiter.next()

    request = {"instances": images[0:1].tolist()}
    response = server.predict(request)
    assert isinstance(response["predictions"][0], list)
```

**Comment by golimix** [comment]
```
Events:
  Type     Reason         Age                From                Message
  ----     ------         ----               ----                -------
  Warning  InternalError  5s (x15 over 87s)  v1beta1Controllers  fails to reconcile predictor: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: expected exactly one, got neither: spec.template.spec.volumes[0].configMap, spec.template.spec.volumes[0].projected, spec.template.spec.volumes[0].secret
must not set the field(s): spec.template.spec.volumes[0].emptyDir
```

the same error when deploy a custom inference service

can some one do some help?

**Comment by pkurzend** [comment]
same error here.
This is my yaml:
```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: myInferenceService
  annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1m5s"
spec:
  predictor:
    containerConcurrency: 1
    minReplicas: 0
    maxReplicas: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: gpu.nvidia.com/class
              operator: In
              values:
              - RTX_A5000
            - key: topology.kubernetes.io/region
              operator: In
              values:
              - ORD1 
    volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: stable-diffusion-model-cache
    containers:
      - name: kserve-container
        image: <imagename>
        env:
          - name: HF_HOME
            value: /mnt/models/
        volumeMounts:
          - name: model-cache
            mountPath: /mnt/models
        resources:
          requests:
            cpu: 6
            memory: 32Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 6
            memory: 32Gi
            nvidia.com/gpu: 1
```

Is it not possible to mount the pvc in inference service? I am aware of the STORAGE_URI env variable, but it gives readonly access.
can some one do some help?
