### ISSUE TITLE
Unable to serve basic sklearn Pipeline based model with mixed type features

### ISSUE THREAD

**Issue by marrrcin** [kserve/kserve#1799]
/kind bug

**What steps did you take and what happened:**
1. Get dataset with multiple column types (e.g. strings and floats / ints).
2. Create sklearn Pipeline-based model with `ColumnTransformer` inside.
3. Train the model, dump it to storage, deploy it using `InferenceService`.
(You can train simple model using this all-in-one notebook: https://gist.github.com/marrrcin/838a90077c3fabaf7dc53f0ae543018d )

<details>
  <summary>See example sklearn model:</summary>

```python

p = Pipeline(
        [
            (
                "preprocess",
                ColumnTransformer(
                    [
                        (
                            "numerical",
                            make_pipeline(
                                SimpleImputer(strategy="mean"),
                                StandardScaler(),
                            ),
                            ["a", "b", "c"],
                        ),
                        (
                            "categorical",
                            make_pipeline(
                                SimpleImputer(strategy="most_frequent"),
                                OneHotEncoder(handle_unknown="ignore", sparse=False),
                            ),
                            ["d", "e", "f"],
                        ),
                    ]
                ),
            ),
            ("regressor", SGDRegressor(random_state=666)),
        ]
)
```

</details>

**What did you expect to happen:**

## With v1 protocol
In order to even deploy this model with v1 protocol, you need to update sklearn version as per https://github.com/kubeflow/kfserving/tree/master/python/sklearnserver#building-your-own-scikit-learn-server-docker-image ).

<details>
  <summary>InferenceService</summary>

```yaml
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "my-model"
spec:
  predictor:
    sklearn:
      storageUri: "s3://<path to my model>"
      protocolVersion: "v1"
      resources:
        limits:
          cpu: 1.0
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
```

</details>

When I deploy the model using `v1` protocol, I expect it to return valid responses, but I get:
```
curl -X POST http://my-model.kfserving-test.svc.cluster.local/v1/models/my-model:predict -d '{"instances":[[548, 8450, 7, 2003, 2008, "Reg", "RL", "CollgCr", "WD", "AllPub"]]}'

<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>
```
```
     Traceback (most recent call last): 
       File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute 
         result = await result 
       File "/kfserving/kfserving/handlers/http.py", line 71, in post 
         response = await model(body) 
       File "/kfserving/kfserving/kfmodel.py", line 61, in __call__ 
         else self.predict(request) 
       File "/sklearnserver/sklearnserver/model.py", line 56, in predict 
         raise Exception("Failed to predict %s" % e) 
     Exception: Failed to predict Specifying the columns using strings is only supported for pandas DataFrames 
```

## With v2 protocol

<details>
  <summary>InferenceService</summary>

```yaml
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "my-model"
spec:
  predictor:
    sklearn:
      storageUri: "s3://<path to my model>"
      protocolVersion: "v2"
      resources:
        limits:
          cpu: 1.0
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
```

</details>

When I deploy the model using `v2` protocol, I expect it to return valid responses, but I get:

```
curl -X POST http://my-model.kfserving-test.svc.cluster.local/v2/models/my-model/infer -d '{"inputs": [{"name": "GarageArea", "datatype": "INT32", "shape": [1], "data": [548]}, {"name": "LotArea", "datatype": "INT32", "shape": [1], "data": [8450]}, {"name": "OverallQual", "datatype": "INT32", "shape": [1], "data": [7]}, {"name": "YearBuilt", "datatype": "INT32", "shape": [1], "data": [2003]}, {"name": "YrSold", "datatype": "INT32", "shape": [1], "data": [2008]}, {"name": "LotShape", "datatype": "BYTES", "shape": [1], "data": ["Reg"], "parameters": {"content_type": "str"}}, {"name": "MSZoning", "datatype": "BYTES", "shape": [1], "data": ["RL"], "parameters": {"content_type": "str"}}, {"name": "Neighborhood", "datatype": "BYTES", "shape": [1], "data": ["CollgCr"], "parameters": {"content_type": "str"}}, {"name": "SaleType", "datatype": "BYTES", "shape": [1], "data": ["WD"], "parameters": {"content_type": "str"}}, {"name": "Utilities", "datatype": "BYTES", "shape": [1], "data": ["AllPub"], "parameters": {"content_type": "str"}}]}'
```

```json
{"error":"SKLearnModel only supports a single input tensor (10 were received)"
```

I see no other way to pass mixed data types into v2 protocol other than splitting the features.

**Anything else you would like to add:**
It blocks the productivity of Data Scientists who are used to sklearn Pipelines, because they would have to split the models into separate _Transformer_ and _Predictor_ pieces even for simple use cases, such as this one.

**Environment:**

- Istio Version: 1.11.1
- Knative Version: 0.25.0
- KFServing Version: 0.6.0
- Kubeflow version: n/a (standalone deployment)
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): n/a
