### ISSUE TITLE
InferenceService times out when scaling back up from zero

### ISSUE THREAD

**Issue by pratikgujjar** [kserve/kserve#1805]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Ran the kfserving custom model example https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1alpha2/custom/kfserving-custom-model but with the resource definition in v1beta1 format:

```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: kfserving-custom-model
  annotations:
    autoscaling.knative.dev/target: "1"
spec:
  predictor:
    minReplicas: 0
    containers:
      - name: kfserving-container
        image: {username}/kfserving-custom-model
    imagePullSecrets:
      - name: credentials
```
Load is generated using hey as suggested 

` hey -z 30s -c 5 -m POST -host ${HOST} -D $INPUT_PATH http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models/$MODEL_NAME:predict `

This results in a client timeout error while the pods are being scaled up from zero.

```
Summary:
  Total:        40.0026 secs
  Slowest:      0.0000 secs
  Fastest:      0.0000 secs
  Average:       NaN secs
  Requests/sec: 0.2500


Response time histogram:


Latency distribution:

Details (average, fastest, slowest):
  DNS+dialup:    NaN secs, 0.0000 secs, 0.0000 secs
  DNS-lookup:    NaN secs, 0.0000 secs, 0.0000 secs
  req write:     NaN secs, 0.0000 secs, 0.0000 secs
  resp wait:     NaN secs, 0.0000 secs, 0.0000 secs
  resp read:     NaN secs, 0.0000 secs, 0.0000 secs

Status code distribution:

Error distribution:
  [10]  Post http://192.168.49.2:31402/v1/models/kfserving-custom-model:predict: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

```

**What did you expect to happen:**
No errors. But slower response time.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.9.0
- Knative Version: v0.22.0
- KFServing Version: v0.6.0
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version: 1.22.0
- Kubernetes version: (use `kubectl version`): 1.19.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04
