### ISSUE TITLE
Multiple Transformers in Multi Model Serving

### ISSUE THREAD

**Issue by swapkh91** [kserve/kserve#1809]
I have a use case where I need to deploy 2 (and maybe more) models on triton, which I think can be done using MMS. 

These models have different preprocess and postprocess steps.

As per the documentation, I need to create an `InferenceService` with predictor as `triton` and no `storageUri` and 2 `TrainedModel` CRs. 

But where do I specify the image to use of those 2 models' transformers, like we do in normal InferenceService as `containers`? I don't see that option in [ModelSpec](https://github.com/kubeflow/kfserving/blob/master/python/kfserving/docs/V1beta1ModelSpec.md)

**Comment by swapkh91** [comment]
Figured out a workaround, not exaxtly MMS of KServe. This also detaches the 2 models from triton and all 3 can scale independently (best when triton set to deploy only on GPU nodes)
Setting `predictor_host` of `triton` InferenceService for other 2 InferenceServices.

For other's reference:

triton.yaml
```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "triton-mms"
spec:
  predictor:
    triton:
      storageUri: <model repo of models to be loaded on triton>
      imagePullPolicy: IfNotPresent
      args:
      - --allow-sagemaker=false
      runtimeVersion: 21.07-py3
      resources:
        limits:
          cpu: "1"
          memory: "4Gi"
        requests:
          cpu: "1"
          memory: "4Gi"
```

model.yaml
```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: model
spec:
  predictor:
    containers:
      - name: kfserving-container
        image: <custom model image>
        args:
          - --predictor_host=triton-mms-predictor-default.kfserving-test <triton_isvc_name-predictor-default.namespace>
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
```

model1.yaml
```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: model1
spec:
  predictor:
    containers:
      - name: kfserving-container
        image: <2nd custom model image>
        args:
          - --predictor_host=triton-mms-predictor-default.kfserving-test
        resources:
         limits:
          cpu: "500m"
          memory: "1Gi"
         requests:
          cpu: "500m"
          memory: "1Gi"
```

Create triton client:
`triton_client = httpclient.InferenceServerClient(url=predictor_host, verbose=False)`

@yuzisun
