### ISSUE TITLE
Custom TorchServe service does not work

### ISSUE THREAD

**Issue by yurkoff-mv** [kserve/kserve#1810]
I have a yaml-file:
```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "my-service"
spec:
  predictor:
    containers:
    - image: pytorch/torchserve-kfs:0.4.1-gpu
      name: kfserving-container
      env:
          - name: STORAGE_URI
            value: "pvc://my-claim/"
      resources:
        limits:
          cpu: 2
          memory: 16Gi
          nvidia.com/gpu: 1
        requests:
          cpu: 1
          memory: 8Gi
          nvidia.com/gpu: 1
```

I'm trying to run it, but the containers in the pod produces the following:
`!kubectl logs -n default {POD} -c storage-initializer`
```
[I 210922 14:59:02 initializer-entrypoint:13] Initializing, args: src_uri [/mnt/pvc/] dest_path[ [/mnt/models]
[I 210922 14:59:02 storage:45] Copying contents of /mnt/pvc/ to local
[I 210922 14:59:02 storage:223] Linking: /mnt/pvc/model-store_ to /mnt/models/model-store_
[I 210922 14:59:02 storage:223] Linking: /mnt/pvc/config to /mnt/models/config
[I 210922 14:59:02 storage:223] Linking: /mnt/pvc/model-store to /mnt/models/model-store
```

`!kubectl logs -n default {POD} -c kfserving-container`
/usr/local/lib/python3.6/dist-packages/ray/autoscaler/_private/cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  "update your install command.", FutureWarning)
```
[I 210922 14:59:03 __main__:68] Wrapper : Model names ['my-model'], inference address http//0.0.0.0:8085, management address http://0.0.0.0:8081, model store /mnt/models/model-store
[I 210922 14:59:03 TorchserveModel:48] kfmodel Predict URL set to 0.0.0.0:8085
[I 210922 14:59:03 TorchserveModel:50] kfmodel Explain URL set to 0.0.0.0:8085
[I 210922 14:59:03 TSModelRepository:26] TSModelRepo is initialized
[I 210922 14:59:03 kfserver:151] Registering model: my-model
[I 210922 14:59:03 kfserver:121] Setting asyncio max_workers as 6
[I 210922 14:59:03 kfserver:128] Listening on port 8080
[I 210922 14:59:03 kfserver:130] Will fork 1 workers
```

My config-file:
```
inference_address=http://0.0.0.0:8085
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
grpc_inference_port=7070
grpc_management_port=7071
max_request_size=1073741824
max_response_size=1073741824
install_py_dep_per_model=true
NUM_WORKERS=1
number_of_gpu=1
number_of_netty_threads=32
job_queue_size=1000
model_store=/mnt/models/model-store
model_snapshot={"name":"startup.cfg","modelCount":1,"models":{"my-model":{"1.0":{"defaultVersion":true,"marName":"roberta_base.mar","minWorkers":1,"maxWorkers":5,"batchSize":1,"maxBatchDelay":5000,"responseTimeout":5000}}}}
```

I try prediction:
```
PREDICTION = !curl -H "Host: {SERVICE_HOSTNAME}" -H "Cookie: authservice_session={SESSION}" http://{INGRESS_HOST}:{INGRESS_PORT}/predictions/{MODEL_NAME} -d {INPUT_PATH}
```
```
['  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current',
 '                                 Dload  Upload   Total   Spent    Left  Speed',
 '',
 '  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0',
 '100   267  100    69  100   198   7666  22000 --:--:-- --:--:-- --:--:-- 33375',
 '<html><title>404: Not Found</title><body>404: Not Found</body></html>']
```
As a result, the service does not work.
