### ISSUE TITLE
Propose new storage spec to support next-gen multi-model serving

### ISSUE THREAD

**Issue by Tomcli** [kserve/kserve#1814]
/kind feature

**Describe the solution you'd like**
We want to introduce a new storage spec for inference service and trained model, so it can support the next-gen model mesh multi-model serving with different storage provider. The storageUri can continue to work with this new storage spec.
Example:
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: example-sklearn-isvc
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    sklearn:
      # Use either storageUri or storage spec
      # storageUri: s3://modelmesh-example-models/sklearn/mnist-svm.joblib
      storage:
        key: localMinIO
        path: sklearn/mnist-svm.joblib
        # schemaPath: null
        parameters:
          bucket: modelmesh-example-models
```

Proposed new storage spec design doc: https://docs.google.com/document/d/1rYNh93XNMRp8YaR56m-_zK3bqpZhhGKgpVbLPPsi-Ow/edit#
Phase 1 implementation for modelmesh serving controller: https://github.com/kserve/modelmesh-serving/pull/56

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
