### ISSUE TITLE
Support LightGBM with V2 protocol

### ISSUE THREAD

**Issue by adriangonz** [kserve/kserve#1842]
/kind feature

**Describe the solution you'd like**
MLServer supports serving LightGBM models. However, this is not currently exposed in the KServe CRD (at least for the V2 protocol).

Given that the support is already on the MLServer side, it would be good to also support this on the KServe CRD.

**Comment by adriangonz** [comment]
Happy to take this one @yuzisun

**Comment by jonathansp** [comment]
hey @adriangonz @yuzisun any updates on this?

**Comment by adriangonz** [comment]
Hey @jonathansp, I believe that LightGBM is now supported under the new set of `ServingRuntimes`. The name of the runtime should be `kserve-lgbserver`.

You can find some example manifests here:

https://kserve.github.io/website/master/modelserving/servingruntimes/

@Suresh-Nakkeran and @yuzisun know more about this one though, so perhaps it would be worth waiting for them to confirm that the above is correct.

**Comment by Suresh-Nakkeran** [comment]
@jonathansp LightGBM V2 support is added in `kserve-mlserver` runtime and does not require it in inferenceservice request. Below is a sample.

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "lightgbm-v2-isvc"
spec:
  predictor:
    model:
      modelFormat:
        name: lightgbm
      protocolVersion: v2
      storageUri: "<MODEL_STORAGE_URI>"
```
