### ISSUE TITLE
Inputs to use private docker registry.

### ISSUE THREAD

**Issue by BakingBrains** [kserve/kserve#1846]
I followed the procedure given  here [https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line](url). I am able to create the secret key. But after deploying .yaml file, the inference service status is False.

All the other dependencies in a cluster is satisfied and also tested for public repo, it was working fine.

Looking for some inputs to use private docker registry , the kfserving is installed with kubeflow . Inside a cluster I created a separate namespace and the secret key is generated inside that namespace. The .yaml file is deployed inside that namespace as well.

Below is the .yaml file

```
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: <name>
spec:
  default:
    predictor:
      custom:
        container:
          image: https://index.docker.io/<docker username>/<private repo name>: <image name>
  imagePullSecrets:
  - name: test-sec
```

And also how to specify the link to dockerhub private repo
