### ISSUE TITLE
Deleting an inference Service occasionally does not delete the knative service

### ISSUE THREAD

**Issue by amybachir** [kserve/kserve#1884]
kfserving version 0.6.0
knative serving version 0.24.0

Occasionally and randomly, I delete an inference service but all the knative components such as the knative service, configuration, revision, route and deployment hang around and do not get deleted.

The inference service was deleted for sure with no problem. I attempted to delete the knative service but it would recreate over and over although the inference service no longer exists.

I haven't been able to identify a pattern. This seems to happen randomly. The only way I was able to get rid of the knative service is by editing the owner references on it and setting `blockOwnerDeletion: false`

**Comment by sivanantha321** [comment]
Closing this issue as it is too old

**Comment by dpnoworyta** [comment]
I would like to reopen this issue: using Kserve `v0.14.1` and `0.15.0` (both in `deploymentMode: "RawDeployment"`) I'm seeing reported behavior every single time when I'm deleting `InferenceService` manifest. 

When removing manifest with InferenceService simple as this:
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: flower-sample
  namespace: kserve
spec:
  predictor:
    tensorflow:
      storageUri: gs://kfserving-examples/models/tensorflow/flowers
```

Other, tied with this Kind items that are not removed:

- Deployment
- Replicaset
- Pods
- HPA
- Service
- Endpoint
