### ISSUE TITLE
ksvc Uninitialized with Waiting for load balancer to be ready error

### ISSUE THREAD

**Issue by amybachir** [kserve/kserve#1900]
/kind bug

**What steps did you take and what happened:**
I deployed the following custom predictor inference service definition:
```
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  annotations:
    autoscaling.knative.dev/maxScale: '5'
    autoscaling.knative.dev/minScale: '1'
  labels:
    app: iris
    app.kubernetes.io/instance: iris-dev
    controller-tools.k8s.io: '1.0'
    env: mlk8s-dev
    sidecar.istio.io/inject: 'false'
    version: 0.0.35
  name: iris
  namespace: dev
spec:
  default:
    predictor:
      custom:
        container:
          env:
            - name: PATH_TO_MODEL
              value: '/mnt/models/iris/models/2021-05-05T18:47:18.359991/'
            - name: STORAGE_URI
              value: 'pvc://dev-pvc'
            - name: MODEL_VERSION
              value: 0.0.35
          image: 'custom-image/iris-kfserving:0.0.35'
          name: kfserving-container
          resources:
            limits:
              cpu: '1'
              memory: 6Gi
            requests:
              cpu: 250m
              memory: 4Gi
```

**What did you expect to happen:**
The inference service to be in `READY` status `True` and routes to be setup correctly.

**Anything else you would like to add:**
I installed kubeflow through [aws argoflow distribution ](https://github.com/argoflow/argoflow-aws).
I noticed there is a missing virtual service:
```
kubectl get vs -n dev | grep iris
iris-predictor-default-ingress                                ["istio-system/cluster-local-gateway","kubeflow/kubeflow-gateway"]   ["iris-predictor-default.dev","iris-predictor-default.dev.serving.domain-name","iris-predictor-default.dev.svc","iris-predictor-default.dev.svc.cluster.local"]                                                                                                                       22m
iris-predictor-default-mesh                                   ["mesh"]                                                             ["iris-predictor-default.dev","iris-predictor-default.dev.svc","iris-predictor-default.dev.svc.cluster.local"]                                                                                                                                                                             22m
```

**Environment:**

- Istio Version: 1.10.2
- Knative Version: v0.24.0
- KFServing Version: v0.6.0
- Kubeflow version: v1.3.0
- Kfdef: N/A
- Minikube version: EKS cluster 
- Kubernetes version: (use `kubectl version`): `kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T10:03:32Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}`
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@amybachir Please check https://github.com/knative/serving/issues/10115, if you can get the `network-istio` pod log in `knative-serving` namespace that would be helpful.

**Comment by amybachir** [comment]
@yuzisun Thanks much for looking into this! I took a look at `knative/serving#10115` and it doesn't seem similar to the issue I'm having. I encountered this issue on new inference services' deployments as well.

I did not see any errors in net-istio log (I attached the log in case you wanted to look at it). However, the controller log has some errors. I cleaned up the controller log from any irrelevant log statements like `INFO` and attached it as well.

[net-istio.log](https://github.com/kserve/kserve/files/7498023/net-istio.log)
[knative-controller.log](https://github.com/kserve/kserve/files/7498024/knative-controller.log)

**Comment by amybachir** [comment]
@yuzisun @karlschriek 's issue [here](https://github.com/knative-sandbox/net-istio/issues/700) sounds a lot like what I'm experiencing. The only difference I have mTLS set to `PERMISSIVE` since I terminate TLS at the AWS load balancer outside the cluster.

There seems to be no pattern of when the ksvc gets a ready status. I have 3/4 of my inference services up and running and some of them just occasionally go into `Uninitialized` with `Waiting for load balancer to be ready` error.

This is my route status:
```
Status:
  Address:
    URL:  http://wiper-malware-event-predictor-default.dev.svc.cluster.local
  Conditions:
    Last Transition Time:  2021-11-08T20:03:29Z
    Status:                True
    Type:                  AllTrafficAssigned
    Last Transition Time:  2021-11-08T20:03:29Z
    Message:               autoTLS is not enabled
    Reason:                TLSNotEnabled
    Status:                True
    Type:                  CertificateProvisioned
    Last Transition Time:  2021-11-08T20:03:29Z
    Message:               Waiting for load balancer to be ready
    Reason:                Uninitialized
    Status:                Unknown
    Type:                  IngressReady
    Last Transition Time:  2021-11-08T20:03:29Z
    Message:               Waiting for load balancer to be ready
    Reason:                Uninitialized
    Status:                Unknown
    Type:                  Ready
  Observed Generation:     1
  Traffic:
    Latest Revision:  true
    Percent:          100
    Revision Name:    wiper-malware-event-predictor-default-00001
  URL:                http://wiper-malware-event-predictor-default.dev.serving.domain-name
Events:
  Type    Reason           Age   From              Message
  ----    ------           ----  ----              -------
  Normal  FinalizerUpdate  38m   route-controller  Updated "wiper-malware-event-predictor-default" finalizers
  Normal  Created          32m   route-controller  Created placeholder service "wiper-malware-event-predictor-default"
  Normal  Created          32m   route-controller  Created Ingress "wiper-malware-event-predictor-default"
```
and this is my ksvc status:
```
Status:
  Address:
    URL:  http://wiper-malware-event-predictor-default.dev.svc.cluster.local
  Conditions:
    Last Transition Time:        2021-11-08T20:03:29Z
    Status:                      True
    Type:                        ConfigurationsReady
    Last Transition Time:        2021-11-08T20:03:29Z
    Message:                     Waiting for load balancer to be ready
    Reason:                      Uninitialized
    Status:                      Unknown
    Type:                        Ready
    Last Transition Time:        2021-11-08T20:03:29Z
    Message:                     Waiting for load balancer to be ready
    Reason:                      Uninitialized
    Status:                      Unknown
    Type:                        RoutesReady
  Latest Created Revision Name:  wiper-malware-event-predictor-default-00001
  Latest Ready Revision Name:    wiper-malware-event-predictor-default-00001
  Observed Generation:           1
  Traffic:
    Latest Revision:  true
    Percent:          100
    Revision Name:    wiper-malware-event-predictor-default-00001
  URL:                http://wiper-malware-event-predictor-default.dev.serving.domain-name
Events:
  Type     Reason         Age                From                Message
  ----     ------         ----               ----                -------
  Warning  InternalError  45m                service-controller  service: "wiper-malware-event-predictor-default" does not own configuration: "wiper-malware-event-predictor-default"
  Normal   Created        45m                service-controller  Created Configuration "wiper-malware-event-predictor-default"
  Warning  InternalError  45m (x2 over 45m)  service-controller  service: "wiper-malware-event-predictor-default" does not own route: "wiper-malware-event-predictor-default"
  Warning  InternalError  45m                service-controller  failed to reconcile Configuration: Operation cannot be fulfilled on configurations.serving.knative.dev "wiper-malware-event-predictor-default": the object has been modified; please apply your changes to the latest version and try again
  Normal   Created        45m                service-controller  Created Route "wiper-malware-event-predictor-default"
```
I see this error often in the knative controller log:
```
{"severity":"WARNING","timestamp":"2021-11-08T07:03:25.861331165Z","logger":"controller","caller":"route/reconcile_resources.go:187","message":"Failed to update k8s service","commit":"c75484e","knative.dev/pod":"controller-7bccdf6fdb-bh99f","knative.dev/controller":"knative.dev.serving.pkg.reconciler.route.Reconciler","knative.dev/kind":"serving.knative.dev.Route","knative.dev/traceid":"39fc5047-7c88-4c9c-bb03-dff807255c15","knative.dev/key":"dev/sl-identifier-ocr-predictor-default","error":"failed to fetch loadbalancer domain/IP from ingress status"}
```
And this error in the activator:
```
{"severity":"ERROR","timestamp":"2021-11-08T20:49:19.70322555Z","logger":"activator","caller":"net/revision_backends.go:357","message":"Failed to probe clusterIP 172.20.247.122:80","commit":"c75484e","knative.dev/controller":"activator","knative.dev/pod":"activator-dfc4f7578-jshcr","knative.dev/key":"integration/data-breach-predictor-default-00001","error":"unexpected body: want \"queue\", got \"no healthy upstream\"","stacktrace":"knative.dev/serving/pkg/activator/net.(*revisionWatcher).checkDests\n\tknative.dev/serving/pkg/activator/net/revision_backends.go:357\nknative.dev/serving/pkg/activator/net.(*revisionWatcher).run\n\tknative.dev/serving/pkg/activator/net/revision_backends.go:402"}
```
but no errors in net-istio log

**Comment by amybachir** [comment]
Knative seems to create 3 virtual service per inference service. The virtual services status shows some proxies are out of date:
```
status:
  conditions:
  - lastProbeTime: "2021-11-08T22:27:52.376791656Z"
    lastTransitionTime: "2021-11-08T22:27:52.376791822Z"
    message: 367/390 proxies up to date.
    status: "False"
    type: Reconciled
  observedGeneration: "1"
```
I found that restarting `istiod` pods consistently always fixes the issue. The proxies get updated and the inference service goes into `Ready = True` status. However, on the next revision deployment, the issue _sometimes_ happens again. I did not notice a pattern in the behavior as some consecutive revisions do not have the issue.

Continuing to troubleshoot and identify the root cause.
