### ISSUE TITLE
setting request auth and auth policies, always return rbac even when valid token is provided

### ISSUE THREAD

**Issue by vaporpin** [kserve/kserve#1903]
/kind bug

Hi, I followed https://kserve.github.io/website/get_started/first_isvc/ and managed to set up an inference service. Next I tried to set up request auth and auth policies to restrict access without valid token (note: in the manifest file, dash was converted to bullet point automatically on this page, not sure of how to stop the conversion):

apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-example"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.6/security/tools/jwt/samples/jwks.json"

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: httpbin
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: DENY
  rules:
  - from:
    - source:
        notRequestPrincipals: ["*"]

I managed to restrict access, RBAC: access denied return. 
However, even when I provide a valid token, I'm still getting RBAC: access denied. 

POST /v1/models/iris/infer HTTP/1.1
Host: iris.test.35.127.145.71.nip.io
User-Agent: curl/7.64.1
Accept: /
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRIRmJwb0lVcXJZOHQyenBBMnFYZkNtcjVWTzVaRXI0UnpIVV8tZW52dlEiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjQ2ODU5ODk3MDAsImZvbyI6ImJhciIsImlhdCI6MTUzMjM4OTcwMCwiaXNzIjoidGVzdGluZ0BzZWN1cmUuaXN0aW8uaW8iLCJzdWIiOiJ0ZXN0aW5nQHNlY3VyZS5pc3Rpby5pbyJ9.CfNnxWP2tcnR9q0vxyxweaF3ovQYHYZl82hAUsn21bwQd9zP7c-LS9qd_vpdLG4Tn1A15NxfCjp5f7QNBUo-KC9PJqYpgGbaXhaGx7bEdFWjcwv3nZzvc7M__ZpaCERdwU7igUmJqYGBYQ51vr2njU9ZimyKkfDe3axcyiBZde7G6dabliUosJvvKOPcKIWPccCgefSj_GNfwIip3-SsFdlR7BtbVUcqR-yv-XOxJ3Uc1MI0tz3uMiiZcyPV7sNCU4KRnemRIMHVOfuvHsU60_GhGbiSFzgPTAa9WTltbnarTbxudb_YEOx12JiwYToeX0DCPb43W1tzIBxgm8NxUg
Content-Length: 178
Content-Type: application/x-www-form-urlencoded

upload completely sent off: 178 out of 178 bytes
< HTTP/1.1 403 Forbidden
< content-length: 19
< content-type: text/plain
< date: Tue, 09 Nov 2021 10:25:51 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 0
<
Connection #0 to host iris.test.35.127.145.71.nip.io left intact
RBAC: access denied* Closing connection 0

Need advice if I can use istio's way of creating auth policies or i need to do something more due to some more routing or gateways generated by KServe. 

Thank you.

**Comment by mdrijwan123** [comment]
Hi @vaporpin any luck in solving above issue.

**Comment by ofey404** [comment]
@vaporpin @mdrijwan123 I encountered the same problem, too.

But I come up with a solution:

- WORKS: select with the specific `InferenceService`.
  - eg: `serving.kserve.io/inferenceservice: sklearn-iris`
- Don't work: select the whole istio gateway.

```yaml
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: inference-service
  namespace: istio-system
spec:
  selector:
    matchLabels:
      serving.kserve.io/inferenceservice: sklearn-iris
      # istio: ingressgateway # use Istio default gateway implementation
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: first-inference-service
  namespace: istio-system
spec:
  selector:
    matchLabels:
      serving.kserve.io/inferenceservice: sklearn-iris
      # istio: ingressgateway # use Istio default gateway implementation
```

The outcome:

```
curl -v -H "Authorization: Bearer $TOKEN" -H "Host: sklearn-iris.default.example.com" -H "Content-Type: application/json" "http://localhost:8080/v1/models/sklearn-iris:predict" -d @./iris-input.json
# {"predictions":[1,1]}
curl -v -H "Authorization: Bearer $TOKEN_DEADBEEF" -H "Host: sklearn-iris.default.example.com" -H "Content-Type: application/json" "http://localhost:8080/v1/models/sklearn-iris:predict" -d @./iris-input.json
# RBAC: access denied
```

Full script to see: https://github.com/ofey404/experiments/blob/a89c81a8deaa9e35d02bdce0e5de1e74156f1734/cloud/kserve/manifests/auth-policy.yaml#L2-L10
