### ISSUE TITLE
Allow setting autoscaling options on components

### ISSUE THREAD

**Issue by markwinter** [kserve/kserve#1911]
/kind feature

Currently knative autoscaling can be applied via `annotations` (except for `containerConcurrency` which is already per component).  This means every component gets the same settings in the underlying ksvc.

Example as follows

```YAML
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "flowers-sample"
  annotations:
    autoscaling.knative.dev/target: "1"
spec:
  predictor:
    tensorflow:
      storageUri: "gs://kfserving-samples/models/tensorflow/flowers"
```

**Describe the solution you'd like**
In the case of having a `Predictor` component and a `Transformer` component, it would be helpful to be able to set the knative scaling options per component. In practice, the `Transformer` needs much different scaling options to the `Predictor`.

Quick example

```YAML
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "flowers-sample"
spec:
  predictor:
    scaleTarget: "1"
    scaleMetric: "rps"
    ...
  transformer:
    scaleTarget: "10"
    scaleMetric: "rps"
    ...
```

I see that the same is already done for `minReplicas` `maxReplicas` which is specified at the component level and then gets set as an annotation on the underlying ksvc
