### ISSUE TITLE
Model status is not ready until first request is received

### ISSUE THREAD

**Issue by markwinter** [kserve/kserve#1915]
/kind bug

**What steps did you take and what happened:**

I am trying to set up a `readinessProbe` like this for a pytorch server

```YAML
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: torchserve
spec:
  predictor:
    pytorch:
      storageUri: "gs://kfserving-examples/models/torchserve/image_classifier"
      readinessProbe:
        httpGet:
          path: /v1/models/<MODEL_NAME>
        initialDelaySeconds: 5
        periodSeconds: 5
```

However the url `/v1/models/<MODEL_NAME>` always returns HTTP 503 (and  raw HTML), until the server processes the first request. This means the `readinessProbe` always fails as we can't send the first request until the server is ready.

Check that the model is loaded
```BASH
$ curl "http://torchserve.markwinter.example.com:32222/v1/models"
["mnist"]
```

Then check the status of the model. It always returns HTTP 503
```BASH
$ curl "http://torchserve.markwinter.example.com:32222/v1/models/mnist"
<html><title>503: Model with name mnist is not ready.</title><body>503: Model with name mnist is not ready.</body></html>

```

As soon as I send the first request, it correctly returns HTTP 200
```BASH
$ curl "http://torchserve.markwinter.example.com:32222/v1/models/mnist"
{"name": "mnist", "ready": true}
```

**What did you expect to happen:**
The path `/v1/models/<model_name>` should return HTTP 200 when the model is ready.

**Environment:**

- Istio Version: 1.9
- Knative Version: 0.23
- KFServing Version: 0.7
