### ISSUE TITLE
Predictor from getting started example stuck fetching dockerhub

### ISSUE THREAD

**Issue by jacobmalmberg** [kserve/kserve#1919]
/kind bug

**What steps did you take and what happened:**
1. Created the InferenceService from https://kserve.github.io/website/get_started/first_isvc/.
2. Changed apiVersion to "serving.kubeflow.org/v1beta1" since we run KubeFlow 1.4 on prem.
YAML:
```yaml
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  namespace: "kserve"
  name: "sklearn-iris"
spec:
  predictor:
    sklearn:
      storageUri: "gs://seldon-models/sklearn/iris"
```
3. The InferenceService does not get ready. Describing it yields
```yaml
Last Transition Time:  2021-11-17T12:55:44Z
Message:               Revision "sklearn-iris-predictor-default-00001" failed with message: Unable to fetch image "kfserving/sklearnserver:v0.6.1": failed to resolve image to digest: Get "https://index.docker.io/v2/": context deadline exceeded.
Reason:                RevisionFailed
Severity:              Info
Status:                False
Type:                  PredictorRouteReady
```

Entire description can be found here https://appp.me/Z29cYd.

This happens regardless of which image I choose. I always have to supply the digest myself for it to work.

**What did you expect to happen:**

For it to become ready / work.

**Anything else you would like to add:**
Selected part from inferenceservice-config configmap in the kubeflow namespace is below. Entire confimap can be found here https://appp.me/8idlMK. 

```yaml
  predictors: |-
    {
    
      "sklearn": {
        "v1": {
          "image": "kfserving/sklearnserver",
          "defaultImageVersion": "v0.6.1",
          "supportedFrameworks": [
            "sklearn"
          ],
          "multiModelServer": true
        },
        "v2": {
          "image": "docker.io/seldonio/mlserver",
          "defaultImageVersion": "0.2.1",
          "supportedFrameworks": [
            "sklearn"
          ],
          "multiModelServer": false
        }
      },
  }
```
**Environment:**

- Istio Version:1.9.6
- Knative Version: 0.22.1
- KFServing Version: 0.6.1
- Kubeflow version:1.4
- Kfdef:[k8s_istio/istio_dex/]
- Kubernetes version: (use `kubectl version`): v1.21.5
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3
