### ISSUE TITLE
Using MMS with a custom predictor doesn't respect containerPort

### ISSUE THREAD

**Issue by varunsh-xilinx** [kserve/kserve#1920]
/kind bug

**What steps did you take and what happened:**

```
apiVersion: "serving.kserve.io/v1beta1"
kind: InferenceService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    app: custom-predictor
  name: custom-predictor
spec:
  predictor:
    containers:
      - name: custom
        image: someRegistry/someImage
        env:
          - name: MULTI_MODEL_SERVER
            value: "true"
        ports:
          - containerPort: 8998
            protocol: TCP
```

If we enable MMS on the custom predictor, the agent sidecar attempts to connect to 8080 instead of the containerPort specified.

```
$ kubectl logs <pod> agent
aggressive probe error:  dial tcp 127.0.0.1:8080: connect: connection refused
aggressive probe error:  dial tcp 127.0.0.1:8080: connect: connection refused
aggressive probe error:  dial tcp 127.0.0.1:8080: connect: connection refused
```

**What did you expect to happen:**
It should use the containerPort instead of 8080.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This issue looks similar to #1536. Similarly, forcing the predictor to listen on 8080 is a workaround.

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: 0.7
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
