### ISSUE TITLE
InferenceService Status restructuring

### ISSUE THREAD

**Issue by pvaneck** [kserve/kserve#2042]
Currently, ModelMesh has its own set of status fields that it populates in the InferenceService status since we [allow unknown fields](https://github.com/kserve/kserve/pull/1855/files) there. Similarly, KServe has its own status fields that are predominantly based on knative fields. 

The goal here is to converge on a common set of status fields that would work with the various different deployment modes.

As an overview, here are the current status fields:

### [InferenceServiceStatus](https://github.com/kserve/kserve/blob/7347e2fa644f2fed842759644fa5a995ca42a756/pkg/apis/serving/v1beta1/inference_service_status.go#L28)
```
InferenceServiceStatus
  ├──── duckv1.Status `json:",inline"`
  │        │    // The 'Generation' of the Service that was last processed by the controller.
  │        ├─── ObservedGeneration int64 `json:"observedGeneration,omitempty"`
  │        │
  │        │    // Conditions the latest available observations of a resource's current state.
  │        |    // Condition defines a readiness condition for a Knative resource.
  │        ├─── Conditions Conditions `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`
  │        | 
  │        |     // Additional Status fields for the Resource to save some additional State as well as convey more information to the user.
  │        ├─── Annotations map[string]string `json:"annotations,omitempty"`
  │
  ├──── Address *duckv1.Addressable `json:"address,omitempty"`
  ├──── URL *apis.URL `json:"url,omitempty"`
  ├──── Components map[ComponentType]ComponentStatusSpec `json:"components,omitempty"`
```
`ComponentTypes` are `predictor`, `explainer`, `transformer`. Which map to a [ComponentStatusSpec](https://github.com/kserve/kserve/blob/7347e2fa644f2fed842759644fa5a995ca42a756/pkg/apis/serving/v1beta1/inference_service_status.go#L48).

An example of an actual status can be found here: https://pastebin.com/wkCrZyxk

### [ModelMesh Predictor Status](https://github.com/kserve/modelmesh-serving/blob/5f0e5bbf900d18bf11dd90cc971c1eb7a319c61a/apis/serving/common/common_types.go#L113)

```
PredictorStatus
  ├──── Available bool `json:"available"`
  │
  │     // One of 'UpToDate', 'InProgress', 'BlockedByFailedLoad', or 'InvalidSpec'
  ├──── TransitionStatus TransitionStatus `json:"transitionStatus"
  │
  │     // High level state string: Pending, Standby, Loading, Loaded, FailedToLoad
  ├──── ActiveModelState ModelState `json:"activeModelState"
  ├──── TargetModelState ModelState `json:"targetModelState"`
  │
  │     // Details of last failure, when load of target model is failed or blocked
  ├──── LastFailureInfo *FailureInfo `json:"lastFailureInfo,omitempty"`
  │
  │     // Addressable endpoint for the deployed trained model. This will be "static" and will not change when the model is mutated
  ├──── HTTPEndpoint string `json:"httpEndpoint"`
  ├──── GrpcEndpoint string `json:"grpcEndpoint"`
  │
  │     // How many copies of this predictor's models failed to load recently
  ├──── FailedCopies int `json:"failedCopies"`
```
An example of an actual predictor status can be found here:  https://pastebin.com/wBM3WgFW

___

**Action item**: Decide how we can restructure the fields in a way that make sense for all the deployment modes. Do we still rely on the Knative types?

**Comment by pvaneck** [comment]
FYI @yuzisun , @njhill , @chinhuang007

**Comment by chinhuang007** [comment]
For both KServe and ModelMesh to update and understand the status/state of an inference service, I would suggest to continue to use the Knative types. That probably means that InferenceServiceStatus needs to cover ModelMesh status requirements, and ModelMesh needs to include Knative packages and change code accordingly.

**Comment by yuzisun** [comment]
My proposal is to collapse the model related fields from ModelMesh's `PredictorStatus` into a new struct `ModelStatus` on InferenceService status. On InferenceService there isn't any status field about the model, when storage initializer fails to download or model server fails to load the model, we just say that service is not ready which could be due to many other reasons, so I think it is good to start to populate the model status fields for single model serving case.  

`HTTPEndpoint` and `gRPCEndpoint` can be merged onto the Predictor's `ComponentStatusSpec` url fields, `available` I think it is basically the predictor ready condition, WDYT?

```
ModelStatus
  │     // One of 'UpToDate', 'InProgress', 'BlockedByFailedLoad', or 'InvalidSpec'
  ├──── TransitionStatus TransitionStatus `json:"transitionStatus"
  │
  │     // High level state string: Pending, Standby, Loading, Loaded, FailedToLoad
  ├──── ActiveModelState ModelState `json:"activeModelState"
  ├──── TargetModelState ModelState `json:"targetModelState"`
  │
  │     // Details of last failure, when load of target model is failed or blocked
  ├──── LastFailureInfo *FailureInfo `json:"lastFailureInfo,omitempty"`
  │
  │     // How many copies of this predictor's models failed to load recently
  ├──── FailedCopies int `json:"failedCopies"`

Components map[ComponentType]ComponentStatusSpec `json:"components,omitempty"`
duckv1.Status `json:",inline"`
URL *apis.URL `json:"url,omitempty"`
```

**Comment by pvaneck** [comment]
I think that's seems pretty tenable. So it looks like we maintain the use of `Conditions` where ModelMesh will populate the necessary Predictor types (i.e. `PredictorRouteReady`, etc.) ?

Also, do we omit the Address field that was in the original Status?

**Comment by chinhuang007** [comment]
Feels like ModelStatus is additional to, not a replacement of, ComponentStatusSpec. So that seems to suggest the predictor component and its status should be populated and maintained regardless it is single model or ModelMesh. Please help clarify if my thinking is incorrect.

**Comment by yuzisun** [comment]
> Feels like ModelStatus is additional to, not a replacement of, ComponentStatusSpec. So that seems to suggest the predictor component and its status should be populated and maintained regardless it is single model or ModelMesh. Please help clarify if my thinking is incorrect.

ye we can add the `ModelStatus` in addition to the component status, we don't need to populate every single field on component status and most of the fields are optional, ModelMesh can set the `PredictorReady` condition and the url related fields.

**Comment by pvaneck** [comment]
Thinking more, does it make sense to have `ModelStatus` contents be a part of the predictor ComponentSpec instead of being top level since these are fields related to the Predictor?

I know currently a lot of the fields in the ComponentSpec are Knative specific with things like `Revisions` and `TrafficTarget`, but we could potentially mesh the two sets of status fields. ModelMesh does kinda have the concept of revisions with internal modelIds that change if a user does an update. So these could potentially be mapped to some of the revision fields.

In any case, we could just not populate some of the fields that might not be useful for ModelMesh-deployed predictors and the `omitempty` in the struct tags would ensure these aren't shown to the user.

Example Modelmesh-deployed InferenceService status:

```yaml
Components:
    Predictor:
      Latest Created Revision:    sample-mnist__isvc-b52e1c8a05
      Latest Ready Revision:      sample-mnist__isvc-b52e1c8a05
      Latest Rolledout Revision:  sample-mnist__isvc-b52e1c8a05

      Transition Status:  UpToDate
      Active Model State: Loaded
      Failed Copies: 0

      HTTP URL: http://modelmesh-serving.modelmesh-serving:8008
      Grpc URL: grpc://modelmesh-serving.modelmesh-serving:8033
    Transformer:
      Address:
        URL:                      http://sample-mnist-transformer-default.modelmesh-serving.svc.cluster.local
    ...
Conditions:
  Predictor:
    Type:                  PredictorReady
    Last Transition Time:  2022-02-22T04:46:34Z
    Severity:              Info
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-02-22T04:47:08Z
    Severity:              Info
    Status:                True
    ...
```

`LastFailureInfo` for ModelMesh can also be put in Conditions similar to how single-model serving errors are propagated to the user through something like the `PredictorReady` condition type.

Throwing this out there as an option.
