### ISSUE TITLE
Can a custom init container be used when deploying isvc？

### ISSUE THREAD

**Issue by SeibertronSS** [kserve/kserve#2057]
When I deployed isvc, I found that the model files are checked in the init container. Since my model files are in private cloud storage, I need to modify the image of the init container to pass the check. The yaml file I use is as follows,
```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: pytorch-cifar
spec:
  predictor:
    initContainers:
    - name: myinitcontainer
      image: is.default.svc.xxx.xxx.xx.local/kfserving/initcontainer:v0.1
    pytorch:
      storageUri: s3://xxx/xxx
      modelClassName: Net
      image: is.default.svc.xxx.xxx.xx.local/kfserving/pytorchserver:v0.5.1
      imagePullPolicy: IfNotPresent
```
But when I deploy, k8s prompts me that there is no `initContainers` in `serving.kubeflow.org/v1beta1`
