### ISSUE TITLE
StatusCode.UNIMPLEMENTED when calling torchserve grpc using port-forward

### ISSUE THREAD

**Issue by ittus** [kserve/kserve#2120]
/kind bug

**What steps did you take and what happened:**
1. Deployed [torchserve v1 grpc example](https://github.com/kserve/kserve/blob/master/docs/samples/v1beta1/torchserve/v1/grpc.yaml) on EKS
2. Run port-forward
```bash
kubectl port-forward torchserve-grpc-predictor-default-00001-deployment-78c8557sl8xm 8080:7070
```
3. Changing code of [torchserve_grpc_client.py](https://github.com/kserve/kserve/blob/master/docs/samples/v1beta1/torchserve/v1/torchserve_grpc_client.py)
```bash
def get_inference_stub():
    channel = grpc.insecure_channel(
        'localhost:8080',))
    stub = inference_pb2_grpc.InferenceAPIsServiceStub(channel)
    return stub
```
4. Run inference successfully
```
python torchserve_grpc_client.py infer mnist imgconv/1.png
```
5. Stop port-forward above
6. Start port-forward on istio-ingressgateway
```
kubectl port-forward svc/istio-ingressgateway 8080:80
```
7. Changing inference code
```
  channel = grpc.insecure_channel(
        'localhost:8080',
        options=(('grpc.ssl_target_name_override',
                  'torchserve-grpc.default.svc.cluster.local'),))
    stub = inference_pb2_grpc.InferenceAPIsServiceStub(channel)
    return stub
```
8. Run inference, but this time it FAILED with `StatusCode.UNIMPLEMENTED`
```bash
$ python torchserve_grpc_client.py infer mnist imgconv/1.png

 File ".../Code/kserve/docs/samples/v1beta1/torchserve/v1/venv/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = ""
	debug_error_string = "{"created":"@1648515486.852262000","description":"Error received from peer ipv6:[::1]:8080","file":"src/core/lib/surface/call.cc","file_line":906,"grpc_message":"","grpc_status":12}"
```

**What did you expect to happen:**
can call grpc service successfully

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Gateway
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  generation: 3
  labels:
    app.kubernetes.io/instance: istio-system
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
    - hosts:
        - "*"
      port:
        name: http
        number: 80
        protocol: HTTP
    # - hosts:
    #     - "*"
    #   port:
    #     name: grpc
    #     number: 81
    #     protocol: GRPC
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  generation: 1
  labels:
    app.kubernetes.io/instance: knative
    networking.knative.dev/ingress-provider: istio
    serving.knative.dev/release: v0.22.1
  name: knative-local-gateway
  namespace: knative-serving
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "*"
      port:
        name: http
        number: 8081
        protocol: HTTP
    - hosts:
        - "*"
      port:
        name: grpc
        number: 8080
        protocol: GRPC
```
**Environment:**

- Istio Version: 
- Knative Version: v0.22.1
- KFServing Version: 0.6.1
- Kubeflow version: 1.4
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.20
