### ISSUE TITLE
Canary route leakage during consecutive canary operations

### ISSUE THREAD

**Issue by Peilun-Li** [kserve/kserve#2130]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

1. Create service
```
cat <<EOF | kubectl apply -f -
apiVersion: serving.kubeflow.org/v1beta1
kind: "InferenceService"
metadata:
  name: "my-model"
spec:
  predictor:
    tensorflow:
      storageUri: "gs://kfserving-samples/models/tensorflow/flowers"
EOF
```
```
$ kubectl get isvc my-model -o jsonpath='{.status.components.predictor.traffic}'
[{"latestRevision":true,"percent":100,"revisionName":"my-model-predictor-default-00002"}]
```

2. Canary rollout
```
cat <<EOF | kubectl apply -f -
apiVersion: serving.kubeflow.org/v1beta1
kind: "InferenceService"
metadata:
  name: "my-model"
spec:
  predictor:
    canaryTrafficPercent: 20
    tensorflow:
      storageUri: "gs://kfserving-samples/models/tensorflow/flowers-2"
EOF
```
```
$ kubectl get isvc my-model -o jsonpath='{.status.components.predictor.traffic}'
[{"latestRevision":true,"percent":20,"revisionName":"my-model-predictor-default-00003"},
{"latestRevision":false,"percent":80,"revisionName":"my-model-predictor-default-00002","tag":"prev"}]
```
3. Canary rollback
```
cat <<EOF | kubectl apply -f -
apiVersion: serving.kubeflow.org/v1beta1
kind: "InferenceService"
metadata:
  name: "my-model"
spec:
  predictor:
    canaryTrafficPercent: 0
    tensorflow:
      storageUri: "gs://kfserving-samples/models/tensorflow/flowers-2"
EOF
```
```
$ kubectl get isvc my-model -o jsonpath='{.status.components.predictor.traffic}'
[{"latestRevision":true,"percent":0,"revisionName":"my-model-predictor-default-00003"},
{"latestRevision":false,"percent":100,"revisionName":"my-model-predictor-default-00002","tag":"prev"}]
```

4. Apply another canary (I'm using a dummy example here but imagine this could apply for any new canary test)
```
cat <<EOF | kubectl apply -f -
apiVersion: serving.kubeflow.org/v1beta1
kind: "InferenceService"
metadata:
  name: "my-model"
spec:
  predictor:
    canaryTrafficPercent: 30
    tensorflow:
      env:
      - name: dummy_env
        value: dummy_value
      storageUri: "gs://kfserving-samples/models/tensorflow/flowers-2"
``` 

```
$ kubectl get isvc my-model -o jsonpath='{.status.components.predictor.traffic}'
[{"latestRevision":true,"percent":30,"revisionName":"my-model-predictor-default-00004"},
{"latestRevision":false,"percent":70,"revisionName":"my-model-predictor-default-00003","tag":"prev"}]
```

As can be seen ideally in step 4 after rollout, we are expecting primary (prev) to be revision 00002 and canary to be revision 00004, however the primary switches to 00003 -- a canary revision is leaked out as primary.

**What did you expect to happen:**
Revision 00003 should not be leaked out as primary in step 4 above.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

1. Is this the expected way we should be using canary? Or as a customer should we enforce that no further canary is allowed if `canaryTrafficPercent` is already set (even it is set to 0)?
2. Does this happen to be fixed in a later kserve version?

**Environment:**

- Istio Version:
- Knative Version: 0.22.1
- KFServing Version: 0.5.1
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
