### ISSUE TITLE
Kserve Triton inference Server unable to read from PureStorage S3 for multi model serving

### ISSUE THREAD

**Issue by suryaiyer** [kserve/kserve#2151]
/kind bug

**What steps did you take and what happened:**

I am trying to deploy a multi model triton inference server which loads the models from s3. I have followed the [documentation](https://kserve.github.io/website/modelserving/storage/s3/s3/). The CRDs are 

Inference Server 

```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: multimodel-triton-serving-v1
spec:
  predictor:
    serviceAccountName: multimodel-sa
    triton:
      args:
      - --log-verbose=1     
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: "1"
          memory: 8Gi
```

Trained Model

```
apiVersion: "serving.kubeflow.org/v1alpha1"
kind: "TrainedModel"
metadata:
  name: "sentiment-triton"
spec:
  inferenceService: multimodel-triton-serving-v1
  model:
    framework: tensorflow
    storageUri: s3://.....
    memory: 5Gi

```

When the services are up the isvc fails to load the model. The logs are 
```
Failed to download model sentiment-triton with err failed to download model: failed to download model: unable to get batch objects MissingRegion: could not find region configuration","stacktrace":"github.com/kubeflow/kfserving/pkg/agent.(*Puller).modelProcessor\n\t/go/src/github.com/kubeflow/kfserving/pkg/agent/puller.go:149"
Is there anything I am missing? I am trying to follow https://kserve.github.io/website/modelserving/storage/s3/s3/
```

**What did you expect to happen:**

Expected the isvc to load the model from s3. The service account has the necessary secrets

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

A standalone model (Inference Service with the s3 path) works fine. It uses the storage initializer to fetch the models. 

I see that the multi model inference server uses a service agent to fetch the models. Is there a way to configure/test the agent standalone?

**Environment:**
- Istio Version: 1.9.6
- Knative Version: v0.22.1
- KFServing Version: 0.6.1
- Kubeflow version: 1.4.0
- Kubernetes version: (use `kubectl version`): v1.19.15
- OS (e.g. from `/etc/os-release`): Red Hat Enterprise Linux 8.5

**Comment by suryaiyer** [comment]
The agent pod looks something like : I don't see the endpoint or the region getting pulled from the sa

```
    - name: ENABLE_PROFILING
      value: "false"
    - name: SERVING_ENABLE_PROBE_REQUEST_LOG
      value: "false"
    - name: METRICS_COLLECTOR_ADDRESS
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: AWS_ACCESS_KEY_ID
          name: multimodel-s3-secret
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: AWS_SECRET_ACCESS_KEY
          name: multimodel-s3-secret
    image: kfserving/agent:v0.6.1
    imagePullPolicy: IfNotPresent
    name: agent
    readinessProbe:
      exec:
        command:
        - /ko-app/agent
        - --probe-period
        - "0"
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
```
