### ISSUE TITLE
Proxy istio-ingressgateway with ingress

### ISSUE THREAD

**Issue by SeibertronSS** [kserve/kserve#2182]
I want to proxy istio-ingressgateway with ingress so I can access isvc using domain name instead of istio-ingressgateway svc ip. Access is in the form of
```
requests.post(url="http://easy-test01.xy.com/v1/models/tabular:predict", json=data, headers={"Host": "tabular.default.example.com"})
```

The ingress yaml is
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: istio-ingressgateway-ingress
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
  - host: istio.com
  - http:
      paths:
      - path: /v1
        backend:
          serviceName: istio-ingressgateway
          servicePort: 80
```

But I get a 503 status code.
Can I access isvc through a domain name through ingress proxy istio?
