### ISSUE TITLE
logger is not working with grpc request.

### ISSUE THREAD

**Issue by JuHyung-Son** [kserve/kserve#2251]
/kind bug

I`m following payload logger example with custom preditor using grpc.

when I add logger, grpc request returns error

isvc yaml (when i remove logger, it works well and I`m using triton on custom predictor for testing)

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: torchscript-cifar10
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8002'
spec:
  predictor:
    serviceAccountName: sa
    logger:
      mode: all
      url: http://message-dumper.default/
    containers:
      - name: triton
        image: nvcr.io/nvidia/tritonserver:20.10-py3
        command:
          - tritonserver
        args:
          - --model-repository=/mnt/models
          - --http-port=8088
          - --grpc-port=9000
        ports:
          - containerPort: 9000
            name: h2c
            protocol: TCP
        env:
          - name: STORAGE_URI
            value: 
        resources:
          limits:
            memory: 10Gi
            nvidia.com/gpu: 1
```

grpc request
```
python client.py
<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "{"created":"@1655347294.370618675","description":"Error received from peer ipv4:172.16.200.4:30791","file":"src/core/lib/surface/call.cc","file_line":1070,"grpc_message":"Stream removed","grpc_status":2}"
>
Traceback (most recent call last):
  File "client.py", line 48, in <module>
    response = grpc_stub.ServerReady(request)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "{"created":"@1655347294.373034711","description":"Error received from peer ipv4:172.16.200.4:30791","file":"src/core/lib/surface/call.cc","file_line":1070,"grpc_message":"Stream removed","grpc_status":2}"
```

**Environment:**

- Istio Version: 1.11.5
- Knative Version: 1.3
- Kubeflow version: 0.8.0
- Kubernetes version: (use `kubectl version`): 1.21
- OS (e.g. from `/etc/os-release`): ubuntu 20.04
