### ISSUE TITLE
Is path-based serving supported?

### ISSUE THREAD

**Issue by kandrio** [kserve/kserve#2257]
/kind feature

Hello everyone!

I see that the current way to serve `KServe` models is host-based. That is, the URL of a model looks something like this:
- `http://<model-name>-<namespace>.<domain>`.

This way, one needs to create a DNS record and a certificate for the sub-domain `<model-name>-<namespace>` where the model is hosted.

So, my question is: _is there an alternative way? A **path-based way**?_.

In that case, one should not bother about DNS records and certificates. The URL of the model could look something like this:
- `http://<domain>/<namespace>/<model-name>`

I couldn't find any issues with a similar question. Is something like this currently supported?

If not, then what are the difficulties of such a feature?

**Comment by padrian2s** [comment]
in standalone mode (serverless), the routes are coming from knative,  

https://knative.dev/docs/serving/services/private-services/

yes, the wildcard root-based certificates are not easy to get.

**Comment by yuzisun** [comment]
@kandrio There is no difficulties and I created [the issue](https://github.com/kserve/kserve/issues/824) 2 years ago but did not find person signing for this contribution.

**Comment by kandrio** [comment]
@yuzisun Thanks for pointing me to the issue. It was really helpful and it got me in sync with the proposal.

I believe that supporting path-based serving would be a great feature for KServe. And I'm interested in taking up the implementation.

Let me expose an initial draft that I have in mind.

## Design

At the end of the day, the model should be exposed under a URL that looks like this:
- `status.url`: `<Scheme>://<IngressDomain>/<Namespace>/<Name>`

Here's a list of steps that I think would make sense for  supporting path-based serving:
1. Extend the `inferenceservice-config` `ConfigMap` with a `urlTemplate` field.
    * This field essentially will be a template for the `inferenceservice.status.url` field.
    * It will allow the user to enable path-based serving by setting: `"urlTemplate": "{{ .Scheme }}://{{ .IngressDomain }}/{{ .Namespace }}/{{ .Name }}"`
    * This will have default value: `""`. In that case, the KServe controller works as before.
2. Extend the KServe controller to add an extra rule in the top-level `VirtualService` that it creates for each model.
    * The KServe Controller will add the extra rule in the case that the `"urlTemplate"` is path-based.
    * This extra rule will route all requests that reach the public `Gateway`, with a `/<namespace>/<model-name>` prefix (path-based requests), to the local `Gateway`.
    * It will also overwrite their `Host` header to: `<model-name>-<component>-default.<namespace>.svc.cluster.local` in order for the local `Gateway` to route it to the correct `Service`.
    * This is how this rule will look like:

    ```yaml    
    - headers:
        request:
          set:
            Host: <model-name>-<component>-default.<namespace>.svc.cluster.local
      match:
      - authority:
          regex: <host-template>
        gateways:
        - <public-gateway>
        uri:
          prefix: /<namespace>/<model-name>/
      - authority:
          regex: <host-template>
        gateways:
        - <public-gateway>
        uri:
          exact: /<namespace>/<model-name>
      rewrite:
        uri: /
      route:
      - destination:
          host: <local-gateway-service>
          port:
            number: 80
        weight: 100
    ```
    * _**NOTE**_: The KServe Controller will look at the `ingressDomain` field of `ConfigMap` `inferenceservice-config` in order to construct the `match.authority.regex` field of the `VirtualService`.
3. Extend the KServe controller to expose a path-based URL (instead of the host-based one) in the `status.URL` field of the `InferenceService`.
    * The KServe controller will generate the `isvc.status.url` field based on the value of `urlTemplate`.
    * If `"urlTemplate": ""`, then the controller falls back to its default behavior and it will generate the `isvc.status.url` as it does currently.

**Comment by yuzisun** [comment]
@kandrio Thanks for proposal! Overall it looks great, a few details might need to pay attention:

* There are two different names: `InferenceService name` and `model name`, sometimes they can be different as a service can host multiple models, so we need to encode both service name and model name in the url path.
* There are two inference protocols kserve currently supports: `v1 `and `v2`, the endpoint paths are slightly different between the two, for example the predict path for v1 is `v1/models/<model-name>:predict` while for v2 it is `v2/models/<model-name>/infer`. The switch for v1 or v2 can be based on the `protocolVersion` field on `InferenceService` spec.

The virtual service template might look like following:
```
- headers:
    request:
      set:
        Host: <service-name>-<component>-default.<namespace>.svc.cluster.local
  match:
  - authority:
      regex: <host-template>
    gateways:
    - <public-gateway>
    uri:
      prefix: /<namespace>/<service-name>/<protocol-version>/models/<model-name>
  rewrite:
    uri: /<protocol-version>/models/<model-name>
  route:
  - destination:
      host: <local-gateway-service>
      port:
        number: 80
    weight: 100
```

**Comment by kandrio** [comment]
@yuzisun thanks for the reply! I have a few follow-up questions regarding your comment:

1. Regarding the first bullet, I see:
    * > a service can host multiple models
    * I actually am not in sync with this. I haven't found any piece of documentation on how to create an `InferenceService` that contains more than one models (e.g: `predictors`). Could you point me to any docs that show how this feature works?
2. Regarding the `VirtualService` template, I see that:
    * you propose to match the `prefix`: `/<namespace>/<service-name>/<protocol-version>/models/<model-name>`
    * But this won't match requests with prefix: `/<namespace>/<service-name>/v2/health/live` or just `/<namespace>/<service-name>/` for example. These requests check the liveliness of the `InferenceService`
    * Here's the list of all the possible paths we want to match: https://github.com/kserve/kserve/blob/343bae6e501e4c6a68f624c9715bde6bd2774796/python/kserve/kserve/model_server.py#L69-L95

I assume you are talking about exposing each model in a separate path-based URL, especially given you first comment about multi-model serving. Again, I may be missing something here, so feel free to clarify anything.

In my proposal, I am talking about exposing **the entire `InferenceService`**, regardless of the models that it contains. So, I assume that this would be a good first iteration anyway, since it would factor in all the models served by the `InferenceService`.

What do you think?

**Comment by kandrio** [comment]
Hello again!

@yuzisun @zijianjoy any ideas on my last comment?

**Comment by kandrio** [comment]
Hello everyone!

I created a pull-request for this. Let's continue the discussion there:
- https://github.com/kserve/kserve/pull/2357

**Comment by yuzisun** [comment]
> @yuzisun thanks for the reply! I have a few follow-up questions regarding your comment:
> 
> 1. Regarding the first bullet, I see:
>    
>    * > a service can host multiple models
>    * I actually am not in sync with this. I haven't found any piece of documentation on how to create an `InferenceService` that contains more than one models (e.g: `predictors`). Could you point me to any docs that show how this feature works?

All KServe serving runtimes support loading multiple models from a model repository specified by `storageUri`, the yaml isn't different and you can call the model by specifying `$modelName` on the the url path. 

> 2. Regarding the `VirtualService` template, I see that:
>    
>    * you propose to match the `prefix`: `/<namespace>/<service-name>/<protocol-version>/models/<model-name>`
>    * But this won't match requests with prefix: `/<namespace>/<service-name>/v2/health/live` or just `/<namespace>/<service-name>/` for example. These requests check the liveliness of the `InferenceService`
>    * Here's the list of all the possible paths we want to match: https://github.com/kserve/kserve/blob/343bae6e501e4c6a68f624c9715bde6bd2774796/python/kserve/kserve/model_server.py#L69-L95

You can actually only match the prefix `/<namespace>/<service-name>` part and strip it when rewriting the url. The original URI was matched based on prefix `/<namespace>/<service-name>`, the rewrite will replace the corresponding matched prefix with empty string and forward the remaining inference protocol url path. 

> I assume you are talking about exposing each model in a separate path-based URL, especially given you first comment about multi-model serving. Again, I may be missing something here, so feel free to clarify anything.
> 
> In my proposal, I am talking about exposing **the entire `InferenceService`**, regardless of the models that it contains. So, I assume that this would be a good first iteration anyway, since it would factor in all the models served by the `InferenceService`.
> 
> What do you think?

**Comment by lizzzcai** [comment]
Hi @kandrio , thanks for the proposal, that is a feature we needed for a while. You can find our use cases and requirement [here](https://github.com/knative/serving/issues/11997#issuecomment-953131641).

Currently, we are using an additional virtual service to route the path-based request to the `cluster-local-gateway`. See the example below. It will be great that KServe can support it natively.
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service1-path-based-endpoint
  namespace: user1-ns1
spec:
  gateways:
  - istio-system/ingress-gateway
  hosts:
  - api.example.com
  http:
  - name: "service1-path-based-routes"
    match:
    - uri:
        prefix: "/user1-ns1/service1/"
      ignoreUriCase: true
    rewrite:
      uri: "/"
    route:
    - destination:
        host: local-gateway.istio-system.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Host: service1.user1-ns1.svc.cluster.local
      weight: 100
```

Instead of `urlTemplate`, maybe having an additional `pathTemplate` to work with the existing `domainTemplate` to define the path will be better?

```
domainTemplate: {{` "{{.Name}}-{{.Namespace}}.{{.Domain}}" `}}
pathTemplate: {{` "{{.Namespace}}/{{.Name}}" `}} # user need to avoid conflict of the path by themselves.
```
Above will generate an inferenceService URL with the following format:
```
"{{.Name}}-{{.Namespace}}.{{.Domain}}/{{.Namespace}}/{{.Name}}"
# example: svc1-ns-1.example.com/ns1/svc1
```
If the pathTemplate is empty, then it will be host-based routing.

What do you think?
