### ISSUE TITLE
HPA in rawDeployment error: close new pod after created 

### ISSUE THREAD

**Issue by gawsoftpl** [kserve/kserve#2269]
When run benchmark for my model during increase loads. Hpa cant create new pods.

1. Cpu utilization increase over 80%
2. HPA create new pod 
3. After 10 seconds pod is closed
4. And is still only one pod

I see in logs that when HPA create new pod: 
1. create container storage-initializer, 
2. imediatelly kill storage-initializer container.
I have models in private s3 bucket, maybe hpa when create new pod not assign secrets or else.

```sh
kubectl get hpa
```
```txt
ml-ensemble            Deployment/ml-ensemble-predictor-default             187%/60%   1         6         1          28m
```

@Iamlovingit 

```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "ml-ensemble"
  annotations:
    #serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/autoscalerClass: hpa
    serving.kserve.io/metric: cpu
    serving.kserve.io/targetUtilizationPercentage: "80"
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 10
    timeout: 10
    batcher:
      maxBatchSize: 16
      maxLatency: 50
    model:
      modelFormat:
        name: custom-ensemble
      runtime: custom-mlserver
      storageUri: "s3://ml-models-files/"
      env:
        - name: OMP_NUM_THREADS
          value: "1"
        - name: MLSERVER_PARALLEL_WORKERS
          value: "1"
      ports:
       - containerPort: 8080
         name: rest
         protocol: TCP
       - containerPort: 9000
         name: grpc
         protocol: TCP
```
Logs from kserve-controller-manager
```txt
{"level":"info","ts":1655916682.2173252,"logger":"DeploymentReconciler","msg":"deployment reconcile","checkResult":2,"err":null}
{"level":"info","ts":1655916682.2173607,"logger":"ServiceReconciler","msg":"service reconcile","checkResult":2,"err":null}
{"level":"info","ts":1655916682.2173955,"logger":"HPAReconciler","msg":"service reconcile","checkResult":2,"err":null}
{"level":"info","ts":1655916682.2292483,"logger":"v1beta1Controllers.InferenceService","msg":"Inference service deployment mode ","deployment mode ":"RawDeployment"}
{"level":"info","ts":1655916682.2292736,"logger":"v1beta1Controllers.InferenceService","msg":"Reconciling inference service","apiVersion":"serving.kserve.io/v1beta1","isvc":"ml-cookies-words-vectors"}
{"level":"info","ts":1655916682.2296598,"logger":"PredictorReconciler","msg":"Resolved container","container":"&Container{Name:kserve-container,Image:registry.example.com/ensemble:0.0.1,Command:[],Args:[],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:grpc,HostPort:0,ContainerPort:9000,Protocol:TCP,HostIP:,},},Env:[]EnvVar{EnvVar{Name:MLSERVER_MODEL_IMPLEMENTATION,Value:,ValueFrom:nil,},EnvVar{Name:MLSERVER_HTTP_PORT,Value:8080,ValueFrom:nil,},EnvVar{Name:MLSERVER_GRPC_PORT,Value:9000,ValueFrom:nil,},EnvVar{Name:MLSERVER_MODELS_DIR,Value:/mnt/models,ValueFrom:nil,},EnvVar{Name:OMP_NUM_THREADS,Value:2,ValueFrom:nil,},EnvVar{Name:MLSERVER_PARALLEL_WORKERS,Value:2,ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{cpu: {{1 0} {<nil>} 1 DecimalSI},memory: {{1073741824 0} {<nil>} 1Gi BinarySI},},Requests:ResourceList{cpu: {{500 -3} {<nil>} 500m DecimalSI},memory: {{1073741824 0} {<nil>} 1Gi BinarySI},},},VolumeMounts:[]VolumeMount{},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:,ImagePullPolicy:,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,}","podSpec":{"containers":[{"name":"kserve-container","image":"registry.example.comensemble:0.0.1","ports":[{"name":"grpc","containerPort":9000,"protocol":"TCP"}],"env":[{"name":"MLSERVER_MODEL_IMPLEMENTATION"},{"name":"MLSERVER_HTTP_PORT","value":"8080"},{"name":"MLSERVER_GRPC_PORT","value":"9000"},{"name":"MLSERVER_MODELS_DIR","value":"/mnt/models"},{"name":"OMP_NUM_THREADS","value":"2"},{"name":"MLSERVER_PARALLEL_WORKERS","value":"2"}],"resources":{"limits":{"cpu":"1","memory":"1Gi"},"requests":{"cpu":"500m","memory":"1Gi"}}}]}}
{"level":"info","ts":1655916682.2298896,"logger":"DeploymentReconciler","msg":"deployment reconcile","checkResult":2,"err":null}
{"level":"info","ts":1655916682.2299218,"logger":"ServiceReconciler","msg":"service reconcile","checkResult":2,"err":null}
{"level":"info","ts":1655916682.2299523,"logger":"HPAReconciler","msg":"service reconcile","checkResult":2,"err":null}
{"level":"info","ts":1655916682.2370474,"logger":"v1beta1Controllers.InferenceService","msg":"Inference service deployment mode ","deployment mode ":"RawDeployment"}
{"level":"info","ts":1655916682.237076,"logger":"v1beta1Controllers.InferenceService","msg":"Reconciling inference service","apiVersion":"serving.kserve.io/v1beta1","isvc":"ml-cookies-words-vectors"}
{"level":"info","ts":1655916682.237448,"logger":"PredictorReconciler","msg":"Resolved container","container":"&Container{Name:kserve-container,Image:registry.example.com/ensemble:0.0.1,Command:[],Args:[],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:grpc,HostPort:0,ContainerPort:9000,Protocol:TCP,HostIP:,},},Env:[]EnvVar{EnvVar{Name:MLSERVER_MODEL_IMPLEMENTATION,Value:,ValueFrom:nil,},EnvVar{Name:MLSERVER_HTTP_PORT,Value:8080,ValueFrom:nil,},EnvVar{Name:MLSERVER_GRPC_PORT,Value:9000,ValueFrom:nil,},EnvVar{Name:MLSERVER_MODELS_DIR,Value:/mnt/models,ValueFrom:nil,},EnvVar{Name:OMP_NUM_THREADS,Value:2,ValueFrom:nil,},EnvVar{Name:MLSERVER_PARALLEL_WORKERS,Value:2,ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{cpu: {{1 0} {<nil>} 1 DecimalSI},memory: {{1073741824 0} {<nil>} 1Gi BinarySI},},Requests:ResourceList{cpu: {{500 -3} {<nil>} 500m DecimalSI},memory: {{1073741824 0} {<nil>} 1Gi BinarySI},},},VolumeMounts:[]VolumeMount{},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:,ImagePullPolicy:,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,}","podSpec":{"containers":[{"name":"kserve-container","image":"registry.example.com/ensemble:0.0.1","ports":[{"name":"grpc","containerPort":9000,"protocol":"TCP"}],"env":[{"name":"MLSERVER_MODEL_IMPLEMENTATION"},{"name":"MLSERVER_HTTP_PORT","value":"8080"},{"name":"MLSERVER_GRPC_PORT","value":"9000"},{"name":"MLSERVER_MODELS_DIR","value":"/mnt/models"},{"name":"OMP_NUM_THREADS","value":"2"},{"name":"MLSERVER_PARALLEL_WORKERS","value":"2"}],"resources":{"limits":{"cpu":"1","memory":"1Gi"},"requests":{"cpu":"500m","memory":"1Gi"}}}]}}
{"level":"info","ts":1655916682.237631,"logger":"DeploymentReconciler","msg":"deployment reconcile","checkResult":2,"err":null}
{"level":"info","ts":1655916682.2376547,"logger":"ServiceReconciler","msg":"service reconcile","checkResult":2,"err":null}
{"level":"info","ts":1655916682.2376752,"logger":"HPAReconciler","msg":"service reconcile","checkResult":2,"err":null}
```

Environment:

No Istio, Nginx ingress
Kserve Version: 0.8
Kubernetes version: 1.24.0 Kind emulator
OS (e.g. from /etc/os-release): Ubuntu 20.04
