### ISSUE TITLE
Hpa scale up failed when in rawdeployment

### ISSUE THREAD

**Issue by Iamlovingit** [kserve/kserve#2278]
/kind bug
**What steps did you take and what happened:**
Deploy `isvc` in `RawDeployment` mode, add `annotation`:
```
annotations:
    serving.kserve.io/deploymentMode: "RawDeployment"
    serving.kserve.io/autoscalerClass: "hpa"
    serving.kserve.io/metrics: "cpu"
    serving.kserve.io/targetUtilizationPercentage: "30"
```
then, start load testing, and watching the behavior of hpa controller.

**What did you expect to happen:**
increase the pod num

**Anything else you would like to add:**
By watching the log of `kserve-manager`, we can get the deployment of the target `isvc` prints `check_result=1`, that means the deployment object is updated, after debugging this, we found that: when `isvc` is scaled up, the `replicas` of deployment is changed, and `kserve-manager` got this as an unexpected update, so reset the deployment to last version, this cause the failed of scaling.
