### ISSUE TITLE
AIX container image didn't respect the one specified in spec field

### ISSUE THREAD

**Issue by hsinhoyeh** [kserve/kserve#2281]
/kind bug

(not sure whether it is actually a bug or restricted by design, just post it here)

**What steps did you take and what happened:**

When specifying an explainer with AIX as defined below:

```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: tensorflow-example
  namespace: kubeflow-user-example-com
spec:
  predictor:
    tensorflow:
      storageUri: gs://kfserving-examples/models/tensorflow/flowers
      image: tensorflow/serving:2.8.0-gpu
  explainer:
    aix:  
      image: myrepo/aixserver
      runtimeVersion: v0.5.1-debug
```

the image field was captured by the inference service controller (with [ExplainerExtensionSpec](https://github.com/kserve/kserve/blob/2992d430c0b7c7458d0b557a642db8e6129c4f7c/pkg/apis/serving/v1beta1/explainer.go#L54) ) , as we described inferenservice with  kubectl:

```
Spec:
  Explainer:
    Aix:
      Config:
        min_weight:   0.01
        num_samples:  100
        top_labels:   10
      Image:          myrepo/aixserver
      Name:           kfserving-container
```

But on the controller side, it only refer the image repository from [the one specified in configmap](https://github.com/kserve/kserve/blob/master/pkg/apis/serving/v1beta1/explainer_aix360.go#L87) ):

```
return &v1.Container{
		Image:     config.Explainers.AIXExplainer.ContainerImage + ":" + *s.RuntimeVersion,
		Name:      constants.InferenceServiceContainerName,
		Resources: s.Resources,
		Args:      args,
	}
```

I believed this created confusion as the manager didn't not respect `spec` fields.

**What did you expect to happen:**

the manager should respect the image path specified in `spec` field.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

No.

**Environment:**

- KFServing Version: v0.5.1 ( but I checked the master, the code are the same)
- Kubeflow version: v1.4.1
