### ISSUE TITLE
collocate of transformer and triton predictor throwing error 

### ISSUE THREAD

**Issue by mdrijwan123** [kserve/kserve#2349]
/kind bug

**What steps did you take and what happened:**
I am working with transformer and onnx runtime so have to use triton server. My application is very latency specific, but due to two pods I believe there is a latency overhead as given in this issue: https://github.com/kserve/kserve/issues/1957
So, I want to achieve collocate feature so that in one pod both transformer and predictor will run. But not able to achive this and throwing error in predictor. I tested with single predictor only and its working, but with transformer throwing error, the manifest is given below:

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "kserve-inference-service"
spec:
  predictor:
    serviceAccountName: sa
    containers:
    - image: demoregistry.azurecr.io/transformer:v1
      name: transformer-container
      command:
      - "python"
      - "-m"
      - "transformer"
      args:
        - --user_entity_ids
        - id
        - --user_feature_refs
        - user_feature_view:pFeatures
        - --product_entity_ids
        - product_id
        - --product_feature_refs
        - product_view:Product_Features
        - --predictor_host
        - localhost:8080
      ports:
        - containerPort: 8000
          protocol: TPS
      env:
        - name: BLOB_KEY
          value: "key-value"
    - image: nvcr.io/nvidia/tritonserver:20.10-py3
      name: triton-server
      args:
        - tritonserver
        - --model-store=/mnt/models
        - --grpc-port=9000
        - --http-port=8080
        - --allow-grpc=true
        - --allow-http=true
      env:
        - name: STORAGE_URI
          value: https://blobdl.blob.core.windows.net/model/onnx/
```

**What did you expect to happen:**
I was aiming that both transformer and predictor would run in one single pod, don't know where is the issue here, or this collocate can only supported with pytorch not triton server.

**Environment:**

- Istio Version: v1.10.3
- Knative Version: v1.0.0
- KFServing Version: v0.8.0
- Kubeflow version: X
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version: X
- Kubernetes version: (use `kubectl version`): 1.21.9
- OS (e.g. from `/etc/os-release`):  ubuntu
