### ISSUE TITLE
Failure to create gRPC InferenceService when specifying multiple ContainerPorts

### ISSUE THREAD

**Issue by zz-x404** [kserve/kserve#2376]
/kind bug

Opening the issue based on conversation in Slack: https://kubeflow.slack.com/archives/CH6E58LNP/p1659980003450359

**What steps did you take and what happened:**
When trying to create a gRPC InferenceService following https://kserve.github.io/website/0.8/modelserving/v1beta1/tensorflow/#create-the-grpc-inferenceservice guide, and providing multiple port configs like below
```
...
      ports:
        - containerPort: 9000
          name: h2c
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
```
in the K8s Service, only the h2c port would appear:
```
...
spec:
  ports:
    - name: my-model-server-predictor-default
      protocol: TCP
      port: 80
      targetPort: 9000
```

**What did you expect to happen:**
That the port configs are all present in the K8s Service

**Anything else you would like to add:**
I am using the RawDeployment installation mode.

**Environment:**

- Istio Version:
  - (from `istioctl version`)
    ```
    control plane version: 1.14.1
    data plane version: 1.14.1 (150 proxies)
    ```
- Knative Version: N/A
- KFServing Version: 0.8.0
- Kubeflow version: N/A
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]: N/A
- Minikube version: N/A
- Kubernetes version: (use `kubectl version`): `v1.21.13-eks-84b4fe6`
- OS (e.g. from `/etc/os-release`):
  ```
  NAME="Ubuntu"
  VERSION="18.04.6 LTS (Bionic Beaver)"
  ```
