### ISSUE TITLE
Transformer support for InferenceGraph

### ISSUE THREAD

**Issue by abhinavgpt** [kserve/kserve#2379]
/kind feature

**Describe the solution you'd like**
This will solve the issue of transformer redundancy when the first or last node in the InferenceGraph has multiple models (in a splitter or ensemble configuration) using the exact same transformer. 

Consider the example below:

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-iris
  namespace: kserve-test
spec:
  transformer:
    containers:
      - image: transformer:1.0
        name: kserve-container
        command:
          - "python"
          - "-m"
          - "custom_transformer.model"
        args:
          - --model_name
          - sklearn-iris
  predictor:
    sklearn:
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: xgboost-iris
  namespace: kserve-test
spec:
  transformer:
    containers:
      - image: transformer:1.0
        name: kserve-container
        command:
          - "python"
          - "-m"
          - "custom_transformer.model"
        args:
          - --model_name
          - xgboost-iris
  predictor:
    xgboost:
      storageUri: "gs://kfserving-examples/models/xgboost/iris"
---
apiVersion: serving.kserve.io/v1alpha1
kind: InferenceGraph
metadata:
  name: ensemble-model
  namespace: kserve-test
spec:
  nodes:
    root:
      routerType: Ensemble
      steps:
        - serviceName: sklearn-iris
          name: sklearn-iris
        - serviceName: xgboost-iris
          name: xgboost-iris
```

Here InferenceGraph has two InferenceServices.  Since same preprocessing is to be done for both these InferenceService objects, same transformer is present in both the InferenceServices. 

When the above configuration is applied, two separate transformer pods will be created. Both the transformer pods will be doing the exact same preprocessing on the same input and hence, there is redundancy here. If I had 10 models above, 10 transformers would be running.

One solution could be to have transformer support at InferenceGraph level. So the above configuration will look like this:

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-iris
  namespace: kserve-test
spec:
  predictor:
    sklearn:
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: xgboost-iris
  namespace: kserve-test
spec:
  predictor:
    xgboost:
      storageUri: "gs://kfserving-examples/models/xgboost/iris"
---
apiVersion: serving.kserve.io/v1alpha1
kind: InferenceGraph
metadata:
  name: ensemble-model
  namespace: kserve-test
spec:
  transformer:
    containers:
      - image: transformer:1.0
        name: kserve-container
        command:
          - "python"
          - "-m"
          - "custom_transformer.model"
  nodes:
    root:
      routerType: Ensemble
      steps:
        - serviceName: sklearn-iris
          name: sklearn-iris
        - serviceName: xgboost-iris
          name: xgboost-iris
```

The incoming input would be processed by InferenceGraph's transformer and then would be passed to the models. Having transformer for InferenceGraph will also allow users to process the output of the graph - for eg, it could be used as a reducer model.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

One alternative solution to the problem would be to allow transformer only InferenceService as requested in #2336 . This would allow for even more possibilities with the InferenceGraph.

Yet another solution may be to allow multiple InferenceService objects to be connected to the same transformer.
