### ISSUE TITLE
How to mount additional custom storage in V1beta1PredictorSpec?

### ISSUE THREAD

**Issue by yurkoff-mv** [kserve/kserve#2427]
/kind bug

I have read previous posts [1733](https://github.com/kserve/kserve/issues/1733) and [1722](https://github.com/kserve/kserve/issues/1722) but they don't answer my question.
The documentation clearly states the point of mounting volumes from [V1beta1PredictorSpec](https://github.com/kserve/kserve/blob/master/python/kserve/docs/V1beta1PredictorSpec.md) to [V1beta1TorchServeSpec.](https://github.com/kserve/kserve/blob/master/python/kserve/docs/V1beta1TorchServeSpec.md)

```
pytorch_predictor=V1beta1PredictorSpec(
    pytorch=V1beta1TorchServeSpec(
        runtime_version='0.5.3-gpu',
        storage_uri='pvc://torchserve-claim/my-model',
        volume_mounts=[V1VolumeMount(name="my-volume", mount_path="/mnt/storage")],
        resources=V1ResourceRequirements(
            requests={'cpu':'1000m', 'memory':'4Gi', 'nvidia.com/gpu': '0'},
            limits={'cpu':'2000m', 'memory':'8Gi', 'nvidia.com/gpu': '0'}
        ),
    ),
    volumes=[V1Volume(name="my-volume",
                      persistent_volume_claim=V1PersistentVolumeClaimVolumeSource(claim_name="my-pvc")
                     ),
            ],
    timeout=20,
)


isvc = V1beta1InferenceService(api_version=constants.KSERVE_V1BETA1,
                               kind=constants.KSERVE_KIND,
                               metadata=client.V1ObjectMeta(name='my-service', namespace=namespace),
                               spec=V1beta1InferenceServiceSpec(predictor=pytorch_predictor))
```

I know there is a storage-uri that mounts to `/mnt/models ` but I want to additionally mount another storage to the containers. The documentation says this is possible, but it doesn't work:
```
Warning  InternalError  20s (x13 over 40s)  v1beta1Controllers  fails to reconcile predictor: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: expected exactly one, got neither: spec.template.spec.volumes[0].configMap, spec.template.spec.volumes[0].projected, spec.template.spec.volumes[0].secret
must not set the field(s): spec.template.spec.volumes[0].persistentVolumeClaim
```
In addition, storage-uri is mounted in ReadOnly mode.

How can i do this? Is there an example somewhere?

**Comment by yuzisun** [comment]
@yurkoff-mv You would need to enable the persistence volume mount flag with knative, see https://knative.dev/docs/serving/configuration/feature-flags/

**Comment by yurkoff-mv** [comment]
I have the following configuration:
- MicroK8s v1.20
- Kubeflow v1.3
- KServe 0.7.0
- Knative v0.22.1

I am trying execute
`kubectl edit configmap config-features -n knative-serving`
There is no option to enable volume (`kubernetes.podspec-persistent-volume-claim`) in the config.

**Comment by pkurzend** [comment]
Hello, i am trying to create an inferenceservice with mounted pvc. However i cant figure out how the yaml config file is supposed to look:

```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: stable-diffusion4
spec:

  predictor:

    containerConcurrency: 1
    minReplicas: 0
    maxReplicas: 5
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: gpu.nvidia.com/class
              operator: In
              values:
              - RTX_A5000
            - key: topology.kubernetes.io/region
              operator: In
              values:
              - ORD1 

    containers:
      - name: kfserving-container # kserve-container
        image: <docker image>
        env:
          # - name: STORAGE_URI #STORAGE_URI # Kserve mounts the PVC at /mnt/models/  --> READONLY
          #   value: pvc://stable-diffusion-model-cache/
          - name: HF_HOME
            value: /mnt/models/
        
        volumeMounts:
          - name: model-cache
            mountPath: /mnt/models

        resources:
          requests:
            cpu: 6
            memory: 32Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 6
            memory: 32Gi
            nvidia.com/gpu: 1
  volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: stable-diffusion-model-cache

```

I keep getting this error:
`unknown field "volumes" in org.kubeflow.serving.v1beta1.InferenceService.spec`

I am aware of the STORAGE_URI  variable, but it gives only read access.

Any idea how i can achieve this? Thanks

**Comment by yurkoff-mv** [comment]
Hello, my service looks like this:
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {your name}
  namespace: {your namespace}
spec:
  predictor:
    pytorch:
      image: {your image if needed}
      name: kserve-container
      protocolVersion: v1
      resources:
        limits:
          cpu: "4"
          memory: 8Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: 6Gi
          nvidia.com/gpu: "1"
      runtimeVersion: 0.5.3-gpu
      storageUri: pvc://{your pvc name}/{directory with direvtory config and directory model-store}
    timeout: 20
```

Maybe you should pay attention to the field `apiVersion`. In my case it is : `serving.kserve.io/v1beta1`.
