### ISSUE TITLE
pod for model server keep pending

### ISSUE THREAD

**Issue by TranThanh96** [kserve/kserve#2433]
I deployed kubeflow on aws distribution.
I tried a sample kserve here: https://awslabs.github.io/kubeflow-manifests/docs/component-guides/kserve/#run-a-sample-inferenceservice and everything works.
Then, I tried an other sample: https://github.com/kserve/kserve/tree/release-0.7/docs/samples/v1beta1/triton/torchscript

My yaml file: 
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "torchscript-cifar"
spec:
  predictor:
    triton:
      storageUri: "gs://kfserving-examples/models/torchscript"
      runtimeVersion: 21.08-py3
      env:
      - name: OMP_NUM_THREADS
        value: "1"
```
after run: kubectl apply -n staging -f torch_script.yaml
the model server keep pending status:

![image](https://user-images.githubusercontent.com/26323599/191210566-01b05022-67e0-47f2-9fa5-a8a806e65e0a.png)
How can I solve this issue?

I tried an other sample on: 
https://github.com/kserve/kserve/tree/release-0.7/docs/samples/v1beta1/torchserve

still the same
