### ISSUE TITLE
kserve with transformer pull image from private ECR

### ISSUE THREAD

**Issue by TranThanh96** [kserve/kserve#2438]
I am trying to deploy a transformer by following this tutorial: https://github.com/kserve/kserve/tree/release-0.7/docs/samples/v1beta1/transformer/torchserve_image_transformer

instead of using public registry, I use my private ECR. But I dont know the right way to add permission to pull image from my ECR.

I tried with a solution:
```
kubectl create secret docker-registry my-secret-registry \
--docker-server=80***********03.dkr.ecr.us-east-1.amazonaws.com \
--docker-username=AWS \
--docker-password=$(aws ecr get-login-password --region us-east-1)
```

then apply my yaml
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: torchserve-transformer
spec:
  transformer:
    imagePullSecrets:
    - name: mysecret-registry
    containers:
    - image: 80***********03.dkr.ecr.us-east-1.amazonaws.com/cnndha:image-transformer-v2
      name: kfserving-container
      env:
        - name: STORAGE_URI
          value: gs://kfserving-examples/models/torchserve/image_classifier
  predictor:
    pytorch:
      storageUri: gs://kfserving-examples/models/torchserve/image_classifier
```

but seem like, it does not work.

Please give me some instructions.
