### ISSUE TITLE
Deploy model by kserve on GKE with workload identity.

### ISSUE THREAD

**Issue by hoanhvong** [kserve/kserve#2439]
/kind bug

hi team, when I deploy the model by kserve on GKE cluster which uses workload identity.  Hope you can help in the situation. 

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I deployed InferenceService on GKE  
+ create a service account, which binding GSA.
   + Configure service account: 
   ```
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kserve-model-sa
        namespace: machine-learning
        annotations:
          iam.gke.io/gcp-service-account: kserve@machine-learning.iam.gserviceaccount.com
   ```
   + In InferenceService:
   ```
      apiVersion: "serving.kserve.io/v1beta1"
      kind: "InferenceService"
      metadata:
        name: "ml-model"
      spec:
        predictor:
          serviceAccountName: kserve-model-sa
          model:
            modelFormat:
              name: mlflow
            protocolVersion: v2
            storageUri: "gs://example/artifacts/model"
   ```
Then when deploy InferenceService, that pods can't binding KSA (kubernetes service account) which GSA (google service account). kserve/storage-initializer:v0.9.0 can't download model, throw this error message
```
Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/kserve@machine-learning.iam.gserviceaccount.com/token?scopes= https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.read_only%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.read_write from the Google Compute Engine metadata service. Status: 403 Response:\nb'Unable to generate access token; IAM returned 403 Forbidden: The caller does not have permission\\nThis error could be caused by a missing IAM policy binding on the target IAM service account.\\nFor more information, refer to the Workload Identity documentation:\\n\\thttps://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to\\n\\n'", <google.auth.transport.requests._Response object at 0x7f9a3dec9fd0>
```

**What did you expect to happen:**
I expect when deploying InferenceService with workload identity that should be a success

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
RawDeployment with kserve only, I deploy kserve on GKE.
- Istio Version: na
- Knative Version: na
- KFServing Version: 0.9
- Kubeflow version: na
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version: GKE
- Kubernetes version: (use `kubectl version`): v.1.24.0
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04 LTS

**Comment by hoanhvong** [comment]
After rechecking, The service account name created is mismatched with InferenceService. 
When check IAM policy binding, we found that the name of KSA which I register is `kserve-example`
```
$ gcloud iam service-accounts get-iam-policy kserve@machine-learning.iam.gserviceaccount.com --project=example

bindings:
- members:
- serviceAccount:machine-learning.svc.id.goog[machine-learning/kserve-example]
role: roles/iam.workloadIdentityUser
etag: BwXnhAYffns=
version: 1
```
So I change the name of service account name from `kserve-model-sa` to `kserve-example` for resolve that. 
The result after change. 

Service account
```
 apiVersion: v1
   kind: ServiceAccount
   metadata:
     name: kserve-example
     namespace: machine-learning
     annotations:
       iam.gke.io/gcp-service-account: kserve@machine-learning.iam.gserviceaccount.com
```
In InferenceService:
``` 
   apiVersion: "serving.kserve.io/v1beta1"
   kind: "InferenceService"
   metadata:
     name: "ml-model"
   spec:
     predictor:
       serviceAccountName: kserve-example
       model:
         modelFormat:
           name: mlflow
         protocolVersion: v2
         storageUri: "gs://example/artifacts/model"
```
