### ISSUE TITLE
Missing documentation for using s3 storage

### ISSUE THREAD

**Issue by leandregagnonlewis** [kserve/kserve#2461]
/kind feature

When looking at how to store a model on s3 the only documentation I found is [this](https://github.com/kserve/kserve/tree/master/docs/samples/storage/s3) and [this](https://kserve.github.io/website/0.9/modelserving/storage/s3/s3/). I followed closely the doc on the github.io page and it is not working for me. 

When I look at the markdown file, it says "Your cluster's Istio Egress gateway must [allow accessing S3 Storage](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/)." But egress doc does not mention s3, so how do I allow s3 access in Istio? I have tried adding an egress to istio

```
  cat << EOF > ./istio-minimal-operator.yaml
  apiVersion: install.istio.io/v1beta1
  kind: IstioOperator
  spec:
    values:
      global:
        proxy:
          autoInject: disabled
        useMCP: false
  
    meshConfig:
      accessLogFile: /dev/stdout
  
    addonComponents:
      pilot:
        enabled: true
  
    components:
      ingressGateways:
        - name: istio-ingressgateway
          enabled: true
      egressGateways:
        - name: istio-egressgateway
          enabled: true
  EOF
```
I have also tried to deploy a service entry
```
  apiVersion: networking.istio.io/v1alpha3
  kind: ServiceEntry
  metadata:
    name: s3
  spec:
    hosts:
    - s3.amazonaws.com
    ports:
    - number: 80
      name: http-port
      protocol: HTTP
    - number: 443
      name: https
      protocol: HTTPS
    resolution: DNS
    location: MESH_EXTERNAL
```
Still, when I try to start my inferenceService, the predictor pod is in error from the start
```
  apiVersion: "serving.kserve.io/v1beta1"
  kind: "InferenceService"
  metadata:
    name: "sklearn"
  spec:
    predictor:
      serviceAccountName: s3-resnet-sa
      model:
        modelFormat:
          name: sklearn
        storageUri: "s3://pytorch-resnet"
```
 For info my bucket contains the minist sklearn model from the samples.
