### ISSUE TITLE
kserve unable to use local images in docker desktop kubernetes cluster

### ISSUE THREAD

**Issue by AKnowlesAtDigit** [kserve/kserve#2469]
/kind bug

**What steps did you take and what happened:**
1. enabled Kubernetes on Docker Desktop version 4.11.0
2. installed kserve quickstart by running `curl -s "https://raw.githubusercontent.com/kserve/kserve/release-0.9/hack/quick_install.sh" | bash`
3. Built a local model named ml_model and tagged it as 1.0.0
4. created a namespace `ml-models`
5. applied this yaml file -
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: wine-model
  namespace: ml-models
spec:
  predictor:
    containers:
      - name: wine-model
        image: ml_model:1.0.0
        imagePullPolicy: Never
```
6. isvc readiness is "FALSE" and has the following state transition log 
```
Revision "wine-model-predictor-default-00001" failed with message: Unable                                                                                                                                                                                                    │
│       to fetch image "ml_model:1.0.0": failed to resolve image to digest: HEAD https://index.docker.io/v2/library/ml_model/manifests/1.0.0:                                                                                                                                                │
│       unexpected status code 401 Unauthorized (HEAD responses have no body, use GET                                                                                                                                                                                                        │
│       for details).
```


**What did you expect to happen:**
I would expect the InferenceService to pull the image from the local cache

**Anything else you would like to add:**
Running the container as a normal deployment worked fine.
Applying the following yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model
  namespace: ml-models
  labels:
    app: ml-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
      - name: ml-model
        image: ml_model:1.0.0
        imagePullPolicy: Never
```
resulted in a pod with the container running successfully inside it.

**Environment:**

- Istio Version: 1.14.0
- Knative Version: knative-v1.4.0
- KFServing Version: 0.9
- Kubeflow version: NA
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version: NA - using docker desktop cluster
- Kubernetes version: (use `kubectl version`): v1.24.2
- OS (e.g. from `/etc/os-release`):

**Comment by AKnowlesAtDigit** [comment]
Solved my own issue - It seems that prefixing the image name with `dev.local` solves this.

https://github.com/knative/serving/issues/6101

**Comment by QuadTriangle** [comment]
```
# name your local image with `dev.local` prefix
docker tag ghcr.io/knative/helloworld-go dev.local/hello
# load image into kind
kind load docker-image --name knative dev.local/hello
# deploy
kubectl apply --filename service.yaml
# find url 
kn service list
```
service.yaml file

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: dev.local/hello2
          imagePullPolicy: IfNotPresent
          env:
            - name: TARGET
              value: "hello from knative!!"

```
