### ISSUE TITLE
Trainedmodels in Unknown state in MMS when GRPC is enabled, but they serve predictions

### ISSUE THREAD

**Issue by molejnik-mergebit** [kserve/kserve#2500]
/kind bug

I created the InferenceService for MMS (multi model serving) with GRPC enabled:

```
apiVersion: 'serving.kserve.io/v1beta1'
kind: 'InferenceService'
metadata:
  name: "testing-isvc-grpc"
spec:
  predictor:
    minReplicas: 1
    serviceAccountName: user-gcp-sa
    model:
      runtime: kserve-mlserver
      name: 'testing-predictor-grpc'
      protocolVersion: v2
      modelFormat:
        name: 'sklearn'
      ports:
        - name: 'h2c'
          containerPort: 9000
          protocol: 'TCP'
```

I created trainedmodels to work with this isvc:

```
apiVersion: serving.kserve.io/v1alpha1
kind: TrainedModel
metadata:
  name: test-tm-1
  namespace: default
spec:
  inferenceService: testing-isvc-grpc
  model:
    framework: sklearn
    memory: 6Mi
    storageUri: gs://test-bucket/model1
---
apiVersion: serving.kserve.io/v1alpha1
kind: TrainedModel
metadata:
  name: test-tm-2
  namespace: default
spec:
  inferenceService: testing-isvc-grpc
  model:
    framework: sklearn
    memory: 6Mi
    storageUri: gs://test-bucket/model2
```

Inference service and pods becomes ready/running:
```
NAME                      URL          READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION      AGE
testing-isvc-grpc   http://testing-isvc-grpc.myurl.com   True           100                              testing-predictor-grpc-default-00001   1d

NAME                                 READY   STATUS    RESTARTS   AGE
testing-predictor-grpc-default-00001-deployment-58577f89d5-76lm8       3/3     Running   0          1d
```

But trainedmodels hangs in the Unknown state:

```
test-tm-1                       http:///testing-isvc-grpc.myurl.com/v2/models/test-tm-1/infer                   Unknown   1d
test-tm-2                         http:///testing-isvc-grpc.myurl.com/v2/models/test-tm-2/infer                     Unknown   1d
```

`describe` output:

```
Name:         test-tm-1  
Namespace:    default
Labels:       inferenceservice=testing-isvc-grpc
              serving.kserve.io/trainedmodel-allocated=testing-isvc-grpc
Annotations: 
API Version:  serving.kserve.io/v1alpha1
Kind:         TrainedModel
Metadata:
  Creation Timestamp:  2022-10-17T15:28:35Z
  Finalizers:
    trainedmodel.finalizer
  Generation:  1
  Managed Fields:
    API Version:  serving.kserve.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:inferenceService:
        f:model:
          .:
          f:framework:
          f:memory:
          f:storageUri:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-10-17T15:28:35Z
    API Version:  serving.kserve.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"trainedmodel.finalizer":
        f:labels:
          .:
          f:inferenceservice:
          f:serving.kserve.io/trainedmodel-allocated:
      f:status:
        .:
        f:address:
          .:
          f:url:
        f:conditions:
        f:url:
    Manager:         manager
    Operation:       Update
    Time:            2022-10-17T15:28:35Z
  Resource Version:  384867017
  UID:               f7f9afe0-53b0-4772-9462-d78dbc06bd19
Spec:
  Inference Service:  testing-isvc-grpc
  Model:
    Framework:    sklearn
    Memory:       6Mi
    Storage Uri:  gs://test-bucket/model1
Status:
  Address:
    URL:  http://testing-isvc-grpc.default.svc.cluster.local/v2/models/test-tm-1/infer
  Conditions:
    Last Transition Time:  2022-10-17T15:28:35Z
    Status:                True
    Type:                  InferenceServiceReady
    Last Transition Time:  2022-10-17T15:28:35Z
    Status:                True
    Type:                  IsMMSPredictor
    Last Transition Time:  2022-10-17T15:28:35Z
    Status:                True
    Type:                  MemoryResourceAvailable
    Last Transition Time:  2022-10-17T15:28:35Z
    Status:                Unknown
    Type:                  Ready
  URL:                     http:///testing-isvc-grpc.myurl.com/v2/models/test-tm-1/infer
Events:                    <none>
```

**Important: Although models are in the Unknown state, they serve it's purpose correctly, i.e. I can make predictions via GRPC. So this is rather minor bug, meaning that just the state reporting seems to be wrong.**

When I do the same, but with HTTP only (no GRPC, i.e. no `ports` section in isvc YAML), all is OK and trainedmodels are in Ready state.

**What did you expect to happen:**

Trainedmodels in MMS with GRPC enabled should report status Ready.

**Environment:**

- KFServing Version: 0.8.0

- Kubernetes version: (use `kubectl version`):
Client Version: v1.23.6
Server Version: v1.21.14-gke.2700
