### ISSUE TITLE
Does KServe not support using pvc in custom images?

### ISSUE THREAD

**Issue by SeibertronSS** [kserve/kserve#2554]
/kind bug

**What steps did you take and what happened:**
I made a mirror myself and stored the model in pvc. My yaml looks like this
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: black-model
spec:
  predictor:
    containers:
      - name: kfserving-container
        image: xxx/isvc-custom-test:1.0
        volumeMounts:
        - name: black-volume
          mountPath: /mnt
          readOnly: true
    volumes:
    - name: black-volume
      persistentVolumeClaim:
        claimName: test-pvc
```
I got an error like this
```
Events:                                                                                                                                                                                                               
Type     Reason         Age                   From                Message                                                                                                                                            ----     ------         ----                  ----                -------                                                                                                                                            
Warning  InternalError  57s (x17 over 6m25s)  v1beta1Controllers  fails to reconcile predictor: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: Persistent volume  │
claim support is disabled, but found persistent volume claim test-pvc:                                                                                                                                                
Persistent volume write support is disabled, but found persistent volume claim test-pvc that is not read-only:                                                                                                       must not set the field(s): spec.template.spec.volumes[0].persistentVolumeClaim
```
Doesn't KServe allow pvc to be used like this?


**What did you expect to happen:**


**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]


**Environment:**

- Istio Version: v1.9.4
- Knative Version: V1.4.0
- KFServing Version: 0.9.0-rc
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.19.9
- OS (e.g. from `/etc/os-release`): CentOS8
