### ISSUE TITLE
Cannot run InferenceService in RawDeployment mode without specifying some annotations

### ISSUE THREAD

**Issue by djmcgreal-cc** [kserve/kserve#2560]
/kind bug

**What steps did you take and what happened:**
Configure kserve 0.9 in RawDeployment mode. Run an InferenceService with `metadata: {annotations: null}`.

The mutating web hook fails admission because https://github.com/kserve/kserve/blob/8fdd82fe109967efe94b7a012f07f9d75ab2eb60/pkg/apis/serving/v1beta1/inference_service_defaults.go#L86 doesn't check for nil annotations map before trying to setup a new annotation.

**What did you expect to happen:**

Kserve to be able to deal with an InferenceService in RawDeployment mode without annotations.

**What's the InferenceService yaml:**
From 
```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  generateName: inference-service-v2-
  labels:
    inference-service-test.cambridgeconsultants.com: "true"
  annotations:
    hello: ok
spec:
  predictor:
    triton:
      storageUri: "gs://kfserving-examples/models/torchscript"
      runtimeVersion: 20.10-py3
      env:
      - name: OMP_NUM_THREADS
        value: "1"
```

The workaround is to simply add a dummy annotation. Unfortunately `annotations: {}` didn't work. 🤷

**Environment:**

- KServe Version: 0.9
- Cloud Environment: EKS
- Kubernetes version: (use `kubectl version`): v1.21.14
- OS (e.g. from `/etc/os-release`): MacOs
