### ISSUE TITLE
Set rention period for pods with autoscaling 0

### ISSUE THREAD

**Issue by mmeendez8** [kserve/kserve#2562]
I am trying to set a retention period for my pods so the remain active after the autoscaler decide to scale them to zero.

I just saw I can use the following annotation in [knative docs](https://knative.dev/docs/serving/autoscaling/scale-to-zero/#scale-to-zero-last-pod-retention-period): `autoscaling.knative.dev/scale-to-zero-pod-retention-period`

But it seems they get propagated to the labels section of the knative layer.

This is what I set annotations on the resource at top level:

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    autoscaling.knative.dev/scale-to-zero-pod-retention-period: 20m
```
This is what I see on knative:

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    ...
  generation: 7
  labels:
    app.kubernetes.io/env: kubeflow
    ...
    autoscaling.knative.dev/scale-to-zero-pod-retention-period: 20m5s
```

Is there anyway of doing this? Can't see any reference to autoscaling annotation in the `InferenceService Annotations`

https://github.com/ddelange/kserve/blob/master/pkg/constants/constants.go#L69
