### ISSUE TITLE
Custom model has model agent injected by default

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#2568]
/kind bug

**What steps did you take and what happened:**
Custom model has model agent injected by default which is not expected, it is incorrectly marked as MMS model server.

https://github.com/kserve/kserve/commit/33bb7afdbf3daee77a3a4bf058473aa1ad7f5397#diff-57baeaa559989f6eb9da5ebbc7d34374151c8f8c9cdc26be56595dae29e0c760L44

```bash
kubectl get pods
NAME                                                              READY   STATUS    RESTARTS      AGE
custom-simple-predictor-default-00001-deployment-5974cf9d5q4b22   3/3     Running   0             111m
```

**What did you expect to happen:**
In serverless mode only two containers should be created for inference service with custom runtime.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
```yaml
 apiVersion: serving.kserve.io/v1beta1
 kind: InferenceService
 metadata:
    name: custom-simple
    namespace: default
spec:
  predictor:
    containers:
    - image: codait/max-object-detector
      name: kserve-container
      ports:
      - containerPort: 5000
        protocol: TCP
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi
    minReplicas: 1
```
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.15
- Knative Version: 1.7
- KServe Version: 0.10.0-rc0
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
