### ISSUE TITLE
Access both http & GRPC with custom model

### ISSUE THREAD

**Issue by mmeendez8** [kserve/kserve#2601]
/kind feature

**Describe the solution you'd like**
I would like to be able to deploy a custom model server (i.e. using a custom torchserve image) and access to it through both http and gRPC.

I have seen [an old example with a very basic custom gRPC server](https://github.com/kserve/kserve/issues/877) that has been removed from the repo. Is this still possible? 
I was able to reach the pod using port forwarding but I cannot reach going through the Istio gateway.

**Anything else you would like to add:**
I am currently using kserve v0.7 installed with kubeflow.

**Comment by yuzisun** [comment]
@mmeendez8 are you port forwarding the gRPC port? For serverless mode currently only one port is allowed.

**Comment by mmeendez8** [comment]
@yuzisun 
What is the easiest way of using a custom torchserve image with GRPC enabled?
I have update to latest kserve version my inference service is the following:

```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "my-server"

spec:
  predictor:
    pytorch:
      storageUri: s3://...
      image: my-image-from-ecr
      resources:
        limits:
          memory: 6Gi
          nvidia.com/gpu: "1"
        requests:
          memory: 2Gi
          nvidia.com/gpu: "1"
    serviceAccountName: my-service-account
```

From what I understand this torchserve inferenceservice is using the [`ClusterServingRuntime`](https://github.com/kserve/kserve/blob/master/config/runtimes/kserve-torchserve.yaml). I tried to override defaults args but without any success. Is there anyway I can just use my custom image entrypoint without adding any extra arguments?
