### ISSUE TITLE
flux cannot work with kserve controller

### ISSUE THREAD

**Issue by life-learner1** [kserve/kserve#2646]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I use fluxCD to manage InferenceService file , but I met an error here.
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: intention-and-similar
spec:
  predictor:
    model:
      image: pytorch/torchserve-kfs:0.6.0-gpu
      modelFormat:
        name: pytorch
      name: ''
      resources:
        limits:
          memory: 10Gi
          nvidia.com/gpu: '1'
        requests:
          memory: 9Gi
          nvidia.com/gpu: '1'
      runtime: kserve-torchserve
      storageUri: pvc://ai-pv-claim/intention-and-similar
```

log in kserve-controller-manager-79ccd97ff-rtjhn pod:
```log
2023/01/11 07:00:09 http: panic serving 10.107.80.233:43034: assignment to entry in nil map
goroutine 4090261 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0x186b040, 0x1d47cb0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/kserve/kserve/pkg/apis/serving/v1beta1.(*InferenceService).DefaultInferenceService(0xc00184ed80, 0xc002990000, 0xc000984530)
	/go/src/github.com/kserve/kserve/pkg/apis/serving/v1beta1/inference_service_defaults.go:86 +0xfd
github.com/kserve/kserve/pkg/apis/serving/v1beta1.(*InferenceService).Default(0xc00184ed80)
	/go/src/github.com/kserve/kserve/pkg/apis/serving/v1beta1/inference_service_defaults.go:79 +0x17d
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*mutatingHandler).Handle(_, {_, _}, {{{0xc001659b30, 0x24}, {{0xc001103110, 0x11}, {0xc002b72858, 0x7}, {0xc002b72860, ...}}, ...}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/webhook/admission/defaulter.go:66 +0x1fe
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle(_, {_, _}, {{{0xc001659b30, 0x24}, {{0xc001103110, 0x11}, {0xc002b72858, 0x7}, {0xc002b72860, ...}}, ...}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/webhook/admission/webhook.go:146 +0xa2
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc000a2e780, {0x7f8e55e4a300, 0xc000f11db0}, 0xc002056f00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/webhook/admission/http.go:99 +0xef0
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1({0x7f8e55e4a300, 0xc000f11db0}, 0xc000f11db0)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:40 +0xd4
net/http.HandlerFunc.ServeHTTP(0x1d7da20, {0x7f8e55e4a300, 0xc000f11db0}, 0x7f8e7d015a68)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x1d7da20, 0xc0014c5c00}, 0xc002056f00)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:101 +0x92
net/http.HandlerFunc.ServeHTTP(0xc0009e8940, {0x1d7da20, 0xc0014c5c00}, 0xc00127a800)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x1d7da20, 0xc0014c5c00}, 0xc002056f00)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:76 +0xa2
net/http.HandlerFunc.ServeHTTP(0x7f8e55fbf538, {0x1d7da20, 0xc0014c5c00}, 0xc0014c5c00)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00194cf38, {0x1d7da20, 0xc0014c5c00}, 0xc002056f00)
	/usr/local/go/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0x1d701a8}, {0x1d7da20, 0xc0014c5c00}, 0xc002056f00)
	/usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0010fbcc0, {0x1d840d8, 0xc000a44210})
	/usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0x4e8
Logs from 1/11/2023, 1:55:01 PM
````

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.13.5
- Knative Version: None
- KServe Version:  v0.9.0
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):  v1.22.15-eks-fb459a0
- OS (e.g. from `/etc/os-release`): 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"

**Comment by yuzisun** [comment]
@life-learner1 Do you have the configmap `inferenceservice-config` installed in kserve namespace?

**Comment by life-learner1** [comment]
> @life-learner1 Do you have the configmap `inferenceservice-config` installed in kserve namespace?
Yeah 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kserve
  labels:
    kustomize.toolkit.fluxcd.io/name: apps
    kustomize.toolkit.fluxcd.io/namespace: flux-system
data:
  agent: |-
    {
        "image" : "kserve/agent:v0.9.0",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1"
    }
  batcher: |-
    {
        "image" : "kserve/agent:v0.9.0",
        "memoryRequest": "1Gi",
        "memoryLimit": "1Gi",
        "cpuRequest": "1",
        "cpuLimit": "1"
    }
  credentials: |-
    {
       "gcs": {
           "gcsCredentialFileName": "gcloud-application-credentials.json"
       },
       "s3": {
           "s3AccessKeyIDName": "AWS_ACCESS_KEY_ID",
           "s3SecretAccessKeyName": "AWS_SECRET_ACCESS_KEY"
       }
    }
  deploy: |-
    {
      "defaultDeploymentMode": "RawDeployment"
    }
  explainers: |-
    {
        "alibi": {
            "image" : "kserve/alibi-explainer",
            "defaultImageVersion": "latest"
        },
        "aix": {
            "image" : "kserve/aix-explainer",
            "defaultImageVersion": "latest"
        },
        "art": {
            "image" : "kserve/art-explainer",
            "defaultImageVersion": "latest"
        }
    }
  ingress: |-
    {
        "ingressGateway" : "istio-system/istio-ingressgateway",
        "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
        "localGateway" : "istio-system/istio-ingressgateway",
        "localGatewayService" : "istio-ingressgateway.istio-system.svc.cluster.local",
        "ingressDomain"  : "horizon.hp.com",
        "ingressClassName" : "istio",
        "domainTemplate": "{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}",
        "urlScheme": "http"
    }
  logger: |-
    {
        "image" : "kserve/agent:v0.9.0",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1",
        "defaultUrl": "http://default-broker"
    }
  predictors: |-
    {
        "tensorflow": {
            "image": "tensorflow/serving",
            "defaultImageVersion": "2.6.2",
            "defaultGpuImageVersion": "2.6.2-gpu",
            "defaultTimeout": "60",
            "supportedFrameworks": [
              "tensorflow"
            ],
            "multiModelServer": false
        },
        "onnx": {
            "image": "mcr.microsoft.com/onnxruntime/server",
            "defaultImageVersion": "v1.0.0",
            "supportedFrameworks": [
              "onnx"
            ],
            "multiModelServer": false
        },
        "sklearn": {
          "v1": {
            "image": "kserve/sklearnserver",
            "defaultImageVersion": "latest",
            "supportedFrameworks": [
              "sklearn"
            ],
            "multiModelServer": true
          },
          "v2": {
            "image": "docker.io/seldonio/mlserver",
            "defaultImageVersion": "1.0.0",
            "supportedFrameworks": [
              "sklearn"
            ],
            "multiModelServer": true
          }
        },
        "xgboost": {
          "v1": {
            "image": "kserve/xgbserver",
            "defaultImageVersion": "latest",
            "supportedFrameworks": [
              "xgboost"
            ],
            "multiModelServer": true
          },
          "v2": {
            "image": "docker.io/seldonio/mlserver",
            "defaultImageVersion": "1.0.0",
            "supportedFrameworks": [
              "xgboost"
            ],
            "multiModelServer": true
          }
        },
        "pytorch": {
          "v1" : {
            "image": "pytorch/torchserve-kfs",
            "defaultImageVersion": "0.6.0",
            "defaultGpuImageVersion": "0.6.0-gpu",
            "supportedFrameworks": [
              "pytorch"
            ],
            "multiModelServer": false
          },
          "v2" : {
            "image": "pytorch/torchserve-kfs",
            "defaultImageVersion": "0.6.0",
            "defaultGpuImageVersion": "0.6.0-gpu",
            "supportedFrameworks": [
              "pytorch"
            ],
            "multiModelServer": false
          }
        },
        "triton": {
            "image": "nvcr.io/nvidia/tritonserver",
            "defaultImageVersion": "21.09-py3",
            "supportedFrameworks": [
              "tensorrt",
              "tensorflow",
              "onnx",
              "pytorch"
            ],
            "multiModelServer": true
        },
        "pmml": {
            "image": "kserve/pmmlserver",
            "defaultImageVersion": "latest",
            "supportedFrameworks": [
              "pmml"
            ],
            "multiModelServer": false
        },
        "lightgbm": {
            "image": "kserve/lgbserver",
            "defaultImageVersion": "latest",
            "supportedFrameworks": [
              "lightgbm"
            ],
            "multiModelServer": false
        },
        "paddle": {
            "image": "kserve/paddleserver",
            "defaultImageVersion": "latest",
            "supportedFrameworks": [
              "paddle"
            ],
            "multiModelServer": false
        }
    }
  router: |-
    {
        "image" : "kserve/router:v0.9.0",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1"
    }
  storageInitializer: |-
    {
        "image" : "kserve/storage-initializer:v0.9.0",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1",
        "storageSpecSecretName": "storage-config"
    }
  transformers: |-
    {
    }
binaryData: {}

```
