### ISSUE TITLE
Descriptive & explicit canary manifests

### ISSUE THREAD

**Issue by SebastianScherer88** [kserve/kserve#2649]
/kind feature

**Describe the solution you'd like**
Currently canary deployments are done by updating the inference service manifest with a traffic percentage entry. The re-deployment of the changed manifest creates a new "most recent" revision, and traffic is then split accordingly between that new revision and the previous one. however, that state is not expressed in the manifest, which only hold info on the new model version but not the old one. that makes it unsuitable for e2e GitOps, as the manifest in the config repository does not give a complete view of that model's state(s).

Is there anything planned to make this more explicit to bridge that gap? Simply declaring all version of the model you want live at the same time seems a lot more intuitive anyway rather than just listing the most recent one and having to investigate the previous one separately.

**Anything else you would like to add:**
[Canary deployment manifests in Seldon Core are explicit](https://docs.seldon.io/projects/seldon-core/en/latest/examples/istio_canary.html), so something like this would be nice

**Comment by yuzisun** [comment]
@SebastianScherer88 You can achieve the same via KServe InferenceGraph which supports multiple branches of a service.

https://github.com/kserve/kserve/blob/master/docs/samples/graph/splitter.yaml

**Comment by SebastianScherer88** [comment]
thanks @yuzisun , that looks really useful! I would assume that updating that manifest's traffic ratio fields would not impact (i.e. update) the individual inferenceservices but purely be a change the traffic routing configurations at the istio level?

**Comment by yuzisun** [comment]
> thanks @yuzisun , that looks really useful! I would assume that updating that manifest's traffic ratio fields would not impact (i.e. update) the individual inferenceservices but purely be a change the traffic routing configurations at the istio level?

Correct, InferenceGraph is primarily a router and can only impact the traffic routing.

**Comment by SebastianScherer88** [comment]
@yuzisun i've tried it out and all is well, however i have one question: i'm using torchserve in a custom container, meaning the actual prediction endpoints is based on the model name, which is specified at the `mar` creation stage, like so:

`.../v1/models/{mar_model_name}:predict`

this is [standard torchserve behaviour as per the docs](https://pytorch.org/serve/inference_api.html#kserve-inference-api).

i have also noticed that the inferencegraph builds the url/path that it routes to based on the name of the individual inferenceservices in the inferencegraph yaml. i.e., in the example you linked to the predict endpoint paths being inferred by the inferencegraph would be something like

-  `.../v1/models/xgboost-iris:predict`
- `.../v1/models/sklearn-iris:predict`

this seems to create a dependency between 
- the name given to the inferenceservice, and 
- the name of the model when building the mar file

i.e. they have to be one and the same. is there any way to configure the splitter (or inferencegraph more generally) and specify the prediction endpoint path it routes too, or is that always inferred from the inferencegraph manifest's inferenceservice names?

**Comment by yuzisun** [comment]
@SebastianScherer88 there is the `serviceUrl` field you can directly specify on the inference graph
```yaml
apiVersion: serving.kserve.io/v1alpha1
kind: InferenceGraph
metadata:
  name: splitter-model
spec:
  nodes:
    root:
      routerType: Splitter
      steps:
        - serviceUrl: .../v1/models/sklearn-iris:predict
          weight: 20
        - serviceUrl: .../v1/models/xgboost-iris:predict
          weight: 80
```

**Comment by SebastianScherer88** [comment]
thats perfect, thanks! i will try this out tomorrow

**Comment by SebastianScherer88** [comment]
hiya, so an update on the above: while referencing the inferenceservices using the `servicename` field works as expected, it looks like the `serviceUrl` values dont get resolved properly. 

here's an example splitter type manifest (i've also tried the switch type with same results) that _works_:

```
apiVersion: serving.kserve.io/v1alpha1
kind: InferenceGraph
metadata:
  name: sentiment-splitter
  namespace: kserve-test
spec:
  nodes:
    root:
      routerType: Splitter
      steps:
        - serviceName: sentiment-test # name of the inferenceservice
          weight: 50
        - serviceName: sentiment-full # name of the inferenceservice
          weight: 50
```

And here's the equivalent url version that doesnt work:

```
apiVersion: serving.kserve.io/v1alpha1
kind: InferenceGraph
metadata:
  name: sentiment-splitter
  namespace: kserve-test
spec:
  nodes:
    root:
      routerType: Splitter
      steps:
        - serviceUrl: http://sentiment-test.kserve-test.example.com/v1/models/sentiment-test:predict
          weight: 50
        - serviceUrl: http://sentiment-full.kserve-test.example.com/v1/models/sentiment-full:predict
          weight: 50
```

error i'm getting when pinging the second inference graph:

```
curl -v \
>     -H "Host: ${SERVICE_HOSTNAME}" \
>     -H "Content-Type: application/json" \
>     -d '{"model-version":"full","instances": [{"content": "Some text document. More than one sentence is possible","entities": [{"test":"dummy value"}]}]}' \
>     http://${INGRESS_HOST}:${INGRESS_PORT}
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST / HTTP/1.1
> Host: sentiment-switch.kserve-test.example.com
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 158
>
* upload completely sent off: 158 out of 158 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-length: 228
< content-type: text/plain; charset=utf-8
< date: Mon, 06 Feb 2023 13:01:35 GMT
< x-envoy-upstream-service-time: 9
< server: istio-envoy
<
* Connection #0 to host localhost left intact
Failed to process request: Post "http://sentiment-full.kserve-test.example.com/v1/models/sentiment-full:predict": dial tcp: lookup sentiment-full.kserve-test.example.com on 10.100.0.10:53: no such host
```

relevant are inferenceservices are ready:

```
$ kubectl get isvc -n kserve-test
NAME                      URL                                                      READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION                               AGE
sentiment-full   http://sentiment-full.kserve-test.example.com   True           100                              sentiment-full-predictor-default-00001   74m
sentiment-test   http://sentiment-test.kserve-test.example.com   True           100                              sentiment-test-predictor-default-00001   74m
```

Checking the inferenceservice pod logs confirms that this request doesnt make it to the pod, i.e. the error is at the routing stage and lies with the inference graph.

is the inferenceservice `url` attribute the value that i should be using in the inferencegraph manifest?
