### ISSUE TITLE
Inference Logger broken with Triton backend

### ISSUE THREAD

**Issue by cakeislife100** [kserve/kserve#2672]
/kind bug

**What steps did you take and what happened:**
I tried deploying the example Triton [torchscript-cifar model](https://github.com/kserve/website/blob/main/docs/modelserving/v1beta1/triton/torchscript/torchscript.yaml) with logging enabled as per [these instructions](https://kserve.github.io/website/0.9/modelserving/logger/logger/#create-an-inferenceservice-with-logger).

When making a request to the model, it returns a strange-looking unicode string (see screenshot).
<img width="1420" alt="Screen Shot 2023-02-02 at 12 48 21 PM" src="https://user-images.githubusercontent.com/94597774/216446184-41121851-bf04-4a19-9f2b-682fead5a1ed.png">

Evidence pointing to this being an isolated Triton issue:
- If I deploy the same model *without* the logger, the model returns the expected output.
- If I deploy the [example Iris model ](https://kserve.github.io/website/modelserving/v1beta1/sklearn/v2/#deploy-with-inferenceservice)(which uses the sklearn backend) *with* the logger, it also works fine.

**What did you expect to happen:**

I expect making a request to the model to return the same output with or without logging enabled using the Triton backend.

**What's the InferenceService yaml:**

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "torchscript-cifar-logger"
  namespace: "kubeflow-ml"
spec:
  predictor:
    logger:
      mode: all
      url: http://message-dumper.kubeflow-ml.svc.cluster.local/
    triton:
      storageUri: "gs://kfserving-examples/models/torchscript"
      runtimeVersion: 21.08-py3
      env:
      - name: OMP_NUM_THREADS
        value: "1"
```

**Anything else you would like to add:**
The example IRIS yaml that works is:
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-irisv2"
  namespace: "kubeflow-ml"
spec:
  predictor:
    logger:
      mode: all
      url: http://message-dumper.kubeflow-ml.svc.cluster.local/
    sklearn:
      protocolVersion: "v2"
      storageUri: "gs://seldon-models/sklearn/iris"
```

**Environment:**

- Istio Version: 
- Knative Version: 0.23.3
- KServe Version: 0.7.0
- Kubeflow version: 1.5
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): 1.21
- OS (e.g. from `/etc/os-release`):
