### ISSUE TITLE
Custom model issue on kserve v0.10

### ISSUE THREAD

**Issue by VAveryanov8** [kserve/kserve#2690]
/kind bug

**What steps did you take and what happened:**
Hi! We've upgraded our kserve cluster from 0.9 to 0.10 and updated python kserve lib from 0.9 to 0.10. After that our custom model image couldn't start because of the below error:
`RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the ‘spawn’ start method`
After explicitly setting 'spawn' method, image starts, but throws following error on every request to `/v1/models/custom-model:predict`:
`AttributeError: Can’t pickle local object ‘request_response.<locals>.app`

**What did you expect to happen:**
We've expected that our model continue to work on kserve v0.10 the same way as it worked on v0.9

**What's the InferenceService yaml:**
```
apiVersion: "serving.kserve.io/v1beta1"
kind: InferenceService
metadata:
  name: avatar
  annotations:
....
  labels:
   ...
spec:
  predictor:
    containerConcurrency: 1
    timeout: 3600 # 60 min
    minReplicas: 0
    maxReplicas: 5
    volumes:
    - name: avatar-bucket-key
      secret:
        secretName: avatar-bucket-key
    containers:
      - name: custom-avatar
        image: ***
        volumeMounts:
        - name: avatar-bucket-key
          mountPath: /var/secrets/google
        env:
...
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 10
            memory: 32Gi
          requests:
            nvidia.com/gpu: 1
            cpu: 2
            memory: 16Gi
```

**Anything else you would like to add:**
I did a little bit of investigation, so I think below findings might help:
1. Accordingly to release notes of kserve v0.10, python lib start leveraging multiprocessing
2. pytorch: Multiprocessing in CUDA runtime doesn't work with 'fork' method -https://pytorch.org/docs/stable/notes/multiprocessing.html#cuda-in-multiprocessing 
3. After changing multiprocessing start method to 'spawn' our custom model images was able to start, but could not handle the requests because of the error: `AttributeError: Can’t pickle local object ‘request_response.<locals>.app`
4. [As I see from source code](https://github.com/kserve/kserve/blob/v0.10.0/python/kserve/kserve/protocol/rest/server.py#L135), kserve uses uvicorn and it looks like uvicorn require different style of server initialisation when used together with multiprocessing in 'spawn' mode - https://www.uvicorn.org/deployment/#running-programmatically

**Environment:**
- Python: 3.8
- Knative Version: 1.9
- KServe Version:  0.10
- Cloud Environment:[gcp gke]
- Kubernetes version: (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.5-gke.1500", GitCommit:"341714971fd5f72a615e49c935c0e4d19e2599e0", GitTreeState:"clean", BuildDate:"2022-12-28T09:36:24Z", GoVersion:"go1.19.4 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): Image based on nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04

Thanks in advance!
