### ISSUE TITLE
There is an additional word after pytorch/torchserve-kfs:0.6.0-gpu 

### ISSUE THREAD

**Issue by life-learner1** [kserve/kserve#2708]
/kind bug

What steps did you take and what happened:
[A clear and concise description of what the bug is.]

kserve output 'pytorch/torchserve-kfs:0.6.0-gpu-gpu' instead of 'pytorch/torchserve-kfs:0.6.0-gpu', after I rollback to kserve0.9.0, it recovers.

source yaml file 
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: intention-and-similar
spec:
  predictor:
    model:
      image: pytorch/torchserve-kfs:0.6.0-gpu
      modelFormat:
        name: pytorch
      name: ''
      resources:
        limits:
          memory: 10Gi
          nvidia.com/gpu: '1'
        requests:
          memory: 9Gi
          nvidia.com/gpu: '1'
      runtime: kserve-torchserve
      storageUri: pvc://ai-pv-claim/intention-and-similar
```

log in kserve-controller-manager-79ccd97ff-rtjhn pod:
```log
{"level":"info","ts":1676883977.3338618,"logger":"PredictorReconciler","msg":"Resolved container","container":"&Container{Name:kserve-container,Image:pytorch/torchserve-kfs:0.6.0-gpu-gpu,Command:[],Args:[torchserve --start --model-store=/mnt/models/model-store --ts-config=/mnt/models/config/config.properties],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{EnvVar{Name:TS_SERVICE_ENVELOPE,Value:kserve,ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{cpu: {{1 0} {<nil>} 1 DecimalSI},memory: {{10737418240 0} {<nil>} 10Gi BinarySI},nvidia.com/gpu: {{1 0} {<nil>} 1 DecimalSI},},Requests:ResourceList{cpu: {{1 0} {<nil>} 1 DecimalSI},memory: {{9663676416 0} {<nil>} 9Gi BinarySI},nvidia.com/gpu: {{1 0} {<nil>} 1 DecimalSI},},},VolumeMounts:[]VolumeMount{},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:,ImagePullPolicy:,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,}","podSpec":{"containers":[{"name":"kserve-container","image":"pytorch/torchserve-kfs:0.6.0-gpu-gpu","args":["torchserve","--start","--model-store=/mnt/models/model-store","--ts-config=/mnt/models/config/config.properties"],"env":[{"name":"TS_SERVICE_ENVELOPE","value":"kserve"}],"resources":{"limits":{"cpu":"1","memory":"10Gi","nvidia.com/gpu":"1"},"requests":{"cpu":"1","memory":"9Gi","nvidia.com/gpu":"1"}}}],"serviceAccountName":"xiaowei-ai"}}
{"level":"info","ts":1676883977.3429856,"logger":"DeploymentReconciler","msg":"Deployment Updated","Diff":"  v1.DeploymentSpec{\n  \t... // 1 ignored field\n  \tSelector: &{MatchLabels: {\"app\": \"isvc.intention-and-similar-predictor-default\"}},\n  \tTemplate: v1.PodTemplateSpec{\n  \t\tObjectMeta: {Name: \"intention-and-similar-predictor-default\", Namespace: \"xiaowei-dev-default\", Labels: {\"app\": \"isvc.intention-and-similar-predictor-default\", \"component\": \"predictor\", \"serviceEnvelope\": \"kserve\", \"serving.kserve.io/inferenceservice\": \"intention-and-similar\"}, Annotations: {\"internal.serving.kserve.io/storage-initializer-sourceuri\": \"s3://xiaowei-ai-models/intention-and-similar_2022-11-03/\", \"kustomize.toolkit.fluxcd.io/reconcile\": \"disabled\", \"serving.kserve.io/deploymentMode\": \"RawDeployment\"}, ...},\n  \t\tSpec: v1.PodSpec{\n  \t\t\tVolumes:        nil,\n  \t\t\tInitContainers: nil,\n  \t\t\tContainers: []v1.Container{\n  \t\t\t\t{\n  \t\t\t\t\tName: \"kserve-container\",\n  \t\t\t\t\tImage: strings.Join({\n  \t\t\t\t\t\t\"pytorch/torchserve-kfs:0.6.0-gpu\",\n- \t\t\t\t\t\t\"-gpu\",\n  \t\t\t\t\t}, \"\"),\n  \t\t\t\t\tCommand: nil,\n  \t\t\t\t\tArgs:    {\"torchserve\", \"--start\", \"--model-store=/mnt/models/model-store\", \"--ts-config=/mnt/models/config/config.properties\"},\n  \t\t\t\t\t... // 18 identical fields\n  \t\t\t\t},\n  \t\t\t},\n  \t\t\tEphemeralContainers: nil,\n  \t\t\tRestartPolicy:       \"Always\",\n  \t\t\t... // 31 identical fields\n  \t\t},\n  \t},\n  \tStrategy:        {Type: \"RollingUpdate\", RollingUpdate: &{MaxUnavailable: &{Type: 1, StrVal: \"25%\"}, MaxSurge: &{Type: 1, StrVal: \"25%\"}}},\n  \tMinReadySeconds: 0,\n  \t... // 3 identical fields\n  }\n"}
{"l
```
 
What did you expect to happen:

What's the InferenceService yaml:
[To help us debug please run kubectl get isvc $name -n $namespace -oyaml and paste the output]

Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

Environment:

Istio Version: 1.13.5
Knative Version: None
KServe Version: v0.10.0
Kubeflow version:
Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
Minikube/Kind version:
Kubernetes version: (use kubectl version): v1.22.15-eks-fb459a0
OS (e.g. from /etc/os-release):
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
