### ISSUE TITLE
No support volcano 1.7  for kserve 0.8

### ISSUE THREAD

**Issue by 631068264** [kserve/kserve#2717]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

deploy kubeflow 1.6 (kserve release-0.8)  with volcano

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "volcano"
spec:
  predictor:
    schedulerName: volcano
    containers:
      - name: kserve-container
        image: xxx:8080/library/model/firesmoke:v1
        env:
          - name: MODEL_NAME
            value: volcano
        command:
          - python
          - -m
          - fire_smoke
        resources:
          limits:
            volcano.sh/gpu-memory: 2048
```

But get error
```
Events:
  Type     Reason         Age                    From                Message
  ----     ------         ----                   ----                -------
  Warning  InternalError  3m4s (x17 over 8m32s)  v1beta1Controllers  fails to reconcile predictor: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: must not set the field(s): spec.template.spec.schedulerName
```

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: [1.14.1](https://github.com/istio/istio/releases/tag/1.14.1)
- Knative Version:  [1.2.5](https://github.com/knative/serving/releases/tag/knative-v1.2.5)
- KServe Version:  [release-0.8](https://github.com/kserve/kserve/tree/8079f375cbcedc4d45a1b4aade2e2308ea6f9ae8/install/v0.8.0)
- Kubeflow version:  1.6.1
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):  1.22
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.2 LTS
