### ISSUE TITLE
Support Direct VolumeMount for PVC in StorageInitializer

### ISSUE THREAD

**Issue by lizzzcai** [kserve/kserve#2737]
/kind feature

**Describe the solution you'd like**

When providing `pvc` in `storageUri` (see example below), provide option to directly mount the pvc to `/mnt/models` in the user container rather than `symlink` it to shared volume via storage initializer (init contianer).

```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-pvc"
spec:
  predictor:
    sklearn:
      storageUri: "pvc://${PVC_NAME}/model.joblib"
```

Storage initializer provides a unified layer to support different storage options in KServe, However it has some limitations like:
* not able to update the model artefact if it is a shared `ReadWriteMany` PV/PVC
* init container runs before the user container, so features like using data orchestration platform (usually a fuse sidecar) to `accelerate` the data access is hard to implement, find details [here](https://github.com/kserve/kserve/issues/2529).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

As KNative support [mounting pvc](https://knative.dev/docs/serving/configuration/feature-flags/#kubernetes-persistentvolumeclaim-pvc)(disabled by default), so it is possible to mount volume like [this](https://github.com/kserve/kserve/issues/2554). However, I would prefer to support it via `storageUri`.
