### ISSUE TITLE
Allow setting multiple domains on an inference service

### ISSUE THREAD

**Issue by cmaddalozzo** [kserve/kserve#2747]
/kind feature

**Describe the solution you'd like**
Currently KServe supports setting only a single external host for inference services. It would be useful if we could support multiple hosts.

We could enable this feature on a global level or on a per inference service basis.

#### Globally:
Add a section to the ingress config in the `inferenceservice-config` configmap that allows users to configure additional ingress domains. e.g.

```yaml
  ingress: |-
    {
        "ingressGateway" : "istio-system/ingress-gateway",
        "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
        "localGateway" : "istio-system/local-gateway",
        "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local",
        "ingressDomain"  : "example.com",
        "additionalIngressDomains": [
             "other-example.com" 
        ]
    }
```

#### Per inference service
A user can specify an "alias" hostname for the inference service. This will be used alongside the automatically generated domain.

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: test-model
spec:
  predictor:
    # predict definition...
  hostAliases:
    - test-model.other-example.com
```

For serverless mode these hosts will be added to the `VirtualService` that KServe creates. This means that only the canonical name of the inference service will have the alias domain attached. i.e. the predictor, explainer, and transformer specific hosts will not be created for the alias domains.
