### ISSUE TITLE
How to inject Configmap as Volume to InferenceService

### ISSUE THREAD

**Issue by gawsoftpl** [kserve/kserve#2749]
How to add ConfigMap values as a volume in kserve inference service?
Kserve v0.10

Example:
I have a config map with model settings. I would like to inject configmap as volume to knative container.
I received a error:

```
v1beta1Controllers  fails to reconcile predictor: admission webhook │
│  "validation.webhook.serving.knative.dev" denied the request: validation failed: volume with name "test" not moun │
│ ted: spec.template.spec.volumes[0].name 
```

```yaml
kind: ConfigMap
metadata:
  name: test
data:
    model-settings.json: |
      {
         "option_1": 1
      }
```

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: "InferenceService"
metadata:
  name: "model"
spec:
  predictor:
    volumes:
      - name: test
        configMap:
          name: test
    model:
      modelFormat:
        name: xgboost
      runtime: model1
      storageUri: "s3://models/model1/"
      env:
        - name: OMP_NUM_THREADS
          value: "1"
      volumeMounts:
         name: test
         mountPath: /mnt/models/model_1/model-settings.json
      ports:
        - containerPort: 8080
          protocol: TCP
          name: http1
```
