### ISSUE TITLE
kserve python library doesn't use environment variable KSERVE_LOGLEVEL

### ISSUE THREAD

**Issue by shahar3012** [kserve/kserve#2761]
/kind bug

**What steps did you take and what happened:**
Define environment variable `KSERVE_LOGLEVEL` in custom model server as `DEBUG`.
kserve only logs `INFO` and above.

**What did you expect to happen:**
kserve should log `DEBUG` and above.

**What's the InferenceService yaml:**
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: inference-service
spec:
  predictor:
    containers:
      - image: inferenceservice-image-tag
        env:
          - name: KSERVE_LOGLEVEL
            value: 'DEBUG'
```

**Anything else you would like to add:**
kserve internal code doesn't use `KSERVE_LOGLEVEL` (as defined in `kserve.constants`).
A small change to the [following line of code](https://github.com/kserve/kserve/blob/master/python/kserve/kserve/model_server.py#L63) can add support for this environment variable:

```python
logging.basicConfig(level=kserve.constants.KSERVE_LOGLEVEL)
```
