### ISSUE TITLE
Using custom mlserver runtime in inference graph

### ISSUE THREAD

**Issue by saeid93** [kserve/kserve#2767]
Is it possible to use a model built with [custom mlserver runtime](https://mlserver.readthedocs.io/en/latest/examples/custom/README.html) in [Kserve inference graph](https://kserve.github.io/website/0.9/modelserving/inference_graph/)?
I'm planning to re-build to graphs I have in this [repo](https://github.com/saeid93/seldon-inference-pipelines) in kserve inference graph instead of Seldon inference graph, as I have used MLServer as my model backend I'm hoping that I can do it with minimum change if they can be used out of the box in kserve.

**Comment by rachitchauhan43** [comment]
You should be able to. `mlserver` is a supported ServingRuntime. See here: https://github.com/kserve/kserve/blob/master/install/v0.10.1/kserve-runtimes.yaml#L31-L72

Essentially with KServe IG , the router acts as a reverse proxy. You can always set the `serviceUrl` in the Inference Step that your model container exposes. See example:
```
apiVersion: serving.kserve.io/v1alpha1
kind: InferenceGraph
metadata:
  name: model-switch
  namespace: kserve-test
spec:
  nodes:
    root:
      routerType: Switch
      steps:
      - condition: '[@this].#(country_code==IN)'
        serviceUrl: http://qbo-in-predictor-default.kserve-test.svc.cluster.local/v1/models/qbo-in:predict
      - condition: '[@this].#(country_code==US)'
        serviceUrl: http://qbo-us-predictor-default.kserve-test.svc.cluster.local/v1/models/qbo-us:predict
```

See field `serviceUrl: http://qbo-us-predictor-default.kserve-test.svc.cluster.local/v1/models/qbo-us:predict`. So, if your model exposes such an endpoint, you can make it part of the the IG. IG router will make Post call to this endpoint.
