### ISSUE TITLE
MLflow modelserver crashing for exported tensorflow model artifacts 

### ISSUE THREAD

**Issue by PiePra** [kserve/kserve#2768]
/kind bug

**What steps did you take and what happened:**
When using the MLflow clusterservingruntime to serve a MLflow model exported from tensorflow the mlserver crashes with 
`mlflow.exceptions.MlflowException: Could not find an "MLmodel" configuration file at "/mnt/models/data" `.
Allthough the Data Structure seems correct with the MLmodel file located at "/mnt/models" but for some reason mlserver is looking for it in the data subdirectory. 

**What did you expect to happen:**
mlserver picking up the MLmodel config file at "/mnt/models"

**What's the InferenceService yaml:**
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "iris-classifier"
spec:
  predictor:
    serviceAccountName: sa-s3
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "s3://mlflow/<mlflow_model_uri>/artifacts/model"
```

**Anything else you would like to add:**
Approach worked for different formats (sklearn, xgboost)

**Environment:**

- Istio Version: 
- Knative Version: v1.3.2
- KServe Version: v0.9.0
- Kubeflow version:
- Cloud Environment:[k8s_istio]
- Minikube/Kind version:
- Kubernetes version: 1.21.6
- OS (e.g. from `/etc/os-release`):
