### ISSUE TITLE
No matches for kind InferenceService

### ISSUE THREAD

**Issue by dunefro** [kserve/kserve#2825]
/kind bug

**What steps did you take and what happened:**
I was trying to follow the [Getting-started](https://kserve.github.io/website/0.10/get_started/#before-you-begin) documentation. 
1. Installed `kind`
2. Installed kubectl
3. Installed the KServe "Quickstart" environment by the following command
```
curl -s "https://raw.githubusercontent.com/kserve/kserve/release-0.10/hack/quick_install.sh" | bash
```
In the next step created a namespace called `kserve-test` and then tried to create an `InferenceService` via the following command
```
kubectl apply -n kserve-test -f - <<EOF
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
EOF
```
I got the below error
```
error: resource mapping not found for name: "sklearn-iris" namespace: "" from "inferenceservice.yaml": no matches for kind "InferenceService" in version "serving.kserve.io/v1beta1"
ensure CRDs are installed first
```

**What did you expect to happen:**
1. Expected a resource with kind `InferenceService`
2. I think `namespace` is also missing from the resource spec.

**What's the InferenceService yaml:**
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: `1.15.0`
- Knative Version:
- KServe Version: 
- Kubeflow version: `1.26.3`
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]: `local`
- Minikube/Kind version: `v0.18.0`
- Kubernetes version: (use `kubectl version`): `1.26.3`
- OS (e.g. from `/etc/os-release`):
