### ISSUE TITLE
Inferenceservice address.url displays wrong url in raw deployment

### ISSUE THREAD

**Issue by sivanantha321** [kserve/kserve#2829]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Inference service status.address.url points to http://\<isvc-name\>.\<namespace\>.svc.cluster.local which is invalid.

**What did you expect to happen:**
It should point to either http://\<isvc-name\>-predictor.\<namespace\>.svc.cluster.local or http://\<isvc-name\>-transformer.\<namespace\>.svc.cluster.local

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
```yaml
status:
  address:
    url: http://mnist.default.svc.cluster.local/
  components:
    predictor:
      latestCreatedRevision: '1'
      url: http://mnist-predictor-default.example.com/
    transformer:
      latestCreatedRevision: '1'
      url: http://mnist-transformer-default.example.com/
  conditions:
    - lastTransitionTime: '2023-04-18T05:54:19Z'
      status: 'True'
      type: IngressReady
    - lastTransitionTime: '2023-04-18T05:54:11Z'
      status: 'True'
      type: PredictorReady
    - lastTransitionTime: '2023-04-18T05:54:19Z'
      status: 'True'
      type: Ready
    - lastTransitionTime: '2023-04-18T05:54:19Z'
      severity: Info
      status: 'True'
      type: TransformerReady
  modelStatus:
    copies:
      failedCopies: 0
      totalCopies: 1
    states:
      activeModelState: Loaded
      targetModelState: Loaded
    transitionStatus: UpToDate
  observedGeneration: 1
  url: http://mnist-default.example.com/
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.16.2
- Knative Version: 1.9.0
- KServe Version: master
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): 1.24.12
- OS (e.g. from `/etc/os-release`):
