### ISSUE TITLE
KNative returns unexpected EOF

### ISSUE THREAD

**Issue by SeibertronSS** [kserve/kserve#2833]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I deployed a 20B GPT-2 model via KServe. When I access it through istio-ingressgateway, knative queue-proxy returns 502 with unexpected EOF. This is the log of queue-proxy
```
{
     "severity": "ERROR",
     "timestamp": "2023-04-19T07:01:57.902205349Z",
     "logger": "queueproxy",
     "caller": "network/error_handler.go:33",
     "message": "error reverse proxying request; sockstat: sockets: used 83\nTCP: inuse 40 orphan 2 tw 17 alloc 513 mem 1663\nUDP: inuse 0 mem 3931\nUDPLITE: inuse 0\nRAW: inuse 0\nFRAG: inuse 0 memory 0\n",
     "commit": "6ec4509",
     "knative.dev/key": "default/triton-mms-1-predictor-default-00001",
     "knative.dev/pod": "triton-mms-1-predictor-default-00001-deployment-64b6b8d4445nmkc",
     "error": "unexpected EOF",
     "stacktrace": "knative.dev/pkg/network.ErrorHandler.func1\n\tknative.dev/pkg@v0.0.0-20220412134708-e325df66cb51/network/error_handler.go:33\nnet/http/httputil.(*ReverseProxy ).ServeHTTP\n\tnet/http/httputil/reverseproxy.go:300\nknative.dev/serving/pkg/queue.(*appRequestMetricsHandler).ServeHTTP\n\tknative.dev/serving/pkg/queue/request_metric.go :199\nknative.dev/serving/pkg/queue.ProxyHandler.func1\n\tknative.dev/serving/pkg/queue/handler.go:75\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server .go:2047\nknative.dev/serving/pkg/queue.ForwardedShimHandler.func1\n\tknative.dev/serving/pkg/queue/forwarded_shim.go:54\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http /server.go:2047\nknative.dev/serving/pkg/http/handler.(*timeoutHandler).ServeHTTP.func4\n\tknative.dev/serving/pkg/http/handler/timeout.go:117",
}
```

**What did you expect to happen:**
The queue-proxy can return normally

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "triton-mms-1"
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
spec:
  predictor:
    timeout: 1  
    volumes:  
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: "2048Mi"
    triton:
      ports:
        - containerPort: 8000 
          name: h2c 
          protocol: TCP
      storageUri: pvc://test-pvc/gpt/gpt-medium  
      image: xxx/tritonserver:22.03-py3-ft  # Triton image compiled by myself
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "tritonserver  --model-repository=/mnt/models --log-verbose=3 --log-info=1 --log-warning=1 --log-error=1"]  
      # args:
      # - --allow-sagemaker=false
      env:
      - name: OMP_NUM_THREADS
        value: "1"
      volumeMounts:
      - mountPath: /dev/shm
        name: dshm
        readOnly: false
      resources:
        limits:
          nvidia.com/gpu: 4
          memory: "10Gi"  
        requests:
          nvidia.com/gpu: 4
          memory: "10Gi"
```
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: v1.9
- Knative Version: v1.4.0
- KServe Version: 0.9.0-rc
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): 1.19.9
- OS (e.g. from `/etc/os-release`):
