### ISSUE TITLE
External DNS not configured by default in KServe in Kubeflow 1.7

### ISSUE THREAD

**Issue by surajkota** [kserve/kserve#2846]
/kind bug

**What steps did you take and what happened:**
In previous Kserve/Kubeflow versions, isvc had both internal and external url by default (external based on config-domain configmap from KNative serving namespace) and the VirtualService created for the isvc had 2 gateways configured by default - `knative-serving/knative-local-gateway` and `kubeflow/kubeflow-gateway`.

In Kubeflow 1.7, if you create an isvc, the virtualservice only has `knative-local-gateway` configured and hence isvc gets only internal URL. To get external URL and configure it with `kubeflow-gateway`, I had to explicitly update the config-domain configmap by running `kubectl patch cm config-domain --patch '{"data":{"example.com":""}}' -n knative-serving`.

I checked the inference-service configmap to make sure `kubeflow/kubeflow-gateway` is configured as ingressGateway.

**What did you expect to happen:**
Both cluster internal and external URLs to be available by default

**Steps to reproduce**
Install Kubeflow 1.7 and run through https://kserve.github.io/website/0.8/get_started/first_isvc/#run-your-first-inferenceservice.

When you get status https://kserve.github.io/website/0.8/get_started/first_isvc/#3-check-inferenceservice-status, you will see `sklearn-iris.kubeflow-user-example-com.svc.cluster.local` instead of `http://sklearn-iris.kubeflow-user-example-com.example.com`. Describe the VirtualService created for the isvc to confirm the above findings

```
kubectl get inferenceservices sklearn-iris -n kserve-test
NAME           URL                                                 READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION                    AGE
sklearn-iris   http://sklearn-iris.kubeflow-user-example-com.svc.cluster.local        True           100                              sklearn-iris-predictor-default-47q2g   7d23h
```

```
kubectl get vs sklearn-iris -n kubeflow-user-example-com
NAME                                      GATEWAYS                                                                HOSTS                                                                                                                                                                                                                                                                                 AGE
sklearn-iris                             ["knative-serving/knative-local-gateway"]   ["sklearn-iris.kubeflow-user-example-com.svc.cluster.local"]
```

**Anything else you would like to add:**
I notice that `inferenceservice-config` configmap has additional configurations for ingress but they are not used. e.g. domain template still comes up as `name.namespace.ingressdomain` and I can override config-domain cm in knative-serving for the ingress domain. Clearly, knative configuration is taking precedence. Is there a flag need to set for `inferenceservice-config` to be used? Is there any documentation around this?

```
ingress: |-
    {
      "ingressGateway": "kubeflow/kubeflow-gateway",
      "ingressService": "istio-ingressgateway.istio-system.svc.cluster.local",
      "localGateway": "knative-serving/knative-local-gateway",
      "localGatewayService": "knative-local-gateway.istio-system.svc.cluster.local",
      "ingressDomain": "example.com",
      "ingressClassName": "istio",
      "domainTemplate": "{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}",
      "urlScheme": "http",
      "disableIstioVirtualHost": false
    }
```

Thanks

**Environment:**

- Istio Version: 1.16.0
- Knative Version: 1.8.1
- KServe Version: 0.10.0
- Kubeflow version: 1.7
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): 1.23
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@andyi2it i think we have the documentation somewhere for this ?

**Comment by yuzisun** [comment]
We have added the warning here on kserve website 
https://kserve.github.io/website/0.10/admin/serverless/serverless/#1-install-knative-serving

**Comment by pashtet04** [comment]
Anything it is not clear to me how to change `domainTemplate` in `config-network` ConfigMap
ConfigMap `config-domain` configured properly and domain is changed but 

```
data:
  custom.domain.com: |
    custom.domain.com: |
```

I've configured, but no changes. Model endpoint is still in `{{.Name}}.{{.Namespace}}.{{.Domain}}` format:
```
data:
  custom.domain.com: |
    ingress-class: "istio.ingress.networking.knative.dev"
    certificate-class: "cert-manager.certificate.networking.knative.dev"
    namespace-wildcard-cert-selector: ""
    domain-template: "{{.Name}}.{{.Domain}}"
    tag-template: "{{.Tag}}-{{.Name}}"
    auto-tls: "Disabled"
    http-protocol: "Enabled"
    rollout-duration: "0"
    autocreate-cluster-domain-claims: "false"
    enable-mesh-pod-addressability: "false"
    mesh-compatibility-mode: "auto"
    default-external-scheme: "http"
    internal-encryption: "false"
```
