### ISSUE TITLE
How can i add 'x.x.x.x hostname' to ksvc pod's /etc/hosts

### ISSUE THREAD

**Issue by alekseyolg** [kserve/kserve#2859]
In #9415 stated the possibility of using hostAliases Also, in the documentation - https://knative.dev/docs/serving/configuration/feature-flags/#kubernetes-node-affinity this option is indicated. But when i try to use:
 
 ```
 apiVersion: serving.kserve.io/v1beta1
 kind: InferenceService
 metadata:
   name: custom-model
   namespace: kserve-test
 spec:
   template:
     spec:
       hostAliases:
       - ip: "10.0.0.10"
         hostnames:
         - "proxy1.dc"
   predictor:
     containers:
       - name: kserve-container
         image: alekseyolg/kserve-custom-model@sha256:5b21247eccdc7810bae865c7fee66663b37e00ca1947a2c187f714d8f58cf408
         imagePullPolicy: IfNotPresent
 ```
 
 I get an error
 
 ```
 error: error validating "custom-model.yaml": error validating data: ValidationError(InferenceService.spec): unknown field "template" in io.kserve.serving.v1beta1.InferenceService.spec; if you choose to ignore these errors, turn validation off with --validate=false
 ```
I already tried asking this question in https://github.com/knative/serving/issues/13921
But following the suggested advice, I get the error:

`Warning  InternalError  21s (x15 over 103s)  v1beta1Controllers  fails to reconcile predictor: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: must not set the field(s): spec.template.spec.hostAliases
`
Thanks for any help!

**Comment by sivanantha321** [comment]
@alekseyolg Have you enabled the hostaliases feature in `config-features` configmap in the knative-serving namespace ? If not you can enable it by adding `kubernetes.podspec-hostaliases: "enabled"` key under the `data` field.  Here is an example yaml for isvc.
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-model
spec:
  predictor:
    hostAliases:
      - ip: "127.0.0.1"
        hostnames:
          - "foo.local"
          - "bar.local"
      - ip: "10.1.2.3"
        hostnames:
        - "foo.remote"
        - "bar.remote"
    containers:
      - name: kserve-container
        image: foo/custom-model:latest
        args:
          - --model_name=custom-model
          - --workers=1
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
```
