### ISSUE TITLE
custom model predictor is not working

### ISSUE THREAD

**Issue by ssilb4** [kserve/kserve#2868]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I am going to run custom model predictor ([docs](https://kserve.github.io/website/0.10/modelserving/v1beta1/custom/custom_model/#deploy-locally-and-test))
When I run apply custom yaml, It occurs error.
```
kubectl apply -f custom.yaml

error: resource mapping not found for name: "custom-model" namespace: "" from "custom.yaml": no matches for kind "InferenceService" in version "serving.kserve.io/v1beta1"
ensure CRDs are installed first
```

So I searched this [docs](https://kserve.github.io/website/0.10/reference/api/#serving.kserve.io/v1beta1.PredictorSpec)
In this docs, there is no predictor > container. so I changed like this
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-model
spec:
  predictor:
    PodSpec:
      containers:
        - name: kserve-container
          image: name/custom-model:v1
```
but It occur same error.

what is wrong? and what documents is right?

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: 0.10
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
