### ISSUE TITLE
Make `status.address.url` consistent across installations

### ISSUE THREAD

**Issue by sivanantha321** [kserve/kserve#2874]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
The status.address.url is inconsistent between raw deployment and serverless deployment. For example the raw deployment status.address.url points to http://sklearn-iris.default.svc.cluster.local while the serverless deployment url points to http://sklearn-iris.default.svc.cluster.local/v2/models/sklearn-irisv2/infer. Because of this we have to create a two different version of yaml when we reference `inferenceservice`.

For serverless deployment
```yaml
apiVersion: [sources.knative.dev/v1beta1](http://sources.knative.dev/v1beta1)
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  # Broker URL. Replace this with the URLs for your kafka cluster,
  # which is in the format of my-cluster-kafka-bootstrap.my-kafka-namespace:9092.
  bootstrapServers:
    - kafka-headless.default.svc.cluster.local:9092
  topics:
    - iris
  sink:
    ref:
      apiVersion: [serving.kserve.io/v1beta1](http://serving.kserve.io/v1beta1)
      kind: InferenceService
      name: sklearn-iris
```
For raw deployment
```yaml
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  # Broker URL. Replace this with the URLs for your kafka cluster,
  # which is in the format of my-cluster-kafka-bootstrap.my-kafka-namespace:9092.
  bootstrapServers:
    - kafka-headless.default.svc.cluster.local:9092
  topics:
    - iris
  sink:
    ref:
      apiVersion: serving.kserve.io/v1beta1
      kind: InferenceService
      name: sklearn-iris
    uri: /v2/models/sklearn-irisv2/infer
```
**What did you expect to happen:**
The status.address.url should be consistent across both installations.  It makes more sense to use this format http://sklearn-irisv2.default.svc.cluster.local , because user can have more control over which endpoint to use by setting the `uri` field in the yaml

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
