### ISSUE TITLE
Enable overriding the storage initializer image for specific protocol(s)

### ISSUE THREAD

**Issue by cmaddalozzo** [kserve/kserve#2885]
/kind feature

Currently KServe only supports [a single storage initializer configuration](https://github.com/kserve/kserve/blob/master/config/configmap/inferenceservice.yaml#L18). We would like administrators to be able to specify which container images handle which schemes/protocols.  This would enable cluster administrators to add support for new, non-standard, or unsupported schemes without needing to override the default image.

**Describe the solution you'd like**
We can update the config to look as follows:

```yaml
  storageInitializer: |-
    {
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1",
        "storageSpecSecretName": "storage-config",
        "enableDirectPvcVolumeMount": false,
        "defaultImage": "kserve/storage-initializer:latest"
        "imageOverrides": [
            {
               "image": "example/ftp-storage-initializer:latest",
               "schemes": ["ftp"]
            }
        ]
    }
``` 

The pod injector will inspect the `storageUri` and set the storage initializer image based on the URI scheme. If no override is found for the detected scheme the `defaultImage` will be used.

**Limitations**

1. This implementation would not allow administrators to provide per-image configuration like requests/limits.
2. The storage initializer currently inspects the full URI to determine which strategy to use for downloading. This implementation only allows images to be selected based on scheme, not the entire URI.
