### ISSUE TITLE
How to access isvc via gRPC

### ISSUE THREAD

**Issue by SeibertronSS** [kserve/kserve#2930]
/kind bug

**What steps did you take and what happened:**
I have deployed an LLM using Triton + KServe, but I cannot call Triton's gRPC interface through Istio. Istio shows 
```
[2023-05-22T12:08:15.910Z] "- - HTTP/2" 0 DPE http2.invalid.header.field - "-" 0 0 0 - "-" "-" "-" "- " "-" - - 11.80.x.xx:8080 11.71.x.xx:15780 - -
```
I use Triton python client to access isvc, my code is as follows
```
import asyncio
import os

import gpt_token_encoder as encoder
import numpy as np
import tritonclient
import tritonclient.grpc.aio as grpcclient
import tritonclient.http as httpclient
from tritonclient.utils import np_to_triton_dtype

OUTPUT_LEN = 100

def prepare_tensor(name, input, protocol):
    client_util = httpclient if protocol == "http" else grpcclient
    t = client_util.InferInput(
        name, input.shape, np_to_triton_dtype(input.dtype))
    t.set_data_from_numpy(input)
    return t



async def async_stream_yield(
    values,
    batch_size,
    # sequence_id,
    # model_name,
    # model_version,
):
    count = 1

    for value in values:
        input0 = [[value]]
        bad_words_list = np.array([[""]], dtype=object)
        stop_words_list = np.array([[""]], dtype=object)
        input0_data = np.array(input0).astype(object)
        output0_len = np.ones_like(input0).astype(np.uint32) * OUTPUT_LEN
        runtime_top_k = (1 * np.ones([input0_data.shape[0], 1])).astype(np.uint32)
        runtime_top_p = 0.0 * np.ones([input0_data.shape[0], 1]).astype(np.float32)
        beam_search_diversity_rate = 0.0 * np.ones([input0_data.shape[0], 1]).astype(np.float32)
        temperature = 1.0 * np.ones([input0_data.shape[0], 1]).astype(np.float32)
        len_penalty = 1.0 * np.ones([input0_data.shape[0], 1]).astype(np.float32)
        repetition_penalty = 1.0 * np.ones([input0_data.shape[0], 1]).astype(np.float32)
        random_seed = np.array(range(0, 1)).astype(np.uint64).reshape([-1, 1])
        is_return_log_probs = True * np.ones([input0_data.shape[0], 1]).astype(bool)
        beam_width = (1 * np.ones([input0_data.shape[0], 1])).astype(np.uint32)
        start_ids = 0 * np.ones([input0_data.shape[0], 1]).astype(np.uint32)
        end_ids = 0 * np.ones([input0_data.shape[0], 1]).astype(np.uint32)
        # prompt_learning_task_name_ids = np.zeros([1, 1]).astype(np.uint32)
        top_p_decay = np.array([[1.0]]).astype(np.float32)
        top_p_min = np.array([[0.5]]).astype(np.float32)
        top_p_reset_ids = np.array([[2]]).astype(np.uint32)

        inputs = [
            prepare_tensor("INPUT_0", input0_data, "grpc"),
            prepare_tensor("INPUT_1", output0_len, "grpc"),
            prepare_tensor("INPUT_2", bad_words_list, "grpc"),
            prepare_tensor("INPUT_3", stop_words_list, "grpc"),
            prepare_tensor("runtime_top_k", runtime_top_k, "grpc"),
            prepare_tensor("runtime_top_p", runtime_top_p, "grpc"),
            prepare_tensor("beam_search_diversity_rate", beam_search_diversity_rate, "grpc"),
            prepare_tensor("temperature", temperature, "grpc"),
            prepare_tensor("len_penalty", len_penalty, "grpc"),
            prepare_tensor("repetition_penalty", repetition_penalty, "grpc"),
            prepare_tensor("random_seed", random_seed, "grpc"),
            prepare_tensor("is_return_log_probs", is_return_log_probs, "grpc"),
            prepare_tensor("beam_width", beam_width, "grpc"),
            prepare_tensor("start_id", start_ids, "grpc"),
            prepare_tensor("end_id", end_ids, "grpc"),

            prepare_tensor("top_p_decay", top_p_decay, "grpc"),
            prepare_tensor("top_p_min", top_p_min, "grpc"),
            prepare_tensor("top_p_reset_ids", top_p_reset_ids, "grpc"),


            # prepare_tensor("prompt_learning_task_name_ids", prompt_learning_task_name_ids, "grpc"),
        ]
        # Create the tensor for INPUT
        # input_ids = np.array(value, dtype=np.uint32)
        # input_lengths = np.array([[input_ids.shape[-1]]], dtype=np.uint32)
        # request_output_len = np.array([[1]], dtype=np.uint32)

        # value_data = np.full(
        #     shape=[batch_size, len(value)], fill_value=value, dtype=np.int32
        # )
        # print(input_ids.shape)  # [1,2]
        # print(input_lengths)

        # # Initialize the data
        # inputs = [
        #     prepare_tensor("input_ids", input_ids),
        #     prepare_tensor("input_lengths", input_lengths),
        #     prepare_tensor("request_output_len", request_output_len)
        #     # grpcclient.InferInput("input_ids", value_data.shape, "INT32"),
        # ]
    
        # outputs = []
        # outputs.append(grpcclient.InferRequestedOutput("OUTPUT"))

        # Issue the asynchronous sequence inference.
        yield {
            "model_name": "ensemble",
            "inputs": inputs,
            # "outputs": outputs,
            "sequence_start": (count == 1),
            "sequence_end": (count == len(values)),
        }

        count = count + 1

async def infer(inputs):
    async with grpcclient.InferenceServerClient(
        url="11.80.x.x:80/v2/models/ensemble/infer", verbose=False
    ) as triton_client:

        async def async_request_iterator():
            async for request in async_stream_yield(inputs, 1):
                yield request

        try:
            print("create client")
            response_iterator = triton_client.stream_infer(
                inputs_iterator=async_request_iterator(), stream_timeout=None,
            )
            print(response_iterator)
            print("wait response")
            async for response in response_iterator:
                result, error = response
                if error:
                    print(error)
                else:
                    output_ids = result.as_numpy("output_ids")
                    sequence_length = result.as_numpy("sequence_length")

                    # print(output_ids)
                    # print(sequence_length)
                    print("result", result.as_numpy("OUTPUT_0")[0].decode())

                    # out = output_ids[0][0][sequence_length - 1]
                    # print("recv:", tokenizer.decode(out))

        except asyncio.exceptions.CancelledError as error:
            import traceback
            traceback.print_exc()
            # print("triton error", error)


if __name__ == "__main__":
    # merge_file = "models/gpt2-merges.txt"
    # vocab_file = "models/gpt2-vocab.json"
    # tokenizer = encoder.get_encoder(vocab_file, merge_file)
    # print("build tokenizer")

    input_text = ["Hello"]
    # inputs = tokenizer.encode(input_text)
    # inputs = [inputs]
    # print(inputs)

    res = infer(input_text)
    asyncio.run(res)

```

**What did you expect to happen:**
The isvc + Triton can be accessed by gRPC from Istio

**What's the InferenceService yaml:**
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "triton-gpt
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
spec:
  predictor:
    maxReplicas: 1
    timeout: 1  
    volumes:  
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: "20480Mi"
    triton:
      ports:
        - containerPort: 9000 
          name: h2c 
          protocol: TCP
      storageUri: pvc://test-pvc/gpt
      image: xxx/tritonserver:22.03-py3-ft
      imagePullPolicy: IfNotPresent
      env:
      - name: OMP_NUM_THREADS
        value: "1"
      volumeMounts:
      - mountPath: /dev/shm
        name: dshm
        readOnly: false
      resources:
        limits:
          cpu: 30
          nvidia.com/gpu: 4
          memory: "80Gi"  
        requests:
          cpu: 30
          nvidia.com/gpu: 4
          memory: "80Gi"

```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.9
- Knative Version: 1.14
- KServe Version: 0.9.0rc
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): 1.19
- OS (e.g. from `/etc/os-release`):
