### ISSUE TITLE
Complete documentation for using Raw Deployment Mode without knative and istio?

### ISSUE THREAD

**Issue by red8888** [kserve/kserve#2943]
I do not want to install knative or istio on my cluster.

It appears RawDeployment Mode is what I want.

But I cannot find complete documentation on how to use kserve in this way.

Perhaps its out there and I just missed it, but every tutorial I see has istio and or knative involved.

Is it even possible to use kserve without knative and or istio?

For example the docs just say I can use other Ingress controllers, but offers no complete examples, how do I do that?
<img width="1005" alt="image" src="https://github.com/kserve/kserve/assets/6265399/2128830d-6113-4705-aa87-6ca83a64400b">

When I look at the official YAML manifest its littered with istio references: https://github.com/kserve/kserve/releases/download/v0.8.0/kserve.yaml

Like this:
```
---
apiVersion: v1
data:
  agent: |-
  ....
  ingress: |-
    {
        "ingressGateway" : "knative-serving/knative-ingress-gateway",
        "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
        "localGateway" : "knative-serving/knative-local-gateway",
        "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local",
        "ingressDomain"  : "example.com"
    }
```

And this
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kserve-manager-role
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  ...
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices/finalizers
  ...
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices/status
  ...
```
