### ISSUE TITLE
Fail to reconcile rollout duration when isvc updated

### ISSUE THREAD

**Issue by henrysecond1** [kserve/kserve#2946]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

- Deploy a isvc without rollout duration annotation.
- Update isvc with rollout duration annotation .
- ksvc rollout duration is not unchanged.

**What did you expect to happen:**
ksvc rollout duration is properly updated

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

Deploy

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: flower-sample
spec:
  predictor:
    model:
      modelFormat:
        name: tensorflow
      storageUri: "gs://kfserving-examples/models/tensorflow/flowers"
```

and update with

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: flower-sample
  annotations:
    serving.knative.dev/rollout-duration: "30s"
spec:
  predictor:
    model:
      modelFormat:
        name: tensorflow
      storageUri: "gs://kfserving-examples/models/tensorflow/flowers"
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: v0.10.0
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
