### ISSUE TITLE
Specifying service account name triggers redundant update in raw deployment

### ISSUE THREAD

**Issue by henrysecond1** [kserve/kserve#2947]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Deploy a raw deployment predictor with service account name like below

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: flower-sample
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    model:
      modelFormat:
        name: tensorflow
      storageUri: "gs://kfserving-examples/models/tensorflow/flowers"
    serviceAccountName: default-editor
```

Deployment reconciler keeps updating `Deployment` due to the `DeprecatedServiceAccount` difference.
I think the reconciler should ignore it.

Logs

```
{"level":"info","ts":1685089916.8137083,"logger":"DeploymentReconciler","msg":"deployment reconcile","checkResult":1,"err":null}

{"level":"info","ts":1685089916.813698,"logger":"DeploymentReconciler","msg":"Deployment Updated","Diff":"  ...

- \t\t\tDeprecatedServiceAccount:     \"\",\n+ \t\t\tDeprecatedServiceAccount:     \"default-editor\",\n  

```

**What did you expect to happen:**

Deployment reconciler should not keep updating

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

Described in above

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
