### ISSUE TITLE
Making the ingress routing more generic

### ISSUE THREAD

**Issue by ReToCode** [kserve/kserve#2957]
/kind feature

## Context
We are working on making `KServe` run on OpenShift. KServe in this case runs on top of OpenShift Serverless (which is basically Knative made running on OpenShift). It is installed based on the updated [guide here](https://github.com/kserve/kserve/blob/master/docs/OPENSHIFT_GUIDE.md). In this setup we have an additional routing layer in front of the `istio-ingressgateway`. As `Knative` relies on the `Knative Ingress` objects to configure networking we end up with issues in routing. This also applies to alternative `Knative` ingresses like `net-contour`.

## In detail problem description

Examples shortened for brevity. (full yamls available here: https://gist.github.com/ReToCode/40a3da622e039f12fdf778ca1b67a591):

Given the following `InferenceService` 

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-iris
  namespace: kserve-demo
status:
  address:
    url: http://sklearn-iris.kserve-demo.svc.cluster.local/v1/models/sklearn-iris:predict
  components:
    predictor:
      address:
        url: http://sklearn-iris-predictor.kserve-demo.svc.cluster.local
      traffic:
      - latestRevision: true
        percent: 100
        revisionName: sklearn-iris-predictor-00001
      url: http://sklearn-iris-predictor-kserve-demo.apps.rlehmann-ocp-4-12.serverless.devcluster.openshift.com
  url: http://sklearn-iris-kserve-demo.apps.rlehmann-ocp-4-12.serverless.devcluster.openshift.com
```

Creates the following `Knative Ingress` :

```yaml
apiVersion: networking.internal.knative.dev/v1alpha1
kind: Ingress
metadata:
  name: sklearn-iris-predictor
  namespace: kserve-demo
spec:
  rules:
  - hosts:
    - sklearn-iris-predictor-kserve-demo.apps.rlehmann-ocp-4-12.serverless.devcluster.openshift.com
    http:
    visibility: ExternalIP
```

**Problem 1**
KServe adds an additional istio `VirtualService` with the domain `sklearn-iris-kserve-demo.apps.rlehmann-ocp-4-12.serverless.devcluster.openshift.com` that `Knative` does not know of. For OpenShift specifically, the issue is that our controller creates OpenShift routes containing the hosts that are defined in `Knative Ingress` objects. So we are missing that additional host, resulting in the url in the `InferenceService` status being not callable.

```yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-6a86a949-245f-49ea-b081-dfd32e623d62-353934363632
  namespace: istio-system
spec:
  host: sklearn-iris-predictor-kserve-demo.apps.rlehmann-ocp-4-12.serverless.devcluster.openshift.com
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    host: sklearn-iris-predictor-kserve-demo.apps.rlehmann-ocp-4-12.serverless.devcluster.openshift.com
```

**Problem 2**
The url in the status field of `InferenceService` does not know/respect that the service is called via `https`. 

### Problem summary
We end up with
- `kubectl get ksvc` returns the domain `https://sklearn-iris-predictor-kserve-demo.apps.rlehmann-ocp-4-12.serverless.devcluster.openshift.com`
- `kubectl get is` returns the domain `http://sklearn-iris-kserve-demo.apps.rlehmann-ocp-4-12.serverless.devcluster.openshift.com`
- The additional host (which is displayed for the user) `sklearn-iris-kserve-demo.apps.rlehmann-ocp-4-12.serverless.devcluster.openshift.com` is not routed by `Knative` or any prevalent routing component like OpenShift router.

## Proposed feature
- Add the ability to configure that external domains are reachable via `https`, even when this happens before `KServe` and `Knative`

## Open points
- I'm not sure how we could fix the wrong "wrapping" service host. How is this intended to work with `kourier` or other ingress Knative solutions? Could we create `Knative Ingress` objects instead of istio specific ones? Have you tried that before? Any other ideas on how to solve this?

/cc @skonto
