### ISSUE TITLE
status.address.url does not match status.url hostname

### ISSUE THREAD

**Issue by danilopeixoto** [kserve/kserve#2958]
/kind bug

**What steps did you take and what happened:**

`status.address.url` does not match `status.url`. Is that expected?

Knative network configuration changes:

```yaml
default-external-scheme: https
domain-template: {{.Name}}-{{.Namespace}}.{{.Domain}}
```

KServe ingress configuration changes:

```json
{
    "urlScheme": "https",
    "domainTemplate": "{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}"
}
```

Output:

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: serverless-test
  namespace: kserve-serverless
  annotations:
    serving.kserve.io/deploymentMode: Serverless
status:
  address:
    url: >-
      http://serverless-test.kserve-serverless.svc.cluster.local/v2/models/serverless-test/infer
  components:
    predictor:
      address:
        url: >-
          http://serverless-test-predictor-default.kserve-serverless.svc.cluster.local
      url: >-
        https://serverless-test-predictor-default-kserve-serverless.company.com
  url: https://serverless-test-kserve-serverless.company.com
spec:
  predictor:
    minReplicas: 0
    model:
      modelFormat:
        name: mlflow
      name: ''
      protocolVersion: v2
      resources: {}
      runtime: kserve-mlserver
      storageUri: >-
        s3://path/to/artifacts/model
```

**What did you expect to happen:**

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: serverless-test
  namespace: kserve-serverless
  annotations:
    serving.kserve.io/deploymentMode: Serverless
status:
  address:
    url: >-
      https://serverless-test-kserve-serverless.company.com/v2/models/serverless-test/infer
  components:
    predictor:
      address:
        url: >-
          https://serverless-test-predictor-default-kserve-serverless.company.com
      url: >-
        https://serverless-test-predictor-default-kserve-serverless.company.com
  url: https://serverless-test-kserve-serverless.company.com
spec:
  predictor:
    minReplicas: 0
    model:
      modelFormat:
        name: mlflow
      name: ''
      protocolVersion: v2
      resources: {}
      runtime: kserve-mlserver
      storageUri: >-
        s3://path/to/artifacts/model
```

**What's the InferenceService yaml:**

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
    name: serverless-test
    annotations:
        serving.kserve.io/deploymentMode: Serverless
spec:
    predictor:
        minReplicas: 0
        serviceAccountName: default
        model:
            protocolVersion: v2
            modelFormat:
                name: mlflow
            storageUri: s3://path/to/artifacts/model
            runtime: kserve-mlserver
```

**Anything else you would like to add:**

No.

**Environment:**

- Istio Version: 1.16.0
- Knative Version: 1.8.0
- KServe Version: 0.10.0
- Kubeflow version: Not applicable
- Cloud Environment: k8s_istio
- Minikube/Kind version: Not applicable
- Kubernetes version: (use `kubectl version`): 1.25.0
- OS (e.g. from `/etc/os-release`): Oracle Linux Server 8.6 / Linux Kernel 4.18.0
