### ISSUE TITLE
RawDeployments do not work with GRPC examples

### ISSUE THREAD

**Issue by ReToCode** [kserve/kserve#2961]
/kind bug

**What steps did you take and what happened:**
It seems that RawDeployment mode with GRPC does not work. Using RawDeployment mode and https://kserve.github.io/website/0.10/modelserving/v1beta1/transformer/torchserve_image_transformer/#run-a-prediction with the following inference service:

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: ts-grpc
  namespace: kserve-demo
spec:
  predictor:
    triton:
      storageUri: gs://kfserving-examples/models/torchscript
      runtimeVersion: 20.10-py3
      ports:
        - containerPort: 9000
          name: h2c
          protocol: TCP
      env:
        - name: OMP_NUM_THREADS
          value: "1"
```

Creates the following ingress object

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
...
spec:
  ingressClassName: openshift-default
  rules:
  - host: torchscript-grpc-kserve-demo.apps.rlehmann-ocp-4-12.serverless.devcluster.openshift.com
    http:
      paths:
      - backend:
          service:
            name: torchscript-grpc-predictor
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: torchscript-grpc-predictor-kserve-demo.apps.rlehmann-ocp-4-12.serverless.devcluster.openshift.com
    http:
      paths:
      - backend:
          service:
            name: torchscript-grpc-predictor
            port:
              number: 80
        path: /
        pathType: Prefix
```

Pointing to port 80, while the k8s service looks like this. Note the port 9000 there:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ts-grpc-predictor
  namespace: kserve-demo
spec:
...
  ports:
  - name: h2c
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: isvc.ts-grpc-predictor
  sessionAffinity: None
  type: ClusterIP
```

**What did you expect to happen:**
GRPC port should be propagated to the ingress object accordingly.

**What's the InferenceService yaml:**
See above

**Anything else you would like to add:**
No

**Environment:**

- Istio Version: not related
- Knative Version: not applicable
- KServe Version: 0.10.1
- Kubeflow version: not applicable
- Cloud Environment: none
- Minikube/Kind version: none
- Kubernetes version: not related
- OS: not related
