### ISSUE TITLE
Emit kubernetes events for the model status

### ISSUE THREAD

**Issue by vsivaraja** [kserve/kserve#2962]
/kind feature
We'd like to use Prometheus to alert on if the model load has failed, i.e, `ModelLoadFailed`. Currently, we can see the load failure in the yaml:
``` 
  modelStatus:
      copies:
        failedCopies: 0
        totalCopies: 1
      lastFailureInfo:
        exitCode: 137
        reason: ModelLoadFailed
      states:
        activeModelState: Loaded
        targetModelState: Loaded
      transitionStatus: UpToDate
```

However, if Kubernetes events could be created for changes in the model state, especially failures, it would make it much easier to have automated alerting on model status failures. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
