### ISSUE TITLE
PVC volume mount is not supporting readOnly: false 

### ISSUE THREAD

**Issue by Agarwal-Saurabh** [kserve/kserve#2975]
I am trying to deploy kserve inference service over knative and mounting PVC on it. But the readOnly is coming as true even if its made false while deploying.

Also is there a way to change default value of readOnly to false instead true for PVC
sharing here the yaml for reference

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService

metadata:
  name: "hatest"
  annotations:
    autoscaling.knative.dev/target: "10"
    autoscaling.knative.dev/target-utilization-percentage: "80"

spec:
  predictor:
    volumes:
      - name: nfs1
        persistentVolumeClaim:
          claimName: nfs
          readOnly: False
    timeout: 600
    minReplicas: 1
    maxReplicas: 10
    imagePullSecrets:
        - name: gcr-secret
    containers:
      - name: "cls"
        image: docker.io/name:latest
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: true
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1
            memory: 2Gi
        volumeMounts:
          - name: nfs1
            readOnly: False
            mountPath: "/mnt/nfs"

        readinessProbe:
          httpGet:
            path: /v1/models/upscale
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
          failureThreshold: 3
```
