### ISSUE TITLE
Kserve with TorchServe Performance is very slow compared to standalone

### ISSUE THREAD

**Issue by gavrissh** [kserve/kserve#2983]
There is a noticeable performance difference when running StandAlone Torchserve and Kserve with TorchServe.

The difference in performance is 8:1 where Standalone Torchserve with just Kserve V2 Service Envelope performs 8 times better than routing requests to TorchServe through Kserve Model Server.

Is the performance difference as expected?

Could someone help with the ideal setup scenarios to get the best performance when running Torchserve with Kserve?

**Comment by yuzisun** [comment]
@gavrishp Can you create an issue under `pytorch/serve` as the code is maintained there not in kserve repository. 
Also please provide more details about your experiments how to reproduce.

**Comment by yuzisun** [comment]
Related issue I created for suggesting removing the kserve model server routing layer
https://github.com/pytorch/serve/issues/2373

**Comment by gavrissh** [comment]
@yuzisun For serving torch models in production what would you suggest is the ideal approach would be using kserve or any other native framework?

**Comment by yuzisun** [comment]
> @yuzisun For serving torch models in production what would you suggest is the ideal approach would be using kserve or any other native framework?

Which version of KServe you are using  and if you can share the inference service yaml? Only by providing more details we can help you

**Comment by gavrissh** [comment]
Using Kserve 10.1
yaml template
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "<name>"
  namespace: "<namespace>'
  annotations:
    "sidecar.istio.io/inject": "false"
    autoscaling.knative.dev/scale-to-zero-pod-retention-period: "5m"
spec:
  predictor:
    minReplicas: 1
    containers:
    - name: "kserve-container"
      image: "<image>"
      resources:
        limits:
           cpu: {{ .Values.n_cpu }}
           memory: {{ .Values.memory_limit }}
           nvidia.com/gpu: {{ .Values.n_gpu }}
```
Right now we are experimenting by using standard vision models as a base. Goal is to run custom containers with torch nlp and vision models.
