### ISSUE TITLE
Complete YAML template (all possible attributes ) for model serving ?

### ISSUE THREAD

**Issue by Rstar1998** [kserve/kserve#2985]
Where can we get entire list of attributes to be used in the following yaml ? I checked the documentation and didn't get info on entire list of attributes  

Sample yaml 
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    sklearn:
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
```
