### ISSUE TITLE
Cannot set custom readinessProbe for the predictor

### ISSUE THREAD

**Issue by elukey** [kserve/kserve#2994]
/kind bug

**What steps did you take and what happened:**

I tried to apply a custom `readinessProbe` config for a custom predictor that takes a little longer to boostrap:

```
spec:
  predictor:
    containers:
    - env:
      - name: MODEL_NAME
        value: falcon-7b-instruct-gpu
      - name: STORAGE_URI
        value: s3://wmf-ml-models/llm/falcon-7b-instruct/
      image: docker-registry.discovery.wmnet/wikimedia/machinelearning-liftwing-inference-services-llm:2023-06-09-090444-publish
      imagePullPolicy: IfNotPresent
      name: kserve-container
      readinessProbe:
        initialDelaySeconds: 120
        timeoutSeconds: 600
      resources:
        limits:
          amd.com/gpu: "1"
          cpu: "8"
          memory: 20Gi
        requests:
          amd.com/gpu: "1"
          cpu: "8"
          memory: 20Gi
    dnsConfig:
      options:
      - name: ndots
        value: "2"
    serviceAccountName: kserve
```

The readinessProbe settings are not passed to the pod, I checked with `kubectl describe pod` and I can only see:

```
Readiness:  http-get http://:15020/app-health/queue-proxy/readyz delay=0s timeout=1s period=10s #success=1 #failure=3
```

Moreover I noticed that when I applied the `readinessProbe` settings to the isvc, no new knative revision was created (hence nothing in the pod changed). Tried to delete the pod as extra verification step, nothing changed.

**What did you expect to happen:**

I expected the readiness probe to be configured with the new values set (longer timeouts/delays).

**Environment:**

- Istio Version: 1.15.7
- Knative Version: 1.7.2
- KServe Version: 0.10.0
- Kubernetes version: .1.23.12
- OS (e.g. from `/etc/os-release`): Debian Bullseye
