### ISSUE TITLE
How to use set  REST_V2.value  in  `self.protocol` of class Model ? 

### ISSUE THREAD

**Issue by Rstar1998** [kserve/kserve#3009]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

How to use set  REST_V2.value  in  `self.protocol` of class Model ? 

![image](https://github.com/kserve/kserve/assets/42741300/648e01f5-f358-4f1d-ab41-30ac6eb3cd39)

https://github.com/kserve/kserve/blob/1314130e93375bbda6ba46703af07a52262d1399/python/kserve/kserve/model.py#L72C14-L72C22

I am currently using a custom container ( custom code deployed as a docker image) and currently its using `v1/models` apis .
I am facing this issue https://github.com/kserve/kserve/issues/3007 for v1 apis , hence I am migrating to `v2/models` apis.  When I searched the documentation , there was no way to pass  the protocol version for custom container. Also even Inside kserve python sdk there is no way to set protocol as  `REST_V2.value` in Model class since it's already hard-coded. 

My yaml 
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: some-name
spec:
  predictor:
    containers:
      - name: some-name
        image: some-image:v1
        env:
          - name: PROTOCOL
            value: v2
          - name: MODEL_NAME
            value: some-name

            
```

My python code : 

```
import kserve
from typing import Dict
from kserve.utils.utils import generate_uuid
from kserve import InferRequest, InferResponse, InferOutput
import os

class AlexNetModel(kserve.Model):
    def __init__(self, name: str):
       super().__init__(name)
       self.name = name
       self.load()
       
    def load(self):
        self.ready = True

    def predict(self, payload: InferRequest, headers: Dict[str, str] = None) -> InferResponse:
       pass
  

if __name__ == "__main__":
    model = AlexNetModel("custom-model")
    kserve.ModelServer().start([model])


```

**Environment:**

- KServe Python sdk Version: kserve==0.10.1.1

**Comment by andyi2it** [comment]
@Rstar1998 

You should be able to pass the protocol as container args like `--protocol`
```yaml
apiVersion: [serving.kserve.io/v1beta1](http://serving.kserve.io/v1beta1)
kind: InferenceService
metadata:
  name: custom-model
spec:
  predictor:
    containers:
      - name: kserve-container
        image: kserve/custom-model:latest
        args:
          - --protocol=v2
          - -- http-port=8080
      
```
