### ISSUE TITLE
Download request for Kserve custom resource model that does not recognize HTTP

### ISSUE THREAD

**Issue by wjp-cn** [kserve/kserve#3013]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
After I created a custom resource through the InferenceService, I provided a correct model link that can be downloaded through HTTP. The Pod created by the custom resource will prompt the following error: "RuntimeError: URI: http://bw-model-svc.bluewhale-platform:8001/modelservice/model/download?path=/bluewhale/model/74/00000123.zip Did not respond with 'Content Type': 'application/octet stream'

**What did you expect to happen:**
I hope this link can be correctly recognized by Kserve

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
  finalizers:
    - inferenceservice.finalizers
  name: bw-model-api-4051
  namespace: bluewhale-platform
spec:
  predictor:
    model:
      modelFormat:
        name: Tensorflow
      name: ''
      resources: {}
      storageUri: >-
        http://bw-model-svc.bluewhale-platform:8001/modelservice/model/download?path=/bluewhale/model/74/00000123.zip
```
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- KServe Version: v0.10.0
