### ISSUE TITLE
Configmap doc comments gets removed during kustomize build

### ISSUE THREAD

**Issue by sivanantha321** [kserve/kserve#3023]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Configmap documentation comments added as part of PR #3016. But the comments are automatically removed during the kustomize build. So the documentation comments no longer available to the users.

**Proposal**
We should follow the knative way of documenting configmap by introducing a field `_example` which contains a example configuration with documentation. As it is added as field kustomize wont remove the documentation comments. Here is an example configmap from knative.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tracing
  namespace: knative-serving
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: tracing
    app.kubernetes.io/version: devel
  annotations:
    knative.dev/example-checksum: "26614636"
data:
  _example: |
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################

    # This block is not actually functional configuration,
    # but serves to illustrate the available configuration
    # options and document them in a way that is accessible
    # to users that `kubectl edit` this config map.
    #
    # These sample configuration options may be copied out of
    # this example block and unindented to be in the data block
    # to actually change the configuration.
    #
    # This may be "zipkin" or "none" (default)
    backend: "none"

    # URL to zipkin collector where traces are sent.
    # This must be specified when backend is "zipkin"
    zipkin-endpoint: "http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans"

    # Enable zipkin debug mode. This allows all spans to be sent to the server
    # bypassing sampling.
    debug: "false"

    # Percentage (0-1) of requests to trace
    sample-rate: "0.1"
```
**What did you expect to happen:**
Documentation comments should be available to the users.

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: master
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
