### ISSUE TITLE
Support model chaining for V2 spec

### ISSUE THREAD

**Issue by ichbinjakes** [kserve/kserve#3051]
/kind feature

**Describe the solution you'd like**

Ability to deploy MLServer custom runtime containers ( or other V2 inference protocol serving container) and chain them together in an InferenceGraph by passing the output of one model as the input to the next. Currently the request on a downstream step fails since 'inputs' are missing from the request:
```{"detail":[{"loc":["body","inputs"],"msg":"field required","type":"value_error.missing"}]}```

**Anything else you would like to add:**

The below example should help demonstrate what I am trying to achieve, which causes the error above

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: model
  name: mulyiply-2
spec:
  containers:
  - image: k3d-registry.localhost:12000/test-model:latest
    imagePullPolicy: Always
    name: test
---
apiVersion: v1
kind: Service
metadata:
  name: multiply-2
spec:
  selector:
    name: model
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
---
apiVersion: serving.kserve.io/v1alpha1
kind: InferenceGraph
metadata:
  name: model-chainer
spec:
  nodes:
    root:
      routerType: Sequence
      steps:
        - serviceUrl: http://multiply-2.default.svc.cluster.local/v2/models/model/infer
        - serviceUrl: http://multiply-2.default.svc.cluster.local/v2/models/model/infer
          data: $response
```
