### ISSUE TITLE
kserve 0.11.0 tests in kubeflow/manifests fails

### ISSUE THREAD

**Issue by DnPlas** [kserve/kserve#3081]
/kind bug

**What steps did you take and what happened:**
Updating the kserve manifests in kubeflow/manifests from v0.10 -> v0.11 (PR kubeflow/manifests#2504) causes the CI to fail when executing the `kserve tests` job.
The complete execution can be found  [here](https://github.com/kubeflow/manifests/actions/runs/5831759378/job/15815819933).

This error is blocking the Kubeflow 1.8 release as we cannot sync the latest manifests.

**What did you expect to happen:**
The CI of that repository executes the tests correctly and all tests succeed.

**What's the InferenceService yaml:**
N/A

**Anything else you would like to add:**
The root cause could be the recent changes done in `kserve_kubeflow.yaml`, where a lot of annotations and field values are have replaced `kubeflow` with `kserve`. For example:

[Here](https://github.com/kserve/kserve/blob/master/install/v0.11.0/kserve_kubeflow.yaml#L20761)
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kserve/serving-cert
  creationTimestamp: null
```
while in the previous version of kserve, the [manifests](https://github.com/kubeflow/manifests/blob/master/contrib/kserve/kserve/kserve_kubeflow.yaml#L20234C1-L20238C58) in kubeflow/manifests had a different value:
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kubeflow/serving-cert
```

These are just examples, but there are several different fields that changed from `kubeflow` to `kserve`.

**Potential fix**
@annajung found out that reverting back the `kubeflow` values actually helps solving the CI error.

**Environment:**

- Istio Version: 1.17.x
- Knative Version: 1.10.x
- KServe Version: 0.11.x
- Kubeflow version: 1.8 (testing, not yet released)
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
