### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by lc2a** [kserve/kserve#3084]
Failed to SKIP SSL verify.
Kindly advise

> Error (etry( File "/prod_venv/lib/python3.9/site-packages/botocore/endpoint.py", line 354, in _needs_retry responses = self._event_emitter.emit( File "/prod_venv/lib/python3.9/site-packages/botocore/hooks.py", line 412, in emit return self._emitter.emit(aliased_event_name, **kwargs) File "/prod_venv/lib/python3.9/site-packages/botocore/hooks.py", line 256, in emit return self._emit(event_name, kwargs) File "/prod_venv/lib/python3.9/site-packages/botocore/hooks.py", line 239, in _emit response = handler(**kwargs) File "/prod_venv/lib/python3.9/site-packages/botocore/retryhandler.py", line 207, in __call__ if self._checker(**checker_kwargs): File "/prod_venv/lib/python3.9/site-packages/botocore/retryhandler.py", line 284, in __call__ should_retry = self._should_retry( File "/prod_venv/lib/python3.9/site-packages/botocore/retryhandler.py", line 320, in _should_retry return self._checker(attempt_number, response, caught_exception) File "/prod_venv/lib/python3.9/site-packages/botocore/retryhandler.py", line 363, in __call__ checker_response = checker( File "/prod_venv/lib/python3.9/site-packages/botocore/retryhandler.py", line 247, in __call__ return self._check_caught_exception( File "/prod_venv/lib/python3.9/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception raise caught_exception File "/prod_venv/lib/python3.9/site-packages/botocore/endpoint.py", line 281, in _do_get_response http_response = self._send(request) File "/prod_venv/lib/python3.9/site-packages/botocore/endpoint.py", line 377, in _send return self.http_session.send(request) File "/prod_venv/lib/python3.9/site-packages/botocore/httpsession.py", line 492, in send raise SSLError(endpoint_url=request.url, error=e) botocore.exceptions.SSLError: SSL validation failed for https://minio.abc.lan:9000/kserve-models?prefix=brain-mri&encoding-type=url [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) ) | Last state: Terminated with 1: Error (etry( File &quot;/prod_venv/lib/python3.9/site-packages/botocore/endpoint.py&quot;, line 354, in _needs_retry responses = self._event_emitter.emit( File &quot;/prod_venv/lib/python3.9/site-packages/botocore/hooks.py&quot;, line 412, in emit return self._emitter.emit(aliased_event_name, **kwargs) File &quot;/prod_venv/lib/python3.9/site-packages/botocore/hooks.py&quot;, line 256, in emit return self._emit(event_name, kwargs) File &quot;/prod_venv/lib/python3.9/site-packages/botocore/hooks.py&quot;, line 239, in _emit response = handler(**kwargs) File &quot;/prod_venv/lib/python3.9/site-packages/botocore/retryhandler.py&quot;, line 207, in __call__ if self._checker(**checker_kwargs): File &quot;/prod_venv/lib/python3.9/site-packages/botocore/retryhandler.py&quot;, line 284, in __call__ should_retry = self._should_retry( File &quot;/prod_venv/lib/python3.9/site-packages/botocore/retryhandler.py&quot;, line 320, in _should_retry return self._checker(attempt_number, response, caught_exception) File &quot;/prod_venv/lib/python3.9/site-packages/botocore/retryhandler.py&quot;, line 363, in __call__ checker_response = checker( File &quot;/prod_venv/lib/python3.9/site-packages/botocore/retryhandler.py&quot;, line 247, in __call__ return self._check_caught_exception( File &quot;/prod_venv/lib/python3.9/site-packages/botocore/retryhandler.py&quot;, line 416, in _check_caught_exception raise caught_exception File &quot;/prod_venv/lib/python3.9/site-packages/botocore/endpoint.py&quot;, line 281, in _do_get_response http_response = self._send(request) File &quot;/prod_venv/lib/python3.9/site-packages/botocore/endpoint.py&quot;, line 377, in _send return self.http_session.send(request) File &quot;/prod_venv/lib/python3.9/site-packages/botocore/httpsession.py&quot;, line 492, in send raise SSLError(endpoint_url=request.url, error=e) botocore.exceptions.SSLError: SSL validation failed for https://minio.abc.lan:9000/kserve-models?prefix=brain-mri&amp;encoding-type=url [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) ), started: Thu, Aug 17 2023 7:36:32 pm, finished: Thu, Aug 17 2023 7:36:45 pm

**Environment:**
```
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      name: ''
      resources: {}
      storageUri: s3://kserve-models/brain-mri
    serviceAccountName: sa
```

```
apiVersion: v1
kind: Secret
metadata:
  name: s3creds
  namespace: kserve-models
  annotations:
     serving.kserve.io/s3-endpoint: minio.abc.lan:9000
     serving.kserve.io/s3-usehttps: "1" 
     serving.kserve.io/s3-verifyssl: "0"
     serving.kserve.io/s3-cabundle: "" 
     serving.kubeflow.org/s3-verifyssl: "0"
     serving.kubeflow.org/s3-cabundle: ""
type: Opaque
stringData: 
  AWS_ACCESS_KEY_ID: 3Y0JOHZM81CE50UNM42BVVCZBQYZHXEZZQ9VXPOCMJFMY0LIJDUICOVV1463TAU5M0WIIU8XVN1J7Q3S5M87937XZDA9G00OFYID39W852ZP
  AWS_SECRET_ACCESS_KEY: QVYL88SG43Q3D198G16KI5K4H6M2KR21E4DMNDB0WJOVMZK5JRD7CAWLPS01ILAKM5CF1TVYM6MZY1XQ2T
  S3_VERIFY_SSL: "0"
  AWS_CA_BUNDLE: ""
```

**Environment:**

- Istio Version:1.18.2
- Knative Version:knative-v1.11.0
- KServe Version:knative-v1.11.0
- Kubernetes version: (use `kubectl version`): v1.25.6
