### ISSUE TITLE
Question on InferenceService Swagger UI

### ISSUE THREAD

**Issue by luntropy** [kserve/kserve#3087]
/kind question

How can I enable the Swagger UI using the old schema?

Currently, the [documentation](https://kserve.github.io/website/0.10/get_started/swagger_ui/#enable-swagger-ui) example is using the new schema: 

> apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
&emsp;  name: "sklearn-iris"
spec:
&emsp;  predictor:
&emsp;&emsp;    model:
&emsp;&emsp;&emsp;      args: ["--enable_docs_url=True"]
&emsp;&emsp;&emsp;      modelFormat:
&emsp;&emsp;&emsp;&emsp;        name: sklearn
&emsp;&emsp;&emsp;      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"

However, I need to incorporate it as part of the old one: 

> apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
&emsp;  name: "sklearn-iris"
spec:
&emsp;  predictor:
&emsp;&emsp;    sklearn:
&emsp;&emsp;&emsp;      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"

Any suggestions how to do it? I tried by providing the argument but it still did not work, is it possible that it is not supported?

**Comment by sivanantha321** [comment]
@luntropy Try with this yaml. It should work.
```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    sklearn:
      args: ["--enable_docs_url=True"]
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
```
