### ISSUE TITLE
Can't Get Model List from InferenceService

### ISSUE THREAD

**Issue by yribeiro** [kserve/kserve#3090]
/kind bug

**What steps did you take and what happened:**
Whenever I try and run the following curl command:

```bash
curl -X GET http://ai-object-detection.***.com/v1/models
```
I get the following response:

```bash
{
  "code": 404,
  "type": "ResourceNotFoundException",
  "message": "Requested resource is not found, please refer to API document."
}
```

The post command using the predict API works fine.

```bash
curl -X POST http://ai-object-detection.***.com/v1/models/object_detector:predict -d @/example_kserve_request.json
```

**What did you expect to happen:**

I was expecting to receive a models list as outlined on the kserve [API webpage](https://kserve.github.io/website/0.10/modelserving/data_plane/v1_protocol/)

**What's the InferenceService yaml:**

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    autoscaling.knative.dev/scale-to-zero-pod-retention-period: 10m
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
  labels:
    app.kubernetes.io/env: kubeflow
    app.kubernetes.io/instance: predictor
    app.kubernetes.io/name: ai-object-detection
    app.kubernetes.io/version: <VERSION>
  name: ai-object-detection
  namespace: ns-ci
spec:
  predictor:
    batcher:
      maxBatchSize: 16
      maxLatency: 200
    containers:
    - env:
      - name: STORAGE_URI
        value: <STORAGE_URI>
      - name: ENV_STATE
        value: kubeflow
      image: <DOCKER_IMAGE>
      name: kfserving-container
      resources:
        limits:
          memory: 6Gi
          nvidia.com/gpu: 1
        requests:
          memory: 6Gi
    maxReplicas: 1
    minReplicas: 1
    nodeSelector:
      nvidia/instance-type: g4dn
    serviceAccountName: kserve-s3-reader
    timeout: 120
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
    - effect: NoSchedule
      key: nvidia/instance-type
      operator: Equal
      value: g4dn
```

**Anything else you would like to add:**

We are running a TorchServe server with the KServe Request Envelope. The torchserve config.properties object is as follows:

```yaml
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
enable_metrics_api=true
metrics_format=prometheus
number_of_netty_threads=4
job_queue_size=10
service_envelope=kserve
model_store=/mnt/models/model-store
max_request_size=100000000
max_response_size=100000000
model_snapshot={"name":"startup.cfg", "modelCount":1, "models":{"object_detector":{"1.0":{"defaultVersion":true, "marName":"ai_object_detection.mar", "minWorkers":1, "maxWorkers":4, "batchSize":1, "maxBatchDelay":200, "responseTimeout":30000}}}}
```

I end up seeing the following in the torchserve server logs:

![image](https://github.com/kserve/kserve/assets/20907507/9667622a-796b-4638-b207-8acb4310f1c4)

**Environment:**

- Istio Version: 1.16.0
- Knative Version: 1.8
- KServe Version: 0.10
- Kubeflow version: 1.7
- Cloud Environment: AWS
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.4 LTS
