### ISSUE TITLE
Is is possible to set a default value of InferenceService's timeout (Serverless mode)

### ISSUE THREAD

**Issue by mexeniz** [kserve/kserve#3092]
/kind question

**What's the question**
I found that a pod created by KServe takes long time to be terminated (300 seconds).
As I understand, `terminationGracePeriodSeconds` in the pod config controls this behavior and we can configure it per InferenceService by `timeout` (Ref: https://github.com/kserve/kserve/issues/1546). 
However, I'd like to decrease this value for all ISVC in our platform, because they take too long time to evict their pods during K8S node operation.
Would it be possible to set a default value of InferenceService's timeout? 

Btw, the below shows my experiment with adjusting a default value at KNative Serving side. It doesn't work.

**What's the InferenceService yaml:**
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: pytorch-mnist
  namespace: default
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      storageUri: gs://kfserving-examples/models/torchserve/image_classifier/v2

```

**What steps did you take and what happened:**
1. Set a default value of `revision-timeout-seconds` in KNative 
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: knative-serving
  name: config-defaults
  namespace: knative-serving
data:
  revision-timeout-seconds: "120"
```
2. Restart KNative controller
3. Deploy the above KServe's InferenceService
4. `terminationGracePeriodSeconds` in InferenceService's pod is still set to `300`

**Environment:**

- Istio Version: v1.18.0
- Knative Version: v1.10.2
- KServe Version: v0.10.1
- Kubeflow version: N/A
- Cloud Environment: AWS
- Minikube/Kind version:
- Kubernetes version: 1.24
- OS (e.g. from `/etc/os-release`):
