### ISSUE TITLE
First inference service example not working in v0.11

### ISSUE THREAD

**Issue by lizzzcai** [kserve/kserve#3117]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I am following the [first inference service](https://kserve.github.io/website/0.11/get_started/first_isvc/) example but it is not working in `v0.11`, getting following error when I send the request.

```json
{"error":"Expected 2D array, got scalar array instead:\narray=nan.\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample."}
```

**What did you expect to happen:**

following response is expected:

```json
{"predictions":[1,1]}
```

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

```
kubectl create namespace kserve-test

kubectl apply -n kserve-test -f - <<EOF
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
      resources:
        limits:
          cpu: 100m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 1Gi
EOF
```

**Anything else you would like to add:**
When I use the runtimes in `v0.10.0`, it works fine.

**Environment:**

- Istio Version: 1.17.3
- Knative Version: v1.11.0
- KServe Version: v0.11
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): v1.26.7
- OS (e.g. from `/etc/os-release`):
