### ISSUE TITLE
Inferences are unable to run successfully 

### ISSUE THREAD

**Issue by TalhaNaeem101** [kserve/kserve#3124]
Hello,

I am stuck with an issue while creating inference services, in which you can help me out. The inference services get created but its corresponding pod is not completed and does not report status on kubeflow UI. As I am using kserve along with kubeflow.
Here is the error I get with inference Service:
```
 Warning  UpdateFailed   5m46s  v1beta1Controllers  Failed to update status for InferenceService "regression": Operation cannot be fulfilled on inferenceservices.serving.kserve.io "regression": the object has been modified; please apply your changes to the latest version and try again
  Warning  InternalError  5m46s  v1beta1Controllers  fails to update InferenceService status: Operation cannot be fulfilled on inferenceservices.serving.kserve.io "regression": the object has been modified; please apply your changes to the latest version and try again
  Warning  InternalError  5m46s  v1beta1Controllers  fails to reconcile predictor: fails to update knative service: Operation cannot be fulfilled on services.serving.knative.dev "regression-predictor-default": the object has been modified; please apply your changes to the latest version and try again
```

Here is the inference' pod logs:
```
kubectl logs -n kubeflow-user-example-com regression-predictor-default-00001-deployment-7bf5bf697f-hz7cz 
ERROR: failed to launch: determine start command: when there is no default process a command is required
```

Following is the manifest for inference service:

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: regression
  namespace: kubeflow-user-example-com
  annotations:
    autoscaling.knative.dev/target: "1"
spec:
  predictor:
    minReplicas: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: dedicated
                  operator: In
                  values:
                    - kubeflow
    tolerations:
      - key: dedicated
        operator: Equal
        value: kubeflow
        effect: NoSchedule
    containers:
      - name: kserve-container
        image: ghcr.io/private-repo/ml-realtime-inference-reg:v1.0.0.e4963328
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
    imagePullSecrets:
      - name: github-auth
 ```

On kubeflow UI, the inference endpoint does not get succeeded:
![image](https://github.com/kserve/kserve/assets/105629434/52a0f347-3893-4486-b848-b735a8d4852b)

**Kubeflow Version: v1.7
Kserve: 0.10.0
EKS version: 1.25**

Thank you for your support in advance!

**Comment by TalhaNaeem101** [comment]
In events of regression-predictor-default-00001-deployment-76c4848669-sqvvs pod , getting the following warning:
`kubectl describe  po -n kubeflow-user-example-com regression-predictor-default-00001-deployment-76c4848669-sqvvs`
```
  Warning  Unhealthy  3m6s (x42 over 8m4s)  kubelet            Readiness probe failed: Get "http://10.0.72.194:15020/app-health/queue-proxy/readyz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by sivanantha321** [comment]
@TalhaNaeem101 Can you provide the full log of the pod ?

**Comment by TalhaNaeem101** [comment]
Here is the output of ` kubectl describe  inferenceservices.serving.kserve.io -n kubeflow-user-example-com regression` :
```
Events:
  Type     Reason         Age   From                Message
  ----     ------         ----  ----                -------
  Warning  UpdateFailed   2m4s  v1beta1Controllers  Failed to update status for InferenceService "regression": Operation cannot be fulfilled on inferenceservices.serving.kserve.io "regression": the object has been modified; please apply your changes to the latest version and try again
  Warning  InternalError  2m4s  v1beta1Controllers  fails to update InferenceService status: Operation cannot be fulfilled on inferenceservices.serving.kserve.io "regression": the object has been modified; please apply your changes to the latest version and try again
```

Since **kserver-controller** is related to it, I am attaching the error log getting in the output of `kubectl logs -n kubeflow kserve-controller-manager-c64bd5574-ckzxs `:
```
{"level":"error","ts":1694759303.5541534,"logger":"controller.inferenceservice","msg":"Reconciler error","reconciler group":"serving.kserve.io","reconciler kind":"InferenceService","name":"regression","namespace":"kubeflow-user-example-com","error":"fails to update InferenceService status: Operation cannot be fulfilled on inferenceservices.serving.kserve.io \"regression\": the object has been modified; please apply your changes to the latest version and try again","errorVerbose":"Operation cannot be fulfilled on inferenceservices.serving.kserve.io \"regression\": the object has been modified; please apply your changes to the latest version and try again\nfails to update InferenceService status\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).updateStatus\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:243\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:219\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```


After creating an inference service, one pod is spun up i.e. regression-predictor-default-00001-deploymen.  So here is the output of `kubectl logs -n kubeflow-user-example-com  regression-predictor-default-00001-deployment-754d56986-wv4c8` . Getting only this log.:
```
ERROR: failed to launch: determine start command: when there is no default process a command is required
```

Please let me know if you want anything else to look at. @sivanantha321 
thanks :pray:

**Comment by sivanantha321** [comment]
@TalhaNaeem101 From this error I believe it has more to do with the image itself than the kserve.
```text
ERROR: failed to launch: determine start command: when there is no default process a command is required
```
This error means that Docker was unable to determine the command to start the container. This can happen for a few reasons:

- The Dockerfile does not specify an ENTRYPOINT or CMD instruction.
- The ENTRYPOINT or CMD instruction is not a valid command.
- The ENTRYPOINT or CMD instruction is not executable.

If it is the first case, then you can try providing the command and required args in the container spec. For example,
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: regression
  namespace: kubeflow-user-example-com
  annotations:
    autoscaling.knative.dev/target: "1"
spec:
  predictor:
    minReplicas: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: dedicated
                  operator: In
                  values:
                    - kubeflow
    tolerations:
      - key: dedicated
        operator: Equal
        value: kubeflow
        effect: NoSchedule
    containers:
      - name: kserve-container
        image: ghcr.io/private-repo/ml-realtime-inference-reg:v1.0.0.e4963328
        command: ["your-command"]
        args: ["arg1", "arg2"]
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
    imagePullSecrets:
      - name: github-auth
```
