### ISSUE TITLE
Runtime selection becomes unpredictable when two different priority is specified for the same model in a servingruntime

### ISSUE THREAD

**Issue by sivanantha321** [kserve/kserve#3180]
/kind bug

**What steps did you take and what happened:**

When we specify two different priority for the same modelFormat with different versions,  the runtime selection becomes unpredictable. 

For example, Here is two serving runtimes. The MLServer runtime specifies two different priority for the 'sklearn' model with different version. At the same time Kserve sklearn runtime also has support for the 'sklearn' model with priority of 1.

Note: The runtimes are truncated for brevity.

**MLServer runtime**
```yaml
apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: kserve-mlserver
spec:
  supportedModelFormats:
    - name: sklearn
      version: "0"
      autoSelect: true
      priority: 1
    - name: sklearn
      version: "1"
      autoSelect: true
      priority: 2
```
**Kserve sklearn runtime**
```yaml
apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: kserve-sklearnserver
spec:
  supportedModelFormats:
    - name: sklearn
      version: "1"
      autoSelect: true
      priority: 1
```
When we apply the following yaml , The MLServer runtime should be selected as it has the higher priority which is 2. But instead Kserve Sklearn runtime is selected.

**InferenceService**
```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      protocolVersion: "v2"
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model" 
```
This is due to the fact that MLServer has two different priorities and one of which is lower i.e. 1. We didn't specify the model version in the isvc, so three of the model formats are valid for this isvc. 

When the runtime is sorted by the supported model's priority at first MLserver  precedes  the Sklearn because of the modelformat with priority value of 2. At the second round Sklearn gets the precedence because of mlserver's modelformat with priority value of 1.

**What did you expect to happen:**
The MLServer runtime should be selected. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
We should add a validation for this edge case.

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: 0.11.1
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
