### ISSUE TITLE
Storage initializer v0.11.1 downloads model.pkl to /mnt/models/model/model.pkl instead of  /mnt/models/model.pkl 

### ISSUE THREAD

**Issue by PiePra** [kserve/kserve#3200]
/kind bug

**What steps did you take and what happened:**

We recently upgraded our KServe instance from v0.9.0 to newest v0.11.1 and encountered weird behaviour for storage initializer. We mainly serve models from mlflow registry. When trying to serve the wine example model from our mlflow registry the kserve-container crashes, because it cannot find model.pkl. The artifact in mlflow looks like this:
```
├── conda.yaml
├── MLmodel
├── model.pkl
├── python_env.yaml
└── requirements.txt
```

Storage initalizer v0.11.1 downloads all files to /mnt/models but downloading model.pkl to subdirectory model /mnt/models/model/model.pkl. So the volume after storage initalizer is done looks like:

```
├── conda.yaml
├── MLmodel
├── model
│     ├── model.pkl
├── python_env.yaml
└── requirements.txt
```
![image](https://github.com/kserve/kserve/assets/22219924/fbdceb6d-fde4-4516-94b1-01a914be786b)

This causes kserve-container to CrashLoopBackOff as it cannot find model.pkl where it is expected. 

Using the storage initializer v0.9.0 the artifact download is done the way kserve expects it. We therefore currently run the setup of kserve v0.11.1 using storage initalizer v0.9.0

**What did you expect to happen:**
storage initializer should download the model.pkl to the same directory as MLmodel

**What's the InferenceService yaml:**
A very basic InferenceService yaml
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: wine
  namespace: default
spec:
  predictor:
    model:
      modelFormat:
        name: mlflow
      name: ""
      protocolVersion: v2
      storageUri: s3://mlflow/4/1c8e8fe765c34c45baeba5030cb96753/artifacts/model
    serviceAccountName: sa-s3
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.16
- Knative Version: 1.4
- KServe Version: 0.11.1
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: 1.22.9
- OS (e.g. from `/etc/os-release`):
