### ISSUE TITLE
It is possible volume mount on InferenceService ?

### ISSUE THREAD

**Issue by reconlabs-luke** [kserve/kserve#3264]
/kind bug

**What steps did you take and what happened:**
I tried to add pv, pvc for sharing volume each other(inference Services) such as kubeflow pipeline
But "volume mount" is not working. Isn't there nice way ?

**What did you expect to happen:**
- volume mount

**What's the InferenceService yaml:**
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: comp1
  namespace: kserve-test
spec:
  predictor:
    containers:
      - name: comp1
        image: ***/serving:comp1-prod
    volumeMounts:
      - name: log-vol
        mountPath: "/tmp/log"
    volumes:
      - name: log-vol
        persistentVolumeClaim:
          claimName: demo-pvc
```

**Anything else you would like to add:**
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/log"
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
```

```
k describe isvc comp1 -n kserve-test

Name:         comp1
Namespace:    kserve-test
Labels:       <none>
Annotations:  <none>
API Version:  serving.kserve.io/v1beta1
Kind:         InferenceService
Metadata:
  Creation Timestamp:  2023-11-23T09:19:56Z
  Finalizers:
    inferenceservice.finalizers
  Generation:  1
  Managed Fields:
    API Version:  serving.kserve.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:predictor:
          .:
          f:containers:
          f:volumes:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-11-23T09:19:55Z
    API Version:  serving.kserve.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"inferenceservice.finalizers":
    Manager:         manager
    Operation:       Update
    Time:            2023-11-23T09:19:56Z
  Resource Version:  6676974
  UID:               d3c35e47-41fa-47f1-b97f-9a6235d33c0a
Spec:
  Predictor:
    Containers:
      Image:  129231402580.dkr.ecr.ap-northeast-1.amazonaws.com/serving:comp1-prod
      Name:   kserve-container
      Resources:
        Limits:
          Cpu:     1
          Memory:  2Gi
        Requests:
          Cpu:     1
          Memory:  2Gi
    Volumes:
      Name:  log-vol
      Persistent Volume Claim:
        Claim Name:  demo-pvc
Events:
  Type     Reason         Age                 From                Message
  ----     ------         ----                ----                -------
  Warning  InternalError  15s (x15 over 97s)  v1beta1Controllers  fails to reconcile predictor: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: Persistent volume claim support is disabled, but found persistent volume claim demo-pvc: 
Persistent volume write support is disabled, but found persistent volume claim demo-pvc that is not read-only: 
must not set the field(s): spec.template.spec.volumes[0].persistentVolumeClaim
volume with name "log-vol" not mounted: spec.template.spec.volumes[0].name
```
**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: 0.11
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
