### ISSUE TITLE
Collocate transformer and predictor for simplifing the deployment

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#3269]
/kind feature

**Describe the solution you'd like**
While deploying transformer/predictor as separate services gives you the flexibility of running different replicas for transformer and predictor. KServe 0.11 already starts to support [collocating transformer and predictor](https://kserve.github.io/website/master/modelserving/v1beta1/transformer/collocation/) in the same pod for custom containers, we'd like to provide an option for collocating transformer with supported serving runtimes as well(e.g triton , TorchServe).

**Anything else you would like to add:**
## Proposed Inference Service Spec Option 1
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: torch-transformer
  annotations:
      serving.kserve.io/collocate: true
spec:
  transformer:
    containers:
    - image: kserve/nlp-tokenizer:latest
      name: transformer-container
      command:
        - "python"
        - "-m"
        - "tokenizer"
      args:
        - --tokenizer
        - nlptokenizer
  predictor:
    model:
      modelFormat:
        name: pytorch
      storageUri: gs://kfserving-examples/models/nlp
```

## Proposed Inference Service Spec Option 2
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: torch-transformer
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      storageUri: gs://kfserving-examples/models/nlp
    containers:
    - name: transformer-container
       args:
        - mapper
        - --task=embedding
        - --tokenizer=/mnt/models/triton/tokenizer_files/
        - predictor-config
        - --predictor-host=localhost:9000
        - model
        - --predictor-model-name=roberta-large-cased-bn-bfw-fp16
        - --name=benchmark-test
        - --return-bytes
```
## Benefits:
- Reduce networking overhead between node to node communications
- Reduce complexity of deploying transformer and predictor as separate services and tune the ratio for best performance
- Reduce the risk of non-compatible changes between transformer and predictor, now they can be deployed as a single unit.

## Other considerations:
* Compare the performance between collocating transformer and predictor vs launching as separate services
* We would also like to rename transformer as there is always confusion with the "Transformer Model" from google's paper.

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]
