### ISSUE TITLE
Can I link custom transformer and inference service ?

### ISSUE THREAD

**Issue by reconlabs-luke** [kserve/kserve#3278]
/kind bug

**What steps did you take and what happened:**
I wanna link custom transformer and inference service each other

Im trying to link them but it is not working well

```
{"error":"Model with name metarecon3:predict does not exist."}% 
```
- transformer did not found model..

```bash
curl -v --max-time 3600 -H "Host: ${SERVICE_HOSTNAME}" -H "Content-Type: application/json" "https://${INGRESS_HOST}/v1/models"

{"models":["metarecon3"]}% 
```
- but It exists

```python
parser.add_argument(
    "--model_name",
    help="The name that the model is served under.",
    default=os.getenv("MODEL_NAME", "metarecon3"),
)
args, _ = parser.parse_known_args()

if __name__ == "__main__":
    model = MyTransformer(
        args.model_name, predictor_host=args.predictor_host, protocol=args.protocol
    )
    ModelServer(workers=1).start([model])
```
- transformer

```python
parser = argparse.ArgumentParser(parents=[model_server.parser])
parser.add_argument(
    "--model_name",
    help="The name that the model is served under.",
    default=os.getenv("MODEL_NAME", "metarecon3"),
)
args, _ = parser.parse_known_args()

if __name__ == "__main__":
    model = MyInferenceService(args.model_name)
    ModelServer(workers=1).start([model])
```
- My inference service

I developed my custom inference service preprcoess, predict, postprocess and transformer preprocess, postprocess.
I tested that isvc is good working. I want to know that it is possible way

**What did you expect to happen:**

**What's the InferenceService yaml:**
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: metarecon3
  namespace: production
spec:
  predictor:
    nodeSelector:
      type: g5.4xlarge
    containers:
      - name: metarecon3
        image: ***/serving:metarecon3-prod
        env:
          - name: MODEL_NAME
            value: metarecon3
        volumeMounts:
          - mountPath: /data
            name: mydata
            readOnly: false
        resources:
          limits:
            cpu: 4
            memory: "15Gi"
            nvidia.com/gpu: 1
          requests:
            cpu: 4
            memory: "15Gi"
            nvidia.com/gpu: 1
    volumes:
      - name: mydata
        persistentVolumeClaim:
          claimName: metarecon3
          readOnly: false

  transformer:
    containers:
      - name: recon-engine-transformer
        image: ***/serving:reco-engine-transformer-prod
        command:
          - "python"
          - "serving/app.py"
        args:
          - --model_name
          - metarecon3
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
