### ISSUE TITLE
Restrict storage uri to predictor only in collocation of transformer and predictor

### ISSUE THREAD

**Issue by sivanantha321** [kserve/kserve#3279]
/kind bug

**What steps did you take and what happened:**

Support for collocating transformer and predictor in a single pod for custom models is introduced by the PR #2873. 
However, This allows the user to specify storage uri in both the transformer and predictor containers. This may introduce some problems.

For example, the user can specify two different storage uris in predictor and transformer, storage container does not support adding two storage uris. so what happens is the storage container takes the uri from the first container (the order containers specified in yaml). 

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-transformer-collocation
spec:
  predictor:
    containers:
      - name: kserve-container
        image: kserve/custom-model-grpc:latest
        args:
          - --model_name=custom-model
          - --grpc_port=8082
          - --http_port=8080
        env:
           - key: STORAGE_URI
             value: gs://some-uri-1    # different uri, this model will be downloaded
        
      - image: kserve/image-transformer:latest
        name: transformer-container   
        args:
          - --model_name=custom-model
          - --protocol=grpc-v2
          - --http_port=8000
          - --grpc_port=8081
          - --predictor_host=localhost:8082
        ports:
          - containerPort: 8000
            protocol: TCP
        env:
           - key: STORAGE_URI
             value: gs://some-uri-2       # different uri, this is ignored by the storage initalizer
```

Another know problem is if the first container does not specy the strorage uri, then the storage initializer is not injected even if the second container has the storage uri.
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-transformer-collocation
spec:
  predictor:
    containers:
      - name: kserve-container
        image: kserve/custom-model-grpc:latest
        args:
          - --model_name=custom-model
          - --grpc_port=8082
          - --http_port=8080
                                                                                # no storage uri, storage initializer won't be injected.
        
      - image: kserve/image-transformer:latest
        name: transformer-container    
        args:
          - --model_name=custom-model
          - --protocol=grpc-v2
          - --http_port=8000
          - --grpc_port=8081
          - --predictor_host=localhost:8082
        ports:
          - containerPort: 8000
            protocol: TCP
        env:
           - key: STORAGE_URI
             value: gs://some-uri-2       # ignored by the storage initalizer
```

**Solution:**
Restrict the storage uri env variable to predictor only and use the same model for transformer.
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-transformer-collocation
spec:
  predictor:
    containers:
      - name: kserve-container
        image: kserve/custom-model-grpc:latest
        args:
          - --model_name=custom-model
          - --grpc_port=8082
          - --http_port=8080
        env:
           - key: STORAGE_URI
             value: gs://some-uri-1    # download this model and use it for both predictor and transformer
        
      - image: kserve/image-transformer:latest
        name: transformer-container    
        args:
          - --model_name=custom-model
          - --protocol=grpc-v2
          - --http_port=8000
          - --grpc_port=8081
          - --predictor_host=localhost:8082
        ports:
          - containerPort: 8000
            protocol: TCP
```

Add a validation to check if storage uri env variable is present in the transformer container. if it is present then, deny the resource creation.

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-transformer-collocation
spec:
  predictor:
    containers:
      - name: kserve-container
        image: kserve/custom-model-grpc:latest
        args:
          - --model_name=custom-model
          - --grpc_port=8082
          - --http_port=8080
        env:
           - key: STORAGE_URI
             value: gs://some-uri-1 
        
      - image: kserve/image-transformer:latest
        name: transformer-container    
        args:
          - --model_name=custom-model
          - --protocol=grpc-v2
          - --http_port=8000
          - --grpc_port=8081
          - --predictor_host=localhost:8082
        ports:
          - containerPort: 8000
            protocol: TCP
        env:
           - key: STORAGE_URI
             value: gs://some-uri-2       # the resource creation will be denied.
```

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: 0.11.0
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
