### ISSUE TITLE
Add support custom ingress definitions/annotations

### ISSUE THREAD

**Issue by abailie3** [kserve/kserve#3286]
/kind feature

**Describe the solution you'd like**
Currently, the ingress created by kserve does not appear to support the features required to make use of the nginx ingress controller. I _believe_ all that's required is to allow for the `tls` spec in the ingress def as well as custom ingress annotations like the following:

```
    external-dns.alpha.kubernetes.io/hostname: 
    nginx.ingress.kubernetes.io/backend-protocol: 
    nginx.ingress.kubernetes.io/use-regex: 
    nginx.ingress.kubernetes.io/rewrite-target: 
    ...etc...
```

**Anything else you would like to add:**
Our current work-around is to turn off the kserve-managed ingress, and create a custom ingress along with the `InferenceService`. However, this has caused issues in the migration from `v0.10` to `v0.11` because the existing InferenceServices (created in `v0.10`) are not updated to reflect the deployment change from `[isvc]-predictor-default` to `[isvc]-predictor`

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]
