### ISSUE TITLE
Create a InferenceService and report an error，lookup index.docker.io on 169.254.20.10:53: server misbehaving

### ISSUE THREAD

**Issue by FlyAIBox** [kserve/kserve#3346]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Create a InferenceService 
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: "torchserve"
  namespace: "kserve-test"
spec:
  predictor:
    pytorch:
     storageUri: pvc://task-pv-claim/mnist-pytorch
```

**What did you expect to happen:**
` Revision "torchserve-predictor-00001" failed with message: Unable to fetch image "pytorch/torchserve-kfs:0.8.2": failed to resolve image to digest: Get "https://index.docker.io/v2/": dial tcp: lookup index.docker.io on 169.254.20.10:53: server misbehaving`

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I created a normal Deployment resource (using nginx: 1.14.2 image,  import cluster) and run correctly
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

````

**Environment:**

- Istio Version: 1.17.2
- Knative Version: 1.10.1
- KServe Version:  0.11.2
- Kubernetes version: (use `kubectl version`):  1.27.2
- OS (e.g. from `/etc/os-release`): centos:7
- Network: Host host has no network,
- Domain name resolution: Host / etc/resolve.conf configuration is empty
- Image: knative-value, kserve-storage-initializer, pytorch-torchserve-kfs has been imported into the cluster

@rhuss @joesepi @matzew @lynnmatrix
