### ISSUE TITLE
Add Huggingface kserve runtime 

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#3393]
/kind feature

**Describe the solution you'd like**
This is a follow up for the [huggingface server implementation](https://github.com/kserve/kserve/pull/3334). We'd like to add this as official KServe runtime for serving huggingface model out of the box.

We need two serving runtimes :

* kserve-huggingface: the serving runtime has a single `kserve-container` hosting the huggingface model by calling the HF model API following inference protocol.
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: "huggingface"
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      runtime: kserve-huggingface
      storageUri: gs://kfserving-examples/models/huggingface
```

* kserve-huggingface-triton: the serving runtime has collocated `transformer-container` to run tokenization step and `kserve-container` container to perform the model inference by transmitting the input token ids to triton inference server for optimized performance.
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: "huggingface-triton"
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface-triton
      runtime: kserve-huggingface-triton
      storageUri: gs://kfserving-examples/models/huggingface
```
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]
