### ISSUE TITLE
Support multiple StorageUri in Inference Service

### ISSUE THREAD

**Issue by lizzzcai** [kserve/kserve#3413]
/kind feature

**Describe the solution you'd like**

Crrently KServe only supports one StorageUri, which fit most of the cases. However, in some scenarios like serving fine-tuned models like LoRA, base model and the LoRA adapters might come from different buckets (it is possible to put it into one but in some cases, it will not work if they belong to different owners). So allowing users to provide multiple storageUri will help in this case, similar to volumeMounts in K8s.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
As multiple storageUri are supported, user should be able to specify the destination of the mounted storage. Below is one of the example:
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: "huggingface"
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      runtime: kserve-huggingface
      storageUri:
      - src: gs://kfserving-examples/models/huggingface
        dest: /mnt/models
      - src: gs://kfserving-examples/adapters/huggingface
        dest: /mnt/adapters
```

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]

**Comment by skuchipu** [comment]
@lizzzcai  do we have runtime kserve-huggingface that comes with Kserve deployment ?

**Comment by lizzzcai** [comment]
Hi @skuchipu , sorry for the late reply. Yes, you can follow [this](https://github.com/kserve/kserve/issues/3393), it is already in `v0.12.0`.

example:

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: bloom
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      #runtime: kserve-huggingface
      args:
      - --model_id=bigscience/bloom-560m
      - --tensor_input_names=input_ids
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi
```

**Comment by Stannislav** [comment]
+1, we're also looking to deploy HuggingFace models with LoRA adapters in kserve, so support for multiple storage URIs would be appreciated.

**Comment by skonto** [comment]
If noone is working on this I can take a look.

**Comment by yuzisun** [comment]
> If noone is working on this I can take a look.

That would be great!!

**Comment by skonto** [comment]
@yuzisun @lizzzcai @terrytangyuan  hi, I was thinking of starting small with a per runtime extension (not all runtime support the feature ).
Then if we see that this is useful we can move to `PredictorExtensionSpec` or put it there anyway from the beginning.
WDYTH? Should I start with a design proposal with some real examples (if possible)?

```
index bc95fbed..ae109616 100644
--- a/pkg/apis/serving/v1beta1/predictor_huggingfaceruntime.go
+++ b/pkg/apis/serving/v1beta1/predictor_huggingfaceruntime.go
@@ -27,6 +27,7 @@ import (
 type HuggingFaceRuntimeSpec struct {
        // Contains fields shared across all predictors
        PredictorExtensionSpec `json:",inline"`
+       Loras                  []LoraSpec `json:"loras"`
 }

 package v1beta1
+
+// LoraSpec defines configuration for Loras
+type LoraSpec struct {
+       // This field points to the location of the adapter model which is mounted onto the pod.
+       // +optional
+       StorageURI       *string `json:"storageUri,omitempty"`
+       AdapterModelPath *string `json:"adapterModelPath,omitempty"`
+       AdapterModelId   *string `json:"adapterModelId,omitempty"`
+}
```

**Comment by lizzzcai** [comment]
Hi @skonto , I think the idea of starting small from a specified runtime looks good to me, like the huggingface runtime.

**Comment by skonto** [comment]
Cool I also see that vllm runtime has some special download capabilities now https://github.com/vllm-project/vllm/issues/6233 if the model is at the HF side which breaks the idea of Kserve downloading stuff directly. Also I think I could utilize the vllm example [here](https://github.com/kubernetes-sigs/llm-instance-gateway/pull/4/files#diff-d8d58cad7c906e09d57425900fcd479ba45dd11e157672e3ce5844be08b45210) for testing. I will take a look at the HF runtime first.

**Comment by zoramt** [comment]
Very interesting and timely work! Following...

**Comment by zoramt** [comment]
Maybe call the (optional) spec parameter `adapterStorageUri` so that we know it's different from the base/reference model artifact uri?

**Comment by abhinonymous** [comment]
@skonto ran into needing exactly this today! would love to know if you think theres a quick solution yet! 

in the meantime , would the following be a decent workaround?

to put the adaptors with the base models such that

1. the base model is in

```
s3://bucket/modeldir/huggingface
```

2. and adaptors are in 

```
s3://bucket/modeldir/adapter1_dir/
s3://bucket/modeldir/adapter2_dir/
```

and then 

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: bloom
spec:
  predictor:
    containers:    
      model:
        storageUri: s3://bucket/modeldir/
        modelFormat:
          name: huggingface
        args:
        - --lora-adapters=/mnt/models/adapter1_dir,/mnt/models/adapter2_dir
```
