### ISSUE TITLE
Ability to change parameters of of the default `initContainer` `storage-initializer`

### ISSUE THREAD

**Issue by averyngo34** [kserve/kserve#3451]
/kind feature

**Describe the solution you'd like**
I'd like to pull the `kserve-storage-initializer` directly from my own container registry or use a specific version, i.e, changing the `image` under `initContainers` `storage-initializer` of the predictor deployment. This could ideally be done in either `ServingRuntime` or `InferenceSever`, or both preferably. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Currently, I cannot override this with `spec.predictor.initContainers` as it simply adds an additional `initContainer` in addition to `storage-initializer` (even if `name: storage-initializer` is defined). `ServingRuntime.spec` does not have a field `initContainers` to override 

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]

**Comment by yuzisun** [comment]
@averyngo34 you can change the storage initializer image configuration in helm values file.
https://github.com/kserve/kserve/blob/master/charts/kserve-resources/values.yaml#L11

**Comment by israel-hdez** [comment]
When installing via Kustomize or pre-rendered manifests, this would be possible to change using the inferenceservice-config ConfigMap. See:https://github.com/kserve/kserve/blob/master/config/configmap/inferenceservice.yaml#L61.

I'm not sure if it would really be useful to customize the storage-initializer image per InferenceService or per ServingRuntime. That would sound like a use case for `ClusterStorageContainer`.

**Comment by averyngo34** [comment]
This is no longer needed, we will directly from redHat.

**Comment by tikr7** [comment]
For me it was in:
```
kubectl get ClusterStorageContainer default -o yaml

apiVersion: serving.kserve.io/v1alpha1
kind: ClusterStorageContainer
metadata:
  name: default
spec:
  container:
    image: kserve/storage-initializer:v0.15.2
    name: storage-initializer
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
  supportedUriFormats:
  - prefix: gs://
  - prefix: s3://
  - prefix: hdfs://
  - prefix: hf://
  - prefix: webhdfs://
  - regex: https://(.+?).blob.core.windows.net/(.+)
  - regex: https://(.+?).file.core.windows.net/(.+)
  - regex: https?://(.+)/(.+)
  workloadType: initContainer
```
