### ISSUE TITLE
 `predictor.model.args` defined in `InferenceService` does not override `containers.args` in `ServingRuntime`

### ISSUE THREAD

**Issue by averyngo34** [kserve/kserve#3453]
/kind bug

**What steps did you take and what happened:**
 When specifying both `args` field in `InferenceService` and `ServingRuntime`, the both `args` field are combined in a list which is then consumed by the predictor deployment  in the example shown below. In this example, the inference-predictor cannot start because the ` text-generation-launcher` command can only takes ` port value. 

```
  containers:
  - args:
    - --port=3000 
    - --port=3000
    - --grpc-port=8033
    - --num-shard=1
     command:
      - text-generation-launcher
```

**What did you expect to happen:**
 I'd expect the `predictor.model.args` defined in `InferenceService` to override `containers.args` in `ServingRuntime`

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
See above

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: N/A
- Knative Version: N/A
- KServe Version: 0.11
- Kubeflow version: N/A
- Cloud Environment: ibm
- Minikube/Kind version: N/A
- Kubernetes version: OCP 4.13 / K8s 1.26
- OS (e.g. from `/etc/os-release`): Linux
