### ISSUE TITLE
In the inference graph, does the serviceName field require the inference service name to be the same as the model name?

### ISSUE THREAD

**Issue by yolk-pie-L** [kserve/kserve#3526]
I have two inference services: one is called diffusers-test with a model name of sdxl-turbo, and the other is called emotions-test with a model name of emotions.

I deploy a simple inferece graph as follows:
```
apiVersion: "serving.kserve.io/v1alpha1"
kind: "InferenceGraph"
metadata:
  name: "simple-pipeline"
spec:
  nodes:
    root:
      routerType: Sequence
      steps:
      - serviceName: emotions-test
        name: emotions-test # step name
      - serviceName: diffusers-test
        name: diffusers-test
        data: $response
```

Then I try to test the inference graph by following python code, which is simply sending a request
```python
import requests
import time
import json


url = "http://aaa.elb.amazonaws.com"
headers = {
    "Content-Type": "application/json",
    "Host": "simple-pipeline.default.example.com"
}
with open('./input.json', 'r') as file:
    data = json.load(file)
    data = json.dumps(data)

a=time.time()
try:
    start = time.time()
    print("sending request...")
    response = requests.post(url, headers=headers, data=data, timeout=24*60*60)
    end = time.time()
    print("请求耗时：", end - start, "秒")
    print("服务器响应：", response.text)
except requests.exceptions.Timeout:
    print("请求超时。服务器没有在预定时间内响应。")
except requests.exceptions.RequestException as e:
    print("请求失败：", e)
b=time.time()
print("总耗时：", b - a, "秒")
```
