### ISSUE TITLE
transformer<->predictor deployment communication issue? 502 Bad Gateway 

### ISSUE THREAD

**Issue by cceyda** [kserve/kserve#3533]
/kind bug

**What steps did you take and what happened:**
I have a very basic transformer(custom)-predictor(triton inference server) deployment similar to this [example.](https://kserve.github.io/website/0.7/modelserving/v1beta1/triton/bert/#extend-modelserver-base-and-implement-prepostprocess). The service is auto-scaling based on rps (generously allocating resources). It works most of the time but looking at the logs 
I'm consistently seeing **a lot of** `502 Bad Gateway` errors while calling the predictor. (I don't see any specific errors on the predictor pod logs)

> '502 Bad Gateway' for url 'http://mymodel-predictor-default.default/v2/models/mymodel/infer

Note that this is different from the rare`504 Gateway Timeout` I see sometimes when the predictor is taking a bit long ( which I can fix by increasing the predictor timeout). I can see I have available predictor pods but somehow still end up with bad gateway (seemingly) randomly.(Calling triton without kserve I never had this problem)

**Questions**:
- What are the possible causes?
- How can I debug this? Could this be an istio networking issue, queue proxy issue? (honestly have no idea about this side of things)
- has anyone else had this problem?
- Is it possible to add a retry logic to the predictor (with something like tenacity for certain error codes)?

**What did you expect to happen:**
`http://mymodel-predictor-default.default/v2/models/mymodel/infer` calls shouldn't fail with 

**What's the InferenceService yaml:**
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mymodel
spec:
  predictor:
    volumes:
    - name: dshm
      emptyDir:
        medium: Memory 
        sizeLimit: 1Gi
    model:
      modelFormat:
        name: triton
      runtime: kserve-tritonserver
      storageUri: s3://[redacted]
      runtimeVersion: 23.10-py3
      imagePullPolicy: IfNotPresent
      args:
      - --log-verbose=0 # detailed logging 1,2...
      - --allow-grpc=false
      - --model-control-mode=explicit 
      - --load-model=mymodel
      env:
        - name: OMP_NUM_THREADS
          value: "1"
      volumeMounts:
      - mountPath: /dev/shm
        name: dshm
      resources:
        limits:
          cpu: "0.5"
          memory: 4Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "0.5"
          memory: 4Gi
  
  transformer:
    volumes:
    - name: model
      emptyDir: {}
    containers:
    - image: dev.local/mymodeltransformer:latest
      name: mymodel_transformer
      args:
      - python
      - serving.py
      - --model_name
      - mymodel
      - --protocol
      - v2
      resources:
        limits:
          cpu: "0.5"
          memory: 2Gi
        requests:
          cpu: "0.5"
          memory: 2Gi
```

**Anything else you would like to add:**

The only notable difference from the example codes deployment is that in my transformer I use async functions and call predictor like this because I need to pass some more info into the postprocessor:

 ```python
   async def predict(self, req: Dict, headers: Dict[str, str] = None) -> Dict:
      result = await super().predict(req["request"], headers)
      req["result"] = result
      return req
 ```

**Environment:**
I'm not the one controlling the development environment but afaik

- KServe Version: 0.11
- Cloud Environment: aws
- Kubernetes version: (use `kubectl version`): 1.27
- OS (e.g. from `/etc/os-release`): Linux

**Comment by cceyda** [comment]
Solved this by switching to GRPC communication between transformer<->predictor!
Be warned that if you use http endpoint and are transferring large arrays to your predictor(as is the case if your transformer is tokenizing your text like an llm processor into `input_ids`,`attention_mask`,`position_ids` etc) it will become a bottleneck.

**Just use GRPC** cannot emphasize it enough! It went from weird gateway errors, OOM errors & low throughput at 8rps to -> no weird errors & 128+rps!

add:
```
###
spec:
  predictor:
    triton:
      ...
      ports:
      - containerPort: 9000
        name: h2c
        protocol: TCP  
```
and start your transformer with `--predictor_protocol=grpc-v2` argument that is it!

Closing~
