### ISSUE TITLE
Explicitly specify pad token id when generating tokens

### ISSUE THREAD

**Issue by sivanantha321** [kserve/kserve#3536]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
We have added a [fallback pad token if it is not already present in the tokenizer](https://github.com/kserve/kserve/blob/11e0ab2ca4d852ec154156fad4f9d220c8768d78/python/huggingfaceserver/huggingfaceserver/model.py#L130-L131) as part of the PR #3459. But it does not explicitly specifies pad_token_id when invoking generate method which leads to huggingface using eos_token_id as the pad_token_id. The log from huggingface server is show below. To avoid this we should explicitly specify the pad_token_id
```
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
```

**What did you expect to happen:**
pad_token_id should be set accordingly.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: huggingface-gpt2
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - "--model_name=gpt2"
        - "--model_id=openai-community/gpt2"
        - "--tensor_input_names=input_ids"
        - "--disable_vllm"
        - "--task=6"
      env:
        - name: CUDA_LAUNCH_BLOCKING
          value: "1"
      resources:
        limits:
          nvidia.com/gpu: "1"
        requests:
          nvidia.com/gpu: "1"
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: master
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
