### ISSUE TITLE
Support download huggingface models in storage initializer

### ISSUE THREAD

**Issue by lizzzcai** [kserve/kserve#3545]
/kind feature

**Describe the solution you'd like**

I would like to use storage initializer to pull the huggingface [models](https://huggingface.co/models) which fits the KServe experience. StorageUri will be in this format: `hf://<repo>/<model>:<hash(optional)>`

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: bloom
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      #runtime: kserve-huggingface
      storageUri: hf://bigscience/bloom-560m:<hash>
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi
```

**Anything else you would like to add:**

Another option is to support any `Git LFS`.

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]

**Comment by jiangxiaobin96** [comment]
Hello, I have some questions about kServe model storage. 
If I have a model installed from huggingface and a python file to load model, how to use `InferenceService` CRD?
Like the following YAML, where is the python file to load model?
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: bloom
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      #runtime: kserve-huggingface
      storageUri: hf://bigscience/bloom-560m:<hash>
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi
```
