### ISSUE TITLE
Transformers don't deploy with ModelMesh InferenceService in RawDeployment mode

### ISSUE THREAD

**Issue by slik13** [kserve/kserve#3553]
/kind bug

**What steps did you take and what happened:**

When defining an InferenceService with the modelmesh annotation it's suppose to be able to handle transformers by delegating the reconciling of it to the kserve controller instead of the modelmesh serving one. One issue I'm hitting is that it is currently only working if the underlying deployment mode is `Serverless` and not `RawDeployment`. This appears to be only a problem of the logic "falling through" an if statement here: https://github.com/kserve/kserve/blob/master/pkg/controller/v1beta1/inferenceservice/components/transformer.go#L171

Since the inferenceService is using ModeMesh as it's deployment mode, it's not covered in the check for creating the service for the transformer. That seems to be a mistake and not intentional as there's no hard dependency to using serverless for modelmesh.

Instead the controller should fall back on the `defaultDeploymentMode` entry in the configmap to figure out which deployment mode should be used to create the transformer deployment and services.

**What did you expect to happen:**

Transformers should not try and create a knative service when using a ModelMesh predictor and KServe is deployed using RawDeployment mode. 

**What's the InferenceService yaml:**

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
  name: resnet
  namespace: kserve
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      name: ""
      storage:
        key: localMinIO
        path: resnet
  transformer:
    containers:
    - args:
      - --model_name
      - resnet
      - --predictor_protocol
      - grpc-v2
      command:
      - python
      - -m
      - custom_transformer.model_grpc
      image: custom-image-transformer-grpc:v0.1.5
      name: kserve-container
      ports:
      - containerPort: 8081
        name: h2c
        protocol: TCP
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi
```

**Anything else you would like to add:**
I've got a working fix locally that I will create a PR for and attach to this issue shortly.

**Environment:**

- Istio Version: N/A
- Knative Version: N/A
- KServe Version: v0.12.0
- Kubeflow version: N/A
- Cloud Environment: kubernetes on prem
- Minikube/Kind version: N/A
- Kubernetes version: (use `kubectl version`): 1.28
- OS (e.g. from `/etc/os-release`): rhel8
