### ISSUE TITLE
Add ability to InferenceGraph to passTrough custom annotations 

### ISSUE THREAD

**Issue by trojaond** [kserve/kserve#3554]
/kind bug

**What steps did you take and what happened:**
Created a InferenceGraph with custom annotation: `custom.annotation/hostname: xxx` this annotaton is not propagated to downstream Knative service.

**What did you expect to happen:**
Expect this annotation to be propagated to downstream KNative Service

**What's the InferenceGraph yaml:**
```
apiVersion: serving.kserve.io/v1alpha1
kind: InferenceGraph
metadata:
  annotations:
    custom.annotation/hostname: test
  labels:
    app.kubernetes.io/instance: test
  name: test
  namespace: default
spec:
  nodes:
    root:
      routerType: Sequence
      steps:
        - name: test-transformer
          serviceName: test-transformer
        - data: $response
          name: test-predictor
          serviceName: test-predictor
```

**Anything else you would like to add:**
There is a precedence for passthrough annotation `serving.knative.openshift.io/enablePassthrough: 'true'` That is explicitly passed [here](https://github.com/kserve/kserve/blob/56b8fe0d189fc0d557e9a8af07eab0c12852d5fd/pkg/controller/v1alpha1/inferencegraph/knative_reconciler.go#L163)

This ability to pass annotations is convenient because it allows to dynamically generate dns records using tools such as external-dns on istio `virtualService` 

**Environment:**

- Istio Version: v1.12.0
- Knative Version: v1.12.2
- KServe Version: v0.12.0
- Cloud Environment:[k8s_istio]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): v1.29.1
