### ISSUE TITLE
Native integration with KEDA for LLM inference autoscaling

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#3561]
/kind feature

**Describe the solution you'd like**
To autoscale LLM inference services Knative's request level metrics may not be the best scaling metrics as LLM inference is performed at the token level and we need to understand the number of input/output tokens to scale. To effectively autoscale LLM inference services, we'd like to scale based on metrics like token throughput, power consumption. 

In order to achieve this Autoscaler needs to be able to query metrics from prometheus. KEDA supports [scaling based on prometheus metrics](https://keda.sh/docs/1.4/scalers/prometheus/) and we would like to implement a native integration with KEDA for both serverless and raw deployment mode to support autoscaling LLM inference out of the box.

A few important metrics:
* Time To First Token (TTFT): Low waiting times for a response are essential in real-time interactions, but less important in offline workloads.
* Time Per Output Token (TPOT): Time to generate an output token for each user that is querying our system. This metric corresponds with how each user will perceive the "speed" of the model.
* Latency: The overall time it takes for the model to generate the full response for a user. Overall response latency can be calculated using the previous two metrics: latency = (TTFT) + (TPOT) * (the number of tokens to be generated). 
* Throughput: The number of output tokens per second an inference server can generate across all users and requests. 
* Power consumption: Metrics produced by [Kepler](https://github.com/sustainable-computing-io/kepler), e.g kepler_container_joules_total.

**Anything else you would like to add:**
- Knative has a PoC to integrate with KEDA and @skonto is [creating a new repo](https://github.com/knative/community/issues/1527) for `serving-keda` under knative-extensions org.
- For Raw Deployment mode we can provision the `ScalerObject` in kserve controller and allow user to specify the metrics query on `InferenceService` spec. 

```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "llama2-vllm"
spec:
  predictor:
    scaleQuery: "average_token_throughput_per_second[1m]"
    scaleMetric: custom
    maxReplicas: 10
    minReplicas: 1
    model:
      modelFormat:
        name: huggingface
      storageUri: "gs://kfserving-examples/models/huggingface/llama2-70b"
```

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaleObject
metadata:
  name: llama2-vllm-scaleobject
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llama2-vllm-deployment
  pollingInterval: 15
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server
        metricName: average_token_per_second
        query: average_token_per_second[1m]
        threshold: "500"
```

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]
