### ISSUE TITLE
Autoscaling with multiple metrics does not work

### ISSUE THREAD

**Issue by shazinahmed** [kserve/kserve#3638]
/kind bug

**What steps did you take and what happened:**
Tried the following

1. Tried creating memory based autoscaling using knative annotations as below. A CPU based HPA was created instead with averageUtilization set to 80.

>     autoscaling.knative.dev/class: "hpa.autoscaling.knative.dev"
>     autoscaling.knative.dev/metric: "memory"
>     autoscaling.knative.dev/target: "75"

2. Tried creating memory based autoscaling using kserve annotations as below. A CPU based HPA was created instead with averageUtilization set to 80.

>     serving.kserve.io/autoscalerClass: hpa
>     serving.kserve.io/deploymentMode: RawDeployment
>     serving.kserve.io/metric: memory
>     serving.kserve.io/targetUtilizationPercentage: "70"

3. Tried creating memory based autoscaling by setting `predictor.scaleMetric` to `memory` and a memory based HPA was created. Yaay!

 In scenario 1 and 2 HPAs are created as expected if the metric is set as `cpu`.

Now, I want my HPA to be controlled by both memory and CPU. I tried setting `predictor.scaleMetric` to `memory` and a corresponding `scaleTarget`. Also set CPU thresholds using `serving.kserve.io/metric: cpu`. But only `predictor.scaleMetric` is respected. 

**What did you expect to happen:**
I want HPA to have both memory and CPU based triggers. 

**What's the InferenceService yaml:**
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/autoscalerClass: hpa
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/metric: cpu
    serving.kserve.io/targetUtilizationPercentage: "70"
  name: custom-model
  namespace: dev-xyz-multimodal-ner
spec:
  predictor:
    containers:
    - env:
      - name: AWS_BUCKET
        value: xyz-xyz-xyz-xyz-xyz-xyz
      image: <custom image>
      name: kserve-container
      resources:
        limits:
          cpu: "4"
          memory: 6Gi
        requests:
          cpu: "1"
          memory: 2Gi
    maxReplicas: 4
    nodeSelector:
      nodetype: modelserving
    scaleMetric: memory
    scaleTarget: 75
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: modelserving
```

**Anything else you would like to add:**
The HPA YAML inferenceservice generates
```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    serving.kserve.io/autoscalerClass: hpa
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/metric: cpu
    serving.kserve.io/targetUtilizationPercentage: "80"
  name: custom-model-predictor-default
  namespace: dev-xyz-multimodal-ner
  ownerReferences:
  - apiVersion: serving.kserve.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: InferenceService
    name: custom-model
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 15
        type: Percent
        value: 100
      selectPolicy: Max
    scaleUp:
      policies:
      - periodSeconds: 15
        type: Pods
        value: 4
      - periodSeconds: 15
        type: Percent
        value: 100
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  maxReplicas: 4
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 75
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: custom-model-predictor-default
```

**Environment:**

- Istio Version: N/A (Using nginx)
- Knative Version: N/A (Using Kubernetes deployment)
- KServe Version: 0.11.0
- Kubeflow version:
- Cloud Environment:[AWS EKS]
- Minikube/Kind version:
- Kubernetes version: v1.28.7-eks-b9c9ed7
- OS (e.g. from `/etc/os-release`): Amazon Linux 2
