### ISSUE TITLE
protocolVersion used by the predictor 

### ISSUE THREAD

**Issue by Csehpi** [kserve/kserve#3674]
Hi community,

I am trying to understand how `protocolVersion` is used by the predictor and I would like to ask some help from you.

Here is a little example:
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-from-uri
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      protocolVersion: v1
      runtime: kserve-sklearnserver
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
```

The doc says: _Protocol version to use by the predictor (i.e. v1 or v2 or grpc-v1 or grpc-v2)_
https://kserve.github.io/website/latest/reference/api/#serving.kserve.io/v1beta1.PredictorExtensionSpec

When pod, service, etc. is ready then I am able to call both V1 and V2 endpoints. Is this the expected behaviour?

Thanks,
Peter
