### ISSUE TITLE
ClusterRole permissions are too broadly scoped?

### ISSUE THREAD

**Issue by jssnirmal** [kserve/kserve#3724]
/kind question

Hello team,

I have a general question. I noticed that the permissions defined in the [kserve-manager-role](https://github.com/kserve/kserve/blob/v0.12.1/charts/kserve-resources/templates/clusterrole.yaml#L97-L108) for kserve-controller-manager are broadly scoped. For example:

````
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
````

This broad scope poses a security risk for us due to our compliance requirements. Is there a specific reason the role needs cluster-wide access to secrets? or can it be scoped down to certain namespaces? please advise

Thank you
