### ISSUE TITLE
Reconciler error while creating InferenceService: failed to call webhook kserve-webhook-server-service.kserve.svc context deadline 

### ISSUE THREAD

**Issue by rosemorozenkova** [kserve/kserve#3770]
/kind bug

### **What steps did you take and what happened:**
I am trying to start quick-start example with sklearn-iris-predictor. 

_Problem:_ webhook that is called when I create InferenceService doesn't work during longtime (~several hours) and then suddenly it works and creates the service.

What I see in the logs of kserve-controller-manager pod:

```log
{"level":"info","ts":"2024-06-28T13:36:26Z","logger":"v1beta1Controllers.InferenceService","msg":"Inference service deployment mode ","deployment mode ":"Serverless"}
{"level":"error","ts":"2024-06-28T13:36:36Z","msg":"Reconciler error","controller":"inferenceservice","controllerGroup":"serving.kserve.io","controllerKind":"InferenceService","InferenceService":{"name":"sklearn-iris","namespace":"app-kserve"},"namespace":"app-kserve","name":"sklearn-iris","reconcileID":"70cc0679-6371-40ab-b5cb-59abfa3c882f","error":"Internal error occurred: failed calling webhook \"inferenceservice.kserve-webhook-server.defaulter\": failed to call webhook: Post \"https://kserve-webhook-server-service.kserve.svc:443/mutate-serving-kserve-io-v1beta1-inferenceservice?timeout=10s\": context deadline exceeded","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
```

These 👆 two lines are constantly repeated. And manager-pod tries this hook again and again till it succeeds. But it takes a lot of time to eventually create InferenceService and start the predictor pod.

I tried to follow debug guide but it offers solution when predictor pod have been already created :( 

The consequence of this problem is that when I try to delete this InferenceService it hangs indefinitely because the webhook timeouts the same way.  

### **What did you expect to happen:**
InferenceService must start immediately and webhook must be stable and send respond immediately. 

### **What's the InferenceService yaml:**
<details>

<summary>InferenceService</summary>

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: s3creds
  annotations:
    serving.kserve.io/s3-endpoint: *** # replace with your s3 endpoint e.g minio-service.kubeflow:9000
    serving.kserve.io/s3-usehttps: "1" # by default 1, if testing with minio you can set to 0
    serving.kserve.io/s3-region: "***"
    serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
type: Opaque
stringData: 
  AWS_ACCESS_KEY_ID: "****"
  AWS_SECRET_ACCESS_KEY: "****"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-model-serving
secrets:
  - name: s3creds
---
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    serviceAccountName: s3-model-serving
    model:
      modelFormat:
        name: sklearn
      storageUri: "s3://***/model/"
---
```

</details>

<details>

<summary>How I start it</summary>

```bash
$ kubectl create ns app-kserve
$ kubectl apply -n app-kserve -f app/sklearn-iris.yaml
```

</details>

<details>

<summary>Other debug info</summary>

```bash
$ kubectl get MutatingWebhookConfiguration
NAME                                            WEBHOOKS   AGE
cert-manager-webhook                            1          37d
inferenceservice.serving.kserve.io              2          2d20h
kyverno-policy-mutating-webhook-cfg             1          6d19h
kyverno-resource-mutating-webhook-cfg           0          6d19h
kyverno-verify-mutating-webhook-cfg             1          6d19h
prometheus-crd-kube-promet-admission            1          37d
vault-secrets-webhook                           2          37d
webhook.domainmapping.serving.knative.dev       1          7d3h
webhook.istio.networking.internal.knative.dev   1          7d3h
webhook.serving.knative.dev                     1          7d3h
```

```bash
$ kubectl get deployments -n kserve
NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
kserve-controller-manager   1/1     1            1           3d1h
```

```bash
$ kubectl get svc -n kserve
NAME                                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
kserve-controller-manager-metrics-service   ClusterIP   10.247.226.182   <none>        8443/TCP   3d1h
kserve-controller-manager-service           ClusterIP   10.247.223.224   <none>        8443/TCP   3d1h
kserve-webhook-server-service               ClusterIP   10.247.23.248    <none>        443/TCP    3d1h
```

```bash
$ kubectl get svc -n knative-serving
NAME                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                   AGE
activator-service            ClusterIP   10.247.12.149    <none>        9090/TCP,8008/TCP,80/TCP,81/TCP,443/TCP   7d3h
autoscaler                   ClusterIP   10.247.125.141   <none>        9090/TCP,8008/TCP,8080/TCP                7d3h
autoscaler-bucket-00-of-01   ClusterIP   10.247.67.20     <none>        8080/TCP                                  7d3h
controller                   ClusterIP   10.247.148.105   <none>        9090/TCP,8008/TCP                         7d3h
domainmapping-webhook        ClusterIP   10.247.167.62    <none>        9090/TCP,8008/TCP,443/TCP                 7d3h
net-istio-webhook            ClusterIP   10.247.66.37     <none>        9090/TCP,8008/TCP,443/TCP                 7d3h
webhook                      ClusterIP   10.247.66.197    <none>        9090/TCP,8008/TCP,443/TCP                 7d3h
```

</details>

### **Anything else you would like to add:**
I test KServe installation in fully isolated "fresh" K8S cluster with no access to the web. 
I installed KNative + Istio from scratch following documentation guides.

### **Environment:**

- Istio Version: 1.16.7
- Knative Version: 1.9.4
- KServe Version: 0.13.0
- Kubeflow version: no Kubeflow
- Cloud Environment: isolated cloud
- Kubernetes version: 1.25.8-r0-25.4.22.6

Please help 🙏
