### ISSUE TITLE
Resource requests and limits not respected / Usage of EmptyDir volume "models-dir" exceeds the limit "1536Mi"

### ISSUE THREAD

**Issue by Zeashh** [kserve/kserve#3792]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

We're trying to test out KServe by deploying [Gemma 2B](https://huggingface.co/google/gemma-2b) using S3 as the storage backend and Triton as the serving runtime, using only CPUs and no GPUs (for now). After applying the InferenceService YAML file (provided below), `modelmesh-serving` containers start running, but eventually enter either "ContainerStatusUnknown" or "Completed" states with the error:

```
  Warning  Evicted            5s    kubelet            Usage of EmptyDir volume "models-dir" exceeds the limit "1536Mi".
  Normal   Killing            5s    kubelet            Stopping container rest-proxy
  Normal   Killing            5s    kubelet            Stopping container mm
  Normal   Killing            5s    kubelet            Stopping container triton-adapter
  Normal   Killing            5s    kubelet            Stopping container triton
  Warning  FailedPreStopHook  2s    kubelet            Exec lifecycle hook ([/opt/kserve/mmesh/stop.sh wait]) for Container "mm" in Pod "modelmesh-serving-triton-2.x-fdb8db4c4-22254_kserve(ab25c32d-3e07-44da-bbbd-60a9466f5ace)" failed - error: command '/opt/kserve/mmesh/stop.sh wait' exited with 137: , message: "waiting for litelinks process to exit after server shutdown triggered\n"
```

For reference, the model file `gemma-2b.gguf` is about 10 GB in size. Storage works properly as far as I can tell.

Additionally, as seen below, we set resource requests and limits for the predictor, which are not respected on any of the modelmesh-serving-* pods or their containers. I'm not sure if this is intended behavior.

Finally, I will note that trying to apply [this example InferenceService](https://kserve.github.io/website/master/modelserving/v1beta1/llm/huggingface/text_generation/#serve-the-hugging-face-llm-model-using-vllm-backend) (albeit with reduced resource requests and limits due to our test cluster's constraints) results in one log line on the controller and nothing else:

``` json
{"level":"info","ts":"2024-07-15T08:41:18Z","logger":"controllers.Predictor","msg":"VModel removed","vmodelId":"huggingface-llama3","namespace":"kserve"}
```

```
$ kubectl get inferenceservices.serving.kserve.io

NAME                 URL   READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION   AGE 
huggingface-llama3                                                                               3m15s
```

**What did you expect to happen:**

I expected Gemma-2b to be deployed successfully, its resource requests and limits to be respected, as well as the example InferenceService to work as described in the documentation.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

``` yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: gemma-2b
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      protocolVersion: v2
      storage:
        key: kserve-lab
        path: gemma-2b.gguf
      resources:
        limits:
          memory: 8Gi
        requests:
          cpu: "2"
          memory: 8Gi
```

**Environment:**

- KServe Version: [this release](https://github.com/kserve/modelmesh-serving/releases/tag/v0.12.0) of modelmesh-serving, installed using [this guide](https://github.com/kserve/modelmesh-serving/blob/release-0.11/docs/install/install-script.md)
- Kubernetes version: (use `kubectl version`): v1.25.14
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS (Focal Fossa)

**Comment by lizzzcai** [comment]
For the modelmesh, it seems like the size of the models-dir is limited by the [memory limit](https://github.com/kserve/modelmesh-serving/blob/f8cc7aa73f6a9360d7635ca5e5c3461d0c60b392/controllers/modelmesh/runtime.go#L59). In this case you probably need to use a big node and set higher memory limit. Same should apply for non modelmesh deployment. And this should be fix by this [issue](https://github.com/kserve/kserve/issues/3687) to use a PVC instead of EmptyDir.

**Comment by Zeashh** [comment]
> For the modelmesh, it seems like the size of the models-dir is limited by the [memory limit](https://github.com/kserve/modelmesh-serving/blob/f8cc7aa73f6a9360d7635ca5e5c3461d0c60b392/controllers/modelmesh/runtime.go#L59). In this case you probably need to use a big node and set higher memory limit. Same should apply for non modelmesh deployment. And this should be fix by this [issue](https://github.com/kserve/kserve/issues/3687) to use a PVC instead of EmptyDir.

According to that code, empty dir size should be 1.5 times greater than the memory limit. However, in the previously shown InferenceService, the memory limit is set to 8 GB, while EmptyDir size is 1.5 GB. That value only makes sense for default resource requests and limits, which we can see in the ServingRuntime:

``` yaml
kind: ServingRuntime
metadata:
  generation: 1
  labels:
    ...
  name: triton-2.x
  namespace: kserve
spec:
  builtInAdapter:
    memBufferBytes: 134217728
    modelLoadingTimeoutMillis: 90000
    runtimeManagementPort: 8001
    serverType: triton
  containers:
  - args:
    - -c
    - 'mkdir -p /models/_triton_models; chmod 777 /models/_triton_models; exec tritonserver
      "--model-repository=/models/_triton_models" "--model-control-mode=explicit"
      "--strict-model-config=false" "--strict-readiness=false" "--allow-http=true"
      "--allow-sagemaker=false" '
    command:
    - /bin/sh
    image: nvcr.io/nvidia/tritonserver:23.04-py3
    livenessProbe:
      exec:
        command:
        - curl
        - --fail
        - --silent
        - --show-error
        - --max-time
        - "9"
        - http://localhost:8000/v2/health/live
      initialDelaySeconds: 5
      periodSeconds: 30
      timeoutSeconds: 10
    name: triton
    resources:
      limits:
        cpu: "5"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
...
```

I'm not sure if I'm misunderstanding the `resources` field in an InferenceService, but shouldn't it change these values, or should I define a new ServingRuntime with higher limits?
