### ISSUE TITLE
Large model deployment timesout

### ISSUE THREAD

**Issue by manstis** [kserve/kserve#3795]
/kind bug

**What steps did you take and what happened:**
When trying to deploy a large model (e.g. `granite-20b-code-instruct`) the `Pod` terminates before completion.

I use a `ServingRuntime` resource and `InferenceService` for single model serving; both attached.

The `kserve-container` takes longer than 5 minutes to deploy.

After this time the `kserve-container`, `queue-proxy` and `istio-proxy` containers are all terminated.

A `TERM` signal is seen to have been received by `queue-proxy`.

I'd like to be able to define something like a `startupProbe` but understand `knative-serving` handles readiness/liveliness differently. I'm guessing `queue-proxy` is not able to return "OK", "All well and good" etc within 5 minutes and k8s is therefore killing it?!?!  

**What did you expect to happen:**
I'd like to be able to configure startup to accommodate large models that take a long time to provision.

**What's the `ServingRuntime` yaml:**
Attached.

**What's the `InferenceService` yaml:**
Attached.

**Anything else you would like to add:**
`kserve-container`, `queue-proxy` and `istio-proxy` logs attached.

[resources.zip](https://github.com/user-attachments/files/16247077/resources.zip)

**Environment:**

- Istio Version:
```
client version: 1.14.0
control plane version: OSSM_2.5.2
data plane version: 1.18.7 (6 proxies)
```
- Knative Version: 1.12
- KServe Version: 
- Kubeflow version:
- Cloud Environment: k8s_istio
- Minikube/Kind version: Red Hat Openshift 4.14.3
- Kubernetes version: (use `kubectl version`):
```
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.14+7852426
```
- OS (e.g. from `/etc/os-release`):

**Comment by sivanantha321** [comment]
@manstis You should be able to use all the container spec. It is exposed under `model` field. https://kserve.github.io/website/latest/reference/api/#serving.kserve.io/v1beta1.PredictorExtensionSpec
```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  labels:
    test: "test"
spec:
  predictor:
    minReplicas: 0
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
      protocolVersion: "v2"
      readinessProbe:
        httpGet:
          path: /v2/models/sklearn-iris/ready
          port: 8080
```

**Comment by manstis** [comment]
I have a `readinessProbe` defined; and this is OK `queue-proxy` can be seen to keep trying.

The generated `serving.knative.dev/v1` / `Service` has my probe incorporated into its definition.

I believe `knative-serving` [re-writes](https://knative.dev/docs/serving/services/configure-probing/) _my_ `readinessProbe`

> Readiness probes, on the other hand, are rewritten by Knative to be executed by the Queue-Proxy container

I cannot find how I might configure a `startupProbe` to prevent `queue-proxy` from being killed.

**Comment by sivanantha321** [comment]
@manstis This [PR](https://github.com/knative/docs/pull/6042/files) has documentation on startup probes with knative. It might help you

**Comment by manstis** [comment]
@sivanantha321 I'm not creating a `knative` `Service` myself; I am only using `ServingRuntime` and `InferenceService`.

I _could_ patch the generated `Service` to add a `startupProbe` but IMO I should not need to.

But thank-you for the link; it is something else I can try if all else fails.

**Comment by sivanantha321** [comment]
@manstis You can try modifiying the [`progress-deadline`]( https://knative.dev/docs/serving/configuration/deployment/) in the knative configmap. That being said, the startup probe is not supported by the knative yet. I think it will be available in next release.

**Comment by manstis** [comment]
Thanks @sivanantha321 I've tried setting the `progess-deadline` already to no avail :cry: 

I think I'm going to have to wait.

**Comment by sivanantha321** [comment]
@manstis I tried to reproduce this by sleeping for 15 mins before starting the server. But I am unable to reprdouce this. I have not changed any configs in Knative. The server started after 15 mins. Note: once the pod is ready, it will be taken down if no traffic is received for 30s as the scale-to-zero is enabled by default.

**Comment by manstis** [comment]
@sivanantha321 I very much appreciate you looking. Can you share your YAML so that I can confirm your findings? The scale to zero is an interesting comment.. can it be prevented (even if just for my experiments)?

**Comment by manstis** [comment]
@sivanantha321 I read [this](https://kserve.github.io/website/0.8/modelserving/autoscaling/autoscaling/#autoscaling-with-containerconcurrency) which suggests scale to zero is disabled by default. I'm certain my min replica is 1 but will check when home.

**Comment by manstis** [comment]
@sivanantha321 I have `minReplica: 1` so I would not expect my deployment to be scaled to zero.

If you can share your YAML I'll happily try it here.. it might give me some ideas.

**Comment by sivanantha321** [comment]
ISVC:
```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  labels:
    test: "test"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
      runtime: "kserve-sklearnserver"
      protocolVersion: "v2"
      readinessProbe:
        httpGet:
          path: /v2/models/sklearn-iris/ready
          port: 8080
```
ClusterServingRuntime:
```yaml
apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
spec:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: '8080'
  containers:
    - args:
        - '--model_name={{.Name}}'
        - '--model_dir=/mnt/models'
        - '--http_port=8080'
      image: docker.io/sivanantha/sklearnserver:latest
      name: kserve-container
      resources:
        limits:
          cpu: '1'
          memory: 2Gi
        requests:
          cpu: '1'
          memory: 2Gi
  protocolVersions:
    - v1
    - v2
  supportedModelFormats:
    - autoSelect: true
      name: sklearn
      priority: 1
      version: '1'
```
You can pass --sleep argument to configure the sleep time. By default it will 900 seconds
