### ISSUE TITLE
TLS with S3 Outside ConfigMap

### ISSUE THREAD

**Issue by bwhartlove** [kserve/kserve#3799]
/kind feature

**Describe the solution you'd like**
If I am understanding correctly from these [docs](https://kserve.github.io/website/latest/modelserving/certificate/kserve/#using-storage-config-secret), in order to set-up certificate validation to an s3 instance, you have to make a `cabundle.crt` key in a ConfigMap, which would seem like less than ideal way to store the data from a security perspective. It'd be great if there was a way to mount the secret into the inference service pod to keep from storing cert data in plain text. Please let me know if I'm misunderstanding the workflow here. Thanks!

**Comment by lizzzcai** [comment]
Thanks for opening an issue. Are you referring to put the cabundle in the secret like this:

```
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: VEhFQUNDRVNTS0VZ
  AWS_SECRET_ACCESS_KEY: VEhFUEFTU1dPUkQ=
  AWS_CA_BUNDLE: xxxxxxxxx # <====
kind: Secret
metadata:
    ...
  name: storage-config
  namespace: kserve-demo
type: Opaque
```
