### ISSUE TITLE
Triton Inference Server  Doesn't Returning Expected Response on Model Endpoint

### ISSUE THREAD

**Issue by Raghul-M** [kserve/kserve#3820]
/kind bug

**What steps did you take and what happened:**

Based on the below configuration, we deployed the ONNX , Tensorflow model from [triton/server/model_repository](https://github.com/triton-inference-server/server/tree/main/docs/examples/model_repository)   on  the Triton Runtime for Inferencing in Redhat Openshift AI for KServe. We checked the endpoints mentioned in the [KServe/Open Inference Protocol](https://kserve.github.io/website/master/modelserving/data_plane/v2_protocol/) doesn't returning the expected output .Is this Expected for Triton server in kserve. But In Triton Documentation they mentioned [triton-inference-server/server](https://github.com/triton-inference-server/server/blob/main/docs/getting_started/quickstart.md#verify-triton-is-running-correctly).Something different

 
**What did you expect to happen:**
- Server Ready endpoint ( v2/health/ready )
-  Model Ready endpoint ( v2/models/<model_name>/ready )
- Server Live ( v2/health/live )

The above Endpoints doesn't returning Expected results and content. Is this Expected or not .

**What's the InferenceService yaml:**
```
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: kserve-tritonserver
spec:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: "8002"
  containers:
    - args:
        - tritonserver
        - --model-store=/mnt/models
        - --grpc-port=9000
        - --http-port=8080
        - --allow-grpc=true
        - --allow-http=true
      image: nvcr.io/nvidia/tritonserver:23.05-py3
      name: kserve-container
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi
      ports:
        - containerPort: 8080
          protocol: TCP
  protocolVersions:
    - v2
    - grpc-v2
  supportedModelFormats:
    - autoSelect: true
      name: tensorrt
      priority: 1
      version: "8"
    - autoSelect: true
      name: tensorflow
      priority: 1
      version: "1"
    - autoSelect: true
      name: tensorflow
      priority: 1
      version: "2"
    - autoSelect: true
      name: onnx
      priority: 1
      version: "1"
    - name: pytorch
      version: "1"
    - autoSelect: true
      name: triton
      priority: 1
      version: "2"
```

**Anything else you would like to add:**

When we curl the endpoint we are Getting this Result :
![Screenshot from 2024-07-18 14-32-01](https://github.com/user-attachments/assets/f2d2f9c9-fd61-4d1e-9830-8fde1ffe8587)
but the response mentioned in Kserve/open-inference-protocol documentation :
![image](https://github.com/user-attachments/assets/78627887-d0ce-4535-ba85-761ed8d47ade)

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version: Redhat Openshift 4.13.9
- Kubernetes version: (use `kubectl version`):

```
Client Version: 4.13.9
Kustomize Version: v4.5.7
Server Version: 4.14.31
Kubernetes Version: v1.27.14+7852426

```
- OS (e.g. from `/etc/os-release`):

cc: @terrytangyuan
