### ISSUE TITLE
Support multiple inference loggers

### ISSUE THREAD

**Issue by ruivieira** [kserve/kserve#3836]
/kind feature

**Describe the solution you'd like**
At the moment, Inference Services can specify a single Inference Logger with

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-iris
spec:
  predictor:
    logger:
      mode: all
      url: ...
```
In certain scenarios it is useful to specify multiple logging destinations directly from the Inference Service, without any additional component. For instance to support multiple logging backends, such as analytics, data post-processing or security audits.

A proposed solution would be to introduce a new (optional) `additionalLoggers` field/array, such that

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-iris
spec:
  predictor:
    logger:
      - mode: ...
        url: ...
    additionalLoggers:
      - mode: all
        url: ...
      - mode: ...
        url: ...
```

is possible. Adding a new (optional) field would keep compatibility with the current `InferenceService` API.

**Anything else you would like to add:**
As a concrete example, TrustyAI uses the Inference Logger mechanism to aggregate inference information an calculate metrics.
However if a logger is already present for other purposes, it would need to be replaced by TrustyAI's own logging endpoint.

cc @terrytangyuan @danielezonca

---
_Update 5th August 2024_

Changed "replacing logger" with "adding a new optional field".
