### ISSUE TITLE
vllm logging is disabled in the latest nightly version of HuggingFace serving runtime

### ISSUE THREAD

**Issue by romanwozniak** [kserve/kserve#3848]
/kind bug

**What steps did you take and what happened:**
After the vllm version was upgraded from `0.4.3` to `0.5.3.post1` [here](https://github.com/kserve/kserve/pull/3828), InferenceService served via `huggingface` serving runtime is no longer producing in-container logs to log received request. 

The last stable release of huggingfaceserver (`kserve/huggingfaceserver:0.13.1`) was producing in-container requests for each inference request, similar to this:
```
Received request %s: prompt: %r, params: %s, prompt_token_ids: %s ...
```
However, after the vllm was upgraded to `0.5.3.post1` these log messages are no longer present in the log feed. At the same time, some other vllm logs are still being produced, e.g. generation metrics logs:
```
2024-08-08 14:28:29.602 uvicorn.access INFO:     10.21.192.22:0 1 - "POST /openai/v1/chat/completions HTTP/1.1" 200 OK
INFO 08-08 14:28:29 metrics.py:396] Avg prompt throughput: 0.3 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%.
INFO 08-08 14:28:34 metrics.py:396] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%.
```

The expected request log is produced by the `RequestLogger` [here](https://github.com/vllm-project/vllm/blob/38c4b7e863570a045308af814c72f4504297222e/vllm/entrypoints/logger.py#L36), and I can't find any changes in the vllm code indicating the change in behaviour from v0.4.3 to v0.5.3.post1.

**What did you expect to happen:**
Having a request log makes it easier to debug the problem with model chat templates and provides better visibility into system behaviour. 
I would expect to still have request logging enabled by default, with an option to disable it by passing `--disable-log-requests` flag to vllm ([Ref](https://docs.vllm.ai/en/latest/models/engine_args.html#async-engine-arguments))

**What's the InferenceService yaml:**
```yaml
kind: InferenceService
metadata:
  name: huggingface-llama3
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=llama3
        - --model_id=meta-llama/meta-llama-3-8b-instruct
      resources:
        limits:
          cpu: "6"
          memory: 24Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "6"
          memory: 24Gi
          nvidia.com/gpu: "1"
```

**Environment:**

- Istio Version: 1.22.x
- Knative Version: 1.14.1
- KServe Version: 0.13.1 
- HuggingFaceServer – Based on https://github.com/kserve/kserve/commit/96fb00e8e12ba4c4cf3dc68a6c7cd445a3f7c3b2
- vllm - 0.5.3.post1
