### ISSUE TITLE
InferenceService in version "v1beta1" cannot be handled as a InferenceService: strict decoding error: unknown field "spec.predictor.podSpec"

### ISSUE THREAD

**Issue by zhouxinlun** [kserve/kserve#3859]
/kind bug

**What steps did you take and what happened:**
This exception was reported when I used the official documentation to deploy the model with the following configuration, I checked the official documentation where you can configure a pod container using the PodSpec property

**What did you expect to happen:**
I wonder if I can mount the deployment directly from the kserve startup container without pulling the online model when I download the huggingface model offline

**What's the InferenceService yaml:**
(base) root@kemove-Super-Server:/data/docker-file# cat gemma-2-9b.yaml 
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: huggingface-gemma-2-9b
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      storageUri: "file:///data/ai/model/gemma-2-9b"
      args:
        - --model_name=gemma
        - --model_id=google/gemma-2-9b
        - --backend=huggingface
      resources:
        limits:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 2Gi
          nvidia.com/gpu: "1"
    podSpec:
      containers:
        - name: kserve-container  # 这是 KServe 的容器名称，保持默认名称
          volumeMounts:
            - mountPath: /data/ai/model  # 容器内的挂载路径
              name: model-storage
              readOnly: true
      volumes:
        - name: model-storage
          hostPath:
            path: /data/ai/model  # 宿主机路径
            type: Directory

**Anything else you would like to add:**

**Environment:**
(base) root@kemove-Super-Server:/data/docker-file# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Istio Version:
(base) root@kemove-Super-Server:/data/docker-file# istioctl version
client version: 1.22.3
control plane version: 1.22.3
data plane version: 1.22.3 (1 proxies)
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
(base) root@kemove-Super-Server:/data/docker-file# kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3
- OS (e.g. from `/etc/os-release`):

**Comment by sivanantha321** [comment]
@zhouxinlun If you want use a custom model server, you have to do something like below. You can't use PodSpec and modelFormat at the same time.
```yaml
piVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-transformer-collocation
spec:
  predictor:
    containers:
      - name: kserve-container        # Do not change the name; This should be the predictor container
        image: "pytorch/torchserve:0.9.0-cpu"
        args:
          - "torchserve"
          - "--start"
          - "--model-store=/mnt/models/model-store"
          - "--ts-config=/mnt/models/config/config.properties"
        env:
          - name: TS_SERVICE_ENVELOPE
            value: kserve
          - name: STORAGE_URI    # This will trigger storage initializer; Should be only present in predictor container
            value: "gs://kfserving-examples/models/torchserve/image_classifier/v1"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 1Gi

      - name: transformer-container    # Do not change the container name
        image: kserve/image-transformer:latest
        args:
          - --model_name=mnist
          - --protocol=v1    # protocol of the predictor; used for converting the input to specific protocol supported by the predictor
          - --http_port=8080
          - --grpc_port=8081
          - --predictor_host=localhost:8085      # predictor listening port
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 1Gi
```

**Comment by spolti** [comment]
@sivanantha321 do we already have this on our docs?
If not, it would be a good addition.

**Comment by zhouxinlun** [comment]
Thanks for your message, you can find the type (InferenceService. PredictorSpec.PodSpec) here in the document, Or if you have a way for me to use kserve to deploy Pods that I can directly reference to the huggingface model that has been downloaded locally, that would be fine, thanks
![Snipaste_2024-08-15_10-49-48](https://github.com/user-attachments/assets/7f2b829e-f694-485c-9540-0d390beb0a5b)
![Uploading Snipaste_2024-08-15_10-50-07.png…]()

**Comment by sivanantha321** [comment]
> @sivanantha321 do we already have this on our docs? If not, it would be a good addition.

We do. https://kserve.github.io/website/latest/modelserving/v1beta1/transformer/collocation/

**Comment by sivanantha321** [comment]
> if you have a way for me to use kserve to deploy Pods that I can directly reference to the huggingface model that has been downloaded locally, that would be fine, thanks

@zhouxinlun I am not sure If i understand this correctly, But If you want to use the model that is already downloaded, you can provide the path using `--model_dir` and leave out the `--model_id`

**Comment by genlu2011** [comment]
@sivanantha321 I faced the same problem to use PodSpec in predictor. 
Is this field deprecated or what? The field: PodSpec is not in the https://github.com/kserve/kserve/releases/download/v0.13.0/kserve.yaml.

**Comment by sivanantha321** [comment]
@genlu2011 PodSpec is embedded into predictor. You ca use it like this
```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
    serviceAccountName: abc # podsepc field
    ```

**Comment by genlu2011** [comment]
Thanks! I missed the embedded part in the doc. Maybe adding a one-line example there will be useful.

**Comment by macrokernel** [comment]
Hi @sivanantha321, 

It really does:
> - name: STORAGE_URI    # This will trigger storage initializer; Should be only present in predictor container
>             value: "gs://kfserving-examples/models/torchserve/image_classifier/v1"

Can you please advise how to supply STORAGE_CONFIG Kubernetes secret to storage-initializer initContainer in case of a custom predictor?

UPDATE: Figured it out after a while: a Kubernetes secret and a storageaccount should be created and specified in predictor as per this example: https://github.com/kserve/kserve/tree/master/docs/samples/storage/s3:

```yaml
spec:
  predictor:
      serviceAccountName: sa
      containers:
      - name: kserve-container
        image: ...
```
