### ISSUE TITLE
Serverless. Auto-generated Service for Deployment with enabled metrics aggregation missing port "aggr-metric"

### ISSUE THREAD

**Issue by dkondidatov** [kserve/kserve#3864]
/kind bug

**What steps did you take and what happened:**
Deployed sklearn InferenceService with enabled metrics aggregation. Used qpext image in queue-proxy sidecar as described in docs.
Deployment was generated correctly, but Service not. The generated Service missing port "aggr-metric", that was added to Deployment due to metrics aggregation enabled.

**What did you expect to happen:**
Following port appears in Deployment and in autogenerated Service.
```yaml
- name: aggr-metric
  port: 9088
  protocol: TCP
```

**What's the InferenceService yaml:**
```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  namespace: app-kserve-workloads
  annotations:
    serving.kserve.io/enable-metric-aggregation: "true"
    serving.kserve.io/enable-prometheus-scraping: "true"
  labels: 
    app.kubernetes.io/instance: app-kserve-workloads-sklearn
    app.kubernetes.io/name: kserve-workloads
spec:
  predictor:
    annotations:
      serving.kserve.io/metric: cpu
      serving.kserve.io/targetUtilizationPercentage: "80"    
    minReplicas: 3
    maxReplicas: 12
    containerConcurrency: 10
    serviceAccountName: CENSORED
    model:
      args: ["--enable_docs_url=True"]
      modelFormat:
        name: lightgbm
      protocolVersion: v2
      storageUri: "s3://CENSORED/model-examples/lightgbm/mushroom.bst"
      securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          #runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      resources:
        requests:
          cpu: "8"
          memory: 2Gi
        limits:
          cpu: "10"
          memory: 2Gi
      ports:
      - containerPort: 8081
        name: h2c
        protocol: TCP

---
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kourier Version: 1.13.0
- Knative Version: 1.13.2
- KServe Version: 1.13.0
- Kubernetes version: (use `kubectl version`): v1.27.5-r0-27.2.29.6
