### ISSUE TITLE
SDLC is broken when KServe is installed with helm

### ISSUE THREAD

**Issue by sivanantha321** [kserve/kserve#3891]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1. Install KServe using [quick_install.sh](https://github.com/kserve/kserve/blob/master/hack/quick_install.sh) which uses helm.
2. Run `make deploy-dev`

```yaml
 - name: manager
      state:
        waiting:
          reason: CrashLoopBackOff
          message: >-
            back-off 2m40s restarting failed container=manager
            pod=kserve-controller-manager-564985d655-47tts_kserve(b051885e-3bdf-4040-9e95-140793bbd90c)
      lastState:
        terminated:
          exitCode: 127
          reason: ContainerCannotRun
          message: >-
            failed to create task for container: failed to create shim task: OCI
            runtime create failed: runc create failed: unable to start container
            process: exec: "/manager": stat /manager: no such file or directory:
            unknown
          startedAt: '2024-08-26T09:00:15Z'
          finishedAt: '2024-08-26T09:00:15Z'
          containerID: >-
            docker://c1bf44299b930abdee2b65a13a657ddc1e9bcab5336bcd90ad21c6e4e9895b86
      ready: false
      restartCount: 5
```

**What did you expect to happen:**
The Kserve controller should be deployed successfully.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
