### ISSUE TITLE
Revision create failed - Duplicate value: "kserve-provision-location"

### ISSUE THREAD

**Issue by nagar-ajay** [kserve/kserve#3900]
/kind bug

**What steps did you take and what happened:**
I'm testing #3885, I created an isvc that is using [custom storage containers](https://kserve.github.io/website/latest/modelserving/storage/storagecontainers/#create-the-custom-storage-initializer-image) to download a model but the revision create failed with the following error.
```
Pod "llama-3-1-8b-instruct-1xgpu-predictor-00001-deployment-5bbmg8dl" is invalid: [spec.volumes[3].name: Duplicate value: "kserve-provision-location", spec. │
│ containers[0].volumeMounts[3].mountPath: Invalid value: "/mnt/models": must be unique, spec.initContainers[1].name: Duplicate value: "nim-download-single"]
```

**What's the InferenceService yaml:**
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    autoscaling.knative.dev/target: "10"
    storage.kserve.io/readonly: "false"
  name: llama-3-1-8b-instruct-1xgpu
spec:
  predictor:
    minReplicas: 1
    model:
      modelFormat:
        name: nvidia-nim-llama-3.1-8b-instruct
      resources:
        limits:
          nvidia.com/gpu: "1"
        requests:
          nvidia.com/gpu: "1"
      runtime: nvidia-nim-llama-3.1-8b-instruct-1.1.2
      storageUri: nim-registry://
```

Cluster storage container spec:
```
apiVersion: "serving.kserve.io/v1alpha1"
kind: ClusterStorageContainer
metadata:
  name: nvidia-nim-llama-3.1-8b-instruct
spec:
  container:
    name: nim-download-single
    image: nvcr.io/nim/meta/llama-3.1-8b-instruct:1.1.2
    args: ["download-to-cache"]
    env:
    - name: NIM_CACHE_PATH
      value: /mnt/models/cache
    - name: NGC_API_KEY
      valueFrom:
        secretKeyRef:
          name: nvidia-nim-secrets
          key: NGC_API_KEY
  supportedUriFormats:
    - prefix: nim-registry://
```

ClusterServingRuntime - https://github.com/NVIDIA/nim-deploy/blob/main/kserve/runtimes/llama-3.1-8b-instruct-1.1.0.yaml
