### ISSUE TITLE
Kserve agent exec probe failed

### ISSUE THREAD

**Issue by beratturan** [kserve/kserve#3909]
I attempted to add a readiness probe to the InferenceService YAML configuration. Specifically, I used the following configuration:

```
readinessProbe: 
  exec:
    command:
      - /bin/sh
      - '-c'
      - >-
        curl -X GET
        0.0.0.0:8080/v2/models/model/versions/1/ready
```

After applying the InferenceService YAML, KServe created a pod named predictor. This pod contains two containers: kserve-container and agent. The readiness probe was successfully applied to the kserve-container, but the agent container raised an error: "exec probe not supported".

I would like to understand how to ensure that the readiness probe is applied only to the kserve-container and not to the agent container. Is there a way to achieve this configuration, or is there an alternative approach for implementing readiness probes in KServe?

KServe Version: 13.0.1

**Comment by LOADBC** [comment]
Hi, Unfortunately, Kubernetes does not allow specifying readiness probes for individual containers in a multi-container pod through the standard readinessProbe field in a CRD like KServe's InferenceService, 

If your readiness probe logic is simple and needs to be applied only to the kserve-container, you might consider alternatives like using HTTP probes instead of exec probes, which are more broadly supported across containers. For example:

```
readinessProbe:
  httpGet:
    path: /v2/models/model/versions/1/ready
    port: 8080
```

This approach checks the readiness over HTTP rather than executing a shell command, which may be supported by more containers, including the kserve-container.  You may need to either manually modify the deployment or leverage KServe's built-in health checks.

Hope it helps.
