### ISSUE TITLE
Enhance documentation: modelserving/storage/s3/s3

### ISSUE THREAD

**Issue by SeraphicRav** [kserve/kserve#3925]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
The [documentation](https://kserve.github.io/website/master/modelserving/storage/s3/s3/) does not state the necessary permissions to be able to use S3.

**What did you expect to happen:**
I am using the following permissions actions:
- s3:GetObject*
- s3:GetBucket*
- s3:List*

The resources being:
- arn:aws:s3:::my-bucket
- arn:aws:s3:::my-bucket/*

**I would like to know the minimal set of actions needed.**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mnist-s3
  namespace: in-house-ai
spec:
  predictor:
    tolerations:
      - key: ai-filter
        operator: Exists
        effect: NoSchedule
    serviceAccountName: kserve-models
    model:
      modelFormat:
        name: tensorflow
      storageUri: 's3://my-bucket/mnist_test'
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.23.0
- Knative Version: 1.13.1
- KServe Version: 0.13.1
- Kubeflow version: 
- Cloud Environment: aws
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): 1.30
- OS (e.g. from `/etc/os-release`):
