### ISSUE TITLE
Error: kserve with transformer pull image from private habor

### ISSUE THREAD

**Issue by johnzheng1975** [kserve/kserve#3935]
/kind bug

**What steps did you take and what happened:**
I want to pull image from private harbor, but it failed.

**What did you expect to happen:**
I hope it support pul-secret

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: torch-grpc-transformer-github-com-habor
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      storageUri: gs://kfserving-examples/models/torchscript
      runtime: kserve-tritonserver
      runtimeVersion: 20.10-py3
      ports:
      - name: h2c
        protocol: TCP
        containerPort: 9000
  transformer:
    containers:
    - image: harbor.ext.hp.com/onecloud-sol/infra-demo-itg:image-transformer-1.0
      name: kserve-container
      command:
      - "python"
      - "-m"
      - "model"
      args:
      - --model_name
      - cifar10
      - --protocol
      - grpc-v2
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
    state:
      waiting:
        message: 'failed to pull and unpack image "harbor.ext.hp.com/onecloud-sol/infra-demo-itg:image-transformer-1.0":
          failed to resolve reference "harbor.ext.hp.com/onecloud-sol/infra-demo-itg:image-transformer-1.0":
          pull access denied, repository does not exist or may require authorization:
          authorization failed: no basic auth credentials'
        reason: ErrImagePull

**Environment:**
eks

# kubectl  version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.29.7-eks-2f46c53
