### ISSUE TITLE
Log Sampling

### ISSUE THREAD

**Issue by benkawecki** [kserve/kserve#3939]
/kind feature

**Describe the solution you'd like**
Add optional random sampling for inference logging. High traffic inference applications may only want to log a portion of their logs rather than all of them. Sampling could be implemented through knative eventing brokers or on the server directly receiving the logs, but both approach still have network overhead for emitting the logs in the first place. 

The logging configuration should support sampling directly within the logger. Sampling should take a `samplePercentage` float between 0 and 1 where 0.2 indicates that 20% of LogRequests should be emitted. When sampling is enabled, the logging request handler should generate a random number between 0 and 1, if that random number is less than the `samplePercentage` then the request and response CloudEvents will be emitted as normal. If the number is greater than the `samplePercentage` then neither will be emitted. 

To allow for future proofing and keeping the configuration extensible, the configuration should accept a sampling strategy which contains the sampling strategy configuration as a nested set of keys. This way new sampling strategies can be added with their own configuration without breaking users who have onboarded to the sampling strategy listed above. Some example sampling strategies:
* Sampling based on request or response contents. 
* Hash and modulo based sample to ensure sampling is replicable on a given field. 
* Making a call to an external service to determine if an event should be sampled. 

Example configuration:
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-iris
spec:
  predictor:
    logger:
      mode: all
      url: http://message-dumper.default/
      sample:
        samplePercentage: 0.2
    model:
      modelFormat:
        name: sklearn
      storageUri: gs://kfserving-examples/models/sklearn/1.0/model
```

**Anything else you would like to add:**
I'm going to begin a rough draft implementation of what I outline above, I'll make sure to keep in line with where discussion goes on this post.

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]
