### ISSUE TITLE
Support configured metadata for logs

### ISSUE THREAD

**Issue by benkawecki** [kserve/kserve#3940]
/kind feature

**Describe the solution you'd like**
Allow static metadata to be defined in the logger configuration and passed in all emitted CloudEvents. When integrating log CloudEvents with other systems, users may want to ensure that specific metadata is included to information about the deployed component. Currently metadata about the request could be provided in the body of the request or in the request headers, this doesn't seem like a great fit for adding static metadata (for example the AWS region the instance is deployed in). 

Allowing for static metadata configuration allows kserve users to more easily extend logging functionality. The best way to pass this information currently would be in the logging URL field, for longer pieces of information this may not be a good fit. 

From an implementation perspective this should be relatively simple, though there are a number of questions that are worth discussing:
1. Should we reuse the existing [metadata](https://github.com/kserve/kserve/blob/9ec6842546682b338f0141bba2bda769a953a850/pkg/logger/types.go#L34) field on the CloudEvent passing the configured values in. (if we use this approach then we need to determine what behavior occurs when a request header collides with a configured value)
2. What format should the configured values be? Can it support nested objects?

Example config with metadata:
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-iris
spec:
  predictor:
    logger:
      mode: all
      url: http://message-dumper.default/
      metadata:
        foo: bar
        environment: production
    model:
      modelFormat:
        name: sklearn
      storageUri: gs://kfserving-examples/models/sklearn/1.0/model
```

**Anything else you would like to add:**
Anything else you would like to add:
I'm going to begin a rough draft implementation of what I outline above, I'll make sure to keep in line with where discussion goes on this post.

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]
