### ISSUE TITLE
It failed to perform inference of sklearn using raw deployment

### ISSUE THREAD

**Issue by houshengbo** [kserve/kserve#3956]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I followed the steps here to launch kserve locally: https://kserve.github.io/website/0.13/developer/developer/
Then, create the first inference service as in https://kserve.github.io/website/0.13/get_started/first_isvc/.

**What did you expect to happen:**
The section 5 perform inference: https://kserve.github.io/website/0.13/get_started/first_isvc/#4-determine-the-ingress-ip-and-ports, worked if I used knative serving as service backend. However, if did not work for me if used raw deployment

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
```
apiVersion: v1
kind: Namespace
metadata:
  name: kserve-test
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
  name: sklearn-iris
  namespace: kserve-test
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      name: ""
      resources: {}
      storageUri: gs://kfserving-examples/models/sklearn/1.0/model
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Running command:
curl -v -H "Host: sklearn-iris.kserve-test.example.com" -H "Content-Type: application/json" "http://localhost:80/v1/models/sklearn-iris:predict" -d @./iris-input.json

Caused:
``` 
* Host localhost:80 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:80...
* Connected to localhost (::1) port 80
> POST /v1/models/sklearn-iris:predict HTTP/1.1
> Host: sklearn-iris.kserve-test.example.com
> User-Agent: curl/8.7.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 76
> 
* upload completely sent off: 76 bytes
< HTTP/1.1 404 Not Found
< date: Tue, 24 Sep 2024 21:06:09 GMT
< server: istio-envoy
< connection: close
< content-length: 0
< 
* Closing connection
```

**Environment:**

- Istio Version: 1.23
- Knative Version:
- KServe Version: latest source code
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version: docker desktop 4.34.2
- Kubernetes version: (use `kubectl version`): 1.30.2
- OS (e.g. from `/etc/os-release`):

**Comment by terrytangyuan** [comment]
There are some missing docs that get improved here in case helps: https://github.com/kserve/website/pull/398

**Comment by sivanantha321** [comment]
Have you created ingress class ? Raw deployment makes use of ingress.

**Comment by houshengbo** [comment]
@terrytangyuan Thank you for pointing me out, but I configure the ingress information as 
```
                "disableIstioVirtualHost": true,
                "disableIngressCreation": true,
                "ingressDomain": "svc.cluster.local",
                "ingressGateway" : "disabled",
                "ingressService" : "disabled"
```
The service url will become `sklearn-iris-kserve-test.svc.cluster.local`. It still did not work for me.

**Comment by houshengbo** [comment]
@sivanantha321 I do not think I have the ingress class. If I still want to use istio as the ingress, how can I configure it?

**Comment by houshengbo** [comment]
I just added the IngressClass as below, without changing the default configurations in the CM `inferenceservice-config`:
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
```
And it worked for the raw deployment.
