### ISSUE TITLE
Change imagePullPolicy of queue-proxy

### ISSUE THREAD

**Issue by DriverSong** [kserve/kserve#3977]
/kind feature

**Describe the solution you'd like**
Is there any config to modify the imagePullPolicy of queue-proxy? This question has stoned me for a long time and I've read docs of kserve & knative, but cannot find any related solution.

**Anything else you would like to add:**
below is the yaml of my InferenceService
``` yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:                                                                                                                                                                               
  name: kserve-llama-3-8b-0022
  namespace: kserve-test
spec:
  predictor:
    containers:
    - args:
        - --max-model-len
        - "8192"
      command:
        - vllm
        - serve
        - /workspace/vllm/ckpt/llama/Meta-Llama-3.1-8B-Instruct-FP8
      volumeMounts:
        - mountPath: /workspace/vllm
          name: model-volume
          readOnly: true
      image: docker.io/library/test2_vlmm:v1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
      name: kserve-vllm-container-0022
      resources:
        limits:
          cpu: "4"
          memory: 30Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 30Gi
          nvidia.com/gpu: "1"
    volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: llama3-8b-pvc
          readOnly: true
```
[Miscellaneous information that will assist in solving the issue.]

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]

**Comment by DriverSong** [comment]
the deployment yaml created by the InferenceService is as below, with the default imagePullPolicy ```Always```, I've tried to change it to ```IfNotPresent```, while the conf will restore to  ```Always``` automatically
```yaml
spec:
  template:
    spec:
      containers:
      - env:
        image: gcr.io/knative-releases/knative.dev/serving/cmd/queue:latest
        imagePullPolicy: Always
```
