### ISSUE TITLE
Response headers for VirtualService are getting removed

### ISSUE THREAD

**Issue by andrescardosoc12** [kserve/kserve#3980]
/kind bug

**What steps did you take and what happened:**
Wherever i tried to deploy my VirtualService, "something" is removing my custom response headers after a few minutes.

**What did you expect to happen:**
I am trying to implement a solution with Oauth 2.0, so I need custom header `request-type: model-inference`. I want to detect what is removing it and configure that properly.

**What's the InferenceService yaml:**
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    sidecar.istio.io/inject: "true"
  name: model-example
  namespace: stagingv2
  labels:
    app: model-example-staging
spec:
  predictor:
    maxReplicas: 1
    containers:
      - name: kserve-container
        image: my_custom_image
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 240m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: MODEL_PATH
            valueFrom:
              secretKeyRef:
                name: model-secrets
                key: MODEL_PATH
    imagePullSecrets:
        - name: github-container-registry
```

**Anything else you would like to add:**
My VirtualService:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    sidecar.istio.io/inject: "true"
  name: model-example
  namespace: stagingv2
  labels:
    app: model-example-staging
spec:
  gateways:
  - knative-serving/knative-local-gateway
  - kubeflow/kubeflow-gateway
  hosts:
  - model-example.stagingv2.svc.cluster.local
  - model-example.stagingv2.my-domain
  http:
  - headers:
      request:
        set:
          Host: model-example-predictor-default.stagingv2.svc.cluster.local
    match:
    - authority:
        regex: ^model-example\.stagingv2(\.svc(\.cluster\.local)?)?(?::\d{1,5})?$
      gateways:
      - knative-serving/knative-local-gateway
    - authority:
        regex: ^model-example\.stagingv2\.my-domain
      gateways:
      - kubeflow/kubeflow-gateway
    route:
    - destination:
        host: knative-local-gateway.istio-system.svc.cluster.local
        port:
          number: 80
      headers:
          response:
            add:
              request-type: model-inference
      weight: 100
```

**Environment:**

- Istio Version: 1.16
- Knative Version: 1.8.1
- KServe Version: v0.10.0
- Kubeflow version: 1.7.0
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]: keycloak
- Kubernetes version: (use `kubectl version`): v1.29.2
