### ISSUE TITLE
404 Not found even though passed authorization

### ISSUE THREAD

**Issue by reconlabs-luke** [kserve/kserve#3995]
/kind bug

**What steps did you take and what happened:**
I got a authorization and put it in the cookies, But It raised with 404 code

```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

How can i deal with it ?

**What did you expect to happen:**
I did success as using the port-forwarding
```
200
{"test":true}
```

But I couldn't give my request when i use my domain
```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

My request of our external domain passed istio-ingress-gateway but it didn't pass to cluster-local-gateway ..

**What's the InferenceService yaml:**
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: flux-realism
  namespace: luke
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    imagePullSecrets:
      - name: aws-pull-secret
    runtimeClassName: nvidia
    containers:
      - name: flux-realism-serving
        image: ---my test image from private ECR---
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            cpu: "0"
            memory: "0"
            nvidia.com/gpu: 1
```

**Anything else you would like to add:**
```python
import requests
from urllib.parse import urlsplit

import requests.cookies

# HOST = "my-external-domain"
HOST = "http://localhost:8080"
NAME_SPACE = "xxx"
USER_NAME = "xxx@test.com"
USER_PS = "0000"

auth_session = {
    "endpoint_url": HOST,  # KF endpoint URL
    "redirect_url": None,  # KF redirect URL, if applicable
    "dex_login_url": None,  # Dex login URL (for POST of credentials)
    "is_secured": None,  # True if KF endpoint is secured
    "session_cookie": None,  # Resulting session cookies in the form "key1=value1; key2=value2"
}

with requests.Session() as session:
    response = session.get(HOST, allow_redirects=True)
    auth_session["redirect_url"] = response.url
    # if we were NOT redirected, then the endpoint is UNSECURED
    if len(response.history) == 0:
        auth_session["is_secured"] = False
    else:
        auth_session["is_secured"] = True

    redirect_url_obj = urlsplit(auth_session["redirect_url"])
    auth_session["dex_login_url"] = redirect_url_obj.geturl()

    response = session.post(
        auth_session["dex_login_url"], data={"login": USER_NAME, "password": USER_PS}, allow_redirects=True
    )
    print(response.history)
    auth_session["session_cookie"] = "; ".join([f"{c.name}={c.value}" for c in session.cookies])
    auth_session["authservice_session"] = session.cookies.get("authservice_session")

cookies = {"authservice_session": auth_session["authservice_session"]}
jar = requests.cookies.cookiejar_from_dict(cookies)
MODEL_NAME = "flux-realism"
SERVICE_HOSTNAME = f"{MODEL_NAME}.{NAME_SPACE}.example.com"
PREDICT_ENDPOINT = f"{HOST}/v1/models/{MODEL_NAME}:predict"
response = requests.post(
    url=PREDICT_ENDPOINT,
    headers={"Host": SERVICE_HOSTNAME, "Content-Type": "application/json"},
    cookies=jar,
    json={"test": "test"},
    timeout=200,
)
print(response.status_code)
print(response.text)
```

**Environment:**

- Istio Version: 1.16.0
- Knative Version: 1.8.1
- KServe Version: 0.10.0
- Kubeflow version: 1.7
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm] Onpremise
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): 1.26
- OS (e.g. from `/etc/os-release`):
