### ISSUE TITLE
external-URL of Kubeflow Endpoint Includes "predictor" word only in Default Namespace

### ISSUE THREAD

**Issue by muratyarali** [kserve/kserve#4021]
/kind bug

**What steps did you take and what happened:**

Hi everyone,

When I create an inferenceService in the default namespace of Kubeflow, the word "predictor" is appended to the external URL. For instance, if I name the inferenceService "sklearn-iris" in the default namespace, the URL becomes:

`http://sklearn-iris-predictor/.<default-namespace>.example.com`

However, when I create an inferenceService in any other namespaces of Kubeflow, the "predictor" is not added. For example:

`http://sklearn-iris/.<other-namespace>.example.com`

The manifests I use are identical for both cases.

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storage: "gs://kfserving-examples/models/sklearn/1.0/model"
```
      
Default namespace created by kubeflow manifests as you can guess, other namespaces are created as kubeflow profiles manually.

**What did you expect to happen:**

External URLs of endpoints must have the same structure regardless of namespace.

**What's the InferenceService yaml:**

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storage: "gs://kfserving-examples/models/sklearn/1.0/model"
```

**Anything else you would like to add:**

**Environment:**

- Istio Version: 1.17.3
- Knative Version: 1.10.2
- KServe Version: v0.11.0
- Kubeflow version: 1.8.0
- Kubernetes version: (use `kubectl version`): 1.27.X

Does anyone know why this happens?
