### ISSUE TITLE
Tensor device mismatch with embedding model

### ISSUE THREAD

**Issue by erickrf** [kserve/kserve#4050]
/kind bug

**What steps did you take and what happened:**
I set up an endpoint to serve text embeddings. Requests to it return this:

```
{"error":"RuntimeError : Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!"}
```

I believe either the model or the inputs is on GPU, while the other is on CPU.

**What did you expect to happen:**

Embedding values to be returned. In fact, deploying the same configuration on CPU-only works fine.

**What's the InferenceService yaml:**

I don't have the service running right now, but can supply the values file I applied.

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: gte-large
  annotations:
    # istio requires Auth policies for RBAC - for simplicity we just disable it, so everyone can access the service
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    serviceAccountName: "default-editor"
    tolerations:
      - key: "t4-gpu"
        operator: "Equal"
        value: "present"
      - key: "nvidia.com/gpu"
        operator: Equal
        value: "present"
    model:
      storageUri: [... GCS path ...]
      modelFormat:
        name: huggingface
      args:
        - --model_name=gte-large
        - --model_dir=/mnt/models/
        - --task=text_embedding
        - --gpu-memory-utilization=0.98
        - --device cuda
      resources:
        limits:
          cpu: 2
          memory: 4Gi
          nvidia.com/gpu: 1
        requests:
          cpu: 2
          memory: 4Gi
          nvidia.com/gpu: 1
      env:
        # disable prompt logging
        - name: KSERVE_LOGLEVEL
          value: "WARNING"

```

**Anything else you would like to add:**
Just disabling the GPU requests in the values file, as well as the `--device` flag, makes it work on CPU.

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
