### ISSUE TITLE
Can I know why the version is low 0.14, thanks. Can we improve it as 1.xxx?

### ISSUE THREAD

**Issue by johnzheng1975** [kserve/kserve#4071]
/kind feature
Can I know why the version is low as 0.14, thanks.
Can we improve the version with 1.xxx.

Current version 0.14 make it not confident enough to go to prod.
We are using kserve, but my colleagues challenge my choose because of low version of kserve.

**Describe the solution you'd like**
Evaluate whether it is mature enough to change to 1.xxxx.

**Anything else you would like to add:**
I saw you are trying to add to CNCF, it is also very useful make kserve successful!

**Comment by yuzisun** [comment]
hi @johnzheng1975, while KServe is stable for traditional AI inference which we have worked on for years, it is still fast evolving in the GenAI inference areas to support features like vllm inference runtime, autoscaling for LLMs, model caching, LLM observability and multi node inference etc. I do not think we are ready to call it 1.xxx yet, but we are maintaining backwards compatible API for both control and data planes, and many adapters are running KServe on production.

**Comment by johnzheng1975** [comment]
Thanks a lot for your answer. @yuzisun 
"vllm inference runtime"/ "model caching" is really important, we are trying below but met "no permission to write" issue （note the pv is for cache）, so we use custom runtime now and works well.
Should we submit an issue for this? or just wait for "vllm inference runtime" and "model cache"?
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3
  volumeMode: Filesystem
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen
spec:
  predictor:
    nodeSelector:
      node-group: "gpu"
    tolerations:
      - key: "node-group"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
    volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: qwen-pvc-1
      # vLLM needs to access the host's shared memory for tensor parallel inference.
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "8Gi"
    model:
      modelFormat:
        name: huggingface
      args: ["--model_id=Qwen/Qwen2.5-7B-Instruct", "--backend=vllm"]
      env:
#        - name: VLLM_USE_MODELSCOPE
#          value: "True"
        - name: HF_HOME
          value: "/mnt/models"
#        - name: TRANSFORMERS_CACHE
#          value: "/mnt/models"
#        - name: HF_ENDPOINT
#          value: "https://hf-mirror.com"
      resources:
        limits:
          cpu: "4"
          memory: "15Gi"
          nvidia.com/gpu: "1"
        requests:
          cpu: "3"
          memory: "13Gi"
          nvidia.com/gpu: "1"
      volumeMounts:
        - mountPath: /mnt/models
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 600
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 600
        periodSeconds: 5
#      securityContext:
#        runAsNonRoot: false # https://github.com/vllm-project/vllm/issues/9118
```
