### ISSUE TITLE
canary not work

### ISSUE THREAD

**Issue by johnzheng1975** [kserve/kserve#4074]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I installed kseve with https://kserve.github.io/website/latest/admin/kubernetes_deployment/
Istio 1.22.4
v0.13.1
Install with helm.
```
  values:
    kserve:
      controller:
        deploymentMode: "RawDeployment"
```

I also created
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
```

Here is inferenceservice-config.yaml, after run `k get cm -n infra   inferenceservice-config -oyaml > inferenceservice-config.yaml`
[inferenceservice-config.txt](https://github.com/user-attachments/files/17831757/inferenceservice-config.txt)

I am walking through the docs: https://github.com/kserve/kserve/blob/master/docs/samples/v1beta1/rollout/README.md
After I run:
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "my-model"
  annotations:
    serving.kserve.io/gateway: istio-system/apigee-gateway
    serving.kserve.io/istio-ingress: "enabled"
spec:
  predictor:
    tensorflow:
      storageUri: "gs://kfserving-examples/models/tensorflow/flowers"
```
1. No virtual service is created.
2. No percentage for the version
![image](https://github.com/user-attachments/assets/da2e9332-1730-4455-a13b-8856f3a19a9b)

**What did you expect to happen:**
1. virtual service should be created.
2. percentage, version should be showed as sample.
![image](https://github.com/user-attachments/assets/bbfa218b-c5b4-4d3a-b4ab-72a02ec1cb70)

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.22.4
- Knative Version:
- KServe Version: 0.13.1
- Kubeflow version:
- Cloud Environment:[k8s_istio/ aws/eks]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):  v1.30.4-eks-a737599
- OS (e.g. from `/etc/os-release`):

**Comment by johnzheng1975** [comment]
Then I applied new version , with 10% percentage.
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "my-model"
  annotations:
    serving.kserve.io/gateway: istio-system/apigee-gateway
    serving.kserve.io/istio-ingress: "enabled"
spec:
  predictor:
    canaryTrafficPercent: 10
    tensorflow:
      storageUri: "gs://kfserving-examples/models/tensorflow/flowers-2"
```

**Actual result:**
![image](https://github.com/user-attachments/assets/c13a5744-0d41-43c1-820c-9945b9e0c4f3)


**Expect result:**
virtual service can be created.
percentage and version is showed as sample.
![image](https://github.com/user-attachments/assets/a74024e2-48b9-41db-a7af-cc8942abd073)
