### ISSUE TITLE
MultiModelServing: EOF error when downloading zip files

### ISSUE THREAD

**Issue by Jonas-Bruns** [kserve/kserve#4080]
/kind bug

**What steps did you take and what happened:**
Hello, I am currently testing MultiModelServing and I have encountered the problem that zip files cannot be downloaded as storage URI. I get the following error:
`"Failed to download model model10 with err failed to download model: failed to download model: unable to copy file content: EOF","stacktrace":"github.com/kserve/kserve/pkg/agent.(*Puller).modelProcessor.func1\n\t/go/src/github.com/kserve/kserve/pkg/agent/puller.go:156\ngithub.com/kserve/kserve/pkg/agent.(*Puller).modelProcessor\n\t/go/src/github.com/kserve/kserve/pkg/agent/puller.go:220"}`

**What did you expect to happen:**
zip file completely copied and unzipped under /mnt/models

**What's the InferenceService yaml:**
```
[apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "custom2"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      protocolVersion: v2
      runtime: custom-runtime
      resources:
        requests:
          cpu: "1"         
          memory: "16Gi"
          ephemeral-storage: "16Gi"
        limits:
          cpu: "1"
          memory: "16Gi"
          ephemeral-storage: "16Gi"
---
apiVersion: "serving.kserve.io/v1alpha1"
kind: "TrainedModel"
metadata:
  name: "model1"
spec:
  inferenceService: "custom2"
  model:
    storageUri: "https://www.abc.net/v1.zip"
    framework: "test"
    memory: "1Gi"
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: 0.14.0
- Kubeflow version: 1.9.1
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
