### ISSUE TITLE
Swagger UI Not Found Error

### ISSUE THREAD

**Issue by muratyarali** [kserve/kserve#4086]
/kind bug

**What steps did you take and what happened:**
Hi Guys.

I need your help about an issue. I think I need to explain the problem in detail for you to understand.

- I want to reach Swagger-UI page of an ISVC with this URL: http://sklearn-iris-predictor.kubeflow-user-example-com.example.com/docs.

But i can not. I am always getting "{"detail":"Not Found"}" Error. I want to ask you that Can firewall block it?

- I created this ISVC in Kubeflow with this file that is given in the documentation
Documentation: https://kserve.github.io/website/latest/get_started/swagger_ui/#inferenceservice-swagger-ui

**What did you expect to happen:**
I want to see Swagger UI page on my browser

**What's the InferenceService yaml:**
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  namespace: kubeflow-user-example-com
spec:
  predictor:
    model:
      args: ["--enable_docs_url=True"]     # This line allow to reach Swagget-UI
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:1.17.3
- Knative Version:1.10.1
- KServe Version:v0.11.0
- Kubeflow version:v1.8.0-rc.0
- Cloud Environment:-
- Minikube/Kind version:-
- Kubernetes version: v1.27.10
- OS (e.g. from `/etc/os-release`):
