### ISSUE TITLE
When i create a Inference Graph i see a issue

### ISSUE THREAD

**Issue by IonBoleac** [kserve/kserve#4114]
/kind bug

**What steps did you take and what happened:**
I successfully deployed two inference services and they are:

```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "new-first-infsvc"
  namespace: "inference-graph"
spec:
  predictor:
    serviceAccountName: aws-sa
    triton:
      image: "nvcr.io/nvidia/tritonserver:22.12-py3"
      storageUri: "s3://my-models/new_first_inference/"

---

apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "second-infsvc"
  namespace: "inference-graph"
spec:
  predictor:
    serviceAccountName: aws-sa
    triton:
      image: "nvcr.io/nvidia/tritonserver:22.12-py3"
      storageUri: "s3://my-models/second_inference/"
```

They are work properly and I tested them. After that, I deployed an inference graph using this manifest: 

```yaml
apiVersion: "serving.kserve.io/v1alpha1"
kind: "InferenceGraph"
metadata:
  name: "inference-pipeline"
  namespace: "inference-graph"
spec:
  nodes:
    root:
      routerType: Sequence
      steps:
      - serviceName: new-first-infsvc
      - serviceName: second-infsvc
        data: $request
```

The deployments were successfully created, but when I try to run the inference graph, I get that only the second inference service is deployed into the pipeline. Why?

**What did you expect to happen:**
The inference output has to be correct from the sequence.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: I mean 1.22.2
- Knative Version: 1.16.0
- KServe Version: 0.13.0
- Kubeflow version: I use kserve serverless
- Microk8s: v1.31.3 revision 7449
- Kubernetes version: (use `kubectl version`): 
```bash
$$ kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.31.3
```
- OS (e.g. from `/etc/os-release`): 
```bash
$$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
