### ISSUE TITLE
Not able to use temporary credential for S3 because AWS_SESSION_TOKEN is not supported

### ISSUE THREAD

**Issue by lei1liu** [kserve/kserve#4119]
/kind bug

**What steps did you take and what happened:**
I'm trying to load my model stored in S3 to kserve via Raw Deployment. A temporary credential (`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`) are provided and below are the configurations:
**s3_secret.yaml**
```
apiVersion: v1
kind: Secret
metadata:
  name: s3creds
  annotations:
     serving.kserve.io/s3-endpoint: s3.amazonaws.com # replace with your s3 endpoint e.g minio-service.kubeflow:9000
     serving.kserve.io/s3-usehttps: "1" # by default 1, if testing with minio you can set to 0
     serving.kserve.io/s3-region: "us-east-1"
     serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
type: Opaque
stringData: # use `stringData` for raw credential string or `data` for base64 encoded string
  AWS_ACCESS_KEY_ID: xxxxx
  AWS_SECRET_ACCESS_KEY: xxxxx
  AWS_SESSION_TOKEN: xxxxx
```
**creste-s3-sa.yaml**
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-sa
  annotations:
    serving.kserve.io/s3-endpoint: s3.amazonaws.com # replace with your s3 endpoint e.g minio-service.kubeflow:9000
    serving.kserve.io/s3-usehttps: "1" # by default 1, if testing with minio you can set to 0
    serving.kserve.io/s3-region: "us-east-1"
    serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
secrets:
  - name: s3creds
```
**service.yaml**
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "simple"
spec:
  predictor:
    serviceAccountName: kserve-sa
    model:
      modelFormat:
        name: tensorflow
        version: "1"
      storageUri: "s3://my-bucket/path"
      runtime: kserve-tritonserver
      runtimeVersion: 20.10-py3
```

**After deployment, the pod is stuck in initialization stage:**
```
$  kc describe pod/simple-predictor-8559964c-zllzx -n kserve-test

Name:             simple-predictor-8559964c-zllzx
Namespace:        kserve-test
Priority:         0
Service Account:  kserve-sa
Node:             minikube/192.168.49.2
Start Time:       Wed, 11 Dec 2024 13:54:12 -0800
Labels:           app=isvc.simple-predictor
                  app.kubernetes.io/managed-by=Helm
                  component=predictor
                  pod-template-hash=8559964c
                  serving.kserve.io/inferenceservice=simple
Annotations:      internal.serving.kserve.io/storage-initializer-sourceuri: s3://my-bucket/path
                  meta.helm.sh/release-name: simple
                  meta.helm.sh/release-namespace: kserve-test
                  prometheus.kserve.io/path: /metrics
                  prometheus.kserve.io/port: 8002
                  serving.kserve.io/deploymentMode: RawDeployment
                  serving.kserve.io/enable-metric-aggregation: false
                  serving.kserve.io/enable-prometheus-scraping: false
Status:           Pending
IP:               10.244.0.31
IPs:
  IP:           10.244.0.31
Controlled By:  ReplicaSet/simple-predictor-8559964c
Init Containers:
  storage-initializer:
    Container ID:  docker://1b9e22756a2452555aee4988e8c6e62b6995121e245a328ee0124db30deb653b
    Image:         kserve/storage-initializer:v0.14.0
    Image ID:      docker-pullable://kserve/storage-initializer@sha256:f06b727cc7d9557205cf185aaca1199a38876ae61e763493f8704af0649530dd
    Port:          <none>
    Host Port:     <none>
    Args:
      s3://pi-expt-use1-dev/project/ml_platform/lei1.liu/triton/model_repository/simple
      /mnt/models
    State:      Terminated
      Reason:   Error
      Message:  2024-12-11 21:55:03.428 1 kserve INFO [initializer-entrypoint:<module>():16] Initializing, args: src_uri [s3://pi-expt-use1-dev/project/ml_platform/lei1.liu/triton/model_repository/simple] dest_path[ [/mnt/models]
2024-12-11 21:55:03.429 1 kserve INFO [storage.py:download():64] Copying contents of s3://pi-expt-use1-dev/project/ml_platform/lei1.liu/triton/model_repository/simple to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 17, in <module>
    Storage.download(src_uri, dest_path)
  File "/kserve/kserve/storage/storage.py", line 91, in download
    model_dir = Storage._download_s3(uri, out_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kserve/kserve/storage/storage.py", line 231, in _download_s3
    for obj in bucket.objects.filter(Prefix=bucket_path):
  File "/prod_venv/lib/python3.11/site-packages/boto3/resources/collection.py", line 79, in __iter__
    for page in self.pages():
  File "/prod_venv/lib/python3.11/site-packages/boto3/resources/collection.py", line 169, in pages
    for page in pages:
  File "/prod_venv/lib/python3.11/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/prod_venv/lib/python3.11/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/prod_venv/lib/python3.11/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/prod_venv/lib/python3.11/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
**botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.**
```
**The env doesn't have the "AWS_SESSION_TOKEN":**
```
      Exit Code:    1
      Started:      Wed, 11 Dec 2024 13:54:31 -0800
      Finished:     Wed, 11 Dec 2024 13:54:34 -0800
    Ready:          False
    Restart Count:  3
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  100Mi
    Environment:
      AWS_ACCESS_KEY_ID:       <set to the key 'AWS_ACCESS_KEY_ID' in secret 's3creds'>      Optional: false
      AWS_SECRET_ACCESS_KEY:   <set to the key 'AWS_SECRET_ACCESS_KEY' in secret 's3creds'>  Optional: false
      S3_USE_HTTPS:            1
      S3_ENDPOINT:             s3.amazonaws.com
      AWS_ENDPOINT_URL:        https://s3.amazonaws.com
      awsAnonymousCredential:  false
      AWS_DEFAULT_REGION:      us-east-1
```

**What did you expect to happen:**
The inference service pod should be up and running, and "AWS_SESSION_TOKEN" should also be included into the "Environment" variables.

**What's the InferenceService yaml:**
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    meta.helm.sh/release-name: simple
    meta.helm.sh/release-namespace: kserve-test
    serving.kserve.io/deploymentMode: RawDeployment
  creationTimestamp: "2024-12-11T21:54:11Z"
  finalizers:
  - inferenceservice.finalizers
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: simple
  namespace: kserve-test
  resourceVersion: "62149"
  uid: 5793400a-3c82-4183-b9a2-03658b202f3d
spec:
  predictor:
    model:
      modelFormat:
        name: tensorflow
        version: "1"
      name: ""
      resources: {}
      runtime: kserve-tritonserver
      runtimeVersion: 20.10-py3
      storageUri: s3://my-bucket/path
    serviceAccountName: kserve-sa
status:
  address:
    url: http://simple-predictor.kserve-test.svc.cluster.local
  components:
    predictor:
      latestCreatedRevision: "1"
  conditions:
  - lastTransitionTime: "2024-12-11T21:54:11Z"
    status: "True"
    type: IngressReady
  - lastTransitionTime: "2024-12-11T21:54:11Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: PredictorReady
  - lastTransitionTime: "2024-12-11T21:54:11Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Ready
  modelStatus:
    states:
      activeModelState: ""
      targetModelState: Pending
    transitionStatus: InProgress
  observedGeneration: 1
  url: http://simple-kserve-test.svc.cluster.local
```

**Anything else you would like to add:**
I tested in `boto3` that AWS_SESSION_TOKEN is a must if we use aws temporary credential (permanent credential is not recommended/safe in my company):
```
import boto3
from botocore.exceptions import NoCredentialsError, PartialCredentialsError, ClientError
def test_s3_connection(access_key, secret_key, session_token=None, region="us-east-1"):
    try:
        # Initialize S3 client with provided credentials
        s3_client = boto3.client(
            's3',
            aws_access_key_id=access_key,
            aws_secret_access_key=secret_key,
            # aws_session_token=session_token,
            region_name=region
        )
        # List buckets to test the connection
        response = s3_client.list_buckets()
        print("S3 Buckets:")
        for bucket in response['Buckets']:
            print(f"- {bucket['Name']}")
    except NoCredentialsError:
        print("Error: No credentials provided.")
    except PartialCredentialsError:
        print("Error: Incomplete credentials provided.")
    except ClientError as e:
        print(f"Client error: {e}")
    except Exception as e:
        print(f"Unexpected error: {e}")
# Replace with your actual credentials
AWS_ACCESS_KEY_ID = "xxxxx"
AWS_SECRET_ACCESS_KEY = "xxxx"
AWS_SESSION_TOKEN = "xxx"  # Leave blank if not using temporary credentials
# Run the test
test_s3_connection(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN)
```

**Environment:**

- Istio Version: N/A
- Knative Version: N/A
- KServe Version: 0.14.0
- Kubeflow version: N/A
- Cloud Environment: aws
- Minikube/Kind version: **minikube version: v1.34.0**
- Kubernetes version: (use `kubectl version`): Client Version: v1.31.2
- OS (e.g. from `/etc/os-release`): Mac OS 14.4
