### ISSUE TITLE
Support multiple LocalModel NodeGroup 

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#4126]
/kind feature

**Describe the solution you'd like**
When you have multiple GPU types in the cluster like A100, H100:
* Models can be cached on multiple node groups, for each node group we create separate download jobs and localmodelnode controller updates with the expected model list.
* `LocalModelCache` can be updated to remove individual node group, e.g model is no longer needed to be cached on A100 nodes
* Different node groups may have different disk size, model size needs to be validated if the model can be cached or not for the  node groups.

```yaml
apiVersion: serving.kserve.io/v1alpha1
kind: LocalModelCache
metadata:
  name: meta-llama3-8b-instruct
spec:
  modelSize: 10Gi
  nodeGroup: 
  - a100
  - h100
  sourceModelUri: hf://meta-llama/meta-llama-3-8b-instruct
```

when deploying `InferenceService`, node group annotation needs to be specified to schedule the workload to match the node group. `sourceModelUri` and `nodeGroup` need to be matched to use the local model cache.

```yaml
apiVersion: serving.kserve.io/v1beta1
    kind: InferenceService
    metadata:
      name: huggingface-llama3
      annotations:
        serving.kserve.io/nodegroup: a100
    spec:
      predictor:
        model:
          modelFormat:
            name: huggingface
          args:
            - --model_name=llama3
            - --model_id=meta-llama/meta-llama-3-8b-instruct
          resources:
            limits:
              cpu: "6"
              memory: 24Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "6"
              memory: 24Gi
              nvidia.com/gpu: "1"
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]
