### ISSUE TITLE
[Caused by configuration] logger does not work, when I install kserve without knative.  

### ISSUE THREAD

**Issue by johnzheng1975** [kserve/kserve#4128]
/kind bug
Logger does not work, when I install kserve without knative.

Here is isvc
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn
  namespace: onecloud-dev
spec:
  predictor:
    logger:
      mode: all
      url: http://message-dumper/
    model:
      modelFormat:
        name: sklearn
      name: ""
      resources: {}
      storageUri: gs://kfserving-examples/models/sklearn/1.0/model
    serviceAccountName: sklearn
```

The pod is created succesfully
```
sklearn-predictor-64f6c677-bk8pc                  3/3     Running    0                5h49m


$ k logs -n onecloud-dev sklearn-predictor-64f6c677-bk8pc -c agent
# kubectl  logs -n onecloud-dev sklearn-predictor-64f6c677-bk8pc -c agent
{"severity":"INFO","timestamp":"2024-12-15T20:56:56.13155637Z","caller":"logging/config.go:80","message":"Unable to read vcs.revision from binary"}
{"severity":"INFO","timestamp":"2024-12-15T20:56:56.138788836Z","caller":"agent/main.go:140","message":"Starting logger"}
{"severity":"INFO","timestamp":"2024-12-15T20:56:56.13882697Z","caller":"agent/main.go:276","message":"Starting the log dispatcher"}
{"severity":"INFO","timestamp":"2024-12-15T20:56:56.138840009Z","caller":"logger/dispatcher.go:31","message":"Starting worker 1"}
{"severity":"INFO","timestamp":"2024-12-15T20:56:56.138876896Z","caller":"logger/dispatcher.go:31","message":"Starting worker 2"}
{"severity":"INFO","timestamp":"2024-12-15T20:56:56.138886991Z","caller":"logger/dispatcher.go:31","message":"Starting worker 3"}
{"severity":"INFO","timestamp":"2024-12-15T20:56:56.138895683Z","caller":"logger/dispatcher.go:31","message":"Starting worker 4"}
{"severity":"INFO","timestamp":"2024-12-15T20:56:56.138907374Z","caller":"logger/dispatcher.go:31","message":"Starting worker 5"}
{"severity":"INFO","timestamp":"2024-12-15T20:56:56.138917663Z","caller":"agent/main.go:149","message":"Starting agent http server..."}
{"severity":"INFO","timestamp":"2024-12-15T20:56:56.139123044Z","caller":"agent/main.go:316","message":"Building server user port %!s(int=8080) port 9081"}
dial tcp :8080: connect: connection refused
dial tcp :8080: connect: connection refused
```

However, both 8080 and 9081 port is fine.
```
# kubectl  exec -ti -n onecloud-dev sklearn-predictor-64f6c677-bk8pc -c istio-proxy -- curl localhost:8080/v1/models
{"models":["sklearn"]}

# kubectl  exec -ti -n onecloud-dev sklearn-predictor-64f6c677-bk8pc -c istio-proxy -- curl localhost:9081
{"status":"alive"}
```

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
message-dumper service have not got http request, when sklearn predictor

**What did you expect to happen:**
message-dumper service should get http request, when sklearn predictor

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.24
- Knative Version:  NOT installed
- KServe Version: 0.14
- Kubeflow version:  NOT installed
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version: EKS
- Kubernetes version: (use `kubectl version`):
- # kubectl  version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.31.2-eks-7f9249a

- OS (e.g. from `/etc/os-release`):
