### ISSUE TITLE
LocalModelCache admission webhook and isvc mutating webhook fails due to insufficient permission

### ISSUE THREAD

**Issue by sivanantha321** [kserve/kserve#4130]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1. Create a LocalModelCache resource.
```yaml
apiVersion: serving.kserve.io/v1alpha1
kind: LocalModelCache
metadata:
  name: example-local-model-cache
spec:
  nodeGroup: example-local-model-node-group
  sourceModelUri: "hf://facebook/opt-125m"
  modelSize: 250Mi
```
2. The validation webhook fails due to lack of permission
![Screenshot from 2024-12-16 15-22-27](https://github.com/user-attachments/assets/05e7c512-7cc3-425f-ba4b-40b1a2ecfb73)

3. The isvc mutating webhook also fails when localmodelcache is enabled as it is trying to list localmodelcache resources to overwrite the storageuri https://github.com/kserve/kserve/blob/68422b8d26a22f0a63ef5b8ee95e3087a653dfeb/pkg/apis/serving/v1beta1/inference_service_defaults.go#L128
The webhook is registered in kserve-controller and it does not have permission to watch localmodelcache resources.
https://github.com/kserve/kserve/blob/master/config/rbac/role.yaml

**What did you expect to happen:**
The validation webhook should validate resources without errors.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: master
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
