### ISSUE TITLE
InferenceGraphs composing InferenceGraphs

### ISSUE THREAD

**Issue by caamartin35** [kserve/kserve#4144]
/kind feature

## What is changing? (Please include as many details as possible.)
It would be nice to be able to compose InferenceGraphs inside one another like so:
```yaml
apiVersion: "serving.kserve.io/v1alpha1"
kind: "InferenceGraph"
metadata:
  name: "cascade"
spec:
  nodes:
    root:
      routerType: Sequence
      steps:
      - serviceName: model-1
        name: first-service
      - serviceName: model-2
        name: second-service
        data: $request
        condition: "[@this].#(confidence>0.45)"
---
apiVersion: "serving.kserve.io/v1alpha1"
kind: "InferenceGraph"
metadata:
  name: "cascade-2"
spec:
  nodes:
    root:
      routerType: Sequence
      steps:
      - serviceName: cascade
        name: cascade-run
      - serviceName: model-3
        name: third-service
        data: $request
        condition: "[@this].#(confidence>0.25)"
```

If this is already possible with `nodeName` it is not clear from the docs.

## How will this impact our users?
This will allow users to compose InferenceGraphs inside of one another
