### ISSUE TITLE
Define another metrics port, which is different with business port.  [Cannot work]

### ISSUE THREAD

**Issue by johnzheng1975** [kserve/kserve#4168]
/kind bug

Define another metrics port, which is different with business port.  [Cannot work]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
As below example, for sklearn model format, NOT protocolVersion v2

1. Define an isvc as:
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
    serving.kserve.io/deploymentMode: RawDeployment
  name: new-sklearn-clean-v1
  namespace: onecloud-dev
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      name: ""
      resources: {}
      storageUri: gs://kfserving-examples/models/sklearn/1.0/model
```
2. I found `curl localhost:8080/v2` works for business purpose API
3. I found `curl localhost:8080/metrics` works for metrics
4. I want to prometheus use a different port, like 8082.

[Try 1] I hope promethues server -> fetch from 8082 server -> ksever map outside 8082 port to internal 8080 port -> sklearn server 8080 port.
However, it does not work.  `curl localhost:8080/v2` and `curl localhost:8080/metrics` still works. But 8082 port show error
```
$ curl localhost:8082/metrics
curl: (7) Failed to connect to localhost port 8082 after 0 ms: Couldn't connect to server
```
configure for [Try 1]
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    prometheus.io/port: "8082"    # changed to 8082
    prometheus.io/scrape: "true"
    prometheus.kserve.io/path: /metrics  #added
    prometheus.kserve.io/port: "8080"     #added
    serving.kserve.io/deploymentMode: RawDeployment
  name: new-sklearn-clean-v1-improve
  namespace: onecloud-dev
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      name: ""
      resources: {}
      storageUri: gs://kfserving-examples/models/sklearn/1.0/model
```

[Try 2] Ok, I realized my grammar may wrong. Since I use another solution, still fail.
```
curl: (7) Failed to connect to localhost port 8082 after 0 ms: Couldn't connect to server
command terminated with exit code 7
```
configure for [Try 2]
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    prometheus.kserve.io/path: /metrics  #added
    prometheus.kserve.io/port: "8082"     #added
    serving.kserve.io/deploymentMode: RawDeployment
  name: new-sklearn-clean-v1-improve2
  namespace: onecloud-dev
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      name: ""
      resources: {}
      storageUri: gs://kfserving-examples/models/sklearn/1.0/model
```

**What did you expect to happen:**
I want to use port 8082 for metrics, and leave 8080 for business api.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
How to implement this?

**Environment:**

- Istio Version:  1.22
- Knative Version: Not installed
- KServe Version: 0.14
- Kubeflow version: No
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):  Server Version: v1.31.3-eks-56e63d8
- OS (e.g. from `/etc/os-release`):

**Comment by spolti** [comment]
In the runtime, try:
```yaml
spec:
  annotations:
    prometheus.io/port: '8080'
    prometheus.io/path: '/metrics'
```

also, make sure that your serving runtime exposes the metrics on this port.

**Comment by johnzheng1975** [comment]
Thanks for your answer. @spolti 
For this case, the annotation is already added by default
```
spec:
  annotations:
    prometheus.io/port: '8080'
    prometheus.io/path: '/metrics'
```
as https://github.com/kserve/kserve/blob/master/config/runtimes/kserve-sklearnserver.yaml#L6, right?
Test below, not work
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: "8082"
    serving.kserve.io/deploymentMode: RawDeployment
  name: new-sklearn-clean-v1-improve3
  namespace: onecloud-dev
spec:
  #annotations:
  #  prometheus.io/port: '8080'
  #  prometheus.io/path: '/metrics'
  predictor:
    model:
      modelFormat:
        name: sklearn
      name: ""
      resources: {}
      storageUri: gs://kfserving-examples/models/sklearn/1.0/model
```

My purpose is: **I want let Prometheus pull metrics from 8082 port, while remain predict api with 8080.** 
for sklearn model format, NOT protocolVersion v2, seems the original container only expose 8080, for metrics also. 
Can I achieve my goal easily? Or kserve does not support "changing metrics port"?
