### ISSUE TITLE
InferenceGraph issue

### ISSUE THREAD

**Issue by IonBoleac** [kserve/kserve#4172]
/kind bug (issue with inference graph)
This report is similar to https://github.com/kserve/kserve/issues/4114#issue-2732554843 and I created a new one because I hope someone helps me.

I successfully deployed two inference services and they are:

```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "new-first-infsvc"
  namespace: "inference-graph"
spec:
  predictor:
    serviceAccountName: aws-sa
    triton:
      image: "nvcr.io/nvidia/tritonserver:22.12-py3"
      storageUri: "s3://my-models/new_first_inference/"

---

apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "second-infsvc"
  namespace: "inference-graph"
spec:
  predictor:
    serviceAccountName: aws-sa
    triton:
      image: "nvcr.io/nvidia/tritonserver:22.12-py3"
      storageUri: "s3://my-models/second_inference/"
```

They work properly and I tested them using Triton Python API. After that, I deployed an inference graph using this manifest: 

```yaml
apiVersion: "serving.kserve.io/v1alpha1"
kind: "InferenceGraph"
metadata:
  name: "inference-pipeline"
  namespace: "inference-graph"
spec:
  nodes:
    root:
      routerType: Sequence
      steps:
      - serviceName: new-first-infsvc
      - serviceName: second-infsvc
        data: $request
```

The inference graph's `describe` log is:

```bash
$ kubectl -n inference-graph describe ig inference-pipeline 
Name:         inference-pipeline
Namespace:    inference-graph
Labels:       <none>
Annotations:  <none>
API Version:  serving.kserve.io/v1alpha1
Kind:         InferenceGraph
Metadata:
  Creation Timestamp:  2025-01-07T09:54:56Z
  Generation:          1
  Resource Version:    18396279
  UID:                 2e177e4d-a233-4927-8822-5102c0349ace
Spec:
  Nodes:
    Root:
      Router Type:  Sequence
      Steps:
        Service Name:  new-first-infsvc
        Data:          $request
        Service Name:  second-infsvc
Status:
  Conditions:
    Last Transition Time:  2025-01-07T09:55:00Z
    Status:                True
    Type:                  ConfigurationsReady
    Last Transition Time:  2025-01-07T09:55:01Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2025-01-07T09:55:01Z
    Status:                True
    Type:                  RoutesReady
  URL:                     http://inference-pipeline.inference-graph.10.16.11.172.sslip.io
Events:
  Type     Reason               Age   From                      Message
  ----     ------               ----  ----                      -------
  Warning  UpdateFailed         7s    InferenceGraphController  Failed to update status for InferenceGraph "inference-pipeline": Operation cannot be fulfilled on inferencegraphs.serving.kserve.io "inference-pipeline": the object has been modified; please apply your changes to the latest version and try again
  Warning  InternalError        7s    InferenceGraphController  fails to update InferenceGraph status: Operation cannot be fulfilled on inferencegraphs.serving.kserve.io "inference-pipeline": the object has been modified; please apply your changes to the latest version and try again
  Normal   InferenceGraphReady  6s    InferenceGraphController  InferenceGraph [inference-pipeline] is Ready
```

The browser output is:

```log
{"model_name":"second-infsvc","model_version":"1","outputs":[{"name":"label","datatype":"INT64","shape":[0,1],"parameters":{"binary_data_size":0}},{"name":"scores","datatype":"FP32","shape":[0,1],"parameters":{"binary_data_size":0}}]}
```

The deployments were successfully created, but when I try to run the inference graph, only the second inference service is deployed into the pipeline. Why?

Furthermore, I used the `$responce` value in `spec.nodes.root.steps.serviceName.data` key to test if there is any change, but it didn't happen. It's already not working. The log output on the browser is: 

```log
{"error":"Unable to parse 'inputs': attempt to access non-existing object member 'inputs'"}
```
The inference graph's `describe` log is:

```bash
$ kubectl -n inference-graph describe ig inference-pipeline 

Name:         inference-pipeline
Namespace:    inference-graph
Labels:       <none>
Annotations:  <none>
API Version:  serving.kserve.io/v1alpha1
Kind:         InferenceGraph
Metadata:
  Creation Timestamp:  2025-01-07T09:25:23Z
  Generation:          1
  Resource Version:    18385363
  UID:                 a5b8a953-602c-44fb-8cf4-5f9bdc534409
Spec:
  Nodes:
    Root:
      Router Type:  Sequence
      Steps:
        Service Name:  new-first-infsvc
        Data:          $response
        Service Name:  second-infsvc
Status:
  Conditions:
    Last Transition Time:  2025-01-07T09:25:27Z
    Status:                True
    Type:                  ConfigurationsReady
    Last Transition Time:  2025-01-07T09:25:27Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2025-01-07T09:25:27Z
    Status:                True
    Type:                  RoutesReady
  URL:                     http://inference-pipeline.inference-graph.10.16.11.172.sslip.io
Events:                    <none>
```

I tested with curl command using:

```bash
$ curl http://inference-pipeline.inference-graph.10.16.11.172.sslip.io/ -d @./input.json
{"error":"Unable to parse 'inputs': attempt to access non-existing object member 'inputs'"}
```

But the output is the same as the browser output.

For another test is added a condition with `true` value and used the bottom YAML file for ig:

```yaml
apiVersion: serving.kserve.io/v1alpha1
kind: InferenceGraph
metadata:
  name: "inference-pipeline"
  namespace: "inference-graph"
spec:
  nodes:
    root:
      routerType: Sequence
      steps:
        - serviceName: new-first-infsvc
        - serviceName: second-infsvc
          data: $request
          condition: "true"
```

In this case, the inference graph is created with only the first inference service. Why? I can't understand where is the problem. 

The browser's log:

```log
{"model_name":"new-first-infsvc","model_version":"1","outputs":[{"name":"float_input","datatype":"FP32","shape":[0,1100],"parameters":{"binary_data_size":0}}]}
```

The inference graph's log:

```bash
$ kubectl -n inference-graph describe ig inference-pipeline 
Name:         inference-pipeline
Namespace:    inference-graph
Labels:       <none>
Annotations:  <none>
API Version:  serving.kserve.io/v1alpha1
Kind:         InferenceGraph
Metadata:
  Creation Timestamp:  2025-01-07T09:54:56Z
  Generation:          5
  Resource Version:    18410959
  UID:                 2e177e4d-a233-4927-8822-5102c0349ace
Spec:
  Nodes:
    Root:
      Router Type:  Sequence
      Steps:
        Service Name:  new-first-infsvc
        Condition:     true
        Data:          $request
        Service Name:  second-infsvc
Status:
  Conditions:
    Last Transition Time:  2025-01-07T10:34:22Z
    Status:                True
    Type:                  ConfigurationsReady
    Last Transition Time:  2025-01-07T10:34:22Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2025-01-07T10:34:22Z
    Status:                True
    Type:                  RoutesReady
  URL:                     http://inference-pipeline.inference-graph.10.16.11.172.sslip.io
Events:                    <none>
```

**What did you expect to happen:**
The inference output has to be correct from the sequence.

**Anything else you would like to add:**
- I think there is a problem with the `data` key in the inference graph YAML file because there are two types of keys available: `$request` and `$response`. What are the differences? 
- Should I set the condition with another value (if I should use the `condition` key)?
- The multicluster environment can be the problem? 

**Environment:**

- Istio Version: I mean 1.22.2
- Knative Version: 1.16.0
- KServe Version: 0.13.0
- Kubeflow version: I use kserve serverless
- Microk8s: v1.31.3 revision 7449
- Kubernetes version: (use `kubectl version`): 
```bash
$$ kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.31.3
```
- Cluster type: Multicluster with two nodes and both with the same configuration
- OS (e.g. from `/etc/os-release`): 
```bash
$$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by IonBoleac** [comment]
An update. I tried to use a different inference graph declaration. it's in the bottom:

```yaml
apiVersion: serving.kserve.io/v1alpha1
kind: InferenceGraph
metadata:
  name: "inference-pipeline"
  namespace: "inference-graph"
spec:
  nodes:
    root:
      routerType: Sequence
      steps:
        - name: firstStep
          serviceName: new-first-infsvc
        - name: secondStep
          serviceName: second-infsvc
          # pass the output of "firstStep" to "secondStep"
          data: "$(firstStep)"
```

But still it's not working. Anyone can help me?
