### ISSUE TITLE
Changing the defaultDeploymentMode retroactively changes the deploymentMode of existing InferenceServices

### ISSUE THREAD

**Issue by VedantMahabaleshwarkar** [kserve/kserve#4191]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- Deploy Kserve with `defaultDeploymentMode = Serverless`
- Deploy a few InferenceServices without explicit annotation for deploymentMode
- Change `defaultDeploymentMode = RawDeployment` 
- Restart Kserve Controller
- All active InferenceServices have their deploymentMode changed from Serverless to RawDeployment

**What did you expect to happen:**
- Changing the `defaultDeploymentMode` does not affect existing InferenceServices. 

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-v2-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      protocolVersion: v2
      runtime: kserve-sklearnserver
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
```
