### ISSUE TITLE
Support stop InferenceService

### ISSUE THREAD

**Issue by luohua13** [kserve/kserve#4207]
/kind feature

In a private cloud environment, GPU cards are very scarce. Sometimes I create an InferenceService. When not in use, I hope to stop it and release the resources for others to use in a timely manner. This can efficiently utilize the limited GPU resources. Although Serverless is used, but I want to completely stop it to prevent accidental access. When I need to use it later, I can just start it again without creating a new InferenceService instance again.

In the design, we can add an annotation to the InferenceService, for example `kserve.io/stop: true`,  and then the controller component stops the service, and the InferenceService status field will also show stopped.

**Comment by typhoonzero** [comment]
@terrytangyuan is there any related design or discussions about this feature, to temporarily stop a InverenceService for now?

**Comment by Jooho** [comment]
What a coincidence! I’ve been looking into this issue since yesterday as well, and I’ve been discussing it with folks internally at Red Hat.

This is what I found so far

**For Serverless mode, we need to check knative.**
To get straight to the point, there is currently no solution for this issue within Knative.

There is one potential workaround, though. We can set minReplicas/maxReplicas to 0  to make the pod stop but the problem is it would take a little long time to stop all pods because for now, knative assign the revision timeout to the pod's TerminationGracePeriodSeconds which blocks you from terminating gracefully a pod fast enough. There is already github issue about it https://github.com/knative/serving/issues/15599#issuecomment-2450595196

If knative solve this issue, then kserve can use this feature.

**For rawDeployment**
there is no ways to remove deployment or make replicas set to 0 so we should implement it. 

**Conclusion**
To maintain consistency, I believe it is a good idea to add an annotation like serving.kserve.io/maintenance: true. Based on simple local testing, when this annotation is present, it enables the functionality to forcefully delete deployments or ksvc. Since the isvc remains intact, the reconcile logic can reconstruct the runtime using the existing information.

**Comment by spolti** [comment]
Will this feature aim only Serverless mode, or Raw too?

**Comment by Jooho** [comment]
It should support all modes: serverless/raw and modelmesh but I need to research modelmesh part about it.
The most focusing modes are serverless and raw for now.

**Comment by sukumargaonkar** [comment]
Since this features is planning to remove the underlying pods for an InferenceService, we should also remove the corresponding top level istio-virtual-service that kserve creates. This will ensure that istio is also aware requests should not be routed to the inference service.

**Comment by gavrissh** [comment]
@Jooho, Have you started looking at this? Is there a design document?
We were looking into something similar

**Comment by Jooho** [comment]
@gavrissh  I don't have the design doc for this but we will start to implement this soon @hdefazio  Could you please share what we discussed with him? Plus we need community feedback about the new annotation to.

**Comment by gavrissh** [comment]
Thanks @Jooho, looking forward to this. 

@hdefazio Could you share some info here?

**Comment by hdefazio** [comment]
@gavrissh @Jooho So sorry for the late reply! Here is our proposal:

**Proposal:**
Add a new annotation _serving.kserve.io/stop_ in the Inference Service. This annotation will not be included in the ISVC by default. 


**Implementation**:
_Serverless:_ 
When the annotation _serving.kserve.io/stop_ is set to true, the KSVC (and therefore all related resources) are deleted. 
When the annotation _serving.kserve.io/stop_ is set to false or removed, all deleted resources are recreated. 

_Raw_: When the annotation _serving.kserve.io/stop_ is set to true, the HPA (and therefore all related resources) are deleted. 
When the annotation _serving.kserve.io/stop_ is set to false or removed, all deleted resources are recreated. 


**Result**:
I propose that the ISVC status is set to the following when stopped: 

```
status:
  conditions:
	- lastTransitionTime: '2025-02-20T01:00:46Z'
  	reason: Stopped
  	severity: Info
  	status: False
  	type: LatestDeploymentReady
	- lastTransitionTime: '2025-02-20T01:00:46Z'
  	status: False
  	type: Ready
  	reason: Stopped
	- lastTransitionTime: '2025-02-20T01:00:46Z'
  	reason: Stopped
  	severity: Info
  	status: False
  	type: RoutesReady
	- lastTransitionTime: '2025-02-20T01:00:46Z'
  	severity: Info
  	status: 'True'
  	type: Stopped
  modelStatus:
	transitionStatus: 'Stopped'
```
The change involves clearing the status field and then setting all remaining status fields to `reason: Stopped`. We also add a new status of `type: Stopped` that will be set to true/false based on the _serving.kserve.io/stop_ annotation. 

When the ISVC is not stopped, the status will behave as usual.
