### ISSUE TITLE
Unable to Load Model from MinIO: NoCredentialsError and ImagePullBackOff Errors

### ISSUE THREAD

**Issue by MuhamedAyoub** [kserve/kserve#4209]
/kind bug

I’m trying to deploy an InferenceService using KServe to serve a model stored in MinIO. However, the storage-initializer container is failing with a NoCredentialsError. Despite following the documentation and ensuring that the Secret and ServiceAccount are correctly configured, the issue persists.

Steps to Reproduce

**Yaml File**: 
```yaml 
apiVersion: v1
kind: Namespace
metadata:
  name: model-testing

---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: titanic-model
  namespace: model-testing
  annotations:
    sidecar.istio.io/inject: "false"  
spec:
  predictor:
    sklearn:
      storageUri: s3://titanic-model/logistic_model.pkl
      serviceAccountName: kserve-minio-account
      image: kfserving/storage-initializer:v0.6.1

---

apiVersion: v1
kind: Secret
metadata:
  name: kserve-minio-secret
  namespace: model-testing
  annotations:
    serving.kserve.io/s3-endpoint: minio.kubeflow:9000 
    serving.kserve.io/s3-usehttps: "0" 
    serving.kserve.io/s3-region: "minio" 
    serving.kserve.io/s3-useanoncredential: "false" 
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-minio-account
  namespace: model-testing
  annotations:
    serving.kserve.io/s3-endpoint: minio.kubeflow:9000 
    serving.kserve.io/s3-usehttps: "0" 
    serving.kserve.io/s3-region: "minio" 
    serving.kserve.io/s3-useanoncredential: "false" 
secrets:
  - name: kserve-minio-secret


 ```

**Comment by Jooho** [comment]
```
spec:
  predictor:
    sklearn:
      storageUri: s3://titanic-model/logistic_model.pkl
      serviceAccountName: kserve-minio-account
      image: kfserving/storage-initializer:v0.6.1
```
storage-initializer will be injected by mutating webhook so you should not set this in here. so please remove the image field here and refer this example
https://kserve.github.io/website/latest/modelserving/v1beta1/sklearn/v2/#deploy-the-model-with-rest-endpoint-through-inferenceservice
