### ISSUE TITLE
Initializer pod cannot download mlflow artifacts from a non-AWS s3 compatible endpoint

### ISSUE THREAD

**Issue by Safarveisi** [kserve/kserve#4216]
/kind bug

**What steps did you take and what happened:**

I installed KServe following the steps documented at [Serverless Installation Guide](https://kserve.github.io/website/0.13/admin/serverless/serverless/). I would like to deploy a mlflow model (pushed before into a S3 bucket) using the KServe InferenceService CRD. For this, I followed the example at [Model on S3](https://kserve.github.io/website/0.13/modelserving/storage/s3/s3/). The following are the yaml files for `ServiceAccount`, `Secret` and `InferenceService` written based on the example there with some adjustments for the S3 endpoint and its credentials as well as the storage uri:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  annotations:
    serving.kserve.io/s3-endpoint: **s3-de-central.profitbricks.com:443**
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-region: "eu-central-1"
    serving.kserve.io/s3-useanoncredential: "false"
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: s3creds
  annotations:
     serving.kserve.io/s3-endpoint: **s3-de-central.profitbricks.com:443**
     serving.kserve.io/s3-usehttps: "1"
     serving.kserve.io/s3-region: "eu-central-1"
     serving.kserve.io/s3-useanoncredential: "false"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: <ToBeFilled>
  AWS_SECRET_ACCESS_KEY: <ToBeFilled>
```

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
secrets:
- name: s3creds
```

```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "iris-classifier-s3"
  annotations:
    autoscaling.knative.dev/minScale: "1"
    autoscaling.knative.dev/maxScale: "3"
spec:
  predictor:
    serviceAccountName: sa
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "s3://bucket/ml_platform/mlartifacts/1/af117c0db2834973a3b47552b6b68d42/artifacts/iris_xgb"
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
```

After deploying, I get the following error in the initializer pod for the inference deployment: 

```text
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**What did you expect to happen:**

The initializer pod should be able to download the mlflow model artifacts into /mnt/models in the container. 

**Anything else you would like to add:**

Note that I did not change the default configuration for KServe, Istio and Knative before and after installing them. 

**Environment:**

- Istio Version: Installed while installing [Knative 1.11](https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/)
- Knative Version: 1.11
- KServe Version: 0.13
- Cloud Environment: IONOS cloud
- Kubernetes version: (use `kubectl version`): 1.31.3
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.5 LTS
