### ISSUE TITLE
Kubeflow users cannot create TrainedModel type resources

### ISSUE THREAD

**Issue by gigabyte132** [kserve/kserve#4224]
/kind bug

**What steps did you take and what happened:**
The default kubeflow user service account forbids users to create resources of type TrainedModel, this is useful for a  of serving use cases where you want to serve multiple models in the same InferenceService.

I will shortly open a PR to fix this issue as well, as it is just a matter of adding trainedmodels to the `kubeflow-kserve-edit` and `kserve-kubeflow-view` ClusterRoles in `kserve/config/overlays/kubeflow/cluster-role.yaml`

As a normal kubeflow user, in multi-user mode at least, you will get the following error when trying to create a resource of type TrainedModel from inside a Notebook. the serviceAccounts `default-editor` and `default-viewer` do not currently have permissions to create/view such a resource.
```
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "serving.kserve.io/v1alpha1, Resource=trainedmodels", GroupVersionKind: "serving.kserve.io/v1alpha1, Kind=TrainedModel"
Name: "simple-string", Namespace: "rchiores"
from server for: "model2.yaml": trainedmodels.serving.kserve.io "simple-string" is forbidden: User "system:serviceaccount:rchiores:default-editor" cannot get resource "trainedmodels" in API group "serving.kserve.io" in the namespace "rchiores"
```

**What did you expect to happen:**
Users in Kubeflow should be able to create and view `TrainedModel` type resources. 

**What's the InferenceService yaml:**

Triton InferenceService with any TrainedModel type resource
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "triton-mms"
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    triton:
      args:
      - --log-verbose=1
      env:
      - name: OMP_NUM_THREADS
        value: "1"  
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi(base)
```
```
apiVersion: "serving.kserve.io/v1alpha1"
kind: "TrainedModel"
metadata:
  name: "cifar10"
spec:
  inferenceService: triton-mms
  model:
    framework: pytorch
    storageUri: gs://kfserving-examples/models/torchscript/cifar10
    memory: "1Gi"
```

**Anything else you would like to add:**

**Environment:**
- Istio Version:  1.22.1-cni
- Knative Version: v0.13.0
- KServe Version: v0.13.0
- Kubeflow version: 1.9.1
- Cloud Environment: k8s_istio
- Kubernetes version: (use `kubectl version`): v1.30.2
