### ISSUE TITLE
Container won't start when adding  "enable_docs_url=True" argument

### ISSUE THREAD

**Issue by MaxZhuravsky** [kserve/kserve#4240]
I'm running on a local Minikube Kubernetes node and encountering some errors with my deployment.

Here is the content of my deployment.yaml

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "s3-classifier"
  namespace: "mlflow-kserve-testv2"
spec:
  predictor:
    minReplicas: 1
    serviceAccountName: sa
    model:
      args: [--enable_docs_url=True]
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "s3://mycustomurl"
```

added the args according to https://kserve.github.io/website/0.11/get_started/swagger_ui/

error:
Error: failed to start container "kserve-container": Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "--enable_docs_url=True": executable file not found in $PATH: unknown
Back-off restarting failed container kserve-container in pod s3-classifier-predictor-00002-deployment-7f9857b55c-v64vh_mlflow-kserve-testv2(a29b0efa-f496-4d77-b086-e42ee67108d1)
Readiness probe failed: Get "http://10.244.0.236:8012/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

any idea?
