### ISSUE TITLE
Request Logger with multiple metadata headers fails

### ISSUE THREAD

**Issue by tylerhyang** [kserve/kserve#4248]
/kind bug

**What steps did you take and what happened:**
Create an inference service with multiple headers with the following logger section in the predictor spec:
```
    logger:
      metadataHeaders:
        - Custom-Header1
        - Custom-Header2
```
and deploy the modified inference service with the message dumper noted here: https://kserve.github.io/website/0.14/modelserving/logger/logger/

When more than one header is sent, the metadata extension field in the CloudEvent is empty.  When only one header is sent, there is no issue.

**What did you expect to happen:**
Each header should be seen in the metadata extension field

**What's the InferenceService yaml:**
```
spec:
  predictor:
    canaryTrafficPercent: 100
    initContainers:
      - args:
          - [OMITTED]
        env:
          - name: KNATIVE_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['serving.knative.dev/service']
          - name: KNATIVE_CONFIGURATION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['serving.knative.dev/configuration']
          - name: KNATIVE_REVISION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['serving.knative.dev/revision']
          - name: PROMETHEUS_PUSHGATEWAY_URL
            value: OMITTED
        image: >-
          OMITTED
        name: storage-initializer
        resources: {}
        volumeMounts:
          - mountPath: /mnt/serving
            name: model-provision
    logger:
      metadataHeaders:
        - Custom-Header-1
        - Custom-Header-2 
      mode: all
      url: http://message-dumper.default/
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--model-store=/mnt/serving/model-store'
      modelFormat:
        name: OMITTED
      name: ''
      protocolVersion: v2
      resources:
        requests:
          cpu: '1'
          memory: 2Gi
      runtime: OMITTED
      storageUri: >-
       OMITTED
      volumeMounts:
        - mountPath: /mnt/serving
          name: model-provision
          readOnly: true
    serviceAccountName: OMITTED
    volumes:
      - emptyDir: {}
        name: model-provision
```
**Anything else you would like to add:**
I would like to solve this if possible since I believe I have found the issue :)

**Environment:**

- Istio Version: 1.22
- Knative Version: 1.13.1
- KServe Version: 1.14.0
- Kubeflow version: N/A
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]: aws
- Minikube/Kind version: N/A
- Kubernetes version: (use `kubectl version`): 1.30.2
- OS (e.g. from `/etc/os-release`): linux/amd64
