### ISSUE TITLE
How to disable hpa by default, thanks.

### ISSUE THREAD

**Issue by johnzheng1975** [kserve/kserve#4252]
/kind feature

I want to disable hpa, when creating a isvc. 
The reason is: I am using my own hpa based on custom metrics (requests/ gpu/ ...). Knative is not used.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
With an annotation (like: hpaDisabled: true), the hpa object will not be created.

Currently, the hpa will always be created by default
```
# kubectl  get isvc -n xxx-dev samplenew -oyaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    meta.helm.sh/release-name: samplenew
    meta.helm.sh/release-namespace: xxx-dev
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
    serving.kserve.io/deploymentMode: RawDeployment
    autoscaling.knative.dev/class: "disabled"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: samplenew
    helm.toolkit.fluxcd.io/namespace: xxx-dev
  name: samplenew
  namespace: xxx-dev
spec:
  #replicas: 2
  predictor:
    containers:
    - image: harbor.ext.xxx.com/xxxservices/ai_inference-dev:v0.0.224
      livenessProbe:
        httpGet:
          path: /v2/models
          port: 8080
      name: kserve-container
      readinessProbe:
        httpGet:
          path: /v2/models
          port: 8080
      resources:
        limits:
          cpu: "2"
          memory: 3036Mi
        requests:
          cpu: 500m
          memory: 1Gi
    imagePullSecrets:
    - name: pull-secret
```
```
# kubectl  get hpa -n omenservices-dev samplenew-predictor
NAME                  REFERENCE                        TARGETS       MINPODS   MAXPODS   REPLICAS   AGE
samplenew-predictor   Deployment/samplenew-predictor   cpu: 0%/80%   1         1         1          88s
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Links to the design documents:**
[Optional, start with the short-form [RFC template](https://docs.google.com/document/d/1UcBeLfZ_JMGpVrPJmYtEIVH_9Y4U3AEKQdq_IKuOMrU) to outline your ideas and get early feedback.]
[Required, use the longer-form [design doc template](https://docs.google.com/document/d/1Mtoui_PP2a9N59NjYHnsvrdJ8t2iKFwIJAx1zRO_I1c) to specify and discuss your design in more detail]

**Comment by johnzheng1975** [comment]
ok, below annotation can work.
**serving.kserve.io/autoscalerClass: "external"** 

Now, I need not delete this additional hpa or modify it. Just use my own hpa for gpu/ requests.
FYI

With promtheus adapter, 
```
apiVersion: v1
data:
  config.yaml: |
    rules:
    - metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[5m])) by (<<.GroupBy>>)
      name:
        as: requests_per_second
        matches: istio_requests_total
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      seriesQuery: istio_requests_total{pod!="", namespace!=""}
kind: ConfigMap
```

With our own defined hpa,
```
# kubectl  get hpa -n xxx-dev sample
NAME     REFERENCE                     TARGETS    MINPODS   MAXPODS   REPLICAS   AGE
sample   Deployment/sample-predictor   16m/500u   2         4         4          12h


# kubectl  get hpa -n omenservices-dev sample -oyaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    meta.helm.sh/release-name: sample
    meta.helm.sh/release-namespace: xxx-dev
  name: sample
  namespace: xxxx-dev
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 60
        type: Percent
        value: 10
      - periodSeconds: 60
        type: Pods
        value: 4
      selectPolicy: Max
      stabilizationWindowSeconds: 900
    scaleUp:
      policies:
      - periodSeconds: 15
        type: Pods
        value: 4
      - periodSeconds: 15
        type: Percent
        value: 100
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  maxReplicas: 4
  metrics:
  - pods:
      metric:
        name: requests_per_second
      target:
        averageValue: 500u
        type: Value
    type: Pods
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-predictor
```
