### ISSUE TITLE
Add support specifying `ClusterStorageContainer` name in `InferenceService`

### ISSUE THREAD

**Issue by kimminw00** [kserve/kserve#4258]
**Describe the solution you'd like**
Currently, the <code>InferenceService</code> resource allows users to specify the storageUri of the model, but it does not provide a way to specify the name of the <code>ClusterStorageContainer</code> to use. This can lead to ambiguity and confusion, especially in environments where multiple <code>ClusterStorageContainer</code> resources are available.

In the <code>StorageSpec</code> section of the <code>InferenceService</code> resource, only path, schemaPath, parameters, and key are supported. I propose adding a name field to the <code>StorageSpec</code> section, which would allow users to specify the name of the <code>ClusterStorageContainer</code> to use.

Here's an example of how the <code>InferenceService</code> resource could be modified to support specifying the <code>ClusterStorageContainer</code> name:

```yaml
apiVersion: "serving.kserve.io/v1alpha1"
kind: ClusterStorageContainer
metadata:
  name: mr-initializer
spec:
  container:
    name: storage-initializer
    image: quay.io/kubeflow/model-registry-storage-initializer:latest
    env:
    - name: MR_BASE_URL
      value: "modelregistry-sample.kubeflow.svc.cluster.local:8080"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: "1"
  supportedUriFormats:
    - prefix: model-registry://

---

apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: iris-model
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storage:
        # There should be a better field name than 'name'.
        name: mr-initializer 
        path: "model-registry://iris/v1"
        schemaPath: ...
        parameters: ...
        key: ...
```
  
**Reference**
https://kserve.github.io/website/0.14/reference/api/#serving.kserve.io/v1beta1.StorageSpec
