### ISSUE TITLE
KServe: HPA: Support Custom Metric Definition

### ISSUE THREAD

**Issue by egvikosh** [kserve/kserve#4259]
/kind feature

**Describe the solution you'd like**
It would be good to include support of custom metric for hpa according to k8s api: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-metrics-apis.
Our usecase is following: we do the model services autoscaling based on advanced custom metrics from gpu and model service itself (we use triton for serving framework), we have configured prometheus scrapper and prometheus adapter, so we have all metrics from triton in metrics server, but we could not use them, because kserve spec do not have option to provide custom metric definition. We do not need too much here, just to have ability to customize so that config will be put to hpa as is.
We use kserve in raw mode, because decided to do not install knative.
Thank you!

**Anything else you would like to add:**
Some example of possible configuration:

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: model-services-trt-asr-1
  annotations:
    serving.kserve.io/enable-prometheus-scraping: "true"
spec:
  predictor:
    serviceAccountName: default
    imagePullSecrets:
      - name: <artifactory>
    maxReplicas: 2
    metrics:
      - type: Object
        object:
          target:
            kind: Deployment
            name: model-services-trt-asr-1-predictor
          metricName: nv_gpu_utilization
          targetValue: 0.5
    triton:
      image: "<image>"
      storageUri: "<model>"
      resources:
        limits:
          cpu: "3"
          memory: 14Gi
          nvidia.com/gpu: 1
        requests:
          cpu: "2"
          memory: 8Gi
          nvidia.com/gpu: 1
```

**Comment by rahimftd** [comment]
+1 would love to see this as well.

**Comment by yuzisun** [comment]
@egvikosh this is supported in KServe 0.15, do you want to try out?
https://kserve.github.io/website/latest/modelserving/autoscaling/keda/autoscaling_keda/

**Comment by MarshHawk** [comment]
> [@egvikosh](https://github.com/egvikosh) this is supported in KServe 0.15, do you want to try out? https://kserve.github.io/website/latest/modelserving/autoscaling/keda/autoscaling_keda/

@yuzisun could you please clarify specifically:
- in 0.15, using a custom metric for hpa such as `type: ContainerResource` to scale on CPU container percentage (e.g. without Istio sidecar) is not supported w/out Keda?
- similarly, using custom metrics like Istio rps via Prometheus is not supported w/out Keda or knative?

**Comment by pierDipi** [comment]
@MarshHawk yes, in 0.15, KEDA is required for custom metrics autoscaling

**Comment by egvikosh** [comment]
Thanks for update, I created request when version 0.14 was the latest. Solution with KEDA looks good (but requires KEDA installation), for our case we manage to support it with custom logic (disabled hpa creation in kserve and created hpa with metrics config we need). 
Do not know how much work is require, but I think it will good just to support config forwarding to native hpa from inference service config - for the cases when user do not want to install additional frameworks by some reason.

**Comment by MarshHawk** [comment]
> [@MarshHawk](https://github.com/MarshHawk) yes, in 0.15, KEDA is required for custom metrics autoscaling

I can also confirm that we chose to disable hpa creation and use HPA metrics deployed alongside InferenceService and it’s been working nicely as long as minReplicas parameter are aligned in both specs…

**Comment by omij18** [comment]
@pierDipi @MarshHawk 
Does this support scaling modifiers like keda ScaledObject?
What is the major difference creating scaledobject for underlying Deployment vs adding metrics in InferenceService Spec?

**Comment by yuzisun** [comment]
> Thanks for update, I created request when version 0.14 was the latest. Solution with KEDA looks good (but requires KEDA installation), for our case we manage to support it with custom logic (disabled hpa creation in kserve and created hpa with metrics config we need). Do not know how much work is require, but I think it will good just to support config forwarding to native hpa from inference service config - for the cases when user do not want to install additional frameworks by some reason.

@egvikosh can you help elaborate which config can not be passed from InferenceService to HPA ?

**Comment by ajaen4** [comment]
@egvikosh @MarshHawk how did you disable the HPA creation? I am setting the following annotation with no luck:

`serving.kserve.io/autoscalerClass: external`

**Comment by egvikosh** [comment]
> [@egvikosh](https://github.com/egvikosh) [@MarshHawk](https://github.com/MarshHawk) how did you disable the HPA creation? I am setting the following annotation with no luck:
> 
> `serving.kserve.io/autoscalerClass: external`

```
metadata:
  annotations:
    serving.kserve.io/autoscalerClass: "external"
```
This works for me with kserve version 0.14.1

**Comment by egvikosh** [comment]
> > Thanks for update, I created request when version 0.14 was the latest. Solution with KEDA looks good (but requires KEDA installation), for our case we manage to support it with custom logic (disabled hpa creation in kserve and created hpa with metrics config we need). Do not know how much work is require, but I think it will good just to support config forwarding to native hpa from inference service config - for the cases when user do not want to install additional frameworks by some reason.
> 
> [@egvikosh](https://github.com/egvikosh) can you help elaborate which config can not be passed from InferenceService to HPA ?

Basically forward of standard hpa metrics section:
```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
spec:
  scaleTargetRef:
    kind: Deployment
    name: <deployment-name>
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Object
      object:
        describedObject:
          kind: Deployment
          name: <deployment-name>
          apiVersion: apps/v1
        target:
          type: Value
          value: '700'
        metric:
          name: nv_inference_request_latency_ms
```

Also would be nice to forward behavior section also:
```
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 480
    scaleDown:
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
```
