### ISSUE TITLE
How model versions suppose to work?

### ISSUE THREAD

**Issue by lethnis** [kserve/kserve#4264]
I have a PVC with the following structure:
```
volume/
├─ models/
│  ├─ lightgbm-iris/
│  │  ├─ 1/
│  │  │  ├─ model.bst
│  │  ├─ 2/
│  │  │  ├─ model.bst
│  │  ├─ 3/
│  │  │  ├─ model.bst
```
I created an endpoint using following yaml:
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "lightgbm-v2-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: lightgbm
      runtime: kserve-lgbserver
      protocolVersion: v2
      storageUri: "pvc://volume/models/lightgbm-iris"
```
When I send a get request to it, it shows that i have 3 different models, instead of 1 model with 3 different versions.
What i get:
```
response = requests.get("http://lightgbm-v2-iris.../v2/models/")
response.text
# {"models":["1","2","3"]}
```
What I expected:
```
response = requests.get("http://lightgbm-v2-iris.../v2/models/")
response.text
# {"models":["lightgbm-iris"]}
```
What I get when I send a get request to a specific model:
```
response = requests.get("http://lightgbm-v2-iris.../v2/models/1")
response.text
# {"name":"1","versions":null,"platform":"","inputs":[],"outputs":[]}
```
What I expected if I've had model 'lightgbm-iris':
```
response = requests.get("http://lightgbm-v2-iris.../v2/models/lightgbm-iris")
response.text
# {"name":"1","versions":["1","2","3"],"platform":"","inputs":[],"outputs":[]}
```
How to properly organize volume structure or what to edit in yaml file to make it work with model versions? Does versioning even work? Do I need modelmesh for it?
