### ISSUE TITLE
tls: failed to verify certificate: x509 on Multi-Model Serving

### ISSUE THREAD

**Issue by vmalaga** [kserve/kserve#4304]
/kind bug

**What steps did you take and what happened:**

I am trying to deploy a Multi-Model Serving with tritonserver, but the agent container gives an error when adding the TrainedModel hosted on an artifactory server with a self-signed certificate

**What did you expect to happen:**

When I deploy the inferenceservice with the storageUri, the storagecontainer correctly uses the caBundleConfigMapName where the CA is, but if I use the multi-model, first the inferenceservice without storageUri and also the TrainedModel with its storageUri in artifactory, it returns the error

**What's the InferenceService yaml:**

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "triton-mms"
  namespace: "ie-infra"
  annotations:
    serving.kserve.io/secretName: artifactory-inference-auth
spec:
  predictor:
    nodeSelector:
      nvidia.com/gpu: "true"
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    triton:
      args:
      - --log-verbose=1     
      resources:
        limits:
          cpu: "4"
          memory: 10Gi
        requests:
          cpu: "2"
          memory: 4Gi
---
apiVersion: "serving.kserve.io/v1alpha1"
kind: "TrainedModel"
metadata:
  name: "images-training"
  namespace: "ie-infra"
spec:
  inferenceService: triton-mms
  model:
    framework: tensorflow
    storageUri: "https://artifactory-server.mydomain/artifactory/generic-local/infrastructure-binaries/testmodels/images_training_trt.zip"
    memory: 3Gi
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.25.0
- Knative Version: NA
- KServe Version: v0.14.0 - RawDeployment
- Kubeflow version: NA
- Cloud Environment: aws
- Minikube/Kind version: NA
- Kubernetes version: 1.31

kubectl -n ie-infra logs triton-mms-predictor-788956c7f4-9lwfg agent

{"severity":"INFO","timestamp":"2025-03-12T08:35:51.68863541Z","caller":"agent/puller.go:144","message":"Worker is started for images-training"}
{"severity":"INFO","timestamp":"2025-03-12T08:35:51.68868611Z","caller":"agent/puller.go:152","message":"Downloading model from https://artifactory-server.mydomain/artifactory/gl-seiri-generic-local/infrastructure-binaries/testmodels/images_training_trt.zip"}
{"severity":"INFO","timestamp":"2025-03-12T08:35:51.688747821Z","caller":"agent/downloader.go:47","message":"Downloading https://artifactory-server.mydomain/artifactory/gl-seiri-generic-local/infrastructure-binaries/testmodels/images_training_trt.zip to model dir /mnt/models"}
{"severity":"INFO","timestamp":"2025-03-12T08:35:51.688855734Z","logger":"modelAgent","caller":"storage/https.go:45","message":"Download model ","modelName":"images-training","storageUri":"https://artifactory-server.mydomain/artifactory/gl-seiri-generic-local/infrastructure-binaries/testmodels/images_training_trt.zip","modelDir":"/mnt/models"}
{"severity":"ERROR","timestamp":"2025-03-12T08:35:51.710312588Z","caller":"agent/puller.go:157","message":"Failed to download model images-training with err failed to download model: failed to download model: failed to make a request: Get \"https://artifactory-server.mydomain/artifactory/gl-seiri-generic-local/infrastructure-binaries/testmodels/images_training_trt.zip\": tls: failed to verify certificate: x509: certificate signed by unknown authority","stacktrace":"github.com/kserve/kserve/pkg/agent.(*Puller).modelProcessor.func1\n\t/go/src/github.com/kserve/kserve/pkg/agent/puller.go:157\ngithub.com/kserve/kserve/pkg/agent.(*Puller).modelProcessor\n\t/go/src/github.com/kserve/kserve/pkg/agent/puller.go:221"}
{"severity":"INFO","timestamp":"2025-03-12T08:35:51.710366361Z","caller":"agent/puller.go:137","message":"completion event for model images-training, in flight ops 0"}
