### ISSUE TITLE
No error reported in the status when storageUri protocol validation fails

### ISSUE THREAD

**Issue by danielezonca** [kserve/kserve#4309]
/kind bug

**What steps did you take and what happened:**
- Create an InferenceService with a wrong protocol in `storageUri` like `asd://`
- Apply the resource
- The reconcile loop fails without reporting the error in the `status` of the InfererenceService 
- The InferenceService remains unprocessed and without `status`
 
In `kserve-controller` log there is this message
```log
{"level":"error","ts":"2025-03-10T10:16:47Z","logger":"v1beta1Controllers.InferenceService","msg":"Failed to reconcile","reconciler":"<*components.Predictor Value>","Name":"test","error":"StorageURI not supported: storageUri, must be one of: [gs://, s3://, pvc://, file://, https://, http://, hdfs://, webhdfs://, oci://] or match https://{}.blob.core.windows.net/{}/{} or be an absolute or relative local path. StorageUri [hf://facebook/opt-125m] is not supported","stacktrace":"github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime...
{"level":"error","ts":"2025-03-10T10:16:47Z","msg":"Reconciler error","controller":"inferenceservice","controllerGroup":"serving.kserve.io","controllerKind":"InferenceService","InferenceService":{"name":"test","namespace":"test-project"},"namespace":"test-project","name":"test","reconcileID":"bcf94d32-ceaf-48fd-adfa-6e03a135905b","error":"fails to reconcile component: StorageURI not supported: storageUri, must be one of: [gs://, s3://, pvc://, file://, https://, http://, hdfs://, webhdfs://, oci://] or match https://{}.blob.core.windows.net/{}/{} or be an absolute or relative local path. StorageUri [hf://facebook/opt-125m] is not supported","errorVerbose":"StorageURI not supported: storageUri, must be one of: [gs://, s3://, pvc://, file://, https://, http://, hdfs://, webhdfs://, oci://] or match https://{}.blob.core.windows.net/{}/{} or be an absolute or relative local path. StorageUri [hf://facebook/opt-125m] is not supported\nfails to reconcile component\ngithub.com/kserve/kserve/pkg/controller/v1beta1/...
```

**What did you expect to happen:**
The validation error should be reported in the status

**What's the InferenceService yaml:**
InferenceService
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: test
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: huggingface
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 4Gi
      runtime: test
      storageUri: 'asd://facebook/opt-125m'
```
