### ISSUE TITLE
Hugging Face protocol (hf://) is not accepted

### ISSUE THREAD

**Issue by danielezonca** [kserve/kserve#4310]
/kind bug

**What steps did you take and what happened:**
KServe 0.14 introduced the [hf:// protocol](https://kserve.github.io/website/latest/blog/articles/2024-12-13-KServe-0.14-release/#support-for-hugging-face-hub-in-storage-initializer) to download automatically the model from Hugging Face but it looks not working.

Steps:
- Apply a InferenceService that uses `hf://` protocol as `storageURI`
- The model is not scheduled
- No status update (reported in https://github.com/kserve/kserve/issues/4309 as a different bug)

Digging in the code the bug is related to a fixed list of supported protocols that has not been updated to include `hf://` that makes the reconcile loop fail.
https://github.com/kserve/kserve/blob/master/pkg/apis/serving/v1beta1/component.go#L61
```python
	SupportedStorageSpecURIPrefixList = []string{"s3://", "hdfs://", "webhdfs://"}
```

There is a misleading error message too in this other method where the `hf://` protocol is checked but not reported in the error message
https://github.com/kserve/kserve/blob/master/python/kserve/kserve/storage/storage.py#L106-L107
```python
                raise Exception(
                    "Cannot recognize storage type for "
                    + uri
                    + "\n'%s', '%s', '%s', and '%s' are the current available storage type."
                    % (_GCS_PREFIX, _S3_PREFIX, _LOCAL_PREFIX, _HTTP_PREFIX)
                )
```

**What did you expect to happen:**
The model to be deployed

**What's the InferenceService yaml:**
InferenceService
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: test
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: huggingface
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 4Gi
      runtime: test
      storageUri: 'hf://facebook/opt-125m'
```

The resource is not updated (aka no status) but in `kserve-controller` log there is this message
```log
{"level":"error","ts":"2025-03-10T10:16:47Z","logger":"v1beta1Controllers.InferenceService","msg":"Failed to reconcile","reconciler":"<*components.Predictor Value>","Name":"test","error":"StorageURI not supported: storageUri, must be one of: [gs://, s3://, pvc://, file://, https://, http://, hdfs://, webhdfs://, oci://] or match https://{}.blob.core.windows.net/{}/{} or be an absolute or relative local path. StorageUri [hf://facebook/opt-125m] is not supported","stacktrace":"github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime...
{"level":"error","ts":"2025-03-10T10:16:47Z","msg":"Reconciler error","controller":"inferenceservice","controllerGroup":"serving.kserve.io","controllerKind":"InferenceService","InferenceService":{"name":"test","namespace":"test-project"},"namespace":"test-project","name":"test","reconcileID":"bcf94d32-ceaf-48fd-adfa-6e03a135905b","error":"fails to reconcile component: StorageURI not supported: storageUri, must be one of: [gs://, s3://, pvc://, file://, https://, http://, hdfs://, webhdfs://, oci://] or match https://{}.blob.core.windows.net/{}/{} or be an absolute or relative local path. StorageUri [hf://facebook/opt-125m] is not supported","errorVerbose":"StorageURI not supported: storageUri, must be one of: [gs://, s3://, pvc://, file://, https://, http://, hdfs://, webhdfs://, oci://] or match https://{}.blob.core.windows.net/{}/{} or be an absolute or relative local path. StorageUri [hf://facebook/opt-125m] is not supported\nfails to reconcile component\ngithub.com/kserve/kserve/pkg/controller/v1beta1/...
```

**Anything else you would like to add:**
It looks like the list of protocol is duplicated and it should benefit from being refactored.

**Comment by spolti** [comment]
Interesting, it looks like this const is defined it two different places:
 https://github.com/kserve/kserve/blob/master/pkg/controller/v1beta1/inferenceservice/utils/utils.go#L47

**Comment by danielezonca** [comment]
> Interesting, it looks like this const is defined it two different places: https://github.com/kserve/kserve/blob/master/pkg/controller/v1beta1/inferenceservice/utils/utils.go#L47

Yes, this seems to be part of the cause of the issue, there is duplication in the list of protocol and validation that should be refactored as I have suggested

> Anything else you would like to add:
> It looks like the list of protocol is duplicated and it should benefit from being refactored.

I would keep this ticket just to fix the issue and unlock the usage of `hf://` protocol and postpone to a later ticket the refactoring of storage initializer logic

**Comment by spolti** [comment]
> I would keep this ticket just to fix the issue and unlock the usage of hf:// protocol and postpone to a later ticket the refactoring of storage initializer logic

This can be done as part of the second ticket you've opened.

**Comment by ValerioSpenn** [comment]
Hello, i have installed tha 0.14.1 version. I have the same issue. I followed this guide:
https://kserve.github.io/website/master/modelserving/storage/huggingface/hf/

**Comment by spolti** [comment]
Hi, the pr is here: https://github.com/kserve/kserve/pull/4359
Please take a look!

Thanks.

**Comment by spolti** [comment]
I hit this issue while testing it:
```bash
2025-04-03 19:26:55.288 1 kserve INFO [initializer-entrypoint:<module>():16] Initializing, args: src_uri [hf://google/t5-small-lm-adapt] dest_path[ [/mnt/models]
2025-04-03 19:26:55.289 1 kserve INFO [storage.py:download():64] Copying contents of hf://google/t5-small-lm-adapt to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 17, in <module>
    Storage.download(src_uri, dest_path)
  File "/kserve/kserve/storage/storage.py", line 101, in download
    model_dir = Storage._download_hf(uri, out_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kserve/kserve/storage/storage.py", line 313, in _download_hf
    snapshot_download(
  File "/prod_venv/lib64/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/prod_venv/lib64/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 265, in snapshot_download
    os.makedirs(os.path.dirname(ref_path), exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  [Previous line repeated 1 more time]
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/.cache'
```

Will investigate it better.

**Comment by spolti** [comment]
@ValerioSpenn 

You can use `ClusterStorageContainer`:
```yaml
apiVersion: "serving.kserve.io/v1alpha1"
kind: ClusterStorageContainer
metadata:
  name: default
spec:
  container:
    name: storage-initializer
    image: kserve/storage-initializer:latest
    env: 
      - name: HUGGINGFACE_HUB_CACHE
        value: /mnt/models
  supportedUriFormats:
    - prefix: hf://
    - prefix: gs://
    - prefix: s3://
    - prefix: hdfs://
    - prefix: webhdfs://
    - regex: "https://(.+?).blob.core.windows.net/(.+)"
    - regex: "https://(.+?).file.core.windows.net/(.+)"
    - regex: "https?://(.+)/(.+)"
```
