### ISSUE TITLE
KServe not create `gateway instance pod` and a `LoadBalancer service` in RawDeployment mode with kong ingress gateway

### ISSUE THREAD

**Issue by superlins** [kserve/kserve#4335]
/kind bug

**What steps did you take and what happened:**

Step1, create two gatewayclass use `konghq.com/kic-gateway-controller` and `ACCEPTED` eq true

```bash
kubectl get gatewayclasses.gateway.networking.k8s.io                                                                                   ⎈ minikube 00:08:19
NAME    CONTROLLER                          ACCEPTED   AGE
envoy   konghq.com/kic-gateway-controller   True       64m
kong    konghq.com/kic-gateway-controller   True       7d1h
```

Step2, install kserve by helm(i already installed cret-manager and kserve-crds)

```bash
helm upgrade --install -n kserve kserve oci://ghcr.io/kserve/charts/kserve --version v0.14.1 \
 --set kserve.controller.deploymentMode=RawDeployment \
 --set kserve.controller.gateway.ingressGateway.enableGatewayApi=true \
 --set kserve.controller.gateway.ingressGateway.createGateway=true \
 --set kserve.controller.gateway.ingressGateway.kserveGateway=kserve/kserve-ingress-gateway
```

Step3, like [Kubernetes Ingress to Gateway API Migration Guide](https://kserve.github.io/website/master/admin/gatewayapi_migration/) desc

> KServe can automatically create a default Gateway named kserve-ingress-gateway during installation if the Helm value kserve.controller.gateway.ingressGateway.createGateway set to true. If you choose to use this default gateway, you can skip this step and proceed to [step 6](https://kserve.github.io/website/master/admin/gatewayapi_migration/#6-restart-the-kserve-controller).

i exec cmd as below and get nothing..

```bash
kubectl get pods,svc -l serving.kserve.io/gateway=kserve-ingress-gateway -A
No resources found
```

I checked kserve-controller-manager logs but nothing, what i missing??

I try to manual create `gateway` like below(ref [kserve helm tmp/ingress_gateway.yaml](https://github.com/kserve/kserve/blob/master/charts/kserve-resources/templates/ingress_gateway.yaml)) and i got a error: Error from server (BadRequest): error when creating "/private/var/folders/cl/hf4wd6cd6q521141kxy5n3pm0000gn/T/0da4dc1b70fcf62d6973e6db11e5953a/resource.yaml": Gateway in version "v1" cannot be handled as a Gateway: strict decoding error: unknown field "spec.infrastructure"

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kserve-ingress-gateway
  namespace: kserve
spec:
  gatewayClassName: kong
  listeners:
  - name: proxy
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
         from: All
  infrastructure:
    labels:
      serving.kserve.io/gateway: kserve-ingress-gateway
```

deploy success when i delete `infrastructure` node, but no change - also not exists `gateway instance pod` and a `LoadBalancer service`.

**What did you expect to happen:**

Auto-config gateway and httproute if possible.

**What's the InferenceService yaml:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- Minikube version: v1.33.1
- OS: macos
