### ISSUE TITLE
Preprocessing in runtime? Multiple ports issue

### ISSUE THREAD

**Issue by kalantar** [kserve/kserve#4343]
I would like to implement some preprocessing for inference requests. To do this, I am trying to add a container that inspects requests and forwards them.  It would listen for requests (assume http), inspect them and then forward via localhost to the serving container.  I created a `ServingRuntime` to do this by adding a container:
```yaml
  containers:
  - name: preprocess-container
    image: my_container_image
    ports:
    - containerPort: 3000
    env:
    - name: TARGET_URL
      value: http://localhost:3001/
  - name: kserve-container
    ports:
    - containerPort: 3001
    ...
```
However, it appears that the admission webhook rejects the request:
`fails to reconcile predictor: admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: more than one container port is set: spec.template.spec.containers[*].ports\nOnly a single port is allowed across all containers`

Is there a way to implement this sort function?
