### ISSUE TITLE
KServe dataplane cannot find LoRA model

### ISSUE THREAD

**Issue by mikelam-us-aixplain** [kserve/kserve#4345]
/kind bug

**What steps did you take and what happened:**
After [sivanantha321](https://github.com/sivanantha321)'s fix yesterday, I was able to successfully load the LoRA module as indicated by this log message:
`INFO 03-28 14:40:34 serving_models.py:174] Loaded new LoRA adapter: name 'llama_adapter', path '/mnt/large_models/test-finetuned-model/'`

However, when I call the service with a request of the following form, KServe throws an error stating that the model cannot be found.

Request:
```
curl --location 'http://{domain}/openai/v1/completions' \
--header 'Host: {Host URL}' \
--header 'Content-Type: application/json' \
--data '{
    "model": "llama_adapter",
    "prompt": "San Francisco is a",
    "temperature": 0
}'
```

Error:
```
{
    "error": "Model with name llama_adapter does not exist."
}
```

**What did you expect to happen:**
The server should've returned a completion using the LoRA adapter that had been loaded. For reference, this is what a typical response looks like using the base model:
```
{"id":"cmpl-19b421e9-1a0c-4ec0-ad91-8344141885b1","object":"text_completion","created":1743180616,"model":"llama-finetuned","choices":[{"index":0,"text":" city that is known for its many attractions. San Francisco is a city that","logprobs":null,"finish_reason":"length","stop_reason":null,"prompt_logprobs":null}],"usage":{"prompt_tokens":5,"total_tokens":21,"completion_tokens":16,"prompt_tokens_details":null}}
```
**What's the InferenceService yaml:**
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: test-finetuned-model-huggingface
  namespace: default
spec:
  predictor:
    containerConcurrency: 4
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
      - --model_name=llama-finetuned
      - --model_dir=/mnt/large_models/test-finetuned-model/base_model/
      # - --model_id=meta-llama/Llama-2-7b-hf
      - --backend=vllm
      - --enable-lora
      - --lora-modules={"name":"llama_adapter", "path":"/mnt/large_models/test-finetuned-model/"}
      env:
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            key: HF_TOKEN
            name: hf-secret
            optional: false
      modelFormat:
        name: huggingface
      name: ""
      image: 535945872701.dkr.ecr.us-east-1.amazonaws.com/kserve/huggingfaceserver:76a04f95db0faefcc1d3a4d58df771f5814c2039-gpu # Built from https://github.com/sivanantha321/kserve/tree/fix-lora-adaptors-not-loaded
      resources:
        limits:
          cpu: "3.5"
          memory: 29Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "3.5"
          memory: 29Gi
          nvidia.com/gpu: "1"
      volumeMounts:
      - mountPath: /mnt/large_models
        name: kserve-provision-efs
        readOnly: true
    tolerations:
    - effect: NoExecute
      key: dedicated
      operator: Equal
      value: nvidia-l40-1
    volumes:
    - name: kserve-provision-efs
      persistentVolumeClaim:
        claimName: llm-pv-claimer
        readOnly: true
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Previously, [sivanantha321](https://github.com/sivanantha321) had tested the fix using the following 2 lines:

Starting the server:
```
python3 -m huggingfaceserver --http_port=8083 --model_name=llama-3 --model_id=meta-llama/Llama-3.2-1B-Instruct \
    --dtype=float16 --max-model-len=4096 --enable-lora --max-lora-rank=256 \
    --lora-modules indonesian-lora=$HOME/.cache/huggingface/hub/models--digo-prayudha--Llama-3.2-1B-Indonesian-lora/snapshots/636127d560d858bf0b6bf95b798e65cd761aa273
```

Querying the server:
```
curl -v -H "content-type: application/json" -d '{"model": "llama-3", "messages":[{"role": "user", "content": "Tentukan subjek dari kalimat berikut: Film tersebut dirilis kemarin."}]}' http://localhost:8083/openai/v1/chat/completions
```

However, the query uses the _base model_ rather than the _LoRA weights_. I believe his query should've been the following:
```
curl -v -H "content-type: application/json" -d '{"model": "indonesian-lora", "messages":[{"role": "user", "content": "Tentukan subjek dari kalimat berikut: Film tersebut dirilis kemarin."}]}' http://localhost:8083/openai/v1/chat/completions
```

The only exception would be if KServe somehow redirects requests using the base name to the LoRA-adapted weights by default, which would be inconsistent with the [vLLM LoRA implementation](https://docs.vllm.ai/en/stable/features/lora.html#serving-lora-adapters).

I'd appreciate it greatly if you could take a look at this. Thanks in advance, and thank you for the excellent work done so far! Shoutout to [sivanantha321](https://github.com/sivanantha321) for his fantastic and quick service.
