### ISSUE TITLE
Support for Multiple ContainerStorageContainers

### ISSUE THREAD

**Issue by jsnayak** [kserve/kserve#4361]
I am setting up an environment where I have two ClusterStorageContainer defined and created.

- default-csc : Uses the kserve/storage-initializer:latest image
- custom-csc: This is a custom defined csc that I have defined to handle the URI model-registry:// . It is using a custom image (created following the rules defined in [kserve-clusterstoragecontainer](https://kserve.github.io/website/master/modelserving/storage/storagecontainers/#create-the-clusterstoragecontainer-cr)

```
apiVersion: "serving.kserve.io/v1alpha1"
kind: ClusterStorageContainer
metadata:
  name: sftp-csc
spec:
  container:
    name: storage-initializer
    image: myregistry/storage-init-model:1.0.0
    resources:
      limits:
        cpu: "1"
        ephemeral-storage: 1Gi
        memory: 1Gi
      requests:
        cpu: 100m
        ephemeral-storage: 100Mi
        memory: 100Mi
  supportedUriFormats:
    - prefix: model-registry://
```

When I create an InferenceService with the `storageUri: model-registry://model/data`, the system complains and throws the error:
```StorageURI not supported: storageUri, must be one of: [gs://, s3://, pvc://, file://, https://, http://, hdfs://, webhdfs://, oci://], or match https://{}.blob.core.windows.net/{}/{} or be an absolute or relative local path. StorageUri [model-registry://model/data] is not supported```

I further investigated and modified the `storageInitializer` section in the ConfigMap `inferenceservice-config`. When I tested this, I see that the image listed in this configmap is picked in all scenarios irrespective of the URI format.
I understand that the image in this configmap is the default storage initializer image uri but I am not able to override this as required when working with a custom defined URI.

Have I missed any point?

KServe Version: 0.14.0

**Comment by jack-lio** [comment]
Hi, I'd like to work on this issue 

I'm new to KServe but I'm currently exploring how `ClusterStorageContainer` works.  
I'll begin by reproducing the issue and investigating whether it can be addressed through a code fix or a documentation update.

Please let me know if anyone else is already actively working on this.

Thanks!

**Comment by spolti** [comment]
When using the clusterStorageConfig, there is no need to edit the info in the `inferenceservice-config` configMap, it should be able to recognize the new protocols as it is.
I did a recent test with another protocol and I didn't get any issues.

Also just tested your example with:

```yaml
apiVersion: "serving.kserve.io/v1alpha1"
kind: ClusterStorageContainer
metadata:
  name: default
spec:
  container:
    name: storage-initializer
  supportedUriFormats:
    - prefix: model-registry://
    - prefix: hf://
    - prefix: gs://
    - prefix: s3://
    - prefix: hdfs://
    - prefix: webhdfs://
    - regex: "https://(.+?).blob.core.windows.net/(.+)"
    - regex: "https://(.+?).file.core.windows.net/(.+)"
    - regex: "https?://(.+)/(.+)"
```

isvc:
```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "huggingface-t5"
  annotations:
    serving.kserve.io/deploymentMode: "RawDeployment"
spec:
  predictor:
    imagePullSecrets:
    - name: dockerhub-pull-secret
    model:
      modelFormat:
        name: vLLM
      storageUri: "model-registry://google/t5-small-lm-adapt"
```

this isvc does not work, it will fail to start, however, the protocol is working.

What is the KServe version that you are using?
