### ISSUE TITLE
Support secure access to the metrics server with TriggerAuthentication for KEDA autoscaling

### ISSUE THREAD

**Issue by pierDipi** [kserve/kserve#4371]
/kind feature

**Describe the solution you'd like**
Currently, when using KEDA for autoscaling with Prometheus in KServe, there is no way to configure authentication parameters.

This would enable secure access to the metrics server configuring KEDA authentication parameters (using TriggerAuthentication).

Maybe with the following API changes:

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: huggingface-fbopt
  annotations:
    serving.kserve.io/deploymentMode: "RawDeployment"
    serving.kserve.io/autoscalerClass: "keda"
    serving.kserve.io/enable-prometheus-scraping: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
    prometheus.io/scheme: "http"
spec:
  # ...
    autoScaling:
      metrics:
        - type: External
          external:
            metric:
              backend: "prometheus"
              serverAddress: "http://<prometheus-host>:9090"
              query: vllm:num_requests_running
            authenticationRef:
              name: keda-prom-creds
            target:
              type: Value
              value: "2"
---
# Just for reference ...
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-prom-creds
spec:
  secretTargetRef:
    - parameter: username
      name: keda-prom-secret
      key: username
    - parameter: password
      name: keda-prom-secret
      key: password
```

**Anything else you would like to add:**

This feature is crucial for production environments where secure access to metrics is a requirement.

Refs:
- https://keda.sh/docs/2.17/scalers/prometheus/#authentication-parameters
