### ISSUE TITLE
KEDA scaledobject target value is set to pointer instead of specified value

### ISSUE THREAD

**Issue by andyi2it** [kserve/kserve#4414]
/kind bug

**What steps did you take and what happened:**
I have created an InferenceService with KEDA autoscaler, and defined the CPU averageUtilization threshold in the spec. However, the resulting ScaledObject resource sets the metric value to a pointer-like number instead of the provided value of 50.

**What did you expect to happen:**
The ScaledObject created from the InferenceService spec should reflect the given CPU averageUtilization value of 50.

**What's the InferenceService yaml:**
```yaml
apiVersion: "[serving.kserve.io/v1beta1](http://serving.kserve.io/v1beta1)"
kind: "InferenceService"
metadata:
  name: "sklearn-v2-iris"
  annotations:
    [serving.kserve.io/deploymentMode](http://serving.kserve.io/deploymentMode): "RawDeployment"
    [serving.kserve.io/autoscalerClass](http://serving.kserve.io/autoscalerClass): "keda"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      protocolVersion: v2
      runtime: kserve-sklearnserver
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
    minReplicas: 1
    maxReplicas: 5
    autoScaling:
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: "Utilization"
              averageUtilization: 50
```
**Anything else you would like to add:**

![Image](https://github.com/user-attachments/assets/6f79cd95-ffaa-4bb8-af19-db94a98df941)

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
