### ISSUE TITLE
Missing ISVC status in raw deployment mode when model is not ready

### ISSUE THREAD

**Issue by saileshd1402** [kserve/kserve#4454]
/kind bug

**What steps did you take and what happened:**

When ISVC is in a non ready state, I am not able to see the status field when I do `kubectl get isvc -o yaml`

I installed Kserve with raw deployment mode. installation commands:
```
 helm install kserve-crd oci://ghcr.io/kserve/charts/kserve-crd --version v0.15.0 -n kserve --create-namespace --wait

 helm install kserve oci://ghcr.io/kserve/charts/kserve -n kserve --version v0.15.0 \
       --set kserve.controller.deploymentMode=RawDeployment \
       --set kserve.controller.gateway.ingressGateway.enableGatewayApi=true \
       --set kserve.controller.gateway.ingressGateway.createGateway=false \
       --set kserve.controller.gateway.ingressGateway.kserveGateway=kserve-test/custom-ingress-gateway

```

When I created the following valid ISVC, I noticed that while the deployment was still progressing, status was not visible
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
 annotations:
   serving.kserve.io/deploymentMode: RawDeployment
   storage.kserve.io/readonly: "false"
 labels:
   endpoint: gemma-cpu
 name: gemma-cpu
 namespace: kserve-test
spec:
 predictor:
   imagePullSecrets:
   - name: docker-secret
   maxReplicas: 1
   minReplicas: 1
   model:
     args:
     - --model_dir=/mnt/models
     - --model_name=gemma-cpu
     - --served-model-name=gemma-cpu
     image: kserve/huggingfaceserver:v0.15.0
     modelFormat:
       name: huggingface
     name: ""
     protocolVersion: v2
     storageUri: pvc://test-ce02c9d3-019f-4b27-bdcd-9d-pvc-claim/model-files
```
When deployment had this status, the status of ISVC was empty:
```
status:
    conditions:
    - lastTransitionTime: "2025-05-08T14:01:03Z"
      lastUpdateTime: "2025-05-08T14:01:03Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2025-05-08T14:01:03Z"
      lastUpdateTime: "2025-05-08T14:01:03Z"
      message: ReplicaSet "gemma-cpu-predictor-849cd84f67" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
```

When I intentionally gave an invalid image in ISVC, the deployment went into ProgressDeadlineExceeded state but I was still unable to see any status in ISVC. This was the status of deployment in this case:
```
  status:
    conditions:
    - lastTransitionTime: "2025-05-08T14:02:34Z"
      lastUpdateTime: "2025-05-08T14:02:34Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2025-05-08T14:12:35Z"
      lastUpdateTime: "2025-05-08T14:12:35Z"
      message: ReplicaSet "gemma-cpu-predictor-6788db956b" has timed out progressing.
      reason: ProgressDeadlineExceeded
      status: "False"
      type: Progressing
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
```

**What did you expect to happen:**
Ideally status should be set during any state of ISVC to clearly let the user know.

**Environment:**

- Envoy Gateway Version: v1.3.2
- Gateway API Version: v1.2.1 
- Istio Version: N/A
- Knative Version: N/A
- KServe Version: v0.15.0
- Kubeflow version: N/A
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]: N/A
- Minikube/Kind version: N/A
- Kubernetes version: (use `kubectl version`): Client Version: v1.30.0, Server Version: v1.31.4
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.3 LTS
