### ISSUE TITLE
ModelCache not working properly

### ISSUE THREAD

**Issue by xrwang8** [kserve/kserve#4462]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```bash
[root@node01 modelcache]# kubectl  describe  pvc -n cc-localmodel-jobs 
Name:          meta-llama3-8b-instruct-hf-workers
Namespace:     cc-localmodel-jobs
StorageClass:  local-storage
Status:        Pending
Volume:        meta-llama3-8b-instruct-hf-workers-download
Labels:        <none>
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      0
Access Modes:  
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason          Age                  From                         Message
  ----     ------          ----                 ----                         -------
  Warning  VolumeMismatch  4s (x26 over 6m14s)  persistentvolume-controller  Cannot bind to requested volume "meta-llama3-8b-instruct-hf-workers-download": storageClassName does not match
```

```bash 
kubectl  get pv
NAME                                          CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                               STORAGECLASS   REASON   AGE
meta-llama3-8b-instruct-hf-workers-download   1700G      RWO            Retain           Available                                                               6m47s
``` 

**What did you expect to happen:**

Expect successful binding of PVC and PV, and successful model download.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

```
apiVersion: serving.kserve.io/v1alpha1
kind: LocalModelNodeGroup
metadata:
  name: hf-workers
spec:
  storageLimit: 1T
  persistentVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50G
    storageClassName: local-storage
    volumeMode: Filesystem
    volumeName: models
  persistentVolumeSpec:
    accessModes:
      - ReadWriteOnce
    volumeMode: Filesystem
    capacity:
      storage: 1700G
    local:
      path: /models
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - "NVIDIA-GeForce-RTX-3090"

--- 
apiVersion: v1
kind: Secret
metadata:
  name: hf-secret
  namespace: kserve-localmodel-jobs
type: Opaque
stringData:
  HF_TOKEN: ZG1kbWRtZW1lbW0 # fill in the hf hub token

---
apiVersion: "serving.kserve.io/v1alpha1"
kind: ClusterStorageContainer
metadata:
  name: hf-hub
spec:
  container:
    name: storage-initializer
    image: kserve/storage-initializer:latest
    env:
    - name: HF_TOKEN  # Option 2 for authenticating with HF_TOKEN
      valueFrom:
        secretKeyRef:
          name: hf-secret
          key: HF_TOKEN
          optional: false
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: "1"
  supportedUriFormats:
    - prefix: hf://
  workloadType: localModelDownloadJob


---
apiVersion: serving.kserve.io/v1alpha1
kind: LocalModelCache
metadata:
  name: meta-llama3-8b-instruct
spec:
  sourceModelUri: hf://meta-llama/meta-llama-3-8b-instruct
  modelSize: 10Gi
  nodeGroups: 
  - hf-workers

```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- KServe Version: v0.15.0
- Kubernetes version: (use `kubectl version`):  v1.28.14+k3s-109139f5 
- OS (e.g. from `/etc/os-release`):

``` bash
 kubectl  get po   -n kserve
NAME                                                    READY   STATUS    RESTARTS       AGE
kserve-controller-manager-7cbf8668ff-89wm6              2/2     Running   10 (13m ago)   5d21h
kserve-localmodel-controller-manager-7d47c7ccd6-twnkm   1/1     Running   1 (5d1h ago)   5d22h
kserve-localmodelnode-agent-5vcnb                       1/1     Running   1 (5d1h ago)   5d22h
```
