### ISSUE TITLE
[Bug] KServe InferenceService fails with "NoSupportingRuntime" for sklearn despite correct predictor.sklearn spec (v0.13.1)

### ISSUE THREAD

**Issue by onggizam** [kserve/kserve#4464]
/kind bug

### Summary
Deploying an InferenceService with predictor.sklearn schema fails with NoSupportingRuntime error, even though a proper ClusterServingRuntime is defined. No serving pods are created. Runtime matching seems broken for sklearn.

### Environment
- KServe Version: v0.13.1
- Kubernetes Version: v1.30.3(3 node) v1.29.6(3node)
- Kubeflow: 1.9.2
- InferenceService API Version: serving.kserve.io/v1beta1
- ClusterServingRuntime:
  - Name: sklearn
  - Image: kserve/sklearnserver:v0.13.1

### Describe the Bug
I am deploying an InferenceService using the new schema (predictor.sklearn) but KServe still fails with:

```bash
No runtime found to support predictor with model type: {sklearn <nil>}
```

Even though:
- I created the ClusterServingRuntime with supportedModelFormats: [{name: sklearn, version: "*"}]
- InferenceService spec uses predictor.sklearn with correct storageUri.
- PVC is bound and verified.
- No serving pods are created.
- Controller logs show repeated NoSupportingRuntime errors.

### YAML for InferenceService

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-iris
  namespace: <namespace>
spec:
  predictor:
    sklearn:
      storageUri: "pvc://<MY-PVC-NAME>/modeldir/"
      protocolVersion: v2
```

### YAML for ClusterServingRuntime

```yaml
apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: sklearn
spec:
  supportedModelFormats:
    - name: sklearn
      version: "*"
  containers:
    - name: sklearn
      image: kserve/sklearnserver:v0.13.1
      args:
        - --model_name=$(MODEL_NAME)
        - --model_dir=$(STORAGE_URI)
      ports:
        - containerPort: 8080
```

### Controller Logs (error)

```bash
no runtime found to support predictor with model type: {sklearn <nil>}
fails to reconcile component
```

### Actual Behavior
- KServe fails with NoSupportingRuntime
- No serving pods created.
- PVC is mounted correctly.
- ClusterServingRuntime is visible in kubectl get clusterservingruntimes but seems ignored.

Thank you 🙏

Thank you for your great work on KServe. I would really appreciate your help on this issue!
