### ISSUE TITLE
pytorch does not support enable swagger ui

### ISSUE THREAD

**Issue by xrwang8** [kserve/kserve#4475]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```yaml
kind: "InferenceService"
apiVersion: "serving.kserve.io/v1beta1"
metadata:
  name: "torchserve"
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      storageUri: gs://root/image-classifier
      protocolVersion: v2
      args:
      - --model-store=/mnt/models/v2/model-store 
      - --ts-config=/mnt/models/v2/config/config.properties 
      - --enable_docs_url=True 
                                          
```
 
``` bash

 kubectl  logs -f torchserve-predictor-7fd4b5df4c-2k6jk
Defaulted container "kserve-container" out of: kserve-container, storage-initializer (init)
usage: torchserve [-h] [-v | --start | --stop] [--ts-config TS_CONFIG]
                  [--model-store MODEL_STORE]
                  [--workflow-store WORKFLOW_STORE]
                  [--models MODEL_PATH1 MODEL_NAME=MODEL_PATH2... [MODEL_PATH1 MODEL_NAME=MODEL_PATH2... ...]]
                  [--log-config LOG_CONFIG] [--foreground]
                  [--no-config-snapshots] [--plugins-path PLUGINS_PATH]
torchserve: error: unrecognized arguments: --enable_docs_url=True

```

**What did you expect to happen:**
enable swagger ui 

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- KServe Version: v1.15.0
