### ISSUE TITLE
MIG support for huggingface runtime

### ISSUE THREAD

**Issue by tmvfb** [kserve/kserve#4505]
/kind feature

**Describe the solution you'd like**
From my understanding, KServe currently does not support running models on multi-instance GPUs, but the upstream vLLM seems to support it. Something like this won't work:

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: multilingual-e5-large-instruct
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=multilingual-e5-large-instruct
        - --model_id=intfloat/multilingual-e5-large-instruct
      resources:
        limits:
          nvidia.com/mig-1g.12gb: "2"
      env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
```

There are no explicit error messages, but the InferenceService fails to create any workloads (Pods/Deployments/ReplicaSets). Maybe a validating webhook does not allow this (see [allowed constants](https://github.com/kserve/kserve/blob/ae964630d9c480af199e2bfa77fb99d47915048f/pkg/constants/constants.go#L246), for example), maybe this is a much more complicated problem, I am ufortunately not familiar with KServe architecture.

That being said, this vLLM-based solution will work:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-e5-mig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-e5
  template:
    metadata:
      labels:
        app: vllm-e5
    spec:
      containers:
      - name: vllm
        image: vllm/vllm-openai:v0.9.0.1
        command:
        - "python3"
        - "-m"
        - "vllm.entrypoints.openai.api_server"
        - "--model"
        - "intfloat/multilingual-e5-large-instruct"
        - "--port=8000"
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/mig-1g.12gb: 1
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-e5-service
spec:
  selector:
    app: vllm-e5
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP 
```

Would be nice to run a similar setup with huggingface ClusterServingRuntime.
