### ISSUE TITLE
KServe CPU Spikes in transformer

### ISSUE THREAD

**Issue by dugar-tarun-z** [kserve/kserve#4509]
/kind bug

**What steps did you take and what happened:**
I have deployed transformer and model colocated in a pod on a shared kubernetes cluster. I have high throughput coming in to the range of 200k rpm. I have attached the config below:
```yaml
namespace: ""
metadata:
  name: ''
  component: ''
  environment: ''
  team: ''
deployment:
  type: ""
  colocate:
    predictor:
      image: kserve:seldon-mlserver-1.7.0-xgboost
      args:
      env:
        - name: TS_SERVICE_ENVELOPE
          value: kserve
        - name: STORAGE_URI
          value: 
        - name: MLSERVER_MODEL_NAME
          value: 
        - name: MLSERVER_MODEL_URI
          value: /mnt/models
        - name: MLSERVER_MODEL_IMPLEMENTATION
          value: mlserver_xgboost.XGBoostModel
        - name: MLSERVER_HTTP_PORT
          value: '8085'
        - name: MLSERVER_GRPC_PORT
          value: '9000'
        - name: MODELS_DIR
          value: /mnt/models
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1000m"
          memory: '1Gi'
      probes:
        readinessProbe:
          failureThreshold: 6
          periodSeconds: 5
          successThreshold: 1
          httpGet:
            path: /v2/health/ready
            port: 8085
          timeoutSeconds: 5
          initialDelaySeconds: 10
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            path: /v2/health/live
            port: 8085
          timeoutSeconds: 5
          initialDelaySeconds: 10
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            path: /v2/health/ready
            port: 8085
          timeoutSeconds: 1
          initialDelaySeconds: 15
    transformer:
      repository: 
      tag: 
      imagePullSecrets:
        - name: 
      resources:
        requests:
          cpu: "500m"
          memory: '1Gi'
        limits:
          cpu: "1000m"
          memory: '1Gi'
      probes:
        readinessProbe:
          failureThreshold: 6
          periodSeconds: 5
          successThreshold: 1
          httpGet:
            path: /v2/health/ready
            port: 8080
          timeoutSeconds: 5
          initialDelaySeconds: 10
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            path: /v2/health/live
            port: 8080
          timeoutSeconds: 5
          initialDelaySeconds: 10
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            path: /v2/health/ready
            port: 8080
          timeoutSeconds: 1
          initialDelaySeconds: 15
      args:
        - --model_name=
        - --predictor_host=localhost:8085
        - --protocol=v2
        - --http_port=8080
        - --workers=1
        - --log-level=info
        - --enable_grpc=False
        - --enable_latency_logging=False
        - --max_asyncio_workers=2
predictorIngress:
  enabled: true
  rules:
    - ingressType: private
      connectionType: http
      annotations:
        alb.ingress.kubernetes.io/group.name: 
      spec:
        rules:
          - host: ''
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: ''
                      port:
                        number: use-annotation
podDisruptionBudget:
  enabled: true
  minAvailable: "80%"
rollout:
  enabled: true
  minReplicas: 10
  maxReplicas: 60
  dynamicStableScale: false
  scaleDownDelaySeconds: 60
  revisionHistoryLimit: 5
  canary:
    steps:
      - setCanaryScale:
          weight: 10
      - setWeight: 0
      - pause: {duration: 60}
      - setCanaryScale:
          weight: 20
      - setWeight: 5
      - pause: {duration: 90}
      - pause: {}
      - setCanaryScale:
          weight: 30
      - setWeight: 20
      - pause: {duration: 120}
      - setCanaryScale:
          weight: 50
      - setWeight: 40
      - pause: {duration: 120}
      - setCanaryScale:
          weight: 60
      - setWeight: 55
      - pause: {duration: 120}
      - pause: {}
      - setCanaryScale:
          weight: 70
      - setWeight: 70
      - pause: {duration: 90}
      - setCanaryScale:
          matchTrafficWeight: true
      - setWeight: 80
      - pause: {duration: 60}
      - setWeight: 99
      - pause: {duration: 60}
      - setWeight: 100
rolloutHpa:
  cpuUtilizationPercentage: "50"
  memoryUtilizationPercentage: "60"
  modelContainerCpuUtilizationPercentage: "50"
  processingContainerCpuUtilizationPercentage: "50"
  scaleUpStabilizationWindowSeconds: 0
  scaleDownStabilizationWindowSeconds: 300
  scaleDown:
    policies:
      - periodSeconds: 15
        type: Pods
        value: 8
      - periodSeconds: 15
        type: Percent
        value: 20
    selectPolicy: Min
  scaleUp:
    policies:
      - periodSeconds: 5
        type: Pods
        value: 8
      - periodSeconds: 5
        type: Percent
        value: 100
    selectPolicy: Max
serviceMonitor:
  enabled: true
  prometheus:
    label: kube-prometheus
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
serviceAccount:
  enabled: true
  annotations:
    eks.amazonaws.com/role-arn: 
```
**What did you expect to happen:**
Expected the model to serve the throughput successfully.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
  creationTimestamp: '2025-05-01T15:59:12Z'
  finalizers:
    - inferenceservice.finalizers
    containers:
      - env:
          - name: TS_SERVICE_ENVELOPE
            value: kserve
          - name: STORAGE_URI
            value: 
          - name: MLSERVER_MODEL_NAME
            value: 
          - name: MLSERVER_MODEL_URI
            value: /mnt/models
          - name: MLSERVER_MODEL_IMPLEMENTATION
            value: mlserver_xgboost.XGBoostModel
          - name: MLSERVER_HTTP_PORT
            value: '8085'
          - name: MLSERVER_GRPC_PORT
            value: '9000'
          - name: MODELS_DIR
            value: /mnt/models
        image: >-
          kserve:seldon-mlserver-1.7.0-xgboost
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/sh
                - '-c'
                - sleep 45
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /v2/health/live
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: kserve-container
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /v2/health/ready
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /v2/health/ready
            port: 8085
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      - args:
          - '--model_name='
          - '--predictor_host=localhost:8085'
          - '--protocol=v2'
          - '--http_port=8080'
          - '--workers=1'
          - '--log-level=info'
          - '--enable_grpc=False'
          - '--enable_latency_logging=False'
          - '--max_asyncio_workers=2'
        command:
          - python
          - '-m'
          - model
        image:
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/sh
                - '-c'
                - sleep 45
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /v2/health/live
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: transformer-container
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /v2/health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /v2/health/ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
```
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

We have set the scaling threshold to 50% cpu, 50% kserve container, 50% transformer container. We have multiple models deployed on the same shared cluster. We see issues simultaneously across models. The CPU spikes only in the transformer container - increasing the latencies for all the pods and it does not settle immediately. The issue occurs randomly in the day and has no apparent pattern. No spikes in throughput. We use clusters internal svc endpoint to hit the server.

**Environment:**

- Istio Version: NA
- Knative Version: NA 
- KServe Version: 0.14
- Kubeflow version: NA
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm] NA
- Minikube/Kind version: NA 
- Kubernetes version: (use `kubectl version`): 1.27
- OS (e.g. from `/etc/os-release`): ubuntu
