### ISSUE TITLE
Can't create Serverless InferenceService when knative is installed in non-default namespace

### ISSUE THREAD

**Issue by Tiegris** [kserve/kserve#4517]
/kind bug

**What steps did you take and what happened:**
1. I was running kserve 0.15.0, and created a Serverless InferenceService.
2. I upgraded kserve from 0.15.0 to 0.15.2
3. The same Serverless InferenceService creation now throw an error:
  ```
  failed to retrieve the knative autoscaler configuration: fails to retrieve the config-autoscaler configmap from the knative-serving namespace.: configmaps \"config-autoscaler\" not found","errorVerbose":"configmaps \"config-autoscaler\" not found\nfails to retrieve the config-autoscaler configmap from the knative-serving namespace.
  ```

After investigation I found this commit in 0.15.1: [209ba7c
](https://github.com/kserve/kserve/commit/209ba7c26219b84693d7b050aaccd52da939fb43#diff-938f381e935e85bb3880dfd8b1c43a56a1ef18e582f1e1f93ae10f22f56b3c88R44-R153)

This commit added search for a ConfigMap in the namespace defined by the `KNATIVE_CONFIG_AUTOSCALER_NAMESPACE` env var (defaults to: knative-serving) In our deployment we installed knative to a different NS: knative-serving-ns. This is the root cause of the bug.

**What did you expect to happen:**
- I expected this change to be documented in the installation guide for example.
- I expected the value of KNATIVE_CONFIG_AUTOSCALER_NAMESPACE to be easily modified from helm values.

Please update the documentation and the helm chart so that one can easily provide this important config param.

**What's the InferenceService yaml:**
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/deploymentMode: Serverless
  creationTimestamp: "2025-06-11T07:40:57Z"
  finalizers:
    - inferenceservice.finalizers
  generation: 2
  labels:
    app: pythondeployment-kapitan-1749627522005-0
    app.kubernetes.io/name: pythondeployment-kapitan-1749627522005-0
  name: pythondeployment-kapitan-1749627522005-0
  namespace: ...
spec:
  ...
```

**Environment:**

- Istio Version: 1.25.0
- Knative Version: 1.17.0
- KServe Version: 0.15.2
- Cloud Environment: aws
- Kubernetes version: v1.31.7-eks-4096722
