### ISSUE TITLE
[Autoscaling KEDA] Make the stabilizationWindowSeconds for scaleUp and scaleDown configurable

### ISSUE THREAD

**Issue by houshengbo** [kserve/kserve#4541]
/kind feature

**Describe the solution you'd like**
In HPA, the default stabilizationWindowSeconds for scaleUp is 0, and the default stabilizationWindowSeconds for scaleDown is 5 minutes. The inference spec should be able to configure both of them with different values.

**Anything else you would like to add:**
My suggestion is to able to add the following section into the scaledobject:

```
advanced:
  horizontalPodAutoscalerConfig:
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 10
      scaleUp:
        stabilizationWindowSeconds: 10
```

**Links to the design documents:**
Similar to configure the HPA section as below:
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#default-behavior
