### ISSUE TITLE
[Autoscaling KEDA] Differentiate the same metrics across different deployments under different namespaces

### ISSUE THREAD

**Issue by houshengbo** [kserve/kserve#4542]
/kind feature

**Describe the solution you'd like**
We leverage the OTEL-ADDON as the intermediate storage to save the metrics collected from the workloads, and serve them to KEDA via the PromQL queries.

If we have multiple services running under the same or even different namespaces, but all of them collect and scale based on the same metric, e.g. `vllm:num_requests_running`, the metrics collected will be all mixed together in the `OTEL-ADDON`.

It means if we scale the workloads with the query:
```
      - podmetric:
          metric:
            backend: opentelemetry
            metricNames:
            - vllm:num_requests_running
            operationOverTime: avg
            query: sum(vllm:num_requests_running)
``` 
we won't be able to differentiate the which metrics `vllm:num_requests_running` are coming from which deployment under which namespace.

Maybe I have missed some configuration options, but I am wondering if we support adding deployment name and namespace into the metrics, so that we can query with something like:
```
query: "sum(vllm:num_requests_waiting{namespace=<the namespace>, deployment=<the workload name>})"
```
to scale the workload, only based on the metrics coming from the specific workload.

**Anything else you would like to add:**
I personally leverage the OpenTelemetry processors to add the namespace and the deployment name into the metrics collected from the workload like:
```
    processors:
      resourcedetection/env:
        detectors: [env]
        timeout: 2s
        override: false
      transform:
        metric_statements:
          - context: datapoint
            statements:
              - set(attributes["namespace"], resource.attributes["k8s.namespace.name"])
              - set(attributes["pod"], resource.attributes["k8s.pod.name"])
              - set(attributes["deployment"], resource.attributes["k8s.deployment.name"])
```
This is able to configure with the CR of OpenTelemetryCollector, but is glad to see if there is any other option to configure it as well.

**Links to the design documents:**
