### ISSUE TITLE
Controller panics if autoscaler class is not set to keda with external autoscaling config

### ISSUE THREAD

**Issue by pierDipi** [kserve/kserve#4548]
/kind bug

**What steps did you take and what happened:**

I had these resources [1] and without the `serving.kserve.io/autoscalerClass: keda` the controller panics on this line https://github.com/kserve/kserve/blob/9e55d59c9823b2c4337d613da8c0a21681f5616b/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go#L64 because `Resource` is `nil`.

I would expect it to fail validation and give me an actionable error message.

[1]
```yaml
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: vllm-runtime
  namespace: keda-demo
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
    - args:
        - --port=8080
        - --model=/mnt/models
        - --served-model-name={{.Name}}
      command:
        - python
        - '-m'
        - vllm.entrypoints.openai.api_server
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: quay.io/modh/vllm@sha256:8a3dd8ad6e15fe7b8e5e471037519719d4d8ad3db9d69389f2beded36a6f5b21
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
  multiModel: false
  supportedModelFormats:
  - autoSelect: true
    name: vLLM

---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite
  namespace: keda-demo
  annotations:
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 2
    autoScaling:
      metrics:
        - type: External
          external:
            authenticationRef:
              name: inference-prometheus-auth
            metric:
              authModes: bearer
              backend: "prometheus"
              serverAddress: "https://thanos-querier.xyz.svc:9092"
              query: "sum(vllm:num_requests_running{namespace='keda-demo', job='granite-metrics'})"
              namespace: 'keda-demo'
            target:
              type: Value
              value: "2"
    model:
      modelFormat:
        name: vLLM
      args:
        - --model_name=granite-3-2-8b-instruct
        - --model_dir=/mnt/models
      storageUri: hf://ibm-granite/granite-3.2-8b-instruct
      env:
        - name: VLLM_CACHE_ROOT
          value: '/tmp'
      resources:
        limits:
          cpu: '6'
          memory: 24Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '1'
          memory: 8Gi
          nvidia.com/gpu: '1'
      runtime: vllm-runtime
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists

```

**What did you expect to happen:**

I would expect it to fail validation and give me an actionable error message.

**What's the InferenceService yaml:**

See above.

**Anything else you would like to add:**

- We need to have a test to validate that the controller doesn't panic in this case and gives the user an actionable and clear error message.

**Environment:**

- Istio Version: Any
- Knative Version: 1.16
- KServe Version: 0.15
- Cloud Environment: Any
- Minikube/Kind version: Any
- Kubernetes version: (use `kubectl version`): Any
- OS (e.g. from `/etc/os-release`): Any

**Comment by orfeas-k** [comment]
I 'm interested in working on this but I don't have permissions to assign myself. 

With a first quick look,
1. Are there specific logs you 're seeing @pierDipi so I ensure I reproduce the same issue
2. Looks like I cannot pull the image `quay.io/modh/vllm@sha256:8a3dd8ad6e15fe7b8e5e471037519719d4d8ad3db9d69389f2beded36a6f5b21`. I understand that this image isn't needed for reproducing, right?

**Comment by pierDipi** [comment]
For 1:
```
{
  "level": "error",
  "ts": "2025-06-26T13:38:17Z",
  "msg": "Observed a panic",
  "controller": "inferenceservice",
  "controllerGroup": "serving.kserve.io",
  "controllerKind": "InferenceService",
  "InferenceService": {
    "name": "granite",
    "namespace": "keda-demo"
  },
  "namespace": "keda-demo",
  "name": "granite",
  "reconcileID": "7a3570a9-8415-48f5-bd71-4cf90d8b5802",
  "panic": "runtime error: invalid memory address or nil pointer dereference",
  "panicGoValue": "\"invalid memory address or nil pointer dereference\"",
  "stacktrace": "runtime.sigpanic\n\t/usr/lib/golang/src/runtime/signal_unix.go:917\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa.getHPAMetrics\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go:64\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa.createHPA\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go:157\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa.NewHPAReconciler\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go:51\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler.createAutoscaler\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go:94\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler.NewAutoscalerReconciler\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go:65\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/raw.NewRawKubeReconciler\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/raw/raw_kube_reconciler.go:90\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components.(*Predictor).reconcileRawDeployment\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components/predictor.go:712\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components.(*Predictor).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components/predictor.go:207\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:243\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:224"
}
```

for 2: yes, you can use any other runtime or vllm image, as it's not vllm specific

**Comment by shhubhxm** [comment]
Hi @pierDipi and KServe maintainers,

I’m interested in contributing to this issue to address the controller panic in the InferenceService reconciler when autoscalerClass is not set to keda with external autoscaling configurations. I see that @orfeas-k is assigned and has started investigating, and I’d like to offer support to help resolve this issue.

To ensure I can contribute effectively, could you clarify:

1. Would it be helpful for me to reproduce the panic using the provided YAML and test @orfeas-k’s potential fix, focusing on validating the new error message?
2. Should I propose a test case in the KServe test suite (e.g., under test/) to ensure the controller rejects invalid configurations with a clear, actionable error?
3. Are there preferred validation patterns or error message formats for the fix in hpa_reconciler.go?
4. How can I best coordinate with @orfeas-k to assist with implementation or testing without overlapping efforts?

I’ve set up a KServe development environment with Kubernetes and am prepared to reproduce the issue, test proposed fixes, or contribute validation logic. Any guidance on next steps or specific areas where I can add value would be appreciated. Thank you for supporting contributions to KServe!

**Comment by orfeas-k** [comment]
#### Minimal reproduction of error
I reproduced using the [KEDA example](https://kserve.github.io/website/latest/modelserving/autoscaling/keda/autoscaling_keda/#create-inferenceservice) but
1. removed `serving.kserve.io/autoscalerClass`
2. replaced the `metrics` field with one similar to this example
	```
      metrics:
        - type: External
          external:
            metric:
              backend: "prometheus"
            target:
              type: Value
              value: "2"
	```

#### Why it's happening
My understanding is:
1. There is no `serving.kserve.io/autoscalerClass` annotation set, thus it assumes the default one in
	https://github.com/kserve/kserve/blob/47f30145d2edfedb288224e8f0235877f695f44d/pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go#L75-L83, which is HPA
	https://github.com/kserve/kserve/blob/47f30145d2edfedb288224e8f0235877f695f44d/pkg/constants/constants.go#L185-L191
2. It runs the HPAReconciler
	https://github.com/kserve/kserve/blob/47f30145d2edfedb288224e8f0235877f695f44d/pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go#L91

Given that (but please confirm) using HPA as the default `autoscalerClass` is expected, the failure comes from the fact that getHPAMetrics tries to iterate the `metric.Resource.Name` but there is no such field.

https://github.com/kserve/kserve/blob/d20d4228a8b2956b800ad5a3e62c0578b5a5b97f/pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go#L62


Thus, does the validation mentioned above refers to validating the `metrics` during HPA creation and more specifically during getHPAmetrics? If so, what should we validate it against? Which are the expected fields for `autoscalerClassHPA`? I noticed that the HPA reconciler also runs for `external` autoscalerClass
https://github.com/kserve/kserve/blob/d20d4228a8b2956b800ad5a3e62c0578b5a5b97f/pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go#L93-L95. My current guess is that we 'd need to only confirm there is a `metric.Resource.Name`.
cc @pierDipi

**Comment by orfeas-k** [comment]
Hi @shhubhxm, I just got back to this bug. I think this is a pretty trivial bug (if my understanding from above is correct) and thus fixing and writing a test won't be too involved. It will be a bit hard to collaborate on that. From my point of view, you could definitely test the provided fix and confirm that this works and probably also give my PR a review.

**Comment by mwaykole** [comment]
hey @orfeas-k  are u still working on this issue?

**Comment by rpathade** [comment]
I will like to work on this, if this is still up for grabs

**Comment by atharvamhaske** [comment]
@spolti whats update on this bug?

**Comment by varad-ahirwadkar** [comment]
Hi @spolti, @Jooho if this hasn't been fixed yet, may I work on it?

**Comment by spolti** [comment]
Hi @varad-ahirwadkar sure, let me assign to you.

Thanks.

**Comment by spolti** [comment]
> @spolti whats update on this bug?

Hey, sorry, missed your ping, @varad-ahirwadkar volunteered to help with it.

**Comment by varad-ahirwadkar** [comment]
Hi @spolti,

I was trying to reproduce this issue, using an `InferenceService` without `serving.kserve.io/autoscalerClass: keda`
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-v2-iris"
  annotations:
    serving.kserve.io/deploymentMode: "Standard"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      protocolVersion: v2
      runtime: kserve-sklearnserver
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
    minReplicas: 1
    maxReplicas: 5
    autoScaling:
      metrics:
        - type: External
          external:
            metric:
              backend: "prometheus"
              serverAddress: "https://thanos-querier.xyz.svc:9092"
              query: "sum(vllm:num_requests_running{namespace='kserve-test', job='granite-metrics'})"
              namespace: "kserve-test"
            target:
              type: Value
              value: "2"
```

I observed the following:

- The admission webhook accepts the object.
- The controller reconciles it using the HPA reconciler.
- A default CPU-based HPA is created.
- The requested External metric is silently ignored.
- The predictor pod is created successfully, and the controller does not restart, so I don't observe the panic described in the original issue.

Am I using the correct reproduction scenario for the current codebase?

I'm wondering if the panic was fixed elsewhere since the issue was opened, and the remaining problem is that this invalid configuration is silently accepted and falls back to HPA. Or is there a different manifest or setup required to reproduce the original panic?
