### ISSUE TITLE
[Autoscaling KEDA] Multiple metrics collection is not supported

### ISSUE THREAD

**Issue by houshengbo** [kserve/kserve#4559]
/kind bug

**What steps did you take and what happened:**
This is how I configure the spec of my isvc:
```
spec:
  predictor:
    autoScaling:
      metrics:
        - podmetric:
            metric:
              backend: opentelemetry
              metricNames:
                - vllm:num_requests_running
              operationOverTime: avg
              query: sum(vllm:num_requests_running)
            target:
              type: Value
              value: "180"
          type: PodMetric
        - podmetric:
            metric:
              backend: opentelemetry
              metricNames:
                - vllm:gpu_cache_usage_perc
              operationOverTime: avg
              query: sum(vllm:gpu_cache_usage_perc)
            target:
              type: Value
              value: 600m
          type: PodMetric
    maxReplicas: 5
    minReplicas: 1
```

I tried to leverage both `vllm:num_requests_running` and `vllm:gpu_cache_usage_perc` to scale my isvc workload. However, the OpenTelemetryCollector only collects ONE metric as below(Only pick up the one at the bottom of the array). The other metric is ignored. It seems that the OpenTelemetryCollector does not pick up all the metrics defined in our isvc spec. This is what `OpenTelemetryCollector` looks like:

```
spec:
  config:
    processors:
      filter/ottl:
        error_mode: ignore
        metrics:
          metric:
          - name != "vllm:gpu_cache_usage_perc"
```

**What did you expect to happen:**
We need to make sure the processors in OpenTelemetryCollector get all the metrics defined in isvc spec.

**What's the InferenceService yaml:**
Users can specify what the metrics, would it be better if OpenTelemetryCollector use inclusion to list them all? Like:
```
    processors:
      filter/metrics:
        metrics:
          include:
            match_type: strict
            metric_names:
              - vllm:gpu_cache_usage_perc
              - vllm:num_requests_waiting
              - vllm:num_requests_running
```
This processor defines which metrics to pick up.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
