### ISSUE TITLE
Component annotations

### ISSUE THREAD

**Issue by salanki** [kserve/kserve#666]
/kind feature

**Describe the solution you'd like**
Currently, a `InferenceService` will attach all annotations on it's child components. This means that a Service with both a `predictor` and a `transformer` will have the same annotations on both. This is suboptimal in many cases, ie:

1) When predicting on GPU, it is rarely needed for the transformer to run on a GPU host. Transformers should run on CPU-optimized nodes, but currently they will be required to run on GPU nodes as the `gke-accelerator` annotation is applied to them as well.

2) For a heavy inference operation, you'd want to set `autoscaling.knative.dev/target` fairly low (1-4). The transformer however can usually handle a lot more than this, as it is often just a simple encoder / decoder. Scaling up transformers in the same pace as `predictors` does not make sense.

It would be good to be able to add annotations on the component level (predictor, transformer, explainer) as well as global.

**Anything else you would like to add:**
Example `InferenceService`
```
kind: "InferenceService"
metadata:
  name: "tensorflow-gpu"
  annotations:
    autoscaling.knative.dev/target: "4"
    serving.kubeflow.org/gke-accelerator: "nvidia-tesla-t4"
spec:
  default:
    predictor:
      minReplicas: 1
      maxReplicas: 2
      serviceAccountName: s3-sa
      tensorflow:
        storageUri: s3://coreweave/gpt-2/124M/
        runtimeVersion: "1.14.0-gpu"
        resources:
          limits:
            cpu: 2
            nvidia.com/gpu: 1
    transformer:
      custom:
        container:
          image: coreweave/gpt-transformer:0.9
          name: user-container
          resources:
            limits:
              cpu: 3000m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 256Mi
```
