### ISSUE TITLE
'log components' such as outlier detectors tied to models

### ISSUE THREAD

**Issue by ryandawsonuk** [kserve/kserve#679]
The proposal is to make 'logComponents' available in CRD to include outlier detectors and adversarial detectors. The main reason for handling this in the CRD is that these components would be trained on same data, likely in same training job as the main predictor model so they are logically tied together. Otherwise you have to create a separate manifest for something that needs to be kept in sync. Ideally the detectors would be downloaded from modelUris like the main model so the whole user experience would be better if it was in the same CRD.

Currently you can send to a logging component via a knative broker using:
```
      logger:
        mode: all
        url: http://default-broker/
```
This should be kept. The proposal is to also add:
```
      logComponent:
        mode: all
        type: outlier-detector
        modelUri: gs://models/model1/outlier-detector
        logToUrl: http://default-broker/
```
The OD would process the request to check whether it is an outlier and then forward to the broker for storing the outlier score. So the OD component implementation would be almost the same as in the [existing example](https://github.com/SeldonIO/alibi-detect/tree/master/integrations) (only change being it would send score on directly rather than using reply-to)
