### ISSUE TITLE
Add support for web proxy for KFServing when model is downloaded from Google Storage, S3 etc.

### ISSUE THREAD

**Issue by tomasz-sadowski** [kserve/kserve#825]
/kind feature

Please add support for web proxy to connect to GoogleStorage, S3, etc.

Currently, no web proxy is supported for `storage-initializer`. Library used - `urllib3` supports environment variables like `http_proxy` or `https_proxy` but I am not aware of any way how to pass environment variables to `storage-initializer`.  

Please add the support of web proxy to `storage-initializer` and other containers.

It could be implemented by possibility of passing environment variables to these containers.

**Comment by wave112** [comment]
https://github.com/kubeflow/kfserving/blob/e25758f6da020e3e8ad63f0880ab95de6af8395b/pkg/webhook/admission/pod/storage_initializer_injector.go#L167

**Comment by yuzisun** [comment]
> `storage-initializer` container is created here:
> 
> https://github.com/kubeflow/kfserving/blob/e25758f6da020e3e8ad63f0880ab95de6af8395b/pkg/webhook/admission/pod/storage_initializer_injector.go#L167
> 
> 
> I do not see a way to pass environment variables from any resource.

We could add proxy configuration here 
https://github.com/kubeflow/kfserving/blob/master/config/default/configmap/inferenceservice.yaml#L75, feel free to raise PR for this.

**Comment by gabrielecastellano** [comment]
Has this been addressed?

**Comment by muzhi1991** [comment]
any progress?

**Comment by yuzisun** [comment]
Add an example to show how to add the http_proxy envs to the storage initializer in the [website storage section](https://kserve.github.io/website/0.11/modelserving/control_plane/) with the recent addition for customized storage initializer https://github.com/kserve/kserve/issues/825

**Comment by tessapham** [comment]
Created https://github.com/kserve/kserve/issues/3136 to document usage of customized storage initializer.

**Comment by yuzisun** [comment]
You can now customizing the storage initializer container by injecting the HTTP proxy envs, for example
```yaml
apiVersion: "serving.kserve.io/v1alpha1"
kind: ClusterStorageContainer
metadata:
  name: default
spec:
  container:
    name: storage-initializer
    image: kserve/storage-initializer:latest
    env:
    - name: HTTPS_PROXY
       value: xxxxx
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: "1"
  supportedUriFormats:
    - prefix: gs://
    - prefix: s3://
    - prefix: hdfs://
    - prefix: webhdfs://
    - regex: "https://(.+?).blob.core.windows.net/(.+)"
    - regex: "https://(.+?).file.core.windows.net/(.+)"
    - regex: "https?://(.+)/(.+)"
```


more details can be found on https://kserve.github.io/website/0.11/modelserving/storage/storagecontainers/
