### ISSUE TITLE
PVC write to volume

### ISSUE THREAD

**Issue by decewei** [kserve/kserve#872]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
We created a mounted pvc inside the custom container. Using something like the following:
```
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: nlu-confidence-exam
spec:
  default:
    predictor:
      custom:
        container:
          image: tensorflow/serving
          env:
            - name: MODEL_NAME
              value: "nlu-confidence-exam"
            - name: MODEL_BASE_PATH
              value: "/mnt/models"
            - name: STORAGE_URI
              value: pvc://{PVC_NAME}/export
          ports:
            - containerPort: 8500
```
The PVC mounted here is read-only volume. Is there a way to mount a Read Write PVC volume?

**Environment:**
- KFServing Version: 0.2.2
- Kubeflow version: 1.0.0
- Microk8s version: 1.18.2

**Comment by mokpolar** [comment]
I have same issue. 

```yaml
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: model
spec:
  default:
    predictor:
      #minReplicas: 1
      custom:
        container:
          name: kfserving-container
          image: {my-image}
          resources:
            limits:
              cpu: 1500m
              memory: 10Gi
            requests:
              cpu: 1500m
              memory: 10Gi
          env:
            - name: STORAGE_URI
              value: pvc://{my-pvc}

```

Is there a way to mount a Read Write PVC volume?
